const {
  OBJECT_LEVEL_PERMISSION_TABLE_GRID_AUTO_COLUMNS_WITHOUT_FIELD_PERMISSIONS,
  OBJECT_LEVEL_PERMISSION_TABLE_GRID_AUTO_COLUMNS,
} = {
  OBJECT_LEVEL_PERMISSION_TABLE_GRID_AUTO_COLUMNS_WITHOUT_FIELD_PERMISSIONS:
    '180px 1fr 1fr',
  OBJECT_LEVEL_PERMISSION_TABLE_GRID_AUTO_COLUMNS: '26% 16% 16% 16% 16% 10%',
};

export {
  OBJECT_LEVEL_PERMISSION_TABLE_GRID_AUTO_COLUMNS_WITHOUT_FIELD_PERMISSIONS,
  OBJECT_LEVEL_PERMISSION_TABLE_GRID_AUTO_COLUMNS,
};
