export const FLAT_FIELD_METADATA_SHORT_CODE_BY_KEY = new Map<string, string>([
  ['applicationId', '$0'],
  ['applicationUniversalIdentifier', '$1'],
  ['calendarEndViewIds', '$2'],
  ['calendarEndViewUniversalIdentifiers', '$3'],
  ['calendarViewIds', '$4'],
  ['calendarViewUniversalIdentifiers', '$5'],
  ['createdAt', '$6'],
  ['defaultValue', '$7'],
  ['description', '$8'],
  ['fieldPermissionIds', '$9'],
  ['fieldPermissionUniversalIdentifiers', '$a'],
  ['icon', '$b'],
  ['id', '$c'],
  ['isActive', '$d'],
  ['isLabelSyncedWithName', '$e'],
  ['isNullable', '$f'],
  ['isSystem', '$g'],
  ['isSystemSideEffect', '$h'],
  ['isUIEditable', '$i'],
  ['isUIReadOnly', '$j'],
  ['isUnique', '$k'],
  ['kanbanAggregateOperationViewIds', '$l'],
  ['kanbanAggregateOperationViewUniversalIdentifiers', '$m'],
  ['label', '$n'],
  ['mainGroupByFieldMetadataViewIds', '$o'],
  ['mainGroupByFieldMetadataViewUniversalIdentifiers', '$p'],
  ['morphId', '$q'],
  ['name', '$r'],
  ['objectMetadataId', '$s'],
  ['objectMetadataUniversalIdentifier', '$t'],
  ['options', '$u'],
  ['overrides', '$v'],
  ['relationTargetFieldMetadataId', '$w'],
  ['relationTargetFieldMetadataUniversalIdentifier', '$x'],
  ['relationTargetObjectMetadataId', '$y'],
  ['relationTargetObjectMetadataUniversalIdentifier', '$z'],
  ['searchFieldMetadataIds', '$A'],
  ['searchFieldMetadataUniversalIdentifiers', '$B'],
  ['settings', '$C'],
  ['type', '$D'],
  ['universalIdentifier', '$E'],
  ['universalSettings', '$F'],
  ['updatedAt', '$G'],
  ['viewFieldIds', '$H'],
  ['viewFieldUniversalIdentifiers', '$I'],
  ['viewFilterIds', '$J'],
  ['viewFilterUniversalIdentifiers', '$K'],
  ['viewSortIds', '$L'],
  ['viewSortUniversalIdentifiers', '$M'],
  ['workspaceId', '$N'],
]);

export const FLAT_FIELD_METADATA_KEY_BY_SHORT_CODE = new Map<string, string>(
  [...FLAT_FIELD_METADATA_SHORT_CODE_BY_KEY].map(([key, shortCode]) => [
    shortCode,
    key,
  ]),
);

export const FLAT_FIELD_METADATA_EMPTY_ARRAY_KEYS = [
  'kanbanAggregateOperationViewIds',
  'calendarViewIds',
  'calendarEndViewIds',
  'mainGroupByFieldMetadataViewIds',
  'viewFieldIds',
  'viewFilterIds',
  'fieldPermissionIds',
  'viewFieldUniversalIdentifiers',
  'viewFilterUniversalIdentifiers',
  'kanbanAggregateOperationViewUniversalIdentifiers',
  'calendarViewUniversalIdentifiers',
  'calendarEndViewUniversalIdentifiers',
  'mainGroupByFieldMetadataViewUniversalIdentifiers',
  'viewSortIds',
  'viewSortUniversalIdentifiers',
  'searchFieldMetadataIds',
  'searchFieldMetadataUniversalIdentifiers',
  'fieldPermissionUniversalIdentifiers',
] as const;

export const FLAT_FIELD_METADATA_EMPTY_ARRAY_KEY_SET: ReadonlySet<string> =
  new Set(FLAT_FIELD_METADATA_EMPTY_ARRAY_KEYS);
