import { isDefined } from 'twenty-shared/utils';
import { type ObjectLiteral, type SelectQueryBuilder } from 'typeorm';

import { UserInputError } from 'src/engine/core-modules/graphql/utils/graphql-errors.util';
import {
  decodeCursor,
  encodeCursorData,
  getPaginationInfo,
} from 'src/engine/api/graphql/graphql-query-runner/utils/cursors.util';
import { type CursorConnection } from 'src/engine/metadata-modules/pagination/dtos/cursor-connection-type.factory';
import { type CursorPagingInput } from 'src/engine/metadata-modules/pagination/dtos/cursor-paging.input';

type EntityWithId = ObjectLiteral & { id: string };

const decodeCursorIdOrThrow = (cursor: string): string => {
  let cursorData: unknown;

  try {
    cursorData = decodeCursor(cursor);
  } catch {
    throw new UserInputError(`Invalid cursor: ${cursor}`);
  }

  // Decoded JSON can be any value (null, number, array...) — only accept an
  // object carrying a string id, so malformed cursors stay user-input errors.
  if (
    typeof cursorData !== 'object' ||
    cursorData === null ||
    Array.isArray(cursorData) ||
    typeof (cursorData as { id?: unknown }).id !== 'string'
  ) {
    throw new UserInputError(`Invalid cursor: ${cursor}`);
  }

  return (cursorData as { id: string }).id;
};

// Cursor pagination over core metadata entities, replacing the resolvers
// auto-generated by @ptc-org/nestjs-query-graphql. Sorting is fixed to
// id DESC, which both the objects and fields queries used as default sort
// with sorting disabled. Cursors are keyset cursors on id.
export const findManyWithCursorPagination = async <
  TEntity extends EntityWithId,
>({
  queryBuilder,
  alias,
  paging,
  defaultResultSize,
  maxResultsSize,
}: {
  queryBuilder: SelectQueryBuilder<TEntity>;
  alias: string;
  paging: CursorPagingInput | undefined;
  defaultResultSize: number;
  maxResultsSize: number;
}): Promise<CursorConnection<TEntity>> => {
  const { first, last, after, before } = paging ?? {};

  if (isDefined(first) && isDefined(last)) {
    throw new UserInputError('Cannot use both first and last');
  }

  if (isDefined(first) && isDefined(before)) {
    throw new UserInputError('Cannot use first with before');
  }

  if (isDefined(last) && isDefined(after)) {
    throw new UserInputError('Cannot use last with after');
  }

  if (isDefined(after) && isDefined(before)) {
    throw new UserInputError('Cannot use both after and before');
  }

  if ((isDefined(first) && first < 0) || (isDefined(last) && last < 0)) {
    throw new UserInputError('Page size cannot be negative');
  }

  const limit = first ?? last ?? defaultResultSize;

  if (limit > maxResultsSize) {
    throw new UserInputError(
      `Requested page size of ${limit} exceeds the maximum size of ${maxResultsSize}`,
    );
  }

  const isForwardPagination = !isDefined(last) && !isDefined(before);

  if (isForwardPagination) {
    queryBuilder.orderBy(`${alias}.id`, 'DESC');

    if (isDefined(after)) {
      queryBuilder.andWhere(`${alias}.id < :cursorId`, {
        cursorId: decodeCursorIdOrThrow(after),
      });
    }
  } else {
    queryBuilder.orderBy(`${alias}.id`, 'ASC');

    if (isDefined(before)) {
      queryBuilder.andWhere(`${alias}.id > :cursorId`, {
        cursorId: decodeCursorIdOrThrow(before),
      });
    }
  }

  const entities = await queryBuilder.take(limit + 1).getMany();

  const { hasNextPage, hasPreviousPage, hasMoreRecords } = getPaginationInfo(
    entities,
    limit,
    isForwardPagination,
  );

  if (hasMoreRecords) {
    entities.pop();
  }

  if (!isForwardPagination) {
    entities.reverse();
  }

  const edges = entities.map((entity) => ({
    node: entity,
    cursor: encodeCursorData({ id: entity.id }),
  }));

  return {
    edges,
    pageInfo: {
      // Paging past a cursor implies records on the other side of it, matching
      // the auto-generated resolvers this replaces.
      hasNextPage: isForwardPagination ? hasNextPage : isDefined(before),
      hasPreviousPage: isForwardPagination ? isDefined(after) : hasPreviousPage,
      startCursor: edges.length > 0 ? edges[0].cursor : null,
      endCursor: edges.length > 0 ? edges[edges.length - 1].cursor : null,
    },
  };
};
