export enum SettingsFeatures {
  API_KEYS_AND_WEBHOOKS = 'API_KEYS_AND_WEBHOOKS',
  WORKSPACE_SETTINGS = 'WORKSPACE_SETTINGS',
  WORKSPACE_USERS = 'WORKSPACE_USERS',
  ROLES = 'ROLES',
  DATA_MODEL = 'DATA_MODEL',
  ADMIN_PANEL = 'ADMIN_PANEL',
  SECURITY_SETTINGS = 'SECURITY_SETTINGS',
}
