export enum CurrencyCode {
  CAD = 'CAD',
  CHF = 'CHF',
  CNY = 'CNY',
  CZK = 'CZK',
  EUR = 'EUR',
  GBP = 'GBP',
  HKD = 'HKD',
  JPY = 'JPY',
  USD = 'USD',
  NOK = 'NOK',
  SEK = 'SEK',
  MAD = 'MAD',
  QAR = 'QAR',
  AED = 'AED',
}
