import { FieldType } from '@/sdk';
import type { Manifest } from 'twenty-shared/application';
import { PermissionFlagType } from 'twenty-shared/constants';

export const EXPECTED_MANIFEST: Manifest = {
  publicAssets: [
    {
      checksum: '99496069dcc2a1488e1cae9f826d2707',
      fileName: 'favicon.png',
      filePath: 'public/favicon.png',
      fileType: 'png',
    },
  ],
  application: {
    applicationVariables: {
      DEFAULT_RECIPIENT_NAME: {
        description: 'Default recipient name for postcards',
        isSecret: false,
        universalIdentifier: '19e94e59-d4fe-4251-8981-b96d0a9f74de',
        value: 'Alex Karp',
      },
    },
    description: 'A simple rich app',
    displayName: 'Rich App',
    defaultRoleUniversalIdentifier: 'b648f87b-1d26-4961-b974-0908fd991061',
    icon: 'IconWorld',
    universalIdentifier: '4ec0391d-18d5-411c-b2f3-266ddc1c3ef7',
    yarnLockChecksum: 'd41d8cd98f00b204e9800998ecf8427e',
    packageJsonChecksum: '42c3913415952d91ff1cf67ef6452872',
  },
  frontComponents: [
    {
      builtComponentPath: 'src/root.front-component.mjs',
      builtComponentChecksum: '[checksum]',
      componentName: 'RootComponent',
      description: 'A root-level front component',
      name: 'root-component',
      sourceComponentPath: 'src/root.front-component.tsx',
      universalIdentifier: 'a0a1a2a3-a4a5-4000-8000-000000000001',
    },
    {
      builtComponentPath: 'src/components/card.front-component.mjs',
      builtComponentChecksum: '[checksum]',
      componentName: 'CardDisplay',
      description: 'A component using an external component file',
      name: 'card-component',
      sourceComponentPath: 'src/components/card.front-component.tsx',
      universalIdentifier: '88c15ae2-5f87-4a6b-b48f-1974bbe62eb7',
    },
    {
      builtComponentPath: 'src/components/greeting.front-component.mjs',
      builtComponentChecksum: '[checksum]',
      componentName: 'GreetingComponent',
      description: 'A component that uses greeting utility',
      name: 'greeting-component',
      sourceComponentPath: 'src/components/greeting.front-component.tsx',
      universalIdentifier: '370ae182-743f-4ecb-b625-7ac48e21f0e5',
    },
    {
      builtComponentPath: 'src/components/test.front-component.mjs',
      builtComponentChecksum: '[checksum]',
      componentName: 'TestComponent',
      description: 'A test front component',
      name: 'test-component',
      sourceComponentPath: 'src/components/test.front-component.tsx',
      universalIdentifier: 'f1234567-abcd-4000-8000-000000000001',
    },
  ],

  fields: [
    {
      objectUniversalIdentifier: '54b589ca-eeed-4950-a176-358418b85c05',
      description: 'Post card category',
      label: 'Category',
      name: 'category',
      options: [
        {
          color: 'blue',
          label: 'Personal',
          position: 0,
          value: 'PERSONAL',
        },
        {
          color: 'green',
          label: 'Business',
          position: 1,
          value: 'BUSINESS',
        },
        {
          color: 'orange',
          label: 'Promotional',
          position: 2,
          value: 'PROMOTIONAL',
        },
      ],
      type: FieldType.SELECT,
      universalIdentifier: '8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e',
    },
    {
      objectUniversalIdentifier: '54b589ca-eeed-4950-a176-358418b85c05',
      description: 'Priority level for the post card (1-10)',
      label: 'Priority',
      name: 'priority',
      type: FieldType.NUMBER,
      universalIdentifier: '7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d',
    },
  ],
  objects: [
    {
      description: 'A simple root-level object',
      fields: [
        {
          label: 'Title',
          name: 'title',
          type: FieldType.TEXT,
          universalIdentifier: 'b0b1b2b3-b4b5-4000-8000-000000000002',
        },
        {
          label: 'Body',
          name: 'body',
          type: FieldType.TEXT,
          universalIdentifier: 'b0b1b2b3-b4b5-4000-8000-000000000003',
        },
      ],
      icon: 'IconNote',
      labelPlural: 'Root notes',
      labelSingular: 'Root note',
      namePlural: 'rootNotes',
      nameSingular: 'rootNote',
      universalIdentifier: 'b0b1b2b3-b4b5-4000-8000-000000000001',
    },
    {
      description: 'A post card object',
      fields: [
        {
          description: "Postcard's content",
          icon: 'IconAbc',
          label: 'Content',
          name: 'content',
          type: FieldType.TEXT,
          universalIdentifier: '58a0a314-d7ea-4865-9850-7fb84e72f30b',
        },
        {
          icon: 'IconUser',
          label: 'Recipient name',
          name: 'recipientName',
          type: FieldType.FULL_NAME,
          universalIdentifier: 'c6aa31f3-da76-4ac6-889f-475e226009ac',
        },
        {
          icon: 'IconHome',
          label: 'Recipient address',
          name: 'recipientAddress',
          type: FieldType.ADDRESS,
          universalIdentifier: '95045777-a0ad-49ec-98f9-22f9fc0c8266',
        },
        {
          defaultValue: "'DRAFT'",
          icon: 'IconSend',
          label: 'Status',
          name: 'status',
          options: [
            {
              color: 'gray',
              label: 'Draft',
              position: 0,
              value: 'DRAFT',
            },
            {
              color: 'orange',
              label: 'Sent',
              position: 1,
              value: 'SENT',
            },
            {
              color: 'green',
              label: 'Delivered',
              position: 2,
              value: 'DELIVERED',
            },
            {
              color: 'orange',
              label: 'Returned',
              position: 3,
              value: 'RETURNED',
            },
          ],
          type: FieldType.SELECT,
          universalIdentifier: '87b675b8-dd8c-4448-b4ca-20e5a2234a1e',
        },
        {
          defaultValue: null,
          icon: 'IconCheck',
          isNullable: true,
          label: 'Delivered at',
          name: 'deliveredAt',
          type: FieldType.DATE_TIME,
          universalIdentifier: 'e06abe72-5b44-4e7f-93be-afc185a3c433',
        },
      ],
      icon: 'IconMail',
      labelPlural: 'Post cards',
      labelSingular: 'Post card',
      namePlural: 'postCards',
      nameSingular: 'postCard',
      universalIdentifier: '54b589ca-eeed-4950-a176-358418b85c05',
    },
  ],
  roles: [
    {
      canBeAssignedToAgents: false,
      canBeAssignedToApiKeys: false,
      canBeAssignedToUsers: true,
      canDestroyAllObjectRecords: false,
      canReadAllObjectRecords: true,
      canSoftDeleteAllObjectRecords: false,
      canUpdateAllObjectRecords: false,
      canUpdateAllSettings: false,
      description: 'A simple root-level role',
      label: 'Root role',
      universalIdentifier: 'c0c1c2c3-c4c5-4000-8000-000000000001',
    },
    {
      canBeAssignedToAgents: false,
      canBeAssignedToApiKeys: false,
      canBeAssignedToUsers: false,
      canDestroyAllObjectRecords: false,
      canReadAllObjectRecords: false,
      canSoftDeleteAllObjectRecords: false,
      canUpdateAllObjectRecords: false,
      canUpdateAllSettings: false,
      description: 'Default role for function Twenty client',
      fieldPermissions: [
        {
          canReadFieldValue: false,
          canUpdateFieldValue: false,
          fieldUniversalIdentifier: '58a0a314-d7ea-4865-9850-7fb84e72f30b',
          objectUniversalIdentifier: '54b589ca-eeed-4950-a176-358418b85c05',
        },
      ],
      label: 'Default function role',
      objectPermissions: [
        {
          canDestroyObjectRecords: false,
          canReadObjectRecords: true,
          canSoftDeleteObjectRecords: false,
          canUpdateObjectRecords: true,
          objectUniversalIdentifier: '54b589ca-eeed-4950-a176-358418b85c05',
        },
      ],
      permissionFlags: [PermissionFlagType.APPLICATIONS],
      universalIdentifier: 'b648f87b-1d26-4961-b974-0908fd991061',
    },
  ],
  logicFunctions: [
    {
      builtHandlerChecksum: '[checksum]',
      builtHandlerPath: 'src/root.function.mjs',
      handlerName: 'default.config.handler',
      name: 'root-function',
      sourceHandlerPath: 'src/root.function.ts',
      timeoutSeconds: 5,
      httpRouteTriggerSettings: {
        httpMethod: 'GET',
        isAuthRequired: false,
        path: '/root',
      },
      universalIdentifier: 'f0f1f2f3-f4f5-4000-8000-000000000001',
    },
    {
      builtHandlerChecksum: '[checksum]',
      builtHandlerPath: 'src/logic-functions/greeting.function.mjs',
      handlerName: 'default.config.handler',
      name: 'greeting-function',
      sourceHandlerPath: 'src/logic-functions/greeting.function.ts',
      timeoutSeconds: 5,
      httpRouteTriggerSettings: {
        httpMethod: 'GET',
        isAuthRequired: false,
        path: '/greet',
      },
      universalIdentifier: '9d412d9e-2caf-487c-8b66-d1585883dd4e',
    },
    {
      builtHandlerChecksum: '[checksum]',
      builtHandlerPath: 'src/logic-functions/test-function-2.function.mjs',
      handlerName: 'default.config.handler',
      name: 'test-function-2',
      sourceHandlerPath: 'src/logic-functions/test-function-2.function.ts',
      timeoutSeconds: 2,
      cronTriggerSettings: {
        pattern: '0 0 1 1 *',
      },
      universalIdentifier: 'eb3ffc98-88ec-45d4-9b4a-56833b219ccb',
    },
    {
      builtHandlerChecksum: '[checksum]',
      builtHandlerPath: 'src/logic-functions/test-function.function.mjs',
      handlerName: 'default.config.handler',
      name: 'test-function',
      sourceHandlerPath: 'src/logic-functions/test-function.function.ts',
      timeoutSeconds: 2,
      httpRouteTriggerSettings: {
        forwardedRequestHeaders: ['signature'],
        httpMethod: 'GET',
        isAuthRequired: false,
        path: '/post-card/create',
      },
      universalIdentifier: 'e56d363b-0bdc-4d8a-a393-6f0d1c75bdcf',
    },
  ],
};
