storage: /tmp/verdaccio-storage
auth:
  htpasswd:
    file: /tmp/verdaccio-htpasswd
    max_users: 100
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  'twenty-sdk':
    access: $all
    publish: $all
  'create-twenty-app':
    access: $all
    publish: $all
  '**':
    access: $all
    proxy: npmjs
log: { type: stdout, format: pretty, level: warn }
