import { type AMBIGUOUS_ENGINE_COMPONENT_KEYS } from '@/command-menu-item/constants/AmbiguousEngineComponentKeys';
import { type CommandMenuItemSection } from '@/command-menu-item/types/CommandMenuItemSection';
import { EngineComponentKey } from '~/generated-metadata/graphql';

export const COMMAND_MENU_ITEM_SECTION_BY_ENGINE_COMPONENT_KEY = {
  [EngineComponentKey.ADD_TO_FAVORITES]: 'SELECTION',
  [EngineComponentKey.REMOVE_FROM_FAVORITES]: 'SELECTION',
  [EngineComponentKey.DELETE_RECORDS]: 'SELECTION',
  [EngineComponentKey.RESTORE_RECORDS]: 'SELECTION',
  [EngineComponentKey.DESTROY_RECORDS]: 'SELECTION',
  [EngineComponentKey.EXPORT_RECORDS]: 'SELECTION',
  [EngineComponentKey.EXPORT_NOTE_TO_PDF]: 'SELECTION',
  [EngineComponentKey.UPDATE_MULTIPLE_RECORDS]: 'SELECTION',
  [EngineComponentKey.MERGE_MULTIPLE_RECORDS]: 'SELECTION',
  [EngineComponentKey.REPLY_TO_EMAIL_THREAD]: 'SELECTION',
  [EngineComponentKey.EDIT_DASHBOARD_LAYOUT]: 'SELECTION',
  [EngineComponentKey.SAVE_DASHBOARD_LAYOUT]: 'SELECTION',
  [EngineComponentKey.CANCEL_DASHBOARD_LAYOUT]: 'SELECTION',
  [EngineComponentKey.DUPLICATE_DASHBOARD]: 'SELECTION',
  [EngineComponentKey.DUPLICATE_MESSAGE_LIST]: 'SELECTION',
  [EngineComponentKey.DUPLICATE_MESSAGE_CAMPAIGN]: 'SELECTION',
  [EngineComponentKey.DUPLICATE_WORKFLOW]: 'SELECTION',
  [EngineComponentKey.ACTIVATE_WORKFLOW]: 'SELECTION',
  [EngineComponentKey.DEACTIVATE_WORKFLOW]: 'SELECTION',
  [EngineComponentKey.DISCARD_DRAFT_WORKFLOW]: 'SELECTION',
  [EngineComponentKey.TEST_WORKFLOW]: 'SELECTION',
  [EngineComponentKey.ADD_NODE_WORKFLOW]: 'SELECTION',
  [EngineComponentKey.TIDY_UP_WORKFLOW]: 'SELECTION',
  [EngineComponentKey.SEE_ACTIVE_VERSION_WORKFLOW]: 'SELECTION',
  [EngineComponentKey.SEE_RUNS_WORKFLOW]: 'SELECTION',
  [EngineComponentKey.SEE_VERSIONS_WORKFLOW]: 'SELECTION',
  [EngineComponentKey.SEE_VERSION_WORKFLOW_RUN]: 'SELECTION',
  [EngineComponentKey.SEE_WORKFLOW_WORKFLOW_RUN]: 'SELECTION',
  [EngineComponentKey.STOP_WORKFLOW_RUN]: 'SELECTION',
  [EngineComponentKey.RETRY_WORKFLOW_RUN]: 'SELECTION',
  [EngineComponentKey.SEE_RUNS_WORKFLOW_VERSION]: 'SELECTION',
  [EngineComponentKey.SEE_WORKFLOW_WORKFLOW_VERSION]: 'SELECTION',
  [EngineComponentKey.SEE_VERSIONS_WORKFLOW_VERSION]: 'SELECTION',
  [EngineComponentKey.USE_AS_DRAFT_WORKFLOW_VERSION]: 'SELECTION',
  [EngineComponentKey.SEND_MESSAGE_CAMPAIGN]: 'SELECTION',
  [EngineComponentKey.SEND_MESSAGE_CAMPAIGN_TEST]: 'SELECTION',
  [EngineComponentKey.CANCEL_MESSAGE_CAMPAIGN]: 'SELECTION',
  [EngineComponentKey.EMAIL_BLOCK_SETTINGS]: 'SELECTION',
  [EngineComponentKey.DELETE_SINGLE_RECORD]: 'SELECTION',
  [EngineComponentKey.DELETE_MULTIPLE_RECORDS]: 'SELECTION',
  [EngineComponentKey.RESTORE_SINGLE_RECORD]: 'SELECTION',
  [EngineComponentKey.RESTORE_MULTIPLE_RECORDS]: 'SELECTION',
  [EngineComponentKey.DESTROY_SINGLE_RECORD]: 'SELECTION',
  [EngineComponentKey.DESTROY_MULTIPLE_RECORDS]: 'SELECTION',
  [EngineComponentKey.EXPORT_FROM_RECORD_INDEX]: 'SELECTION',
  [EngineComponentKey.EXPORT_FROM_RECORD_SHOW]: 'SELECTION',
  [EngineComponentKey.EXPORT_MULTIPLE_RECORDS]: 'SELECTION',

  [EngineComponentKey.CREATE_NEW_RECORD]: 'THIS_VIEW',
  [EngineComponentKey.CREATE_NEW_VIEW]: 'THIS_VIEW',
  [EngineComponentKey.IMPORT_RECORDS]: 'THIS_VIEW',
  [EngineComponentKey.EXPORT_VIEW]: 'THIS_VIEW',
  [EngineComponentKey.SEE_DELETED_RECORDS]: 'THIS_VIEW',
  [EngineComponentKey.HIDE_DELETED_RECORDS]: 'THIS_VIEW',
  [EngineComponentKey.EDIT_RECORD_PAGE_LAYOUT]: 'THIS_VIEW',

  [EngineComponentKey.ASK_AI]: 'ASK_AND_FIND',
  [EngineComponentKey.SEARCH_RECORDS]: 'ASK_AND_FIND',
  [EngineComponentKey.VIEW_PREVIOUS_AI_CHATS]: 'ASK_AND_FIND',

  [EngineComponentKey.NAVIGATION]: 'GO_TO',
  [EngineComponentKey.NAVIGATE_TO_NEXT_RECORD]: 'GO_TO',
  [EngineComponentKey.NAVIGATE_TO_PREVIOUS_RECORD]: 'GO_TO',
  [EngineComponentKey.GO_TO_PEOPLE]: 'GO_TO',
  [EngineComponentKey.GO_TO_COMPANIES]: 'GO_TO',
  [EngineComponentKey.GO_TO_DASHBOARDS]: 'GO_TO',
  [EngineComponentKey.GO_TO_OPPORTUNITIES]: 'GO_TO',
  [EngineComponentKey.GO_TO_SETTINGS]: 'GO_TO',
  [EngineComponentKey.GO_TO_TASKS]: 'GO_TO',
  [EngineComponentKey.GO_TO_NOTES]: 'GO_TO',
  [EngineComponentKey.GO_TO_WORKFLOWS]: 'GO_TO',
  [EngineComponentKey.GO_TO_RUNS]: 'GO_TO',

  [EngineComponentKey.SEARCH_RECORDS_FALLBACK]: 'FALLBACK',
} as const satisfies Record<
  Exclude<EngineComponentKey, (typeof AMBIGUOUS_ENGINE_COMPONENT_KEYS)[number]>,
  CommandMenuItemSection
>;
