export const EXCLUDED_MIDDLEWARE_OPERATIONS = [
  'GetClientConfig',
  'GetWorkspaceFromInviteHash',
  'Track',
  'TrackAnalytics',
  'AuditTrack',
  'CheckUserExists',
  'GetLoginTokenFromCredentials',
  'GetAuthTokensFromLoginToken',
  'GetLoginTokenFromEmailVerificationToken',
  'ResendEmailVerificationToken',
  'SignUp',
  'RenewToken',
  'EmailPasswordResetLink',
  'ValidatePasswordResetToken',
  'UpdatePasswordViaResetToken',
  'IntrospectionQuery',
  'ExchangeAuthorizationCode',
  'GetAuthorizationUrlForSSO',
  'GetPublicWorkspaceDataByDomain',
] as const;
