import {
  defineObject,
  FieldType,
  OnDeleteAction,
  RelationType,
} from 'twenty-sdk/define';

import {
  POSITION_SPECIFICATION_APPROVED_DATE_FIELD_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_COMPENSATION_RANGE_HIGH_FIELD_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_COMPENSATION_RANGE_LOW_FIELD_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_EMPLOYMENT_TYPE_CONTRACT,
  POSITION_SPECIFICATION_EMPLOYMENT_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_EMPLOYMENT_TYPE_INTERIM,
  POSITION_SPECIFICATION_EMPLOYMENT_TYPE_OPTION_CONTRACT_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_EMPLOYMENT_TYPE_OPTION_INTERIM_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_EMPLOYMENT_TYPE_OPTION_PERMANENT_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_EMPLOYMENT_TYPE_PERMANENT,
  POSITION_SPECIFICATION_LOCATION_FIELD_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_LOCATION_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_LOCATION_TYPE_HYBRID,
  POSITION_SPECIFICATION_LOCATION_TYPE_ONSITE,
  POSITION_SPECIFICATION_LOCATION_TYPE_OPTION_HYBRID_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_LOCATION_TYPE_OPTION_ONSITE_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_LOCATION_TYPE_OPTION_REMOTE_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_LOCATION_TYPE_REMOTE,
  POSITION_SPECIFICATION_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_OBJECT_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_REPORTING_LINE_FIELD_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_ROLE_SUMMARY_FIELD_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_ROLE_TITLE_FIELD_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_SEARCH_ASSIGNMENT_FIELD_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_STATUS_APPROVED,
  POSITION_SPECIFICATION_STATUS_CLIENT_PENDING,
  POSITION_SPECIFICATION_STATUS_DRAFT,
  POSITION_SPECIFICATION_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_STATUS_IN_REVIEW,
  POSITION_SPECIFICATION_STATUS_OPTION_APPROVED_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_STATUS_OPTION_CLIENT_PENDING_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_STATUS_OPTION_DRAFT_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_STATUS_OPTION_IN_REVIEW_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_STATUS_OPTION_REVISED_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_STATUS_REVISED,
  POSITION_SPECIFICATION_VERSION_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_ASSIGNMENT_OBJECT_UNIVERSAL_IDENTIFIER,
  SPECIFICATIONS_ON_SEARCH_ASSIGNMENT_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: POSITION_SPECIFICATION_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'positionSpecification',
  namePlural: 'positionSpecifications',
  labelSingular: 'Position Specification',
  labelPlural: 'Position Specifications',
  description: 'A position specification document for an executive search.',
  icon: 'IconFileText',
  labelIdentifierFieldMetadataUniversalIdentifier:
    POSITION_SPECIFICATION_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier:
        POSITION_SPECIFICATION_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Name of the position specification.',
      icon: 'IconAbc',
    },
    {
      universalIdentifier:
        POSITION_SPECIFICATION_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      description: 'Current status of the position specification.',
      icon: 'IconProgress',
      defaultValue: `'${POSITION_SPECIFICATION_STATUS_DRAFT}'`,
      options: [
        {
          id: POSITION_SPECIFICATION_STATUS_OPTION_DRAFT_UNIVERSAL_IDENTIFIER,
          value: POSITION_SPECIFICATION_STATUS_DRAFT,
          label: 'Draft',
          color: 'gray',
          position: 0,
        },
        {
          id: POSITION_SPECIFICATION_STATUS_OPTION_IN_REVIEW_UNIVERSAL_IDENTIFIER,
          value: POSITION_SPECIFICATION_STATUS_IN_REVIEW,
          label: 'In Review',
          color: 'blue',
          position: 1,
        },
        {
          id: POSITION_SPECIFICATION_STATUS_OPTION_CLIENT_PENDING_UNIVERSAL_IDENTIFIER,
          value: POSITION_SPECIFICATION_STATUS_CLIENT_PENDING,
          label: 'Client Pending',
          color: 'yellow',
          position: 2,
        },
        {
          id: POSITION_SPECIFICATION_STATUS_OPTION_APPROVED_UNIVERSAL_IDENTIFIER,
          value: POSITION_SPECIFICATION_STATUS_APPROVED,
          label: 'Approved',
          color: 'green',
          position: 3,
        },
        {
          id: POSITION_SPECIFICATION_STATUS_OPTION_REVISED_UNIVERSAL_IDENTIFIER,
          value: POSITION_SPECIFICATION_STATUS_REVISED,
          label: 'Revised',
          color: 'orange',
          position: 4,
        },
      ],
    },
    {
      universalIdentifier:
        POSITION_SPECIFICATION_ROLE_TITLE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'roleTitle',
      label: 'Role title',
      description: 'The title of the role being specified.',
      icon: 'IconUser',
      isNullable: true,
    },
    {
      universalIdentifier:
        POSITION_SPECIFICATION_ROLE_SUMMARY_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RICH_TEXT,
      name: 'roleSummary',
      label: 'Role summary',
      description: 'Summary of the role and its key responsibilities.',
      icon: 'IconNotes',
      isNullable: true,
    },
    {
      universalIdentifier:
        POSITION_SPECIFICATION_REPORTING_LINE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'reportingLine',
      label: 'Reporting line',
      description: 'Who this role reports to.',
      icon: 'IconHierarchy2',
      isNullable: true,
    },
    {
      universalIdentifier:
        POSITION_SPECIFICATION_LOCATION_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'location',
      label: 'Location',
      description: 'Primary work location for the role.',
      icon: 'IconMapPin',
      isNullable: true,
    },
    {
      universalIdentifier:
        POSITION_SPECIFICATION_LOCATION_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'locationType',
      label: 'Location type',
      description: 'Type of work location arrangement.',
      icon: 'IconBuilding',
      options: [
        {
          id: POSITION_SPECIFICATION_LOCATION_TYPE_OPTION_ONSITE_UNIVERSAL_IDENTIFIER,
          value: POSITION_SPECIFICATION_LOCATION_TYPE_ONSITE,
          label: 'On-site',
          color: 'blue',
          position: 0,
        },
        {
          id: POSITION_SPECIFICATION_LOCATION_TYPE_OPTION_HYBRID_UNIVERSAL_IDENTIFIER,
          value: POSITION_SPECIFICATION_LOCATION_TYPE_HYBRID,
          label: 'Hybrid',
          color: 'yellow',
          position: 1,
        },
        {
          id: POSITION_SPECIFICATION_LOCATION_TYPE_OPTION_REMOTE_UNIVERSAL_IDENTIFIER,
          value: POSITION_SPECIFICATION_LOCATION_TYPE_REMOTE,
          label: 'Remote',
          color: 'green',
          position: 2,
        },
      ],
    },
    {
      universalIdentifier:
        POSITION_SPECIFICATION_EMPLOYMENT_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'employmentType',
      label: 'Employment type',
      description: 'Type of employment arrangement.',
      icon: 'IconBriefcase',
      options: [
        {
          id: POSITION_SPECIFICATION_EMPLOYMENT_TYPE_OPTION_PERMANENT_UNIVERSAL_IDENTIFIER,
          value: POSITION_SPECIFICATION_EMPLOYMENT_TYPE_PERMANENT,
          label: 'Permanent',
          color: 'blue',
          position: 0,
        },
        {
          id: POSITION_SPECIFICATION_EMPLOYMENT_TYPE_OPTION_INTERIM_UNIVERSAL_IDENTIFIER,
          value: POSITION_SPECIFICATION_EMPLOYMENT_TYPE_INTERIM,
          label: 'Interim',
          color: 'orange',
          position: 1,
        },
        {
          id: POSITION_SPECIFICATION_EMPLOYMENT_TYPE_OPTION_CONTRACT_UNIVERSAL_IDENTIFIER,
          value: POSITION_SPECIFICATION_EMPLOYMENT_TYPE_CONTRACT,
          label: 'Contract',
          color: 'yellow',
          position: 2,
        },
      ],
    },
    {
      universalIdentifier:
        POSITION_SPECIFICATION_COMPENSATION_RANGE_LOW_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.CURRENCY,
      name: 'compensationRangeLow',
      label: 'Compensation range low',
      description: 'Low end of the compensation range.',
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    {
      universalIdentifier:
        POSITION_SPECIFICATION_COMPENSATION_RANGE_HIGH_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.CURRENCY,
      name: 'compensationRangeHigh',
      label: 'Compensation range high',
      description: 'High end of the compensation range.',
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    {
      universalIdentifier:
        POSITION_SPECIFICATION_VERSION_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'version',
      label: 'Version',
      description: 'Version number of the position specification.',
      icon: 'IconNumber',
      defaultValue: 1,
    },
    {
      universalIdentifier:
        POSITION_SPECIFICATION_APPROVED_DATE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE,
      name: 'approvedDate',
      label: 'Approved date',
      description: 'Date the position specification was approved.',
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
    {
      universalIdentifier:
        POSITION_SPECIFICATION_SEARCH_ASSIGNMENT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RELATION,
      name: 'searchAssignment',
      label: 'Search assignment',
      description: 'The search assignment this specification belongs to.',
      icon: 'IconBriefcase',
      relationTargetObjectMetadataUniversalIdentifier:
        SEARCH_ASSIGNMENT_OBJECT_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier:
        SPECIFICATIONS_ON_SEARCH_ASSIGNMENT_FIELD_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.CASCADE,
        joinColumnName: 'searchAssignmentId',
      },
    },
  ],
});
