import {
  defineObject,
  FieldType,
  OnDeleteAction,
  RelationType,
} from 'twenty-sdk/define';

import {
  CRITERIA_ON_POSITION_SPECIFICATION_FIELD_UNIVERSAL_IDENTIFIER,
  POSITION_SPECIFICATION_OBJECT_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_CATEGORY_DISQUALIFIER,
  SEARCH_CRITERION_CATEGORY_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_CATEGORY_MUST_HAVE,
  SEARCH_CRITERION_CATEGORY_NICE_TO_HAVE,
  SEARCH_CRITERION_CATEGORY_OPTION_DISQUALIFIER_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_CATEGORY_OPTION_MUST_HAVE_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_CATEGORY_OPTION_NICE_TO_HAVE_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_CRITERION_TYPE_CERTIFICATION,
  SEARCH_CRITERION_CRITERION_TYPE_CULTURAL,
  SEARCH_CRITERION_CRITERION_TYPE_EDUCATION,
  SEARCH_CRITERION_CRITERION_TYPE_EXPERIENCE,
  SEARCH_CRITERION_CRITERION_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_CRITERION_TYPE_FUNCTIONAL,
  SEARCH_CRITERION_CRITERION_TYPE_INDUSTRY,
  SEARCH_CRITERION_CRITERION_TYPE_LEADERSHIP,
  SEARCH_CRITERION_CRITERION_TYPE_OPTION_CERTIFICATION_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_CRITERION_TYPE_OPTION_CULTURAL_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_CRITERION_TYPE_OPTION_EDUCATION_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_CRITERION_TYPE_OPTION_EXPERIENCE_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_CRITERION_TYPE_OPTION_FUNCTIONAL_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_CRITERION_TYPE_OPTION_INDUSTRY_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_CRITERION_TYPE_OPTION_LEADERSHIP_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_CRITERION_TYPE_OPTION_SKILL_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_CRITERION_TYPE_SKILL,
  SEARCH_CRITERION_DESCRIPTION_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_OBJECT_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_POSITION_SPECIFICATION_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_WEIGHT_CRITICAL,
  SEARCH_CRITERION_WEIGHT_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_WEIGHT_IMPORTANT,
  SEARCH_CRITERION_WEIGHT_OPTION_CRITICAL_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_WEIGHT_OPTION_IMPORTANT_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_WEIGHT_OPTION_PREFERRED_UNIVERSAL_IDENTIFIER,
  SEARCH_CRITERION_WEIGHT_PREFERRED,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: SEARCH_CRITERION_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'searchCriterion',
  namePlural: 'searchCriteria',
  labelSingular: 'Search Criterion',
  labelPlural: 'Search Criteria',
  description: 'A search criterion for evaluating candidates.',
  icon: 'IconListCheck',
  labelIdentifierFieldMetadataUniversalIdentifier:
    SEARCH_CRITERION_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: SEARCH_CRITERION_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Criterion',
      description: 'Name of the search criterion.',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: SEARCH_CRITERION_CATEGORY_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'category',
      label: 'Category',
      description: 'Category of the search criterion.',
      icon: 'IconCategory',
      options: [
        {
          id: SEARCH_CRITERION_CATEGORY_OPTION_MUST_HAVE_UNIVERSAL_IDENTIFIER,
          value: SEARCH_CRITERION_CATEGORY_MUST_HAVE,
          label: 'Must Have',
          color: 'red',
          position: 0,
        },
        {
          id: SEARCH_CRITERION_CATEGORY_OPTION_NICE_TO_HAVE_UNIVERSAL_IDENTIFIER,
          value: SEARCH_CRITERION_CATEGORY_NICE_TO_HAVE,
          label: 'Nice to Have',
          color: 'blue',
          position: 1,
        },
        {
          id: SEARCH_CRITERION_CATEGORY_OPTION_DISQUALIFIER_UNIVERSAL_IDENTIFIER,
          value: SEARCH_CRITERION_CATEGORY_DISQUALIFIER,
          label: 'Disqualifier',
          color: 'orange',
          position: 2,
        },
      ],
    },
    {
      universalIdentifier:
        SEARCH_CRITERION_CRITERION_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'criterionType',
      label: 'Criterion type',
      description: 'Type of the search criterion.',
      icon: 'IconFilter',
      options: [
        {
          id: SEARCH_CRITERION_CRITERION_TYPE_OPTION_EXPERIENCE_UNIVERSAL_IDENTIFIER,
          value: SEARCH_CRITERION_CRITERION_TYPE_EXPERIENCE,
          label: 'Experience',
          color: 'blue',
          position: 0,
        },
        {
          id: SEARCH_CRITERION_CRITERION_TYPE_OPTION_EDUCATION_UNIVERSAL_IDENTIFIER,
          value: SEARCH_CRITERION_CRITERION_TYPE_EDUCATION,
          label: 'Education',
          color: 'green',
          position: 1,
        },
        {
          id: SEARCH_CRITERION_CRITERION_TYPE_OPTION_SKILL_UNIVERSAL_IDENTIFIER,
          value: SEARCH_CRITERION_CRITERION_TYPE_SKILL,
          label: 'Skill',
          color: 'blue',
          position: 2,
        },
        {
          id: SEARCH_CRITERION_CRITERION_TYPE_OPTION_CERTIFICATION_UNIVERSAL_IDENTIFIER,
          value: SEARCH_CRITERION_CRITERION_TYPE_CERTIFICATION,
          label: 'Certification',
          color: 'orange',
          position: 3,
        },
        {
          id: SEARCH_CRITERION_CRITERION_TYPE_OPTION_LEADERSHIP_UNIVERSAL_IDENTIFIER,
          value: SEARCH_CRITERION_CRITERION_TYPE_LEADERSHIP,
          label: 'Leadership',
          color: 'yellow',
          position: 4,
        },
        {
          id: SEARCH_CRITERION_CRITERION_TYPE_OPTION_INDUSTRY_UNIVERSAL_IDENTIFIER,
          value: SEARCH_CRITERION_CRITERION_TYPE_INDUSTRY,
          label: 'Industry',
          color: 'purple',
          position: 5,
        },
        {
          id: SEARCH_CRITERION_CRITERION_TYPE_OPTION_FUNCTIONAL_UNIVERSAL_IDENTIFIER,
          value: SEARCH_CRITERION_CRITERION_TYPE_FUNCTIONAL,
          label: 'Functional',
          color: 'green',
          position: 6,
        },
        {
          id: SEARCH_CRITERION_CRITERION_TYPE_OPTION_CULTURAL_UNIVERSAL_IDENTIFIER,
          value: SEARCH_CRITERION_CRITERION_TYPE_CULTURAL,
          label: 'Cultural',
          color: 'pink',
          position: 7,
        },
      ],
    },
    {
      universalIdentifier: SEARCH_CRITERION_WEIGHT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'weight',
      label: 'Weight',
      description: 'Importance weight of the criterion.',
      icon: 'IconWeight',
      options: [
        {
          id: SEARCH_CRITERION_WEIGHT_OPTION_CRITICAL_UNIVERSAL_IDENTIFIER,
          value: SEARCH_CRITERION_WEIGHT_CRITICAL,
          label: 'Critical',
          color: 'red',
          position: 0,
        },
        {
          id: SEARCH_CRITERION_WEIGHT_OPTION_IMPORTANT_UNIVERSAL_IDENTIFIER,
          value: SEARCH_CRITERION_WEIGHT_IMPORTANT,
          label: 'Important',
          color: 'orange',
          position: 1,
        },
        {
          id: SEARCH_CRITERION_WEIGHT_OPTION_PREFERRED_UNIVERSAL_IDENTIFIER,
          value: SEARCH_CRITERION_WEIGHT_PREFERRED,
          label: 'Preferred',
          color: 'blue',
          position: 2,
        },
      ],
    },
    {
      universalIdentifier:
        SEARCH_CRITERION_DESCRIPTION_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RICH_TEXT,
      name: 'description',
      label: 'Description',
      description: 'Detailed description of the criterion.',
      icon: 'IconNotes',
      isNullable: true,
    },
    {
      universalIdentifier:
        SEARCH_CRITERION_POSITION_SPECIFICATION_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RELATION,
      name: 'positionSpecification',
      label: 'Position specification',
      description: 'The position specification this criterion belongs to.',
      icon: 'IconFileText',
      relationTargetObjectMetadataUniversalIdentifier:
        POSITION_SPECIFICATION_OBJECT_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier:
        CRITERIA_ON_POSITION_SPECIFICATION_FIELD_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.CASCADE,
        joinColumnName: 'positionSpecificationId',
      },
    },
  ],
});
