import {
  OnDeleteAction,
  RelationType,
  STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS,
  defineObject,
  FieldType,
} from 'twenty-sdk/define';

import {
  ENGAGEMENT_TYPE_EMERGENCY,
  ENGAGEMENT_TYPE_INTERIM,
  ENGAGEMENT_TYPE_OPTION_EMERGENCY_UNIVERSAL_IDENTIFIER,
  ENGAGEMENT_TYPE_OPTION_INTERIM_UNIVERSAL_IDENTIFIER,
  ENGAGEMENT_TYPE_OPTION_RETAINED_UNIVERSAL_IDENTIFIER,
  ENGAGEMENT_TYPE_RETAINED,
  ENGAGEMENT_TERMS_ON_COMPANY_FIELD_UNIVERSAL_IDENTIFIER,
  ENGAGEMENT_TERMS_ON_OPPORTUNITY_FIELD_UNIVERSAL_IDENTIFIER,
  FEE_STRUCTURE_FLAT_FEE,
  FEE_STRUCTURE_HOURLY,
  FEE_STRUCTURE_OPTION_FLAT_FEE_UNIVERSAL_IDENTIFIER,
  FEE_STRUCTURE_OPTION_HOURLY_UNIVERSAL_IDENTIFIER,
  FEE_STRUCTURE_OPTION_PERCENTAGE_OF_COMPENSATION_UNIVERSAL_IDENTIFIER,
  FEE_STRUCTURE_OPTION_TIERED_UNIVERSAL_IDENTIFIER,
  FEE_STRUCTURE_PERCENTAGE_OF_COMPENSATION,
  FEE_STRUCTURE_TIERED,
  SEARCH_ENGAGEMENT_TERMS_COMPANY_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_ENGAGEMENT_TERMS_CURRENCY_CODE_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_ENGAGEMENT_TERMS_ENGAGEMENT_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_ENGAGEMENT_TERMS_EXCLUSIVITY_END_DATE_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_ENGAGEMENT_TERMS_FEE_PERCENTAGE_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_ENGAGEMENT_TERMS_FEE_STRUCTURE_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_ENGAGEMENT_TERMS_FLAT_FEE_AMOUNT_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_ENGAGEMENT_TERMS_GUARANTEE_PERIOD_MONTHS_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_ENGAGEMENT_TERMS_IS_EXCLUSIVE_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_ENGAGEMENT_TERMS_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_ENGAGEMENT_TERMS_NOTES_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_ENGAGEMENT_TERMS_OBJECT_UNIVERSAL_IDENTIFIER,
  SEARCH_ENGAGEMENT_TERMS_OPPORTUNITY_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_ENGAGEMENT_TERMS_RETAINER_AMOUNT_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_ENGAGEMENT_TERMS_RETAINER_INSTALLMENTS_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_ENGAGEMENT_TERMS_SIGNED_DATE_FIELD_UNIVERSAL_IDENTIFIER,
  SEARCH_ENGAGEMENT_TERMS_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  STATUS_DRAFT,
  STATUS_EXPIRED,
  STATUS_OPTION_DRAFT_UNIVERSAL_IDENTIFIER,
  STATUS_OPTION_EXPIRED_UNIVERSAL_IDENTIFIER,
  STATUS_OPTION_PROPOSED_UNIVERSAL_IDENTIFIER,
  STATUS_OPTION_SIGNED_UNIVERSAL_IDENTIFIER,
  STATUS_OPTION_TERMINATED_UNIVERSAL_IDENTIFIER,
  STATUS_PROPOSED,
  STATUS_SIGNED,
  STATUS_TERMINATED,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: SEARCH_ENGAGEMENT_TERMS_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'searchEngagementTerms',
  namePlural: 'searchEngagementTerms',
  labelSingular: 'Engagement terms',
  labelPlural: 'Engagement terms',
  description: 'Commercial terms for a retained-search engagement.',
  icon: 'IconCoins',
  labelIdentifierFieldMetadataUniversalIdentifier:
    SEARCH_ENGAGEMENT_TERMS_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier:
        SEARCH_ENGAGEMENT_TERMS_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Engagement term name or reference.',
      icon: 'IconAbc',
    },
    {
      universalIdentifier:
        SEARCH_ENGAGEMENT_TERMS_ENGAGEMENT_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'engagementType',
      label: 'Engagement type',
      description: 'Type of engagement.',
      icon: 'IconCoins',
      defaultValue: `'${ENGAGEMENT_TYPE_RETAINED}'`,
      options: [
        {
          id: ENGAGEMENT_TYPE_OPTION_RETAINED_UNIVERSAL_IDENTIFIER,
          value: ENGAGEMENT_TYPE_RETAINED,
          label: 'Retained',
          color: 'blue',
          position: 0,
        },
        {
          id: ENGAGEMENT_TYPE_OPTION_EMERGENCY_UNIVERSAL_IDENTIFIER,
          value: ENGAGEMENT_TYPE_EMERGENCY,
          label: 'Emergency',
          color: 'red',
          position: 1,
        },
        {
          id: ENGAGEMENT_TYPE_OPTION_INTERIM_UNIVERSAL_IDENTIFIER,
          value: ENGAGEMENT_TYPE_INTERIM,
          label: 'Interim',
          color: 'orange',
          position: 2,
        },
      ],
    },
    {
      universalIdentifier:
        SEARCH_ENGAGEMENT_TERMS_FEE_STRUCTURE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'feeStructure',
      label: 'Fee structure',
      description: 'How the fee is calculated.',
      icon: 'IconCurrencyDollar',
      options: [
        {
          id: FEE_STRUCTURE_OPTION_PERCENTAGE_OF_COMPENSATION_UNIVERSAL_IDENTIFIER,
          value: FEE_STRUCTURE_PERCENTAGE_OF_COMPENSATION,
          label: 'Percentage of compensation',
          color: 'blue',
          position: 0,
        },
        {
          id: FEE_STRUCTURE_OPTION_FLAT_FEE_UNIVERSAL_IDENTIFIER,
          value: FEE_STRUCTURE_FLAT_FEE,
          label: 'Flat fee',
          color: 'green',
          position: 1,
        },
        {
          id: FEE_STRUCTURE_OPTION_TIERED_UNIVERSAL_IDENTIFIER,
          value: FEE_STRUCTURE_TIERED,
          label: 'Tiered',
          color: 'orange',
          position: 2,
        },
        {
          id: FEE_STRUCTURE_OPTION_HOURLY_UNIVERSAL_IDENTIFIER,
          value: FEE_STRUCTURE_HOURLY,
          label: 'Hourly',
          color: 'red',
          position: 3,
        },
      ],
    },
    {
      universalIdentifier:
        SEARCH_ENGAGEMENT_TERMS_FEE_PERCENTAGE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'feePercentage',
      label: 'Fee percentage',
      description: 'Fee as a percentage of compensation (e.g. 33.3).',
      icon: 'IconPercentage',
    },
    {
      universalIdentifier:
        SEARCH_ENGAGEMENT_TERMS_FLAT_FEE_AMOUNT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.CURRENCY,
      name: 'flatFeeAmount',
      label: 'Flat fee amount',
      description: 'Flat fee amount.',
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    {
      universalIdentifier:
        SEARCH_ENGAGEMENT_TERMS_RETAINER_AMOUNT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.CURRENCY,
      name: 'retainerAmount',
      label: 'Retainer amount',
      description: 'Retainer amount.',
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    {
      universalIdentifier:
        SEARCH_ENGAGEMENT_TERMS_RETAINER_INSTALLMENTS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'retainerInstallments',
      label: 'Retainer installments',
      description: 'Number of retainer installments.',
      icon: 'IconNumber',
      isNullable: true,
    },
    {
      universalIdentifier:
        SEARCH_ENGAGEMENT_TERMS_IS_EXCLUSIVE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.BOOLEAN,
      name: 'isExclusive',
      label: 'Exclusive',
      description: 'Whether the engagement is exclusive.',
      icon: 'IconLock',
      defaultValue: true,
    },
    {
      universalIdentifier:
        SEARCH_ENGAGEMENT_TERMS_EXCLUSIVITY_END_DATE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE,
      name: 'exclusivityEndDate',
      label: 'Exclusivity end date',
      description: 'End date of the exclusivity period.',
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
    {
      universalIdentifier:
        SEARCH_ENGAGEMENT_TERMS_GUARANTEE_PERIOD_MONTHS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'guaranteePeriodMonths',
      label: 'Guarantee period (months)',
      description: 'Length of the guarantee period in months.',
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
    {
      universalIdentifier:
        SEARCH_ENGAGEMENT_TERMS_CURRENCY_CODE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'currencyCode',
      label: 'Currency code',
      description: 'Currency code (e.g. USD).',
      icon: 'IconCurrencyDollar',
    },
    {
      universalIdentifier:
        SEARCH_ENGAGEMENT_TERMS_SIGNED_DATE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE,
      name: 'signedDate',
      label: 'Signed date',
      description: 'Date the engagement terms were signed.',
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
    {
      universalIdentifier:
        SEARCH_ENGAGEMENT_TERMS_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      description: 'Current status of the engagement.',
      icon: 'IconProgress',
      defaultValue: `'${STATUS_DRAFT}'`,
      options: [
        {
          id: STATUS_OPTION_DRAFT_UNIVERSAL_IDENTIFIER,
          value: STATUS_DRAFT,
          label: 'Draft',
          color: 'gray',
          position: 0,
        },
        {
          id: STATUS_OPTION_PROPOSED_UNIVERSAL_IDENTIFIER,
          value: STATUS_PROPOSED,
          label: 'Proposed',
          color: 'blue',
          position: 1,
        },
        {
          id: STATUS_OPTION_SIGNED_UNIVERSAL_IDENTIFIER,
          value: STATUS_SIGNED,
          label: 'Signed',
          color: 'green',
          position: 2,
        },
        {
          id: STATUS_OPTION_EXPIRED_UNIVERSAL_IDENTIFIER,
          value: STATUS_EXPIRED,
          label: 'Expired',
          color: 'red',
          position: 3,
        },
        {
          id: STATUS_OPTION_TERMINATED_UNIVERSAL_IDENTIFIER,
          value: STATUS_TERMINATED,
          label: 'Terminated',
          color: 'orange',
          position: 4,
        },
      ],
    },
    {
      universalIdentifier:
        SEARCH_ENGAGEMENT_TERMS_NOTES_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RICH_TEXT,
      name: 'notes',
      label: 'Notes',
      description: 'Additional notes about the engagement.',
      icon: 'IconNotes',
      isNullable: true,
    },
    {
      universalIdentifier:
        SEARCH_ENGAGEMENT_TERMS_COMPANY_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RELATION,
      name: 'company',
      label: 'Client',
      description: 'Client company for this engagement.',
      icon: 'IconBuildingSkyscraper',
      relationTargetFieldMetadataUniversalIdentifier:
        ENGAGEMENT_TERMS_ON_COMPANY_FIELD_UNIVERSAL_IDENTIFIER,
      relationTargetObjectMetadataUniversalIdentifier:
        STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.company.universalIdentifier,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'companyId',
      },
    },
    {
      universalIdentifier:
        SEARCH_ENGAGEMENT_TERMS_OPPORTUNITY_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RELATION,
      name: 'opportunity',
      label: 'Opportunity',
      description: 'Opportunity related to this engagement.',
      icon: 'IconTarget',
      relationTargetFieldMetadataUniversalIdentifier:
        ENGAGEMENT_TERMS_ON_OPPORTUNITY_FIELD_UNIVERSAL_IDENTIFIER,
      relationTargetObjectMetadataUniversalIdentifier:
        STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.opportunity.universalIdentifier,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'opportunityId',
      },
    },
  ],
});
