import { Company } from '@/companies/types/Company';
import { Favorite } from '@/favorites/types/Favorite';
import { FieldMetadataItem } from '@/object-metadata/types/FieldMetadataItem';
import { ObjectMetadataItem } from '@/object-metadata/types/ObjectMetadataItem';
import { WorkspaceMember } from '@/workspace-member/types/WorkspaceMember';

import { mockedUsersData } from './users';

type MockedCompany = Pick<
  Company,
  | 'id'
  | 'name'
  | 'domainName'
  | 'createdAt'
  | 'address'
  | 'employees'
  | 'linkedinUrl'
  | 'xUrl'
  | 'annualRecurringRevenue'
  | 'idealCustomerProfile'
  | 'accountOwnerId'
> & {
  accountOwner: Pick<WorkspaceMember, 'id' | 'avatarUrl' | 'name'> | null;
  Favorite: Pick<Favorite, 'id'> | null;
};

export const mockedCompaniesData: Array<MockedCompany> = [
  {
    id: '89bb825c-171e-4bcc-9cf7-43448d6fb278',
    domainName: 'airbnb.com',
    name: 'Airbnb',
    createdAt: '2023-04-26T10:08:54.724515+00:00',
    address: '17 rue de clignancourt',
    employees: 12,
    linkedinUrl: {
      url: 'https://www.linkedin.com/company/airbnb/',
      label: 'https://www.linkedin.com/company/airbnb/',
    },
    xUrl: {
      url: 'https://twitter.com/airbnb',
      label: 'https://twitter.com/airbnb',
    },
    annualRecurringRevenue: { amountMicros: 5000000, currencyCode: 'USD' },
    idealCustomerProfile: true,
    Favorite: null,
    accountOwnerId: mockedUsersData[0].id,
    accountOwner: {
      name: {
        firstName: 'Charles',
        lastName: 'Test',
      },
      avatarUrl: null,
      id: mockedUsersData[0].id,
    },
  },
  {
    id: 'b396e6b9-dc5c-4643-bcff-61b6cf7523ae',
    domainName: 'aircall.io',
    name: 'Aircall',
    createdAt: '2023-04-26T10:12:42.33625+00:00',
    address: '',
    employees: 1,
    accountOwnerId: null,
    linkedinUrl: {
      url: 'https://www.linkedin.com/company/aircall/',
      label: 'https://www.linkedin.com/company/aircall/',
    },
    xUrl: {
      url: 'https://twitter.com/aircall',
      label: 'https://twitter.com/aircall',
    },
    annualRecurringRevenue: { amountMicros: 500000, currencyCode: 'USD' },
    idealCustomerProfile: false,
    accountOwner: null,
    Favorite: null,
  },
  {
    id: 'a674fa6c-1455-4c57-afaf-dd5dc086361d',
    domainName: 'algolia.com',
    name: 'Algolia',
    createdAt: '2023-04-26T10:10:32.530184+00:00',
    address: '',
    employees: 1,
    linkedinUrl: {
      url: 'https://www.linkedin.com/company/algolia/',
      label: 'https://www.linkedin.com/company/algolia/',
    },
    xUrl: {
      url: 'https://twitter.com/algolia',
      label: 'https://twitter.com/algolia',
    },
    annualRecurringRevenue: { amountMicros: 5000000, currencyCode: 'USD' },
    idealCustomerProfile: true,
    accountOwner: null,
    Favorite: null,
    accountOwnerId: null,
  },
  {
    id: 'b1cfd51b-a831-455f-ba07-4e30671e1dc3',
    domainName: 'apple.com',
    name: 'Apple',
    createdAt: '2023-03-21T06:30:25.39474+00:00',
    address: '',
    employees: 10,
    linkedinUrl: {
      url: 'https://www.linkedin.com/company/apple/',
      label: 'https://www.linkedin.com/company/apple/',
    },
    xUrl: {
      url: 'https://twitter.com/apple',
      label: 'https://twitter.com/apple',
    },
    annualRecurringRevenue: { amountMicros: 1000000, currencyCode: 'USD' },
    idealCustomerProfile: false,
    accountOwner: null,
    Favorite: null,
    accountOwnerId: null,
  },
  {
    id: '5c21e19e-e049-4393-8c09-3e3f8fb09ecb',
    domainName: 'qonto.com',
    name: 'Qonto',
    createdAt: '2023-04-26T10:13:29.712485+00:00',
    address: '10 rue de la Paix',
    employees: 1,
    linkedinUrl: {
      url: 'https://www.linkedin.com/company/qonto/',
      label: 'https://www.linkedin.com/company/qonto/',
    },
    xUrl: {
      url: 'https://twitter.com/qonto',
      label: 'https://twitter.com/qonto',
    },
    annualRecurringRevenue: { amountMicros: 5000000, currencyCode: 'USD' },
    idealCustomerProfile: false,
    accountOwner: null,
    Favorite: null,
    accountOwnerId: null,
  },
  {
    id: '9d162de6-cfbf-4156-a790-e39854dcd4eb',
    domainName: 'facebook.com',
    name: 'Facebook',
    createdAt: '2023-04-26T10:09:25.656555+00:00',
    address: '',
    employees: 1,
    linkedinUrl: {
      url: 'https://www.linkedin.com/company/facebook/',
      label: 'https://www.linkedin.com/company/facebook/',
    },
    xUrl: {
      url: 'https://twitter.com/facebook',
      label: 'https://twitter.com/facebook',
    },
    annualRecurringRevenue: { amountMicros: 5000000, currencyCode: 'USD' },
    idealCustomerProfile: true,
    accountOwner: null,
    Favorite: null,
    accountOwnerId: null,
  },
  {
    id: '9d162de6-cfbf-4156-a790-e39854dcd4ef',
    domainName: 'sequoia.com',
    name: 'Sequoia',
    createdAt: '2023-04-26T10:09:25.656555+00:00',
    address: '',
    employees: 1,
    linkedinUrl: {
      url: 'https://www.linkedin.com/company/sequoia/',
      label: 'https://www.linkedin.com/company/sequoia/',
    },
    xUrl: {
      url: 'https://twitter.com/sequoia',
      label: 'https://twitter.com/sequoia',
    },
    annualRecurringRevenue: { amountMicros: 5000000, currencyCode: 'USD' },
    idealCustomerProfile: true,
    accountOwner: null,
    Favorite: null,
    accountOwnerId: null,
  },
];

export const mockedEmptyCompanyData = {
  id: '9231e6ee-4cc2-4c7b-8c55-dff16f4d968a',
  name: '',
  domainName: '',
  address: '',
  accountOwner: null,
  annualRecurringRevenue: null,
  createdAt: null,
  employees: null,
  idealCustomerProfile: null,
  linkedinUrl: null,
  xUrl: null,
  _activityCount: null,
  __typename: 'Company',
};

export const mockedCompanyMetadata: ObjectMetadataItem = {
  id: '20202020-4a5a-466f-92d9-c3870d9502a9',
  isActive: true,
  isCustom: false,
  isSystem: true,
  labelPlural: 'Companies',
  labelSingular: 'Company',
  namePlural: 'companies',
  nameSingular: 'company',
  createdAt: '2023-11-20T03:45:00.117Z',
  updatedAt: '2023-11-20T03:45:00.117Z',
  fields: [
    {
      __typename: 'field',
      id: '20202020-a61d-4b78-b998-3fd88b4f73a1',
      type: 'LINK',
      name: 'linkedinLink',
      label: 'Linkedin',
      description: 'The company Linkedin account',
      icon: 'IconBrandLinkedin',
      isCustom: false,
      isActive: true,
      isSystem: false,
      isNullable: true,
      createdAt: '2023-11-20T03:45:00.117Z',
      updatedAt: '2023-11-20T03:45:00.117Z',
      fromRelationMetadata: null,
      toRelationMetadata: null,
    },
    {
      __typename: 'field',
      id: '20202020-4dc2-47c9-bb15-6e6f19ba9e46',
      type: 'DATE',
      name: 'createdAt',
      label: 'Creation date',
      description: null,
      icon: 'IconCalendar',
      isCustom: false,
      isActive: true,
      isSystem: true,
      isNullable: false,
      createdAt: '2023-11-20T03:45:00.117Z',
      updatedAt: '2023-11-20T03:45:00.117Z',
      fromRelationMetadata: null,
      toRelationMetadata: null,
    },
    {
      __typename: 'field',
      id: '20202020-ad10-4117-a039-3f04b7a5f939',
      type: 'TEXT',
      name: 'address',
      label: 'Address',
      description: 'The company address',
      icon: 'IconMap',
      isCustom: false,
      isActive: true,
      isSystem: false,
      isNullable: true,
      createdAt: '2023-11-20T03:45:00.117Z',
      updatedAt: '2023-11-20T03:45:00.117Z',
      fromRelationMetadata: null,
      toRelationMetadata: null,
    },
    {
      __typename: 'field',
      id: '20202020-64b8-41bf-a01c-be6a806e8b70',
      type: 'DATE',
      name: 'updatedAt',
      label: 'Update date',
      description: null,
      icon: 'IconCalendar',
      isCustom: false,
      isActive: true,
      isSystem: true,
      isNullable: false,
      createdAt: '2023-11-20T03:45:00.117Z',
      updatedAt: '2023-11-20T03:45:00.117Z',
      fromRelationMetadata: null,
      toRelationMetadata: null,
    },
    {
      __typename: 'field',
      id: '20202020-8169-44a3-9e0b-6bad1ac50f87',
      type: 'UUID',
      name: 'id',
      label: 'Id',
      description: null,
      icon: null,
      isCustom: false,
      isActive: true,
      isSystem: true,
      isNullable: false,
      createdAt: '2023-11-20T03:45:00.117Z',
      updatedAt: '2023-11-20T03:45:00.117Z',
      fromRelationMetadata: null,
      toRelationMetadata: null,
    },
    {
      __typename: 'field',
      id: '20202020-7fbd-41ad-b64d-25a15ff62f04',
      type: 'NUMBER',
      name: 'employees',
      label: 'Employees',
      description: 'Number of employees in the company',
      icon: 'IconUsers',
      isCustom: false,
      isActive: true,
      isSystem: false,
      isNullable: true,
      createdAt: '2023-11-20T03:45:00.117Z',
      updatedAt: '2023-11-20T03:45:00.117Z',
      fromRelationMetadata: null,
      toRelationMetadata: null,
    },
    {
      __typename: 'field',
      id: '20202020-0b9e-4b9e-8b0a-5b0b5b0b5b0b',
      type: 'UUID',
      name: 'accountOwnerId',
      label: 'Account Owner ID (foreign key)',
      description: 'Foreign key for account owner',
      icon: null,
      isCustom: false,
      isActive: true,
      isSystem: true,
      isNullable: true,
      createdAt: '2023-11-20T03:45:00.117Z',
      updatedAt: '2023-11-20T03:45:00.117Z',
      fromRelationMetadata: null,
      toRelationMetadata: null,
    },
    {
      __typename: 'field',
      id: '20202020-5e4e-4007-a630-8a2617914889',
      type: 'TEXT',
      name: 'domainName',
      label: 'Domain Name',
      description:
        'The company website URL. We use this url to fetch the company icon',
      icon: 'IconLink',
      isCustom: false,
      isActive: true,
      isSystem: false,
      isNullable: true,
      createdAt: '2023-11-20T03:45:00.117Z',
      updatedAt: '2023-11-20T03:45:00.117Z',
      fromRelationMetadata: null,
      toRelationMetadata: null,
    },
    {
      __typename: 'field',
      id: '20202020-46e3-479a-b8f4-77137c74daa6',
      type: 'LINK',
      name: 'xLink',
      label: 'X',
      description: 'The company Twitter/X account',
      icon: 'IconBrandX',
      isCustom: false,
      isActive: true,
      isSystem: false,
      isNullable: true,
      createdAt: '2023-11-20T03:45:00.117Z',
      updatedAt: '2023-11-20T03:45:00.117Z',
      fromRelationMetadata: null,
      toRelationMetadata: null,
    },
    {
      __typename: 'field',
      id: '20202020-6d30-4111-9f40-b4301906fd3c',
      type: 'TEXT',
      name: 'name',
      label: 'Name',
      description: 'The company name',
      icon: 'IconBuildingSkyscraper',
      isCustom: false,
      isActive: true,
      isSystem: false,
      isNullable: true,
      createdAt: '2023-11-20T03:45:00.117Z',
      updatedAt: '2023-11-20T03:45:00.117Z',
      fromRelationMetadata: null,
      toRelationMetadata: null,
    },
    {
      __typename: 'field',
      id: '20202020-9e9f-4235-98b2-c76f3e2d281e',
      type: 'BOOLEAN',
      name: 'idealCustomerProfile',
      label: 'ICP',
      description:
        'Ideal Customer Profile:  Indicates whether the company is the most suitable and valuable customer for you',
      icon: 'IconTarget',
      isCustom: false,
      isActive: true,
      isSystem: false,
      isNullable: true,
      createdAt: '2023-11-20T03:45:00.117Z',
      updatedAt: '2023-11-20T03:45:00.117Z',
      fromRelationMetadata: null,
      toRelationMetadata: null,
    },
    {
      __typename: 'field',
      id: '20202020-4a5a-466f-92d9-c3870d9502a9',
      type: 'CURRENCY',
      name: 'annualRecurringRevenue',
      label: 'ARR',
      description:
        'Annual Recurring Revenue: The actual or estimated annual revenue of the company',
      icon: 'IconMoneybag',
      isCustom: false,
      isActive: true,
      isSystem: false,
      isNullable: true,
      createdAt: '2023-11-20T03:45:00.117Z',
      updatedAt: '2023-11-20T03:45:00.117Z',
      fromRelationMetadata: null,
      toRelationMetadata: null,
    },
  ] as FieldMetadataItem[],
};
