export const GRANOLA_HISTORY_BATCH_SIZE = 1;
export const GRANOLA_HISTORY_BATCH_INTERVAL_MILLISECONDS = 4_000;
export const GRANOLA_HISTORY_MAX_PAGES = 1000;
export const GRANOLA_HISTORY_MAX_IMPORT_DAYS = 3_650;
export const GRANOLA_INITIAL_IMPORT_DAYS = 31;
export const GRANOLA_CATCH_UP_WINDOW_DAYS = 2;
export const GRANOLA_JOB_RETRY_LIMIT = 3;
export const GRANOLA_MILLISECONDS_PER_DAY = 86_400_000;
