#
# Basic Crowdin CLI configuration
# See https://crowdin.github.io/crowdin-cli/configuration for more information
# See https://support.crowdin.com/developer/configuration-file/ for all available options
#

#
# Defines whether to preserve the original directory structure in the Crowdin project
# Recommended to set to true
#
"preserve_hierarchy": true

#
# Files configuration.
# See https://support.crowdin.com/developer/configuration-file/ for all available options
#
files: [
  {
    #
    # Source files filter
    # e.g. "/resources/en/*.json"
    #
    "source": "**/en.po",

    #
    # Translation files filter
    # e.g. "/resources/%two_letters_code%/%original_file_name%"
    #
    "translation": "%original_path%/%locale%.po",
  },
  {
    #
    # MDX documentation files - user-guide
    # Using md type to preserve JSX component structure
    # This prevents Crowdin from reformatting <Warning>, <Accordion>, etc.
    #
    "source": "packages/twenty-docs/user-guide/**/*.mdx",
    "translation": "packages/twenty-docs/l/%two_letters_code%/user-guide/**/%original_file_name%",
  },
  {
    #
    # MDX documentation files - developers
    # Using md type to preserve JSX component structure
    #
    "source": "packages/twenty-docs/developers/**/*.mdx",
    "translation": "packages/twenty-docs/l/%two_letters_code%/developers/**/%original_file_name%",
  },
  {
    #
    # MDX documentation files - twenty-ui
    # Using md type to preserve JSX component structure
    #
    "source": "packages/twenty-docs/twenty-ui/**/*.mdx",
    "translation": "packages/twenty-docs/l/%two_letters_code%/twenty-ui/**/%original_file_name%",
  },
  {
    #
    # Navigation labels template - translated into per-locale navigation.json
    #
    "source": "packages/twenty-docs/navigation/navigation.template.json",
    "translation": "packages/twenty-docs/l/%two_letters_code%/navigation.json",
  }
]
