#
# Basic Crowdin CLI configuration
# See https://crowdin.github.io/crowdin-cli/configuration for more information
# See https://support.crowdin.com/developer/configuration-file/ for all available options
#

#
# Defines whether to preserve the original directory structure in the Crowdin project
# Recommended to set to true
#
"preserve_hierarchy": true

#
# Files configuration.
# See https://support.crowdin.com/developer/configuration-file/ for all available options
#
files: [
  {
    #
    # Source files filter
    # e.g. "/resources/en/*.json"
    #
    "source": "**/en.po",

    #
    # Translation files filter
    # e.g. "/resources/%two_letters_code%/%original_file_name%"
    #
    "translation": "%original_path%/%locale%.po",
  },
  {
    #
    # MDX documentation files for Mintlify
    # Source files: English MDX files in packages/twenty-docs (exclude locale folders)
    #
    "source": "packages/twenty-docs/**/*.mdx",
    #
    # Exclude files in locale folders (fr/, es/, etc.)
    #
    "ignore": [
      "packages/twenty-docs/fr/**",
      "packages/twenty-docs/es/**",
      "packages/twenty-docs/de/**",
      "packages/twenty-docs/it/**",
      "packages/twenty-docs/ja/**",
      "packages/twenty-docs/pt-br/**",
      "packages/twenty-docs/zh-cn/**",
      "packages/twenty-docs/ru/**",
      "packages/twenty-docs/ko/**",
      "packages/twenty-docs/tr/**"
    ],
    #
    # Translation files: Place in locale-specific folders preserving directory structure
    # Source: packages/twenty-docs/user-guide/introduction.mdx
    # Translation: packages/twenty-docs/fr/user-guide/introduction.mdx
    # Note: %original_path% includes full path, may need post-processing to remove duplication
    #
    "translation": "packages/twenty-docs/%locale%/%original_path%"
  }
]
