export type FieldType =
  | 'BOOLEAN'
  | 'CHIP'
  | 'DATE'
  | 'DOUBLE_TEXT_CHIP'
  | 'DOUBLE_TEXT'
  | 'EMAIL'
  | 'ENUM'
  | 'MONEY_AMOUNT_V2'
  | 'MONEY_AMOUNT'
  | 'MONEY'
  | 'NUMBER'
  | 'PHONE'
  | 'PROBABILITY'
  | 'RELATION'
  | 'TEXT'
  | 'URL_V2'
  | 'URL';
