export type BackgroundMockCompany = {
  id: string;
  name: string;
  domainName: string;
  createdBy: string | null;
  accountOwner: string | null;
  creationDate: string;
  employees: number;
  address: string;
};

export const BACKGROUND_MOCK_COMPANIES = [
  {
    id: 'google',
    name: 'Google',
    domainName: 'goo.gle',
    createdBy: 'Tim Apple',
    accountOwner: 'Phil Schiller',
    creationDate: 'about 13 hours ago',
    employees: 284571,
    address: 'Mountain View',
  },
  {
    id: 'microsoft',
    name: 'Microsoft',
    domainName: 'microsoft.com',
    createdBy: 'Tim Apple',
    accountOwner: 'Jony Ive',
    creationDate: 'about 13 hours ago',
    employees: 226067,
    address: 'Redmond',
  },
  {
    id: 'meta',
    name: 'Meta',
    domainName: 'metacareers.com',
    createdBy: 'Tim Apple',
    accountOwner: 'Phil Schiller',
    creationDate: 'about 13 hours ago',
    employees: 119511,
    address: 'Menlo Park',
  },
  {
    id: 'slb',
    name: 'SLB',
    domainName: 'slb.com',
    createdBy: 'Tim Apple',
    accountOwner: 'Phil Schiller',
    creationDate: 'about 13 hours ago',
    employees: 113151,
    address: 'Houston',
  },
  {
    id: 'cisco',
    name: 'Cisco',
    domainName: 'cisco.com',
    createdBy: 'Tim Apple',
    accountOwner: 'Phil Schiller',
    creationDate: 'about 13 hours ago',
    employees: 99625,
    address: 'San Jose',
  },
  {
    id: 'uber',
    name: 'Uber',
    domainName: 'uber.com',
    createdBy: 'Tim Apple',
    accountOwner: 'Tim Apple',
    creationDate: 'about 13 hours ago',
    employees: 90545,
    address: 'San Francisco',
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    domainName: 'salesforce.com',
    createdBy: 'Tim Apple',
    accountOwner: 'Phil Schiller',
    creationDate: 'about 13 hours ago',
    employees: 71322,
    address: 'San Francisco',
  },
  {
    id: 'amdocs',
    name: 'Amdocs',
    domainName: 'amdocs.com',
    createdBy: 'Tim Apple',
    accountOwner: 'Jony Ive',
    creationDate: 'about 13 hours ago',
    employees: 35731,
    address: 'Chesterfield',
  },
  {
    id: 'vmware',
    name: 'VMware',
    domainName: 'vmware.com',
    createdBy: 'Tim Apple',
    accountOwner: 'Phil Schiller',
    creationDate: 'about 13 hours ago',
    employees: 34759,
    address: 'Palo Alto',
  },
  {
    id: 'globallogic',
    name: 'GlobalLogic',
    domainName: 'globallogic.com',
    createdBy: 'Tim Apple',
    accountOwner: 'Jony Ive',
    creationDate: 'about 13 hours ago',
    employees: 24461,
    address: 'Santa Clara',
  },
  {
    id: 'servicenow',
    name: 'ServiceNow',
    domainName: 'servicenow.com',
    createdBy: 'Tim Apple',
    accountOwner: 'Tim Apple',
    creationDate: 'about 13 hours ago',
    employees: 24104,
    address: 'Santa Clara',
  },
  {
    id: 'ssctech',
    name: 'SS&C Technologies',
    domainName: 'ssctech.com',
    createdBy: 'Tim Apple',
    accountOwner: 'Phil Schiller',
    creationDate: 'about 13 hours ago',
    employees: 20311,
    address: 'Windsor',
  },
  {
    id: 'workday',
    name: 'Workday',
    domainName: 'workday.com',
    createdBy: 'Tim Apple',
    accountOwner: 'Jony Ive',
    creationDate: 'about 13 hours ago',
    employees: 20036,
    address: 'Pleasanton',
  },
  {
    id: 'redhat',
    name: 'Red Hat',
    domainName: 'redhat.com',
    createdBy: 'Tim Apple',
    accountOwner: 'Phil Schiller',
    creationDate: 'about 13 hours ago',
    employees: 19945,
    address: 'Raleigh',
  },
  {
    id: 'netsuite',
    name: 'NetSuite',
    domainName: 'netsuite.com',
    createdBy: 'Tim Apple',
    accountOwner: 'Jony Ive',
    creationDate: 'about 13 hours ago',
    employees: 19269,
    address: 'Austin',
  },
  {
    id: 'synopsys',
    name: 'Synopsys Inc',
    domainName: 'synopsys.com',
    createdBy: 'Tim Apple',
    accountOwner: 'Jony Ive',
    creationDate: 'about 13 hours ago',
    employees: 18061,
    address: 'Sunnyvale',
  },
  {
    id: 'siemens',
    name: 'Siemens Digital Industries',
    domainName: 'sw.siemens.com',
    createdBy: 'Tim Apple',
    accountOwner: 'Tim Apple',
    creationDate: 'about 13 hours ago',
    employees: 17262,
    address: 'Plano',
  },
  {
    id: 'sas',
    name: 'SAS',
    domainName: 'sas.com',
    createdBy: 'Tim Apple',
    accountOwner: 'Phil Schiller',
    creationDate: 'about 13 hours ago',
    employees: 16287,
    address: 'Cary',
  },
  {
    id: 'intuit',
    name: 'Intuit',
    domainName: 'intuit.com',
    createdBy: 'Tim Apple',
    accountOwner: 'Jony Ive',
    creationDate: 'about 13 hours ago',
    employees: 15851,
    address: 'Mountain View',
  },
  {
    id: 'broadcom',
    name: 'Broadcom Software',
    domainName: 'broadcom.com',
    createdBy: 'Tim Apple',
    accountOwner: 'Phil Schiller',
    creationDate: 'about 13 hours ago',
    employees: 15127,
    address: 'San Jose',
  },
  {
    id: 'autodesk',
    name: 'Autodesk',
    domainName: 'autodesk.com',
    createdBy: 'Tim Apple',
    accountOwner: 'Jony Ive',
    creationDate: 'about 13 hours ago',
    employees: 14593,
    address: 'San Francisco',
  },
] satisfies BackgroundMockCompany[];
