export type BackgroundMockPerson = {
  firstName: string;
  lastName: string;
};

export type BackgroundMockCompany = {
  id: string;
  name: string;
  domainName: string;
  employees: number;
  people: BackgroundMockPerson[];
  address: string;
  accountOwner: string | null;
  creationDate: string;
  isIdealCustomerProfile: boolean;
  linkedinHandle: string | null;
  opportunitiesCount: number;
  xHandle: string | null;
};

export const BACKGROUND_MOCK_COMPANIES = [
  {
    id: 'anthropic',
    name: 'Anthropic',
    domainName: 'anthropic.com',
    employees: 1100,
    people: [{ firstName: 'Bertrand', lastName: 'Voulzy' }],
    address: '548 Market Street',
    accountOwner: null,
    creationDate: 'over 1 year ago',
    isIdealCustomerProfile: false,
    linkedinHandle: 'anthropicresearch',
    opportunitiesCount: 0,
    xHandle: null,
  },
  {
    id: 'google',
    name: 'Google',
    domainName: 'google.com',
    employees: 72_000,
    people: [{ firstName: 'Madison', lastName: 'Perez' }],
    address: '1600 Amphitheatre Pkwy',
    accountOwner: null,
    creationDate: 'over 1 year ago',
    isIdealCustomerProfile: false,
    linkedinHandle: 'google',
    opportunitiesCount: 0,
    xHandle: null,
  },
  {
    id: 'facebook',
    name: 'Facebook',
    domainName: 'facebook.com',
    employees: 87_000,
    people: [{ firstName: 'Christopher', lastName: 'Gonzalez' }],
    address: '1 Hacker Way',
    accountOwner: null,
    creationDate: 'over 1 year ago',
    isIdealCustomerProfile: false,
    linkedinHandle: 'facebook',
    opportunitiesCount: 1,
    xHandle: null,
  },
  {
    id: 'netflix',
    name: 'Netflix',
    domainName: 'netflix.com',
    employees: 3_000,
    people: [],
    address: '121 Albright Way',
    accountOwner: null,
    creationDate: 'over 1 year ago',
    isIdealCustomerProfile: false,
    linkedinHandle: 'netflix',
    opportunitiesCount: 0,
    xHandle: null,
  },
  {
    id: 'microsoft',
    name: 'Microsoft',
    domainName: 'microsoft.com',
    employees: 221_000,
    people: [{ firstName: 'Isabella', lastName: 'Scott' }],
    address: '1 Microsoft Way',
    accountOwner: null,
    creationDate: 'over 1 year ago',
    isIdealCustomerProfile: false,
    linkedinHandle: 'microsoft',
    opportunitiesCount: 2,
    xHandle: null,
  },
  {
    id: 'libeo',
    name: 'Libeo',
    domainName: 'libeo.io',
    employees: 50,
    people: [],
    address: '42 rue de paradis',
    accountOwner: null,
    creationDate: 'over 1 year ago',
    isIdealCustomerProfile: false,
    linkedinHandle: 'libeo',
    opportunitiesCount: 0,
    xHandle: null,
  },
  {
    id: 'airbnb',
    name: 'Airbnb',
    domainName: 'airbnb.com',
    employees: 6_000,
    people: [],
    address: '888 Brannan Street',
    accountOwner: null,
    creationDate: 'over 1 year ago',
    isIdealCustomerProfile: false,
    linkedinHandle: 'airbnb',
    opportunitiesCount: 0,
    xHandle: null,
  },
  {
    id: 'claap',
    name: 'Claap',
    domainName: 'claap.io',
    employees: 7,
    people: [],
    address: '901 Fifth Avenue',
    accountOwner: null,
    creationDate: 'over 1 year ago',
    isIdealCustomerProfile: false,
    linkedinHandle: 'claap',
    opportunitiesCount: 0,
    xHandle: null,
  },
  {
    id: 'algolia',
    name: 'Algolia',
    domainName: 'algolia.com',
    employees: 250,
    people: [{ firstName: 'Lorie', lastName: 'Vladim' }],
    address: '3790 El Camino Real',
    accountOwner: null,
    creationDate: 'over 1 year ago',
    isIdealCustomerProfile: false,
    linkedinHandle: 'algolia',
    opportunitiesCount: 0,
    xHandle: null,
  },
  {
    id: 'samsung',
    name: 'Samsung',
    domainName: 'samsung.com',
    employees: 400_000,
    people: [{ firstName: 'Louis', lastName: 'Duss' }],
    address: '129, Samsung-ro',
    accountOwner: null,
    creationDate: 'over 1 year ago',
    isIdealCustomerProfile: false,
    linkedinHandle: 'samsung',
    opportunitiesCount: 0,
    xHandle: null,
  },
  {
    id: 'hasura',
    name: 'Hasura',
    domainName: 'hasura.io',
    employees: 17_000,
    people: [],
    address: '576 Folsom St.',
    accountOwner: null,
    creationDate: 'over 1 year ago',
    isIdealCustomerProfile: false,
    linkedinHandle: 'hasura',
    opportunitiesCount: 0,
    xHandle: null,
  },
  {
    id: 'wework',
    name: 'Wework',
    domainName: 'wework.com',
    employees: 2_000,
    people: [],
    address: '575 Lexington Ave 16th Floor',
    accountOwner: null,
    creationDate: 'over 1 year ago',
    isIdealCustomerProfile: false,
    linkedinHandle: 'wework',
    opportunitiesCount: 0,
    xHandle: null,
  },
  {
    id: 'linkedin',
    name: 'Linkedin',
    domainName: 'linkedin.com',
    employees: 20_000,
    people: [
      { firstName: 'Sylvie', lastName: 'Palmer' },
      { firstName: 'Christoph', lastName: 'Callisto' },
    ],
    address: '315 Montgomery St',
    accountOwner: null,
    creationDate: 'over 1 year ago',
    isIdealCustomerProfile: false,
    linkedinHandle: 'linkedin',
    opportunitiesCount: 1,
    xHandle: null,
  },
] satisfies BackgroundMockCompany[];
