import { CoreApiClient, type CoreSchema } from 'twenty-client-sdk/core';

// Auto-naming for Matching records.
//
// A record is renamed only while its name is still the empty default (`''`).
// Once it carries any name — user-typed, or already generated by us — we never
// touch it again. That makes these helpers idempotent and safe to call from
// BOTH the `*.created` trigger (record created with the relation already set,
// e.g. from an Opportunity's Briefs panel) and the `*.updated` trigger (record
// created blank from the index table, then linked to a relation afterwards).

type BriefAfter = Pick<CoreSchema.Brief, 'id' | 'name' | 'opportunityId'>;
type ApplicationAfter = Pick<
  CoreSchema.Application,
  'id' | 'name' | 'briefId' | 'partnerId'
>;

// "Brief {Opportunity}" once the brief is linked to an opportunity.
export const renameBriefIfNeeded = async (
  after: BriefAfter,
): Promise<boolean> => {
  const opportunityId = after.opportunityId;
  if (!opportunityId || after.name !== '') return false;

  const client = new CoreApiClient();
  const oppRes = await client.query({
    opportunity: {
      __args: { filter: { id: { eq: opportunityId } } },
      name: true,
    },
  });

  const oppName = oppRes.opportunity?.name;
  if (!oppName) return false;

  await client.mutation({
    updateBrief: {
      __args: { id: after.id, data: { name: `Brief ${oppName}` } },
      id: true,
    },
  });

  return true;
};

// "Application {Partner} - {Opportunity}" once the application is linked to
// both a brief and a partner.
export const renameApplicationIfNeeded = async (
  after: ApplicationAfter,
): Promise<boolean> => {
  const briefId = after.briefId;
  const partnerId = after.partnerId;
  if (!briefId || !partnerId || after.name !== '') return false;

  const client = new CoreApiClient();

  // Application → Brief → Opportunity is a two-hop relation; v2.5.1 resolves
  // only a single hop per query, so we walk it explicitly.
  const briefRes = await client.query({
    brief: {
      __args: { filter: { id: { eq: briefId } } },
      opportunityId: true,
    },
  });
  const opportunityId = briefRes.brief?.opportunityId;

  let oppName = '';
  if (opportunityId) {
    const oppRes = await client.query({
      opportunity: {
        __args: { filter: { id: { eq: opportunityId } } },
        name: true,
      },
    });
    oppName = oppRes.opportunity?.name ?? '';
  }

  const partnerRes = await client.query({
    partner: {
      __args: { filter: { id: { eq: partnerId } } },
      name: true,
    },
  });
  const partnerName = partnerRes.partner?.name ?? '';

  if (!oppName && !partnerName) return false;

  const detail = [partnerName, oppName].filter(Boolean).join(' - ');
  const label = `Application ${detail}`;
  await client.mutation({
    updateApplication: {
      __args: { id: after.id, data: { name: label } },
      id: true,
    },
  });

  return true;
};
