import { defineFrontComponent } from '@/sdk';
import { useState } from 'react';

// Tailwind CSS subset (only the utilities used by this component)
// In a real setup, this would be generated by the Tailwind CLI at build time.
const TAILWIND_CSS = `
.p-5{padding:1.25rem}
.mb-4{margin-bottom:1rem}
.mb-2{margin-bottom:.5rem}
.space-y-3>:not(:first-child){margin-top:.75rem}
.rounded-lg{border-radius:.5rem}
.rounded-md{border-radius:.375rem}
.border{border-width:1px}
.border-gray-200{border-color:#e5e7eb}
.bg-white{background-color:#fff}
.bg-blue-600{background-color:#2563eb}
.bg-blue-700{background-color:#1d4ed8}
.bg-gray-50{background-color:#f9fafb}
.px-4{padding-left:1rem;padding-right:1rem}
.py-2{padding-top:.5rem;padding-bottom:.5rem}
.text-sm{font-size:.875rem;line-height:1.25rem}
.text-lg{font-size:1.125rem;line-height:1.75rem}
.text-2xl{font-size:1.5rem;line-height:2rem}
.font-semibold{font-weight:600}
.font-bold{font-weight:700}
.text-gray-500{color:#6b7280}
.text-gray-900{color:#111827}
.text-blue-600{color:#2563eb}
.text-white{color:#fff}
.shadow-sm{box-shadow:0 1px 2px 0 rgb(0 0 0/.05)}
.cursor-pointer{cursor:pointer}
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
`;

const TailwindComponent = () => {
  const [count, setCount] = useState(0);

  return (
    <>
      <style>{TAILWIND_CSS}</style>
      <div
        data-testid="tailwind-component"
        className="p-5 bg-white rounded-lg border border-gray-200 shadow-sm space-y-3"
      >
        <h2 className="text-lg font-bold text-gray-900">
          Tailwind CSS Component
        </h2>
        <p className="text-sm text-gray-500">
          This component uses Tailwind utility classes via className.
        </p>
        <div className="bg-gray-50 rounded-md p-5">
          <span
            data-testid="tailwind-count"
            className="text-2xl font-semibold text-blue-600"
          >
            Count: {count}
          </span>
        </div>
        <button
          data-testid="tailwind-button"
          className="px-4 py-2 bg-blue-600 text-white font-semibold rounded-md text-sm cursor-pointer"
          onClick={() => setCount((previous) => previous + 1)}
        >
          Increment
        </button>
      </div>
    </>
  );
};

export default defineFrontComponent({
  universalIdentifier: 'test-tailwind-0000-0000-0000-000000000005',
  name: 'tailwind-component',
  description: 'A front component using Tailwind CSS utility classes',
  component: TailwindComponent,
});
