import type { MessageDescriptor } from '@lingui/core';
import { msg } from '@lingui/core/macro';

import type { PartnerApplicationState } from './use-partner-application-state';

export const PARTNER_APPLICATION_STEP_IDS = [
  'identity',
  'profile',
  'expertise',
  'commercials',
] as const;

export type PartnerApplicationStepId =
  (typeof PARTNER_APPLICATION_STEP_IDS)[number];

export const PARTNER_TYPE_OF_TEAM_VALUES = ['SOLO', 'AGENCY'] as const;
export type PartnerTypeOfTeam = (typeof PARTNER_TYPE_OF_TEAM_VALUES)[number];

export const PARTNER_TYPE_OF_TEAM_OPTIONS: ReadonlyArray<{
  value: PartnerTypeOfTeam;
  label: MessageDescriptor;
}> = [
  { value: 'SOLO', label: msg`Solo` },
  { value: 'AGENCY', label: msg`Agency` },
];

export const PARTNER_SCOPE_VALUES = [
  'ADVISORY',
  'SOLUTIONING',
  'DEVELOPMENT',
  'HOSTING',
  'SUPPORT',
] as const;
export type PartnerScopeValue = (typeof PARTNER_SCOPE_VALUES)[number];

export const PARTNER_SCOPE_OPTIONS: ReadonlyArray<{
  value: PartnerScopeValue;
  label: MessageDescriptor;
  description: MessageDescriptor;
  examples: MessageDescriptor;
}> = [
  {
    value: 'ADVISORY',
    label: msg`Advisory & Discovery`,
    description: msg`Upfront consulting, scoping, strategy.`,
    examples: msg`CRM audit · Requirements · Process mapping · ROI · RevOps · Vendor selection`,
  },
  {
    value: 'SOLUTIONING',
    label: msg`Solutioning`,
    description: msg`What an admin can do without writing code.`,
    examples: msg`Data modeling · Migrations · No-code workflows · Dashboards · SSO/SCIM · Integrations`,
  },
  {
    value: 'DEVELOPMENT',
    label: msg`Custom Development`,
    description: msg`Anything that needs a developer.`,
    examples: msg`Custom Apps · Scripts · AI/agent integrations`,
  },
  {
    value: 'HOSTING',
    label: msg`Hosting & Infrastructure`,
    description: msg`Anything that needs devops skills.`,
    examples: msg`Self-hosted (Docker/K8s) · Cloud architecture · Scaling · Security · Monitoring`,
  },
  {
    value: 'SUPPORT',
    label: msg`Training, Adoption & Support`,
    description: msg`User-side rollout & ongoing support.`,
    examples: msg`Onboarding · Documentation · Change management · L1/L2 support · Managed services`,
  },
];

// Shown as ghost chips by default — a short, mixed (technical + PLM) starter set.
export const PARTNER_SKILL_SUGGESTIONS: ReadonlyArray<string> = [
  'Data migration',
  'Workflows',
  'Integrations',
  'Custom development',
  'Self-hosting',
  'Data modeling',
  'CRM strategy',
  'Change management',
  'Training & onboarding',
  'AI / agents',
];

// Searchable-only (autocomplete) — broad coverage incl. non-technical / PLM.
// Not rendered as chips; surfaced when the applicant types a match.
export const PARTNER_SKILL_POOL: ReadonlyArray<string> = [
  'React',
  'TypeScript',
  'Node.js',
  'Python',
  'PostgreSQL',
  'GraphQL',
  'Docker',
  'Kubernetes',
  'AWS',
  'GCP',
  'n8n',
  'Zapier',
  'Make',
  'Salesforce',
  'HubSpot',
  'Salesforce migration',
  'HubSpot migration',
  'SAP',
  'Shopify',
  'Stripe',
  'SSO / SCIM',
  'Dashboards & reporting',
  'Pipelines',
  'Multi-language',
  'RevOps',
  'Sales ops',
  'Requirements gathering',
  'Process mapping',
  'Vendor selection',
  'CRM audit',
  'Solution architecture',
  'Managed services',
  'L1/L2 support',
  'Documentation',
  'Onboarding',
  'Adoption',
  'GDPR / data privacy',
  'Compliance',
  'Enterprise support',
  'Scaling',
  'Monitoring',
  'Security',
  'Real estate',
  'B2B SaaS',
];

export const PARTNER_COUNTRY_VALUES = [
  'AFGHANISTAN',
  'ALBANIA',
  'ALGERIA',
  'ANDORRA',
  'ANGOLA',
  'ANTIGUA_AND_BARBUDA',
  'ARGENTINA',
  'ARMENIA',
  'AUSTRALIA',
  'AUSTRIA',
  'AZERBAIJAN',
  'BAHAMAS',
  'BAHRAIN',
  'BANGLADESH',
  'BARBADOS',
  'BELARUS',
  'BELGIUM',
  'BELIZE',
  'BENIN',
  'BHUTAN',
  'BOLIVIA',
  'BOSNIA_AND_HERZEGOVINA',
  'BOTSWANA',
  'BRAZIL',
  'BRUNEI',
  'BULGARIA',
  'BURKINA_FASO',
  'BURUNDI',
  'CAMBODIA',
  'CAMEROON',
  'CANADA',
  'CAPE_VERDE',
  'CENTRAL_AFRICAN_REPUBLIC',
  'CHAD',
  'CHILE',
  'CHINA',
  'COLOMBIA',
  'COMOROS',
  'CONGO',
  'DR_CONGO',
  'COSTA_RICA',
  'CROATIA',
  'CUBA',
  'CYPRUS',
  'CZECH_REPUBLIC',
  'DENMARK',
  'DJIBOUTI',
  'DOMINICA',
  'DOMINICAN_REPUBLIC',
  'ECUADOR',
  'EGYPT',
  'EL_SALVADOR',
  'EQUATORIAL_GUINEA',
  'ERITREA',
  'ESTONIA',
  'ESWATINI',
  'ETHIOPIA',
  'FIJI',
  'FINLAND',
  'FRANCE',
  'GABON',
  'GAMBIA',
  'GEORGIA',
  'GERMANY',
  'GHANA',
  'GREECE',
  'GRENADA',
  'GUATEMALA',
  'GUINEA',
  'GUINEA_BISSAU',
  'GUYANA',
  'HAITI',
  'HONDURAS',
  'HUNGARY',
  'ICELAND',
  'INDIA',
  'INDONESIA',
  'IRAN',
  'IRAQ',
  'IRELAND',
  'ISRAEL',
  'ITALY',
  'IVORY_COAST',
  'JAMAICA',
  'JAPAN',
  'JORDAN',
  'KAZAKHSTAN',
  'KENYA',
  'KIRIBATI',
  'KOSOVO',
  'KUWAIT',
  'KYRGYZSTAN',
  'LAOS',
  'LATVIA',
  'LEBANON',
  'LESOTHO',
  'LIBERIA',
  'LIBYA',
  'LIECHTENSTEIN',
  'LITHUANIA',
  'LUXEMBOURG',
  'MADAGASCAR',
  'MALAWI',
  'MALAYSIA',
  'MALDIVES',
  'MALI',
  'MALTA',
  'MARSHALL_ISLANDS',
  'MAURITANIA',
  'MAURITIUS',
  'MEXICO',
  'MICRONESIA',
  'MOLDOVA',
  'MONACO',
  'MONGOLIA',
  'MONTENEGRO',
  'MOROCCO',
  'MOZAMBIQUE',
  'MYANMAR',
  'NAMIBIA',
  'NAURU',
  'NEPAL',
  'NETHERLANDS',
  'NEW_ZEALAND',
  'NICARAGUA',
  'NIGER',
  'NIGERIA',
  'NORTH_KOREA',
  'NORTH_MACEDONIA',
  'NORWAY',
  'OMAN',
  'PAKISTAN',
  'PALAU',
  'PALESTINE',
  'PANAMA',
  'PAPUA_NEW_GUINEA',
  'PARAGUAY',
  'PERU',
  'PHILIPPINES',
  'POLAND',
  'PORTUGAL',
  'QATAR',
  'ROMANIA',
  'RUSSIA',
  'RWANDA',
  'SAINT_KITTS_AND_NEVIS',
  'SAINT_LUCIA',
  'SAINT_VINCENT',
  'SAMOA',
  'SAN_MARINO',
  'SAO_TOME_AND_PRINCIPE',
  'SAUDI_ARABIA',
  'SENEGAL',
  'SERBIA',
  'SEYCHELLES',
  'SIERRA_LEONE',
  'SINGAPORE',
  'SLOVAKIA',
  'SLOVENIA',
  'SOLOMON_ISLANDS',
  'SOMALIA',
  'SOUTH_AFRICA',
  'SOUTH_KOREA',
  'SOUTH_SUDAN',
  'SPAIN',
  'SRI_LANKA',
  'SUDAN',
  'SURINAME',
  'SWEDEN',
  'SWITZERLAND',
  'SYRIA',
  'TAIWAN',
  'TAJIKISTAN',
  'TANZANIA',
  'THAILAND',
  'TIMOR_LESTE',
  'TOGO',
  'TONGA',
  'TRINIDAD_AND_TOBAGO',
  'TUNISIA',
  'TURKEY',
  'TURKMENISTAN',
  'TUVALU',
  'UGANDA',
  'UKRAINE',
  'UNITED_ARAB_EMIRATES',
  'UNITED_KINGDOM',
  'UNITED_STATES',
  'URUGUAY',
  'UZBEKISTAN',
  'VANUATU',
  'VATICAN',
  'VENEZUELA',
  'VIETNAM',
  'YEMEN',
  'ZAMBIA',
  'ZIMBABWE',
] as const;
export type PartnerCountryValue = (typeof PARTNER_COUNTRY_VALUES)[number];

export const PARTNER_COUNTRY_OPTIONS: ReadonlyArray<{
  value: PartnerCountryValue;
  label: MessageDescriptor;
}> = [
  { value: 'AFGHANISTAN', label: msg`Afghanistan 🇦🇫` },
  { value: 'ALBANIA', label: msg`Albania 🇦🇱` },
  { value: 'ALGERIA', label: msg`Algeria 🇩🇿` },
  { value: 'ANDORRA', label: msg`Andorra 🇦🇩` },
  { value: 'ANGOLA', label: msg`Angola 🇦🇴` },
  { value: 'ANTIGUA_AND_BARBUDA', label: msg`Antigua & Barbuda 🇦🇬` },
  { value: 'ARGENTINA', label: msg`Argentina 🇦🇷` },
  { value: 'ARMENIA', label: msg`Armenia 🇦🇲` },
  { value: 'AUSTRALIA', label: msg`Australia 🇦🇺` },
  { value: 'AUSTRIA', label: msg`Austria 🇦🇹` },
  { value: 'AZERBAIJAN', label: msg`Azerbaijan 🇦🇿` },
  { value: 'BAHAMAS', label: msg`Bahamas 🇧🇸` },
  { value: 'BAHRAIN', label: msg`Bahrain 🇧🇭` },
  { value: 'BANGLADESH', label: msg`Bangladesh 🇧🇩` },
  { value: 'BARBADOS', label: msg`Barbados 🇧🇧` },
  { value: 'BELARUS', label: msg`Belarus 🇧🇾` },
  { value: 'BELGIUM', label: msg`Belgium 🇧🇪` },
  { value: 'BELIZE', label: msg`Belize 🇧🇿` },
  { value: 'BENIN', label: msg`Benin 🇧🇯` },
  { value: 'BHUTAN', label: msg`Bhutan 🇧🇹` },
  { value: 'BOLIVIA', label: msg`Bolivia 🇧🇴` },
  { value: 'BOSNIA_AND_HERZEGOVINA', label: msg`Bosnia & Herzegovina 🇧🇦` },
  { value: 'BOTSWANA', label: msg`Botswana 🇧🇼` },
  { value: 'BRAZIL', label: msg`Brazil 🇧🇷` },
  { value: 'BRUNEI', label: msg`Brunei 🇧🇳` },
  { value: 'BULGARIA', label: msg`Bulgaria 🇧🇬` },
  { value: 'BURKINA_FASO', label: msg`Burkina Faso 🇧🇫` },
  { value: 'BURUNDI', label: msg`Burundi 🇧🇮` },
  { value: 'CAMBODIA', label: msg`Cambodia 🇰🇭` },
  { value: 'CAMEROON', label: msg`Cameroon 🇨🇲` },
  { value: 'CANADA', label: msg`Canada 🇨🇦` },
  { value: 'CAPE_VERDE', label: msg`Cape Verde 🇨🇻` },
  {
    value: 'CENTRAL_AFRICAN_REPUBLIC',
    label: msg`Central African Republic 🇨🇫`,
  },
  { value: 'CHAD', label: msg`Chad 🇹🇩` },
  { value: 'CHILE', label: msg`Chile 🇨🇱` },
  { value: 'CHINA', label: msg`China 🇨🇳` },
  { value: 'COLOMBIA', label: msg`Colombia 🇨🇴` },
  { value: 'COMOROS', label: msg`Comoros 🇰🇲` },
  { value: 'CONGO', label: msg`Congo 🇨🇬` },
  { value: 'DR_CONGO', label: msg`DR Congo 🇨🇩` },
  { value: 'COSTA_RICA', label: msg`Costa Rica 🇨🇷` },
  { value: 'CROATIA', label: msg`Croatia 🇭🇷` },
  { value: 'CUBA', label: msg`Cuba 🇨🇺` },
  { value: 'CYPRUS', label: msg`Cyprus 🇨🇾` },
  { value: 'CZECH_REPUBLIC', label: msg`Czech Republic 🇨🇿` },
  { value: 'DENMARK', label: msg`Denmark 🇩🇰` },
  { value: 'DJIBOUTI', label: msg`Djibouti 🇩🇯` },
  { value: 'DOMINICA', label: msg`Dominica 🇩🇲` },
  { value: 'DOMINICAN_REPUBLIC', label: msg`Dominican Republic 🇩🇴` },
  { value: 'ECUADOR', label: msg`Ecuador 🇪🇨` },
  { value: 'EGYPT', label: msg`Egypt 🇪🇬` },
  { value: 'EL_SALVADOR', label: msg`El Salvador 🇸🇻` },
  { value: 'EQUATORIAL_GUINEA', label: msg`Equatorial Guinea 🇬🇶` },
  { value: 'ERITREA', label: msg`Eritrea 🇪🇷` },
  { value: 'ESTONIA', label: msg`Estonia 🇪🇪` },
  { value: 'ESWATINI', label: msg`Eswatini 🇸🇿` },
  { value: 'ETHIOPIA', label: msg`Ethiopia 🇪🇹` },
  { value: 'FIJI', label: msg`Fiji 🇫🇯` },
  { value: 'FINLAND', label: msg`Finland 🇫🇮` },
  { value: 'FRANCE', label: msg`France 🇫🇷` },
  { value: 'GABON', label: msg`Gabon 🇬🇦` },
  { value: 'GAMBIA', label: msg`Gambia 🇬🇲` },
  { value: 'GEORGIA', label: msg`Georgia 🇬🇪` },
  { value: 'GERMANY', label: msg`Germany 🇩🇪` },
  { value: 'GHANA', label: msg`Ghana 🇬🇭` },
  { value: 'GREECE', label: msg`Greece 🇬🇷` },
  { value: 'GRENADA', label: msg`Grenada 🇬🇩` },
  { value: 'GUATEMALA', label: msg`Guatemala 🇬🇹` },
  { value: 'GUINEA', label: msg`Guinea 🇬🇳` },
  { value: 'GUINEA_BISSAU', label: msg`Guinea-Bissau 🇬🇼` },
  { value: 'GUYANA', label: msg`Guyana 🇬🇾` },
  { value: 'HAITI', label: msg`Haiti 🇭🇹` },
  { value: 'HONDURAS', label: msg`Honduras 🇭🇳` },
  { value: 'HUNGARY', label: msg`Hungary 🇭🇺` },
  { value: 'ICELAND', label: msg`Iceland 🇮🇸` },
  { value: 'INDIA', label: msg`India 🇮🇳` },
  { value: 'INDONESIA', label: msg`Indonesia 🇮🇩` },
  { value: 'IRAN', label: msg`Iran 🇮🇷` },
  { value: 'IRAQ', label: msg`Iraq 🇮🇶` },
  { value: 'IRELAND', label: msg`Ireland 🇮🇪` },
  { value: 'ISRAEL', label: msg`Israel 🇮🇱` },
  { value: 'ITALY', label: msg`Italy 🇮🇹` },
  { value: 'IVORY_COAST', label: msg`Ivory Coast 🇨🇮` },
  { value: 'JAMAICA', label: msg`Jamaica 🇯🇲` },
  { value: 'JAPAN', label: msg`Japan 🇯🇵` },
  { value: 'JORDAN', label: msg`Jordan 🇯🇴` },
  { value: 'KAZAKHSTAN', label: msg`Kazakhstan 🇰🇿` },
  { value: 'KENYA', label: msg`Kenya 🇰🇪` },
  { value: 'KIRIBATI', label: msg`Kiribati 🇰🇮` },
  { value: 'KOSOVO', label: msg`Kosovo 🇽🇰` },
  { value: 'KUWAIT', label: msg`Kuwait 🇰🇼` },
  { value: 'KYRGYZSTAN', label: msg`Kyrgyzstan 🇰🇬` },
  { value: 'LAOS', label: msg`Laos 🇱🇦` },
  { value: 'LATVIA', label: msg`Latvia 🇱🇻` },
  { value: 'LEBANON', label: msg`Lebanon 🇱🇧` },
  { value: 'LESOTHO', label: msg`Lesotho 🇱🇸` },
  { value: 'LIBERIA', label: msg`Liberia 🇱🇷` },
  { value: 'LIBYA', label: msg`Libya 🇱🇾` },
  { value: 'LIECHTENSTEIN', label: msg`Liechtenstein 🇱🇮` },
  { value: 'LITHUANIA', label: msg`Lithuania 🇱🇹` },
  { value: 'LUXEMBOURG', label: msg`Luxembourg 🇱🇺` },
  { value: 'MADAGASCAR', label: msg`Madagascar 🇲🇬` },
  { value: 'MALAWI', label: msg`Malawi 🇲🇼` },
  { value: 'MALAYSIA', label: msg`Malaysia 🇲🇾` },
  { value: 'MALDIVES', label: msg`Maldives 🇲🇻` },
  { value: 'MALI', label: msg`Mali 🇲🇱` },
  { value: 'MALTA', label: msg`Malta 🇲🇹` },
  { value: 'MARSHALL_ISLANDS', label: msg`Marshall Islands 🇲🇭` },
  { value: 'MAURITANIA', label: msg`Mauritania 🇲🇷` },
  { value: 'MAURITIUS', label: msg`Mauritius 🇲🇺` },
  { value: 'MEXICO', label: msg`Mexico 🇲🇽` },
  { value: 'MICRONESIA', label: msg`Micronesia 🇫🇲` },
  { value: 'MOLDOVA', label: msg`Moldova 🇲🇩` },
  { value: 'MONACO', label: msg`Monaco 🇲🇨` },
  { value: 'MONGOLIA', label: msg`Mongolia 🇲🇳` },
  { value: 'MONTENEGRO', label: msg`Montenegro 🇲🇪` },
  { value: 'MOROCCO', label: msg`Morocco 🇲🇦` },
  { value: 'MOZAMBIQUE', label: msg`Mozambique 🇲🇿` },
  { value: 'MYANMAR', label: msg`Myanmar 🇲🇲` },
  { value: 'NAMIBIA', label: msg`Namibia 🇳🇦` },
  { value: 'NAURU', label: msg`Nauru 🇳🇷` },
  { value: 'NEPAL', label: msg`Nepal 🇳🇵` },
  { value: 'NETHERLANDS', label: msg`Netherlands 🇳🇱` },
  { value: 'NEW_ZEALAND', label: msg`New Zealand 🇳🇿` },
  { value: 'NICARAGUA', label: msg`Nicaragua 🇳🇮` },
  { value: 'NIGER', label: msg`Niger 🇳🇪` },
  { value: 'NIGERIA', label: msg`Nigeria 🇳🇬` },
  { value: 'NORTH_KOREA', label: msg`North Korea 🇰🇵` },
  { value: 'NORTH_MACEDONIA', label: msg`North Macedonia 🇲🇰` },
  { value: 'NORWAY', label: msg`Norway 🇳🇴` },
  { value: 'OMAN', label: msg`Oman 🇴🇲` },
  { value: 'PAKISTAN', label: msg`Pakistan 🇵🇰` },
  { value: 'PALAU', label: msg`Palau 🇵🇼` },
  { value: 'PALESTINE', label: msg`Palestine 🇵🇸` },
  { value: 'PANAMA', label: msg`Panama 🇵🇦` },
  { value: 'PAPUA_NEW_GUINEA', label: msg`Papua New Guinea 🇵🇬` },
  { value: 'PARAGUAY', label: msg`Paraguay 🇵🇾` },
  { value: 'PERU', label: msg`Peru 🇵🇪` },
  { value: 'PHILIPPINES', label: msg`Philippines 🇵🇭` },
  { value: 'POLAND', label: msg`Poland 🇵🇱` },
  { value: 'PORTUGAL', label: msg`Portugal 🇵🇹` },
  { value: 'QATAR', label: msg`Qatar 🇶🇦` },
  { value: 'ROMANIA', label: msg`Romania 🇷🇴` },
  { value: 'RUSSIA', label: msg`Russia 🇷🇺` },
  { value: 'RWANDA', label: msg`Rwanda 🇷🇼` },
  { value: 'SAINT_KITTS_AND_NEVIS', label: msg`Saint Kitts & Nevis 🇰🇳` },
  { value: 'SAINT_LUCIA', label: msg`Saint Lucia 🇱🇨` },
  { value: 'SAINT_VINCENT', label: msg`Saint Vincent 🇻🇨` },
  { value: 'SAMOA', label: msg`Samoa 🇼🇸` },
  { value: 'SAN_MARINO', label: msg`San Marino 🇸🇲` },
  { value: 'SAO_TOME_AND_PRINCIPE', label: msg`São Tomé & Príncipe 🇸🇹` },
  { value: 'SAUDI_ARABIA', label: msg`Saudi Arabia 🇸🇦` },
  { value: 'SENEGAL', label: msg`Senegal 🇸🇳` },
  { value: 'SERBIA', label: msg`Serbia 🇷🇸` },
  { value: 'SEYCHELLES', label: msg`Seychelles 🇸🇨` },
  { value: 'SIERRA_LEONE', label: msg`Sierra Leone 🇸🇱` },
  { value: 'SINGAPORE', label: msg`Singapore 🇸🇬` },
  { value: 'SLOVAKIA', label: msg`Slovakia 🇸🇰` },
  { value: 'SLOVENIA', label: msg`Slovenia 🇸🇮` },
  { value: 'SOLOMON_ISLANDS', label: msg`Solomon Islands 🇸🇧` },
  { value: 'SOMALIA', label: msg`Somalia 🇸🇴` },
  { value: 'SOUTH_AFRICA', label: msg`South Africa 🇿🇦` },
  { value: 'SOUTH_KOREA', label: msg`South Korea 🇰🇷` },
  { value: 'SOUTH_SUDAN', label: msg`South Sudan 🇸🇸` },
  { value: 'SPAIN', label: msg`Spain 🇪🇸` },
  { value: 'SRI_LANKA', label: msg`Sri Lanka 🇱🇰` },
  { value: 'SUDAN', label: msg`Sudan 🇸🇩` },
  { value: 'SURINAME', label: msg`Suriname 🇸🇷` },
  { value: 'SWEDEN', label: msg`Sweden 🇸🇪` },
  { value: 'SWITZERLAND', label: msg`Switzerland 🇨🇭` },
  { value: 'SYRIA', label: msg`Syria 🇸🇾` },
  { value: 'TAIWAN', label: msg`Taiwan 🇹🇼` },
  { value: 'TAJIKISTAN', label: msg`Tajikistan 🇹🇯` },
  { value: 'TANZANIA', label: msg`Tanzania 🇹🇿` },
  { value: 'THAILAND', label: msg`Thailand 🇹🇭` },
  { value: 'TIMOR_LESTE', label: msg`Timor-Leste 🇹🇱` },
  { value: 'TOGO', label: msg`Togo 🇹🇬` },
  { value: 'TONGA', label: msg`Tonga 🇹🇴` },
  { value: 'TRINIDAD_AND_TOBAGO', label: msg`Trinidad & Tobago 🇹🇹` },
  { value: 'TUNISIA', label: msg`Tunisia 🇹🇳` },
  { value: 'TURKEY', label: msg`Turkey 🇹🇷` },
  { value: 'TURKMENISTAN', label: msg`Turkmenistan 🇹🇲` },
  { value: 'TUVALU', label: msg`Tuvalu 🇹🇻` },
  { value: 'UGANDA', label: msg`Uganda 🇺🇬` },
  { value: 'UKRAINE', label: msg`Ukraine 🇺🇦` },
  { value: 'UNITED_ARAB_EMIRATES', label: msg`UAE 🇦🇪` },
  { value: 'UNITED_KINGDOM', label: msg`UK 🇬🇧` },
  { value: 'UNITED_STATES', label: msg`USA 🇺🇸` },
  { value: 'URUGUAY', label: msg`Uruguay 🇺🇾` },
  { value: 'UZBEKISTAN', label: msg`Uzbekistan 🇺🇿` },
  { value: 'VANUATU', label: msg`Vanuatu 🇻🇺` },
  { value: 'VATICAN', label: msg`Vatican 🇻🇦` },
  { value: 'VENEZUELA', label: msg`Venezuela 🇻🇪` },
  { value: 'VIETNAM', label: msg`Vietnam 🇻🇳` },
  { value: 'YEMEN', label: msg`Yemen 🇾🇪` },
  { value: 'ZAMBIA', label: msg`Zambia 🇿🇲` },
  { value: 'ZIMBABWE', label: msg`Zimbabwe 🇿🇼` },
];

export const PARTNER_LANGUAGE_VALUES = [
  'ENGLISH',
  'FRENCH',
  'GERMAN',
  'SPANISH',
  'PORTUGUESE',
  'ITALIAN',
  'DUTCH',
  'ARABIC',
  'CHINESE',
  'JAPANESE',
  'RUSSIAN',
  'HINDI',
] as const;
export type PartnerLanguageValue = (typeof PARTNER_LANGUAGE_VALUES)[number];

export const PARTNER_LANGUAGE_OPTIONS: ReadonlyArray<{
  value: PartnerLanguageValue;
  label: MessageDescriptor;
}> = [
  { value: 'ENGLISH', label: msg`English` },
  { value: 'FRENCH', label: msg`French` },
  { value: 'GERMAN', label: msg`German` },
  { value: 'SPANISH', label: msg`Spanish` },
  { value: 'PORTUGUESE', label: msg`Portuguese` },
  { value: 'ITALIAN', label: msg`Italian` },
  { value: 'DUTCH', label: msg`Dutch` },
  { value: 'ARABIC', label: msg`Arabic` },
  { value: 'CHINESE', label: msg`Chinese` },
  { value: 'JAPANESE', label: msg`Japanese` },
  { value: 'RUSSIAN', label: msg`Russian` },
  { value: 'HINDI', label: msg`Hindi` },
];

// Per-step required field names. The wizard reducer reads this to gate `goNext`.
export const PARTNER_APPLICATION_STEP_REQUIRED_FIELDS: Record<
  PartnerApplicationStepId,
  ReadonlyArray<keyof PartnerApplicationState>
> = {
  identity: ['name', 'email', 'company', 'website'],
  profile: ['country', 'typeOfTeam', 'city'],
  expertise: ['partnerScope'],
  commercials: ['hourlyRate', 'projectBudgetMin'],
};
