export type CallRecorderPolicyNotRequiredReason =
  | 'EVENT_CANCELED'
  | 'PREFERENCE_OFF'
  | 'RECORD_BY_DEFAULT_DISABLED'
  | 'MISSING_CONFERENCE_LINK'
  | 'UNSUPPORTED_MEETING_PLATFORM'
  | 'EVENT_NOT_UPCOMING'
  | 'EVENT_BEYOND_SCHEDULING_HORIZON';
