export const CAMPAIGN_MESSAGE_DELIVERY_STATUS = {
  QUEUED: 'QUEUED',
  SENT: 'SENT',
  FAILED: 'FAILED',
  BOUNCED: 'BOUNCED',
  COMPLAINED: 'COMPLAINED',
  SKIPPED: 'SKIPPED',
} as const;

export const CAMPAIGN_STATUS = {
  DRAFT: 'DRAFT',
  SCHEDULED: 'SCHEDULED',
  SENDING: 'SENDING',
  SENT: 'SENT',
  SENT_WITH_ERRORS: 'SENT_WITH_ERRORS',
} as const;

export const MATERIALIZE_CAMPAIGN_JOB = 'MaterializeCampaignJob';
export const SEND_CAMPAIGN_EMAIL_JOB = 'SendCampaignEmailJob';
export const REFRESH_CAMPAIGN_STATS_JOB = 'RefreshCampaignStatsJob';

export const CAMPAIGN_STATS_REFRESH_DEBOUNCE_MS = 10_000;
export const CAMPAIGN_STATS_REFRESH_DELAY_MS =
  CAMPAIGN_STATS_REFRESH_DEBOUNCE_MS + 2_000;

export const MAX_CAMPAIGN_RECIPIENTS = 10000;

export const CAMPAIGN_MESSAGE_ID_NAMESPACE =
  '0c4b9e7a-3f2d-4b6c-9e1a-7d8f5a2c3b4e';
