const VERSION_BYTE_LENGTH = 1;
const KEY_ID_BYTE_LENGTH = 4;
const PURPOSE_BYTE_LENGTH = 1;
const UUID_BYTE_LENGTH = 16;
const SIGNATURE_BYTE_LENGTH = 16;

const HEADER_BYTE_LENGTH =
  VERSION_BYTE_LENGTH + KEY_ID_BYTE_LENGTH + PURPOSE_BYTE_LENGTH;

export const CAMPAIGN_TRACKING_TOKEN_BYTE_LENGTH = {
  keyId: KEY_ID_BYTE_LENGTH,
  uuid: UUID_BYTE_LENGTH,
  signature: SIGNATURE_BYTE_LENGTH,
  clickPayload: HEADER_BYTE_LENGTH + UUID_BYTE_LENGTH + UUID_BYTE_LENGTH,
  openPayload: HEADER_BYTE_LENGTH + UUID_BYTE_LENGTH,
} as const;
