import { CAMPAIGN_MESSAGE_DELIVERY_STATUS } from 'src/engine/core-modules/emailing-domain/constants/campaign.constant';
import { type CampaignMessageDeliveryStatus } from 'src/engine/core-modules/emailing-domain/types/campaign-message-delivery-status.type';

export const CAMPAIGN_MESSAGE_DELIVERY_STATUS_SEVERITY: Record<
  CampaignMessageDeliveryStatus,
  number
> = {
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.QUEUED]: 0,
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.SENDING]: 1,
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.SKIPPED]: 2,
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.SENT]: 3,
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.DELIVERED]: 4,
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.SOFT_BOUNCED]: 5,
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.FAILED]: 6,
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.REJECTED]: 7,
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.RENDERING_FAILED]: 8,
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.BOUNCED]: 9,
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.COMPLAINED]: 10,
};
