import { CAMPAIGN_MESSAGE_DELIVERY_STATUS } from 'src/engine/core-modules/emailing-domain/constants/campaign.constant';
import { type CampaignMessageDeliveryStatus } from 'src/engine/core-modules/emailing-domain/types/campaign-message-delivery-status.type';

const CORRECTABLE_BY_PROVIDER_FEEDBACK: CampaignMessageDeliveryStatus[] = [
  CAMPAIGN_MESSAGE_DELIVERY_STATUS.QUEUED,
  CAMPAIGN_MESSAGE_DELIVERY_STATUS.SENDING,
  CAMPAIGN_MESSAGE_DELIVERY_STATUS.SENT,
  CAMPAIGN_MESSAGE_DELIVERY_STATUS.FAILED,
];

const PRE_COMPLAINT_OUTCOMES: CampaignMessageDeliveryStatus[] = [
  ...CORRECTABLE_BY_PROVIDER_FEEDBACK,
  CAMPAIGN_MESSAGE_DELIVERY_STATUS.DELIVERED,
  CAMPAIGN_MESSAGE_DELIVERY_STATUS.SOFT_BOUNCED,
  CAMPAIGN_MESSAGE_DELIVERY_STATUS.REJECTED,
  CAMPAIGN_MESSAGE_DELIVERY_STATUS.RENDERING_FAILED,
];

export const CAMPAIGN_MESSAGE_DELIVERY_STATUS_OVERRIDABLE_BY: Record<
  CampaignMessageDeliveryStatus,
  CampaignMessageDeliveryStatus[]
> = {
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.DELIVERED]:
    CORRECTABLE_BY_PROVIDER_FEEDBACK,
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.SOFT_BOUNCED]:
    CORRECTABLE_BY_PROVIDER_FEEDBACK,
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.REJECTED]: CORRECTABLE_BY_PROVIDER_FEEDBACK,
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.RENDERING_FAILED]:
    CORRECTABLE_BY_PROVIDER_FEEDBACK,
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.BOUNCED]: PRE_COMPLAINT_OUTCOMES,
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.COMPLAINED]: [
    ...PRE_COMPLAINT_OUTCOMES,
    CAMPAIGN_MESSAGE_DELIVERY_STATUS.BOUNCED,
  ],
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.QUEUED]: [],
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.SENDING]: [],
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.SENT]: [],
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.SKIPPED]: [],
  [CAMPAIGN_MESSAGE_DELIVERY_STATUS.FAILED]: [],
};
