export const CLICK_TRACKING_TOKEN_UUID_BYTE_LENGTH = 16;

export const CLICK_TRACKING_TOKEN_PAYLOAD_BYTE_LENGTH =
  CLICK_TRACKING_TOKEN_UUID_BYTE_LENGTH * 2;

export const CLICK_TRACKING_TOKEN_SIGNATURE_BYTE_LENGTH = 16;

export const CLICK_TRACKING_TOKEN_BYTE_LENGTH =
  CLICK_TRACKING_TOKEN_PAYLOAD_BYTE_LENGTH +
  CLICK_TRACKING_TOKEN_SIGNATURE_BYTE_LENGTH;

export const CLICK_TRACKING_TOKEN_SIGNING_CONTEXT = 'click-tracking-token';

export const CLICK_TRACKING_TOKEN_FORMAT = /^[A-Za-z0-9_-]{64}$/;
