export const EMAIL_SEND_AWS_COST_PER_RECIPIENT_USD = 0.0001;
export const EMAIL_SEND_CREDIT_MARKUP = 3;

export const EMAIL_SEND_THROTTLE_MAX_RECIPIENTS = 500;
export const EMAIL_SEND_THROTTLE_WINDOW_MS = 60_000;
