export enum SettingsPath {
  ProfilePage = 'profile',
  Experience = 'profile/experience',
  Objects = 'objects',
  ObjectDetail = 'objects/:objectSlug',
  ObjectEdit = 'objects/:objectSlug/edit',
  ObjectNewFieldStep1 = 'objects/:objectSlug/new-field/step-1',
  ObjectNewFieldStep2 = 'objects/:objectSlug/new-field/step-2',
  ObjectFieldEdit = 'objects/:objectSlug/:fieldName',
  NewObject = 'objects/new',
  WorkspaceMembersPage = 'workspace-members',
  Workspace = 'workspace',
  Developers = 'api-keys',
  DevelopersNewApiKey = 'api-keys/new',
  DevelopersApiKeyDetail = 'api-keys/:apiKeyId',
}
