import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';
import { MessageChannelType } from 'src/modules/messaging/common/standard-objects/message-channel.workspace-entity';

export const buildMessageChannelStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'messageChannel', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'messageChannel'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: 'Id',
      description: 'Id',
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Creation date',
      description: 'Creation date',
      icon: 'IconCalendar',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Last update',
      description: 'Last time the record was changed',
      icon: 'IconCalendarClock',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Deleted at',
      description: 'Date when the record was deleted',
      icon: 'IconCalendarMinus',
      isNullable: true,
      isUIReadOnly: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  visibility: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'visibility',
      type: FieldMetadataType.SELECT,
      label: 'Visibility',
      description: 'Visibility',
      icon: 'IconEyeglass',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: "'SHARE_EVERYTHING'",
      options: [
        { value: 'METADATA', label: 'Metadata', position: 0, color: 'green' },
        { value: 'SUBJECT', label: 'Subject', position: 1, color: 'blue' },
        {
          value: 'SHARE_EVERYTHING',
          label: 'Share Everything',
          position: 2,
          color: 'orange',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  handle: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'handle',
      type: FieldMetadataType.TEXT,
      label: 'Handle',
      description: 'Handle',
      icon: 'IconAt',
      isNullable: true,
      isUIReadOnly: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  type: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'type',
      type: FieldMetadataType.SELECT,
      label: 'Type',
      description: 'Channel Type',
      icon: 'IconMessage',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: `'${MessageChannelType.EMAIL}'`,
      options: [
        {
          value: MessageChannelType.EMAIL,
          label: 'Email',
          position: 0,
          color: 'green',
        },
        {
          value: MessageChannelType.SMS,
          label: 'SMS',
          position: 1,
          color: 'blue',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  isContactAutoCreationEnabled: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'isContactAutoCreationEnabled',
      type: FieldMetadataType.BOOLEAN,
      label: 'Is Contact Auto Creation Enabled',
      description: 'Is Contact Auto Creation Enabled',
      icon: 'IconUserCircle',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  contactAutoCreationPolicy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'contactAutoCreationPolicy',
      type: FieldMetadataType.SELECT,
      label: 'Contact auto creation policy',
      description:
        'Automatically create People records when receiving or sending emails',
      icon: 'IconUserCircle',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: "'SENT'",
      options: [
        {
          value: 'SENT_AND_RECEIVED',
          label: 'Sent and Received',
          position: 0,
          color: 'green',
        },
        { value: 'SENT', label: 'Sent', position: 1, color: 'blue' },
        { value: 'NONE', label: 'None', position: 2, color: 'red' },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  messageFolderImportPolicy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'messageFolderImportPolicy',
      type: FieldMetadataType.SELECT,
      label: 'Message folder import policy',
      description: 'Message folder import policy',
      icon: 'IconFolder',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: "'ALL_FOLDERS'",
      options: [
        {
          value: 'ALL_FOLDERS',
          label: 'All folders',
          position: 0,
          color: 'green',
        },
        {
          value: 'SELECTED_FOLDERS',
          label: 'Selected folders',
          position: 1,
          color: 'blue',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  excludeNonProfessionalEmails: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'excludeNonProfessionalEmails',
      type: FieldMetadataType.BOOLEAN,
      label: 'Exclude non professional emails',
      description: 'Exclude non professional emails',
      icon: 'IconBriefcase',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  excludeGroupEmails: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'excludeGroupEmails',
      type: FieldMetadataType.BOOLEAN,
      label: 'Exclude group emails',
      description: 'Exclude group emails',
      icon: 'IconUsersGroup',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pendingGroupEmailsAction: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pendingGroupEmailsAction',
      type: FieldMetadataType.SELECT,
      label: 'Pending group emails action',
      description: 'Pending action for group emails',
      icon: 'IconUsersGroup',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: "'NONE'",
      options: [
        {
          value: 'GROUP_EMAILS_DELETION',
          label: 'Group emails deletion',
          position: 0,
          color: 'red',
        },
        {
          value: 'GROUP_EMAILS_IMPORT',
          label: 'Group emails import',
          position: 1,
          color: 'green',
        },
        { value: 'NONE', label: 'None', position: 2, color: 'blue' },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  isSyncEnabled: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'isSyncEnabled',
      type: FieldMetadataType.BOOLEAN,
      label: 'Is Sync Enabled',
      description: 'Is Sync Enabled',
      icon: 'IconRefresh',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  syncCursor: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'syncCursor',
      type: FieldMetadataType.TEXT,
      label: 'Last sync cursor',
      description: 'Last sync cursor',
      icon: 'IconHistory',
      isNullable: true,
      isUIReadOnly: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  syncedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'syncedAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Last sync date',
      description: 'Last sync date',
      icon: 'IconHistory',
      isNullable: true,
      isUIReadOnly: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  syncStatus: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'syncStatus',
      type: FieldMetadataType.SELECT,
      label: 'Sync status',
      description: 'Sync status',
      icon: 'IconStatusChange',
      isNullable: true,
      isUIReadOnly: true,
      options: [
        { value: 'ONGOING', label: 'Ongoing', position: 1, color: 'yellow' },
        {
          value: 'NOT_SYNCED',
          label: 'Not Synced',
          position: 2,
          color: 'blue',
        },
        { value: 'ACTIVE', label: 'Active', position: 3, color: 'green' },
        {
          value: 'FAILED_INSUFFICIENT_PERMISSIONS',
          label: 'Failed Insufficient Permissions',
          position: 4,
          color: 'red',
        },
        {
          value: 'FAILED_UNKNOWN',
          label: 'Failed Unknown',
          position: 5,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  syncStage: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'syncStage',
      type: FieldMetadataType.SELECT,
      label: 'Sync stage',
      description: 'Sync stage',
      icon: 'IconStatusChange',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: "'PENDING_CONFIGURATION'",
      options: [
        {
          value: 'MESSAGE_LIST_FETCH_PENDING',
          label: 'Messages list fetch pending',
          position: 0,
          color: 'blue',
        },
        {
          value: 'MESSAGE_LIST_FETCH_SCHEDULED',
          label: 'Messages list fetch scheduled',
          position: 1,
          color: 'green',
        },
        {
          value: 'MESSAGE_LIST_FETCH_ONGOING',
          label: 'Messages list fetch ongoing',
          position: 2,
          color: 'orange',
        },
        {
          value: 'MESSAGES_IMPORT_PENDING',
          label: 'Messages import pending',
          position: 3,
          color: 'blue',
        },
        {
          value: 'MESSAGES_IMPORT_SCHEDULED',
          label: 'Messages import scheduled',
          position: 4,
          color: 'green',
        },
        {
          value: 'MESSAGES_IMPORT_ONGOING',
          label: 'Messages import ongoing',
          position: 5,
          color: 'orange',
        },
        { value: 'FAILED', label: 'Failed', position: 6, color: 'red' },
        {
          value: 'PENDING_CONFIGURATION',
          label: 'Pending configuration',
          position: 7,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  syncStageStartedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'syncStageStartedAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Sync stage started at',
      description: 'Sync stage started at',
      icon: 'IconHistory',
      isNullable: true,
      isUIReadOnly: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  throttleFailureCount: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'throttleFailureCount',
      type: FieldMetadataType.NUMBER,
      label: 'Throttle Failure Count',
      description: 'Throttle Failure Count',
      icon: 'IconX',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  connectedAccount: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'connectedAccount',
      label: 'Connected Account',
      description: 'Connected Account',
      icon: 'IconUserCircle',
      isNullable: false,
      isUIReadOnly: true,
      targetObjectName: 'connectedAccount',
      targetFieldName: 'messageChannels',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'connectedAccountId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  messageChannelMessageAssociations: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'messageChannelMessageAssociations',
      label: 'Message Channel Association',
      description: 'Messages from the channel.',
      icon: 'IconMessage',
      isNullable: true,
      isUIReadOnly: true,
      targetObjectName: 'messageChannelMessageAssociation',
      targetFieldName: 'messageChannel',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  messageFolders: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'messageFolders',
      label: 'Message Folders',
      description: 'Message Folders',
      icon: 'IconFolder',
      isNullable: true,
      isUIReadOnly: true,
      targetObjectName: 'messageFolder',
      targetFieldName: 'messageChannel',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
