import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildExecutiveCapabilityStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'executiveCapability', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'executiveCapability'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  executiveProfile: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'executiveProfile',
      label: i18nLabel(msg`Executive Profile`),
      description: i18nLabel(msg`Parent executive profile`),
      icon: 'IconUser',
      isNullable: true,
      isUIEditable: false,
      targetObjectName: 'executiveProfile',
      targetFieldName: 'capabilities',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'executiveProfileId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Capability or skill name`),
      icon: 'IconStar',
      isNullable: true,
      isUIEditable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  category: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'category',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Category`),
      description: i18nLabel(msg`Capability category`),
      icon: 'IconCategory',
      isNullable: true,
      isUIEditable: true,
      options: [
        {
          id: 'f6a7b8c9-d0e1-2345-f678-901234567811',
          value: 'LEADERSHIP',
          label: i18nLabel(msg`Leadership`),
          position: 0,
          color: 'blue',
        },
        {
          id: 'f6a7b8c9-d0e1-2345-f678-901234567812',
          value: 'FINANCIAL',
          label: i18nLabel(msg`Financial`),
          position: 1,
          color: 'green',
        },
        {
          id: 'f6a7b8c9-d0e1-2345-f678-901234567813',
          value: 'OPERATIONS',
          label: i18nLabel(msg`Operations`),
          position: 2,
          color: 'orange',
        },
        {
          id: 'f6a7b8c9-d0e1-2345-f678-901234567814',
          value: 'STRATEGY',
          label: i18nLabel(msg`Strategy`),
          position: 3,
          color: 'purple',
        },
        {
          id: 'f6a7b8c9-d0e1-2345-f678-901234567815',
          value: 'TECHNICAL',
          label: i18nLabel(msg`Technical`),
          position: 4,
          color: 'sky',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  proficiencyLevel: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'proficiencyLevel',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Proficiency Level`),
      description: i18nLabel(msg`Level of proficiency`),
      icon: 'IconChartBar',
      isNullable: true,
      isUIEditable: true,
      options: [
        {
          id: 'a7b8c9d0-e1f2-3456-7890-123456789121',
          value: 'EXPERT',
          label: i18nLabel(msg`Expert`),
          position: 0,
          color: 'green',
        },
        {
          id: 'a7b8c9d0-e1f2-3456-7890-123456789122',
          value: 'PROFICIENT',
          label: i18nLabel(msg`Proficient`),
          position: 1,
          color: 'blue',
        },
        {
          id: 'a7b8c9d0-e1f2-3456-7890-123456789123',
          value: 'INTERMEDIATE',
          label: i18nLabel(msg`Intermediate`),
          position: 2,
          color: 'orange',
        },
        {
          id: 'a7b8c9d0-e1f2-3456-7890-123456789124',
          value: 'BEGINNER',
          label: i18nLabel(msg`Beginner`),
          position: 3,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  source: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'source',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Source`),
      description: i18nLabel(msg`Source of the capability assessment`),
      icon: 'IconSourceCode',
      isNullable: true,
      isUIEditable: true,
      options: [
        {
          id: 'b8c9d0e1-f2a3-4567-8901-234567890131',
          value: 'SELF_REPORTED',
          label: i18nLabel(msg`Self Reported`),
          position: 0,
          color: 'blue',
        },
        {
          id: 'b8c9d0e1-f2a3-4567-8901-234567890132',
          value: 'THIRD_PARTY',
          label: i18nLabel(msg`Third Party`),
          position: 1,
          color: 'green',
        },
        {
          id: 'b8c9d0e1-f2a3-4567-8901-234567890133',
          value: 'AI_INFERRED',
          label: i18nLabel(msg`AI Inferred`),
          position: 2,
          color: 'purple',
        },
        {
          id: 'b8c9d0e1-f2a3-4567-8901-234567890134',
          value: 'PUBLIC_PROFILE',
          label: i18nLabel(msg`Public Profile`),
          position: 3,
          color: 'sky',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Capability record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
