import {
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildFavoriteStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardFieldMetadataIdByObjectAndFieldName,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<CreateStandardFieldArgs<'favorite'>, 'context'>): Record<
  AllStandardObjectFieldName<'favorite'>,
  FlatFieldMetadata
> => ({
  // Base fields from BaseWorkspaceEntity
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: 'Id',
      description: 'Id',
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'uuid',
    },
    standardFieldMetadataIdByObjectAndFieldName,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Creation date',
      description: 'Creation date',
      icon: 'IconCalendar',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      settings: { displayFormat: 'RELATIVE' },
    },
    standardFieldMetadataIdByObjectAndFieldName,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Last update',
      description: 'Last time the record was changed',
      icon: 'IconCalendarClock',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      settings: { displayFormat: 'RELATIVE' },
    },
    standardFieldMetadataIdByObjectAndFieldName,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Deleted at',
      description: 'Date when the record was deleted',
      icon: 'IconCalendarMinus',
      isNullable: true,
      isUIReadOnly: true,
      settings: { displayFormat: 'RELATIVE' },
    },
    standardFieldMetadataIdByObjectAndFieldName,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Favorite-specific fields
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.NUMBER,
      label: 'Position',
      description: 'Favorite position',
      icon: 'IconList',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardFieldMetadataIdByObjectAndFieldName,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  view: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'view',
      type: FieldMetadataType.UUID,
      label: 'ViewId',
      description: 'ViewId',
      icon: 'IconView',
      isNullable: true,
    },
    standardFieldMetadataIdByObjectAndFieldName,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Relation fields
  forWorkspaceMember: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'forWorkspaceMember',
      label: 'Workspace Member',
      description: 'Favorite workspace member',
      icon: 'IconCircleUser',
      isNullable: true,
      createdAt,
      targetObjectName: 'workspaceMember',
      targetFieldName: 'favorites',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'forWorkspaceMemberId',
      },
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  person: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'person',
      label: 'Person',
      description: 'Favorite person',
      icon: 'IconUser',
      isNullable: true,
      createdAt,
      targetObjectName: 'person',
      targetFieldName: 'favorites',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'personId',
      },
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  company: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'company',
      label: 'Company',
      description: 'Favorite company',
      icon: 'IconBuildingSkyscraper',
      isNullable: true,
      createdAt,
      targetObjectName: 'company',
      targetFieldName: 'favorites',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'companyId',
      },
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  opportunity: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'opportunity',
      label: 'Opportunity',
      description: 'Favorite opportunity',
      icon: 'IconTargetArrow',
      isNullable: true,
      createdAt,
      targetObjectName: 'opportunity',
      targetFieldName: 'favorites',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'opportunityId',
      },
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  workflow: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'workflow',
      label: 'Workflow',
      description: 'Favorite workflow',
      icon: 'IconSettingsAutomation',
      isNullable: true,
      createdAt,
      targetObjectName: 'workflow',
      targetFieldName: 'favorites',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'workflowId',
      },
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  workflowVersion: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'workflowVersion',
      label: 'Workflow',
      description: 'Favorite workflow version',
      icon: 'IconSettingsAutomation',
      isNullable: true,
      createdAt,
      targetObjectName: 'workflowVersion',
      targetFieldName: 'favorites',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'workflowVersionId',
      },
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  workflowRun: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'workflowRun',
      label: 'Workflow',
      description: 'Favorite workflow run',
      icon: 'IconSettingsAutomation',
      isNullable: true,
      createdAt,
      targetObjectName: 'workflowRun',
      targetFieldName: 'favorites',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'workflowRunId',
      },
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  task: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'task',
      label: 'Task',
      description: 'Favorite task',
      icon: 'IconCheckbox',
      isNullable: true,
      createdAt,
      targetObjectName: 'task',
      targetFieldName: 'favorites',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'taskId',
      },
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  note: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'note',
      label: 'Note',
      description: 'Favorite note',
      icon: 'IconNotes',
      isNullable: true,
      createdAt,
      targetObjectName: 'note',
      targetFieldName: 'favorites',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'noteId',
      },
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  dashboard: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'dashboard',
      label: 'Dashboard',
      description: 'Favorite dashboard',
      icon: 'IconLayoutDashboard',
      isNullable: true,
      createdAt,
      targetObjectName: 'dashboard',
      targetFieldName: 'favorites',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'dashboardId',
      },
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  favoriteFolder: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'favoriteFolder',
      label: 'Favorite Folder',
      description: 'The folder this favorite belongs to',
      icon: 'IconFolder',
      isNullable: true,
      createdAt,
      targetObjectName: 'favoriteFolder',
      targetFieldName: 'favorites',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'favoriteFolderId',
      },
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  custom: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'custom',
      label: 'Custom',
      description: 'Favorite custom object',
      icon: 'IconHeart',
      isNullable: true,
      createdAt,
      targetObjectName: 'note',
      targetFieldName: 'favorites',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'customId',
      },
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
});
