import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export enum MessageChannelSubscriptionProvider {
  GMAIL_PUBSUB = 'GMAIL_PUBSUB',
  MICROSOFT_GRAPH = 'MICROSOFT_GRAPH',
  IMAP_IDLE = 'IMAP_IDLE',
}

export enum MessageChannelSubscriptionStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  FAILED = 'FAILED',
}

export const buildMessageChannelSubscriptionStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'messageChannelSubscription', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'messageChannelSubscription'>,
  FlatFieldMetadata
> => ({
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: 'Id',
      description: 'Id',
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Creation date',
      description: 'Creation date',
      icon: 'IconCalendar',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Last update',
      description: 'Last time the record was changed',
      icon: 'IconCalendarClock',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Deleted at',
      description: 'Date when the record was deleted',
      icon: 'IconCalendarMinus',
      isNullable: true,
      isUIReadOnly: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  provider: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'provider',
      type: FieldMetadataType.SELECT,
      label: 'Provider',
      description: 'Push notification provider',
      icon: 'IconCloud',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: `'${MessageChannelSubscriptionProvider.GMAIL_PUBSUB}'`,
      options: [
        {
          value: MessageChannelSubscriptionProvider.GMAIL_PUBSUB,
          label: 'Gmail Pub/Sub',
          position: 0,
          color: 'red',
        },
        {
          value: MessageChannelSubscriptionProvider.MICROSOFT_GRAPH,
          label: 'Microsoft Graph',
          position: 1,
          color: 'blue',
        },
        {
          value: MessageChannelSubscriptionProvider.IMAP_IDLE,
          label: 'IMAP IDLE',
          position: 2,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  status: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'status',
      type: FieldMetadataType.SELECT,
      label: 'Status',
      description: 'Subscription status',
      icon: 'IconStatusChange',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: `'${MessageChannelSubscriptionStatus.PENDING}'`,
      options: [
        {
          value: MessageChannelSubscriptionStatus.PENDING,
          label: 'Pending',
          position: 0,
          color: 'yellow',
        },
        {
          value: MessageChannelSubscriptionStatus.ACTIVE,
          label: 'Active',
          position: 1,
          color: 'green',
        },
        {
          value: MessageChannelSubscriptionStatus.EXPIRED,
          label: 'Expired',
          position: 2,
          color: 'orange',
        },
        {
          value: MessageChannelSubscriptionStatus.FAILED,
          label: 'Failed',
          position: 3,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  expiresAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'expiresAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Expires at',
      description: 'When the subscription expires',
      icon: 'IconCalendarTime',
      isNullable: true,
      isUIReadOnly: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  providerSubscriptionId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'providerSubscriptionId',
      type: FieldMetadataType.TEXT,
      label: 'Provider Subscription ID',
      description:
        'Provider-specific subscription identifier (e.g., historyId for Gmail)',
      icon: 'IconKey',
      isNullable: true,
      isUIReadOnly: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  lastNotificationAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'lastNotificationAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Last notification at',
      description: 'When the last notification was received',
      icon: 'IconBellRinging',
      isNullable: true,
      isUIReadOnly: true,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  failureCount: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'failureCount',
      type: FieldMetadataType.NUMBER,
      label: 'Failure Count',
      description: 'Number of consecutive failures',
      icon: 'IconAlertTriangle',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  lastError: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'lastError',
      type: FieldMetadataType.TEXT,
      label: 'Last Error',
      description: 'Last error message',
      icon: 'IconBug',
      isNullable: true,
      isUIReadOnly: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  messageChannel: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'messageChannel',
      label: 'Message Channel',
      description: 'Related message channel',
      icon: 'IconMessage',
      isNullable: false,
      isUIReadOnly: true,
      targetObjectName: 'messageChannel',
      targetFieldName: 'subscriptions',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'messageChannelId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
