type MktAttributeDataSeed = {
  id: string;
  name: string;
  description: string;
  position: number;
  createdBySource: string;
  createdByWorkspaceMemberId: string | null;
  createdByName: string;
};

// prettier-ignore
export const MKT_ATTRIBUTE_DATA_SEED_COLUMNS: (keyof MktAttributeDataSeed)[] = [
  'id',
  'name',
  'description',
  'position',
  'createdBySource',
  'createdByWorkspaceMemberId',
  'createdByName',
];
// prettier-ignore
export const MKT_ATTRIBUTE_DATA_SEEDS_IDS = {
  ID_1: '1bacf2e1-54ef-484e-8d5b-cb3bb4bd3853',
  ID_2: 'bdb3400f-c3bb-4194-9df1-dc93d33379d6',
  ID_3: '6d41f987-3682-4a99-a181-106ce3422242',
  ID_4: 'c324d781-7025-41e4-a45a-7675cbde361f',
  ID_5: '95878b9b-a4b8-4926-a776-855cb080dffa',
  ID_6: '0197a480-bab0-4f9a-b13e-eff89eaebab5',
  ID_7: '54543cf3-a6bb-4b0f-9427-c876b566db87',
  ID_8: 'b150cf28-da06-4127-9ba3-0edc418ab4ab',
  ID_9: 'd00573cc-845c-44bd-b71f-98ef811ae5cf',
  ID_10: '1b4f8f4e-c532-486c-9f0e-d7e60bd54bf2',
  ID_11: '871093ef-6888-4f59-91a3-6602b7df5bd6',
  ID_12: '292f1f1d-9551-48e2-9450-ab9252f81760',
  ID_13: '9ad7f2ba-0eab-43a0-9318-c6f766070172',
  MKT_LANGUAGE_ID: '17c105e7-ef2a-40f8-bb53-39c85cd5400a',
  MKT_CHANNEL_ID: '754a989c-d219-4a3e-acf6-71571ae97816',
  MKT_MONTH_DURATION_ID: 'a13160e7-dc57-4ac0-b4e4-e048b35c581e',
  MKT_INTERNAL_TYPE_ID: 'f6ca448c-4f4e-46ec-84e3-4fc75026fddc'
};

//prettier-ignore
export const MKT_ATTRIBUTE_DATA_SEEDS: MktAttributeDataSeed[] = [
  // Product 1: Wireless Bluetooth Headphones (Electronics) - 3 attributes
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.ID_1,
    name: 'Color',
    description: 'Màu sắc của sản phẩm',
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.ID_2,
    name: 'Battery Life',
    description: 'Thời gian sử dụng pin của sản phẩm',
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.ID_3,
    name: 'Noise Cancellation',
    description: 'Khả năng giảm tiếng ồn của sản phẩm',
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  
  // Product 2: Organic Arabica Coffee Beans (Groceries) - 2 attributes
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.ID_4,
    name: 'Roast Level',
    description: 'Mức độ chế biến của cà phê',
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.ID_5,
    name: 'Origin',
    description: 'Nguồn gốc của cà phê',
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  
  // Product 3: Ergonomic Office Chair (Furniture) - 3 attributes
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.ID_6,
    name: 'Material',
    description: 'Vật liệu chế tạo của sản phẩm',
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.ID_7,
    name: 'Weight Capacity',
    description: 'Khả năng chịu tải của sản phẩm',
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.ID_8,
    name: 'Adjustable Features',
    description: 'Tính năng điều chỉnh của sản phẩm',
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  
  // Product 4: Stainless Steel Water Bottle (Outdoor & Travel) - 2 attributes
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.ID_9,
    name: 'Capacity',
    description: 'Dung tích của sản phẩm',
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.ID_10,
    name: 'Insulation Type',
    description: 'Loại cách nhiệt của sản phẩm',
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  
  // Product 5: LED Desk Lamp (Home & Living) - 3 attributes
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.ID_11,
    name: 'Color Temperature',
    description: 'Màu sắc của sản phẩm',
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.ID_12,
    name: 'Brightness Levels',
    description: 'Mức độ sáng của sản phẩm',
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.ID_13,
    name: 'Mounting Type',
    description: 'Loại lắp đặt của sản phẩm',
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  
  // MKT Attributes for MKT_CARE_BASIC
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_LANGUAGE_ID,
    name: 'language',
    description: 'Ngôn ngữ sản phẩm',
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_CHANNEL_ID,
    name: 'channel',
    description: 'Kênh bán hàng',
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_MONTH_DURATION_ID,
    name: 'duration',
    description: 'Thời hạn sử dụng',
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_INTERNAL_TYPE_ID,
    name: 'product_type',
    description: 'Loại sản phẩm (single/combo)',
    position: 4,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  
  // MKT Attributes for MKT_CARE_PREMIUM
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_LANGUAGE_ID,
    name: 'language',
    description: 'Ngôn ngữ sản phẩm',
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_CHANNEL_ID,
    name: 'channel',
    description: 'Kênh bán hàng',
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_MONTH_DURATION_ID,
    name: 'duration',
    description: 'Thời hạn sử dụng',
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_INTERNAL_TYPE_ID,
    name: 'product_type',
    description: 'Loại sản phẩm (single/combo)',
    position: 4,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  
  // MKT Attributes for MKT_EMAIL_PLUS
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_LANGUAGE_ID,
    name: 'language',
    description: 'Ngôn ngữ sản phẩm',
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_CHANNEL_ID,
    name: 'channel',
    description: 'Kênh bán hàng',
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_MONTH_DURATION_ID,
    name: 'duration',
    description: 'Thời hạn sử dụng',
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_INTERNAL_TYPE_ID,
    name: 'product_type',
    description: 'Loại sản phẩm (single/combo)',
    position: 4,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  
  // MKT Attributes for MKT_SEO_STARTER
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_LANGUAGE_ID,
    name: 'language',
    description: 'Ngôn ngữ sản phẩm',
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_CHANNEL_ID,
    name: 'channel',
    description: 'Kênh bán hàng',
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_MONTH_DURATION_ID,
    name: 'duration',
    description: 'Thời hạn sử dụng',
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_INTERNAL_TYPE_ID,
    name: 'product_type',
    description: 'Loại sản phẩm (single/combo)',
    position: 4,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  
  // MKT Attributes for MKT_LICENSE_BIZ
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_LANGUAGE_ID,
    name: 'language',
    description: 'Ngôn ngữ sản phẩm',
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_CHANNEL_ID,
    name: 'channel',
    description: 'Kênh bán hàng',
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_MONTH_DURATION_ID,
    name: 'duration',
    description: 'Thời hạn sử dụng',
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_INTERNAL_TYPE_ID,
    name: 'product_type',
    description: 'Loại sản phẩm (single/combo)',
    position: 4,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  
  // MKT Attributes for MKT_CARE_PRO
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_LANGUAGE_ID,
    name: 'language',
    description: 'Ngôn ngữ sản phẩm',
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_CHANNEL_ID,
    name: 'channel',
    description: 'Kênh bán hàng',
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_MONTH_DURATION_ID,
    name: 'duration',
    description: 'Thời hạn sử dụng',
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_INTERNAL_TYPE_ID,
    name: 'product_type',
    description: 'Loại sản phẩm (single/combo)',
    position: 4,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  
  // MKT Attributes for MKT_CARE_ENTERPRISE
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_LANGUAGE_ID,
    name: 'language',
    description: 'Ngôn ngữ sản phẩm',
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_CHANNEL_ID,
    name: 'channel',
    description: 'Kênh bán hàng',
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_MONTH_DURATION_ID,
    name: 'duration',
    description: 'Thời hạn sử dụng',
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_INTERNAL_TYPE_ID,
    name: 'product_type',
    description: 'Loại sản phẩm (single/combo)',
    position: 4,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  
  // MKT Attributes for MKT_POST_STARTER
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_LANGUAGE_ID,
    name: 'language',
    description: 'Ngôn ngữ sản phẩm',
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_CHANNEL_ID,
    name: 'channel',
    description: 'Kênh bán hàng',
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_MONTH_DURATION_ID,
    name: 'duration',
    description: 'Thời hạn sử dụng',
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_INTERNAL_TYPE_ID,
    name: 'product_type',
    description: 'Loại sản phẩm (single/combo)',
    position: 4,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  
  // MKT Attributes for MKT_POST_PRO
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_LANGUAGE_ID,
    name: 'language',
    description: 'Ngôn ngữ sản phẩm',
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_CHANNEL_ID,
    name: 'channel',
    description: 'Kênh bán hàng',
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_MONTH_DURATION_ID,
    name: 'duration',
    description: 'Thời hạn sử dụng',
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_INTERNAL_TYPE_ID,
    name: 'product_type',
    description: 'Loại sản phẩm (single/combo)',
    position: 4,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  
  // MKT Attributes for MKT_POST_AGENCY
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_LANGUAGE_ID,
    name: 'language',
    description: 'Ngôn ngữ sản phẩm',
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_CHANNEL_ID,
    name: 'channel',
    description: 'Kênh bán hàng',
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_MONTH_DURATION_ID,
    name: 'duration',
    description: 'Thời hạn sử dụng',
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_INTERNAL_TYPE_ID,
    name: 'product_type',
    description: 'Loại sản phẩm (single/combo)',
    position: 4,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  
  // MKT Attributes for MKT_VIRAL_BASIC
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_LANGUAGE_ID,
    name: 'language',
    description: 'Ngôn ngữ sản phẩm',
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_CHANNEL_ID,
    name: 'channel',
    description: 'Kênh bán hàng',
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_MONTH_DURATION_ID,
    name: 'duration',
    description: 'Thời hạn sử dụng',
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_INTERNAL_TYPE_ID,
    name: 'product_type',
    description: 'Loại sản phẩm (single/combo)',
    position: 4,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  
  // MKT Attributes for MKT_VIRAL_PRO
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_LANGUAGE_ID,
    name: 'language',
    description: 'Ngôn ngữ sản phẩm',
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_CHANNEL_ID,
    name: 'channel',
    description: 'Kênh bán hàng',
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_MONTH_DURATION_ID,
    name: 'duration',
    description: 'Thời hạn sử dụng',
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_INTERNAL_TYPE_ID,
    name: 'product_type',
    description: 'Loại sản phẩm (single/combo)',
    position: 4,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  
  // MKT Attributes for MKT_VIRAL_ULTIMATE
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_LANGUAGE_ID,
    name: 'language',
    description: 'Ngôn ngữ sản phẩm',
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_CHANNEL_ID,
    name: 'channel',
    description: 'Kênh bán hàng',
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_MONTH_DURATION_ID,
    name: 'duration',
    description: 'Thời hạn sử dụng',
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
  {
    id: MKT_ATTRIBUTE_DATA_SEEDS_IDS.MKT_INTERNAL_TYPE_ID,
    name: 'product_type',
    description: 'Loại sản phẩm (single/combo)',
    position: 4,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Tim A',
  },
];
