import {
  type AIModelConfig,
  InferenceProvider,
  ModelFamily,
} from './ai-models-types.const';

export const OPENAI_MODELS: AIModelConfig[] = [
  // Active models
  {
    modelId: 'gpt-5.2',
    label: 'GPT-5.2',
    description:
      'Most advanced OpenAI model for coding, agentic tasks, and complex reasoning',
    modelFamily: ModelFamily.OPENAI,
    inferenceProvider: InferenceProvider.OPENAI,
    inputCostPerMillionTokens: 1.75,
    outputCostPerMillionTokens: 14.0,
    cachedInputCostPerMillionTokens: 0.175,
    contextWindowTokens: 400000,
    maxOutputTokens: 128000,
    supportedFileTypes: ['image/png', 'image/jpeg', 'image/gif', 'image/webp'],
    doesSupportThinking: true,
    nativeCapabilities: {
      webSearch: true,
    },
  },
  {
    modelId: 'gpt-5-mini',
    label: 'GPT-5 Mini',
    description: 'Fast and cost-efficient GPT-5 variant for well-defined tasks',
    modelFamily: ModelFamily.OPENAI,
    inferenceProvider: InferenceProvider.OPENAI,
    inputCostPerMillionTokens: 0.25,
    outputCostPerMillionTokens: 2.0,
    cachedInputCostPerMillionTokens: 0.025,
    contextWindowTokens: 128000,
    maxOutputTokens: 32768,
    supportedFileTypes: ['image/png', 'image/jpeg', 'image/gif', 'image/webp'],
    nativeCapabilities: {
      webSearch: true,
    },
  },
  {
    modelId: 'gpt-4.1',
    label: 'GPT-4.1',
    description: 'Strong model with 1M context, cost-effective output pricing',
    modelFamily: ModelFamily.OPENAI,
    inferenceProvider: InferenceProvider.OPENAI,
    inputCostPerMillionTokens: 2.0,
    outputCostPerMillionTokens: 8.0,
    cachedInputCostPerMillionTokens: 0.5,
    contextWindowTokens: 1047576,
    maxOutputTokens: 32768,
    supportedFileTypes: ['image/png', 'image/jpeg', 'image/gif', 'image/webp'],
    nativeCapabilities: {
      webSearch: true,
    },
  },
  {
    modelId: 'gpt-4.1-mini',
    label: 'GPT-4.1 Mini',
    description: 'Budget-friendly model with 1M context for lightweight tasks',
    modelFamily: ModelFamily.OPENAI,
    inferenceProvider: InferenceProvider.OPENAI,
    inputCostPerMillionTokens: 0.4,
    outputCostPerMillionTokens: 1.6,
    cachedInputCostPerMillionTokens: 0.1,
    contextWindowTokens: 1047576,
    maxOutputTokens: 32768,
    supportedFileTypes: ['image/png', 'image/jpeg', 'image/gif', 'image/webp'],
    nativeCapabilities: {
      webSearch: true,
    },
  },

  // Deprecated models - kept for backward compatibility with existing agents
  {
    modelId: 'o3',
    label: 'o3',
    description:
      'Reasoning model for complex queries, coding, math, and science',
    modelFamily: ModelFamily.OPENAI,
    inferenceProvider: InferenceProvider.OPENAI,
    inputCostPerMillionTokens: 2.0,
    outputCostPerMillionTokens: 8.0,
    cachedInputCostPerMillionTokens: 0.5,
    contextWindowTokens: 200000,
    maxOutputTokens: 100000,
    supportedFileTypes: ['image/png', 'image/jpeg', 'image/gif', 'image/webp'],
    doesSupportThinking: true,
    nativeCapabilities: {
      webSearch: true,
    },
    deprecated: true,
  },
  {
    modelId: 'o4-mini',
    label: 'o4-mini',
    description:
      'Cost-effective reasoning model for math, coding, and visual tasks',
    modelFamily: ModelFamily.OPENAI,
    inferenceProvider: InferenceProvider.OPENAI,
    inputCostPerMillionTokens: 1.1,
    outputCostPerMillionTokens: 4.4,
    cachedInputCostPerMillionTokens: 0.275,
    contextWindowTokens: 200000,
    maxOutputTokens: 100000,
    supportedFileTypes: ['image/png', 'image/jpeg', 'image/gif', 'image/webp'],
    doesSupportThinking: true,
    nativeCapabilities: {
      webSearch: true,
    },
    deprecated: true,
  },
  {
    modelId: 'gpt-4o',
    label: 'GPT-4o',
    description:
      'Previous generation multimodal model with strong reasoning and vision',
    modelFamily: ModelFamily.OPENAI,
    inferenceProvider: InferenceProvider.OPENAI,
    inputCostPerMillionTokens: 2.5,
    outputCostPerMillionTokens: 10.0,
    cachedInputCostPerMillionTokens: 1.25,
    contextWindowTokens: 128000,
    maxOutputTokens: 16384,
    supportedFileTypes: ['image/png', 'image/jpeg', 'image/gif', 'image/webp'],
    nativeCapabilities: {
      webSearch: true,
    },
    deprecated: true,
  },
  {
    modelId: 'gpt-4o-mini',
    label: 'GPT-4o Mini',
    description: 'Previous generation fast model for lightweight tasks',
    modelFamily: ModelFamily.OPENAI,
    inferenceProvider: InferenceProvider.OPENAI,
    inputCostPerMillionTokens: 0.15,
    outputCostPerMillionTokens: 0.6,
    cachedInputCostPerMillionTokens: 0.075,
    contextWindowTokens: 128000,
    maxOutputTokens: 16384,
    supportedFileTypes: ['image/png', 'image/jpeg', 'image/gif', 'image/webp'],
    nativeCapabilities: {
      webSearch: true,
    },
    deprecated: true,
  },
  {
    modelId: 'gpt-4-turbo',
    label: 'GPT-4 Turbo',
    description: 'Legacy high-performance model with vision capabilities',
    modelFamily: ModelFamily.OPENAI,
    inferenceProvider: InferenceProvider.OPENAI,
    inputCostPerMillionTokens: 10.0,
    outputCostPerMillionTokens: 30.0,
    contextWindowTokens: 128000,
    maxOutputTokens: 4096,
    supportedFileTypes: ['image/png', 'image/jpeg', 'image/gif', 'image/webp'],
    deprecated: true,
  },
];
