import { ANIMATION } from 'twenty-ui/theme';

const EXPANDED_CHAT_TRANSITION_DURATION_IN_MS =
  ANIMATION.duration.normal * 1000;
const ANIMATION_TAIL_SETTLE_MARGIN_IN_MS = 100;

export const AI_CHAT_SCROLL_PIN_MIN_DURATION_IN_MS =
  EXPANDED_CHAT_TRANSITION_DURATION_IN_MS + ANIMATION_TAIL_SETTLE_MARGIN_IN_MS;
