export enum EnvironmentVariablesSubGroup {
  PasswordAuth = 'password-auth',
  GoogleAuth = 'google-auth',
  MicrosoftAuth = 'microsoft-auth',
  EmailSettings = 'email-settings',
  StorageConfig = 'storage-config',
  Tokens = 'tokens',
  SSL = 'ssl',
  RateLimiting = 'rate-limiting',
  TinybirdConfig = 'tinybird-config',
  StripeConfig = 'stripe-config',
  SentryConfig = 'sentry-config',
  FrontSupportConfig = 'front-support-config',
  CloudflareConfig = 'cloudflare-config',
  CaptchaConfig = 'captcha-config',
  ServerlessConfig = 'serverless-config',
}
