export enum EnvironmentVariablesGroup {
  Authentication = 'authentication',
  Email = 'email',
  Database = 'database',
  Storage = 'storage',
  ServerConfig = 'server-config',
  QueueConfig = 'queue-config',
  Logging = 'logging',
  Cache = 'cache',
  Analytics = 'analytics',
  Billing = 'billing',
  Frontend = 'frontend',
  Security = 'security',
  Serverless = 'serverless',
  Support = 'support',
  LLM = 'llm',
  Workspace = 'workspace',
}
