export enum EnvironmentVariablesSubGroup {
  PasswordAuth = 'password-auth',
  GoogleAuth = 'google-auth',
  MicrosoftAuth = 'microsoft-auth',
  EmailSettings = 'email-settings',
  StorageConfig = 'storage-config',
  TokensDuration = 'tokens-duration',
  SSL = 'ssl',
  RateLimiting = 'rate-limiting',
  TinybirdConfig = 'tinybird-config',
  BillingConfig = 'billing-config',
  ExceptionHandler = 'exception-handler',
  SupportChatConfig = 'support-chat-config',
  CloudflareConfig = 'cloudflare-config',
  CaptchaConfig = 'captcha-config',
  ServerlessConfig = 'serverless-config',
  LLM = 'llm',
}
