import { type AllMetadataName } from 'twenty-shared/metadata';

export const METADATA_EVENTS_TO_EMIT = {
  frontComponent: true,
  objectMetadata: false,
  fieldMetadata: false,
  view: false,
  viewField: false,
  viewFieldGroup: false,
  viewGroup: false,
  viewFilter: false,
  viewFilterGroup: false,
  role: false,
  roleTarget: false,
  agent: false,
  skill: false,
  pageLayout: false,
  pageLayoutWidget: false,
  pageLayoutTab: false,
  commandMenuItem: false,
  navigationMenuItem: false,
  webhook: false,
  rowLevelPermissionPredicate: false,
  rowLevelPermissionPredicateGroup: false,
  index: false,
  logicFunction: false,
} as const satisfies { [P in AllMetadataName]: boolean };
