// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { Prisma } from '@prisma/client';

export type ModelSelectMap = {
  User: Prisma.UserSelect;
  UserSettings: Prisma.UserSettingsSelect;
  Workspace: Prisma.WorkspaceSelect;
  WorkspaceMember: Prisma.WorkspaceMemberSelect;
  Company: Prisma.CompanySelect;
  Person: Prisma.PersonSelect;
  RefreshToken: Prisma.RefreshTokenSelect;
  Activity: Prisma.ActivitySelect;
  Comment: Prisma.CommentSelect;
  ActivityTarget: Prisma.ActivityTargetSelect;
  Pipeline: Prisma.PipelineSelect;
  PipelineStage: Prisma.PipelineStageSelect;
  PipelineProgress: Prisma.PipelineProgressSelect;
  Attachment: Prisma.AttachmentSelect;
  ViewField: Prisma.ViewFieldSelect;
};
