import { CoreApiClient } from 'twenty-client-sdk/core';
import { MetadataApiClient } from 'twenty-client-sdk/metadata';

export const metadata = () => new MetadataApiClient();

// CoreApiClient is code-generated by `appDevOnce` / `yarn twenty dev`.
// In monorepo CI the generated client may not be available, so callers
// should use isCoreClientAvailable() before constructing.
export const core = () => new CoreApiClient();

export function isCoreClientAvailable(): boolean {
  try {
    new CoreApiClient();
    return true;
  } catch {
    return false;
  }
}
