export const USER_GUIDE_INDEX = {
  'User Guide': {
    'Getting Started': [
      { fileName: 'getting-started' },
      { fileName: 'what-is-twenty' },
      { fileName: 'create-workspace' },
      { fileName: 'getting-around-twenty' },
      { fileName: 'configure-workspace-in-three-steps' },
      { fileName: 'implementation-services' },
      { fileName: 'migrating-from-other-crms' },
      { fileName: 'import-export-data' },
    ],
    'Data Model': [
      { fileName: 'customize-your-data-model' },
      { fileName: 'objects' },
      { fileName: 'fields' },
      { fileName: 'object-relations' },
      { fileName: 'data-model-faq' },
      { fileName: 'data-model' },
    ],
    'Core CRM Features': [
      { fileName: 'creating-records' },
      { fileName: 'favorites-management' },
      { fileName: 'core-crm-features' },
      { fileName: 'lead-management' },
      { fileName: 'sales-pipeline-management' },
      { fileName: 'contact-account-management' },
      { fileName: 'activity-tracking' },
      { fileName: 'lead-scoring-workflows' },
      { fileName: 'views-sort-filter' },
      { fileName: 'kanban-views' },
      { fileName: 'creating-managing-views' },
      { fileName: 'field-management' },
      { fileName: 'view-types' },
      { fileName: 'personal-vs-shared-views' },
      { fileName: 'dynamic-filters' },
      { fileName: 'record-name-configuration' },
    ],
    'Workflows': [
      { fileName: 'workflows' },
      { fileName: 'getting-started-workflows' },
      { fileName: 'workflow-management' },
      { fileName: 'workflow-use-cases' },
      { fileName: 'starter-workflows' },
      { fileName: 'workflow-credits' },
      { fileName: 'sales-automation-recipes' },
      { fileName: 'external-tool-integration' },
      { fileName: 'marketing-other-use-cases' },
      { fileName: 'workflow-troubleshooting' },
    ],
    'Collaboration': [
      { fileName: 'collaboration' },
      { fileName: 'emails' },
      { fileName: 'mailbox-calendar-sync' },
      { fileName: 'gmail-outlook-setup' },
      { fileName: 'smtp-caldav-configuration' },
      { fileName: 'notes' },
      { fileName: 'tasks' },
      { fileName: 'team-collaboration-productivity' },
      { fileName: 'team-collaboration-best-practices' },
    ],
    'Integrations & APIs': [
      { fileName: 'integrations' },
      { fileName: 'api-webhooks' },
      { fileName: 'api-types-overview' },
      { fileName: 'api-access' },
      { fileName: 'custom-api-documentation' },
      { fileName: 'api-best-practices' },
      { fileName: 'api-rate-limits' },
      { fileName: 'third-party-integrations' },
    ],
    'Reporting': [
      { fileName: 'reporting' },
      { fileName: 'reporting-overview' },
    ],
    'Settings': [
      { fileName: 'settings' },
      { fileName: 'profile-settings' },
      { fileName: 'experience-settings' },
      { fileName: 'email-calendar-setup' },
      { fileName: 'workspace-settings' },
      { fileName: 'member-management' },
      { fileName: 'permissions' },
      { fileName: 'domains-settings' },
      { fileName: 'releases-settings' },
      { fileName: 'settings-faq' },
    ],
    'Pricing': [
      { fileName: 'pricing' },
      { fileName: 'billing-and-pricing-faq' },
      { fileName: 'workflow-credits-pricing' },
    ],
    'Resources': [
      { fileName: 'resources' },
      { fileName: 'glossary' },
      { fileName: 'github' },
      { fileName: 'troubleshooting-common-issues' },
      { fileName: 'form-integration' },
      { fileName: 'email-marketing' },
      { fileName: 'business-process-integration' },
    ],
  },
  Developers: {
    'Empty Section': [],
  },
};
