export const USER_GUIDE_INDEX = {
  'User Guide': {
    'Getting Started': [
      { fileName: 'getting-started' },
      { fileName: 'what-is-twenty' },
      { fileName: 'create-workspace' },
      { fileName: 'getting-around-twenty' },
      { fileName: 'configure-workspace-in-three-steps' },
      { fileName: 'implementation-services' },
      { fileName: 'migrating-from-other-crms' },
      { fileName: 'import-export-data' },
    ],
    'Data Model': [
      { fileName: 'customize-your-data-model' },
      { fileName: 'objects' },
      { fileName: 'fields' },
      { fileName: 'object-relations' },
      { fileName: 'data-model-faq' },
      { fileName: 'data-model' },
    ],
    'CRM Essentials': [
      { fileName: 'crm-essentials' },
      { fileName: 'contact-and-account-management' },
      { fileName: 'pipeline'},
      { fileName: 'view-management' },
      { fileName: 'sales-use-cases' },
    ],
    'Workflows': [
      { fileName: 'workflows' },
      { fileName: 'getting-started-workflows' },
      { fileName: 'workflow-management' },
      { fileName: 'workflow-use-cases' },
      { fileName: 'starter-workflows' },
      { fileName: 'workflow-credits' },
      { fileName: 'sales-automation-recipes' },
      { fileName: 'external-tool-integration' },
      { fileName: 'marketing-other-use-cases' },
      { fileName: 'workflow-troubleshooting' },
    ],
    'Collaboration': [
      { fileName: 'collaboration' },
      { fileName: 'emails-and-calendars' },
      { fileName: 'notes' },
      { fileName: 'tasks' },
    ],
    'Integrations API': [
      { fileName: 'apis-overview' },
      { fileName: 'api-webhooks' },
      { fileName: 'integrations-api' },
      { fileName: 'integrations' },
    ],
    'Reporting': [
      { fileName: 'reporting' },
      { fileName: 'reporting-overview' },
    ],
    'Settings': [
      { fileName: 'settings' },
      { fileName: 'profile-settings' },
      { fileName: 'experience-settings' },
      { fileName: 'email-calendar-setup' },
      { fileName: 'workspace-settings' },
      { fileName: 'member-management' },
      { fileName: 'permissions' },
      { fileName: 'domains-settings' },
      { fileName: 'releases-settings' },
      { fileName: 'settings-faq' },
    ],
    'Pricing': [
      { fileName: 'pricing' },
      { fileName: 'billing-and-pricing-faq' },
    ],
    'Resources': [
      { fileName: 'resources' },
      { fileName: 'glossary' },
      { fileName: 'github' },
    ],
  },
  Developers: {
    'Empty Section': [],
  },
};
