export enum PermissionFlagType {
  // Settings permissions
  API_KEYS_AND_WEBHOOKS = 'API_KEYS_AND_WEBHOOKS',
  WORKSPACE = 'WORKSPACE',
  WORKSPACE_MEMBERS = 'WORKSPACE_MEMBERS',
  ROLES = 'ROLES',
  DATA_MODEL = 'DATA_MODEL',
  SECURITY = 'SECURITY',
  WORKFLOWS = 'WORKFLOWS',
  IMPERSONATE = 'IMPERSONATE',
  APPLICATIONS = 'APPLICATIONS',
  LAYOUTS = 'LAYOUTS',
  MANAGE_VIEWS = 'MANAGE_VIEWS',
  BILLING = 'BILLING',

  // Tool permissions
  AI = 'AI',
  UPLOAD_FILE = 'UPLOAD_FILE',
  DOWNLOAD_FILE = 'DOWNLOAD_FILE',
  SEND_EMAIL_TOOL = 'SEND_EMAIL_TOOL',
  IMPORT_CSV = 'IMPORT_CSV',
  EXPORT_CSV = 'EXPORT_CSV',
}
