export enum PermissionFlagType {
  // Settings permissions
  API_KEYS_AND_WEBHOOKS = 'API_KEYS_AND_WEBHOOKS',
  WORKSPACE = 'WORKSPACE',
  WORKSPACE_MEMBERS = 'WORKSPACE_MEMBERS',
  ROLES = 'ROLES',
  DATA_MODEL = 'DATA_MODEL',
  ADMIN_PANEL = 'ADMIN_PANEL',
  SECURITY = 'SECURITY',
  WORKFLOWS = 'WORKFLOWS',
  IMPERSONATE = 'IMPERSONATE',
  SSO_BYPASS = 'SSO_BYPASS',

  // Tool permissions
  SEND_EMAIL_TOOL = 'SEND_EMAIL_TOOL',
  IMPORT_CSV = 'IMPORT_CSV',
  EXPORT_CSV = 'EXPORT_CSV',
}
