import { type FlatObjectMetadata } from 'src/engine/metadata-modules/flat-object-metadata/types/flat-object-metadata.type';
import { type ObjectMetadataDTO } from 'src/engine/metadata-modules/object-metadata/dtos/object-metadata.dto';

export const fromFlatObjectMetadataToObjectMetadataDto = (
  flatObjectMetadata: FlatObjectMetadata,
): ObjectMetadataDTO => {
  const {
    createdAt,
    updatedAt,
    color,
    description,
    icon,
    overrides,
    shortcut,
    duplicateCriteria,
    id,
    universalIdentifier,
    isActive,
    isLabelSyncedWithName,
    isRemote,
    isSearchable,
    isSystem,
    isUIEditable,
    isUICreatable,
    labelPlural,
    labelSingular,
    namePlural,
    nameSingular,
    workspaceId,
    imageIdentifierFieldMetadataId,
    labelIdentifierFieldMetadataId,
    applicationId,
  } = flatObjectMetadata;

  return {
    id,
    universalIdentifier,
    isActive,
    isLabelSyncedWithName,
    isRemote,
    isSearchable,
    isSystem,
    isUIEditable,
    isUICreatable,
    isUIReadOnly: !isUIEditable,
    labelPlural,
    labelSingular,
    namePlural,
    nameSingular,
    workspaceId,
    imageIdentifierFieldMetadataId,
    labelIdentifierFieldMetadataId,
    createdAt: new Date(createdAt),
    updatedAt: new Date(updatedAt),
    color: color ?? undefined,
    description: description ?? undefined,
    icon: icon ?? undefined,
    overrides: overrides ?? undefined,
    shortcut: shortcut ?? undefined,
    duplicateCriteria: duplicateCriteria ?? undefined,
    applicationId,
  };
};
