export const SETTINGS_SELECT_MENU_GAP_PIXELS = 4;

export const SETTINGS_SELECT_MENU_MAX_HEIGHT_PIXELS = 320;

export const SETTINGS_SELECT_MENU_WIDTH_PIXELS = 200;

export const SETTINGS_SELECT_MENU_BACKDROP_Z_INDEX = 2000;

export const SETTINGS_SELECT_MENU_Z_INDEX = 2001;
