export const PAGE_LAYOUT_WIDGET_SEEDS = {
  SALES_PIPELINE_NUMBER: 'SALES_PIPELINE_NUMBER_WIDGET',
  SALES_CONVERSION_GAUGE: 'SALES_CONVERSION_GAUGE_WIDGET',
  SALES_MONTHLY_REVENUE: 'SALES_MONTHLY_REVENUE_WIDGET',
  SALES_DEALS_BY_STAGE: 'SALES_DEALS_BY_STAGE_WIDGET',
  SALES_TOP_PERFORMERS: 'SALES_TOP_PERFORMERS_WIDGET',
  SALES_FORECAST_LINE: 'SALES_FORECAST_LINE_WIDGET',

  CUSTOMER_TOTAL_COUNT: 'CUSTOMER_TOTAL_COUNT_WIDGET',
  CUSTOMER_ACQUISITION_TREND: 'CUSTOMER_ACQUISITION_TREND_WIDGET',
  CUSTOMER_SEGMENTS_PIE: 'CUSTOMER_SEGMENTS_PIE_WIDGET',
  CUSTOMER_SATISFACTION_GAUGE: 'CUSTOMER_SATISFACTION_GAUGE_WIDGET',
  CUSTOMER_RETENTION_RATE: 'CUSTOMER_RETENTION_RATE_WIDGET',
  CUSTOMER_LIFETIME_VALUE: 'CUSTOMER_LIFETIME_VALUE_WIDGET',

  TEAM_ACTIVITY_OVERVIEW: 'TEAM_ACTIVITY_OVERVIEW_WIDGET',
  TEAM_PRODUCTIVITY_METRICS: 'TEAM_PRODUCTIVITY_METRICS_WIDGET',
  TEAM_GOAL_PROGRESS: 'TEAM_GOAL_PROGRESS_WIDGET',
  TEAM_MEMBER_LEADERBOARD: 'TEAM_MEMBER_LEADERBOARD_WIDGET',

  REVENUE_TOTAL_NUMBER: 'REVENUE_TOTAL_NUMBER_WIDGET',
  REVENUE_GROWTH_TREND: 'REVENUE_GROWTH_TREND_WIDGET',
  REVENUE_BY_PRODUCT: 'REVENUE_BY_PRODUCT_WIDGET',
  REVENUE_BY_REGION: 'REVENUE_BY_REGION_WIDGET',

  MARKETING_LEADS_GENERATED: 'MARKETING_LEADS_GENERATED_WIDGET',
  MARKETING_CAMPAIGN_ROI: 'MARKETING_CAMPAIGN_ROI_WIDGET',
  MARKETING_CHANNEL_PERFORMANCE: 'MARKETING_CHANNEL_PERFORMANCE_WIDGET',
  MARKETING_CONVERSION_FUNNEL: 'MARKETING_CONVERSION_FUNNEL_WIDGET',

  SUPPORT_TICKET_COUNT: 'SUPPORT_TICKET_COUNT_WIDGET',
  SUPPORT_RESOLUTION_TIME: 'SUPPORT_RESOLUTION_TIME_WIDGET',
  SUPPORT_SATISFACTION_SCORE: 'SUPPORT_SATISFACTION_SCORE_WIDGET',
  SUPPORT_TICKET_BY_PRIORITY: 'SUPPORT_TICKET_BY_PRIORITY_WIDGET',

  PRODUCT_ACTIVE_USERS: 'PRODUCT_ACTIVE_USERS_WIDGET',
  PRODUCT_FEATURE_ADOPTION: 'PRODUCT_FEATURE_ADOPTION_WIDGET',
  PRODUCT_USAGE_HEATMAP: 'PRODUCT_USAGE_HEATMAP_WIDGET',
  PRODUCT_USER_ENGAGEMENT: 'PRODUCT_USER_ENGAGEMENT_WIDGET',

  OPERATIONS_EFFICIENCY_GAUGE: 'OPERATIONS_EFFICIENCY_GAUGE_WIDGET',
  OPERATIONS_COST_BREAKDOWN: 'OPERATIONS_COST_BREAKDOWN_WIDGET',
  OPERATIONS_PROCESS_TIME: 'OPERATIONS_PROCESS_TIME_WIDGET',
  OPERATIONS_ERROR_RATE: 'OPERATIONS_ERROR_RATE_WIDGET',

  FINANCE_CASH_FLOW: 'FINANCE_CASH_FLOW_WIDGET',
  FINANCE_EXPENSES_PIE: 'FINANCE_EXPENSES_PIE_WIDGET',
  FINANCE_PROFIT_MARGIN: 'FINANCE_PROFIT_MARGIN_WIDGET',
  FINANCE_BUDGET_VARIANCE: 'FINANCE_BUDGET_VARIANCE_WIDGET',

  EXECUTIVE_KEY_METRICS: 'EXECUTIVE_KEY_METRICS_WIDGET',
  EXECUTIVE_COMPANY_HEALTH: 'EXECUTIVE_COMPANY_HEALTH_WIDGET',
  EXECUTIVE_QUARTERLY_REVIEW: 'EXECUTIVE_QUARTERLY_REVIEW_WIDGET',
  EXECUTIVE_STRATEGIC_GOALS: 'EXECUTIVE_STRATEGIC_GOALS_WIDGET',
};
