name: Nx Affected CI
inputs:
  parallel:
    required: false
    default: '3'
  tag:
    required: false
  tasks:
    required: true
  configuration:
    required: false
    default: 'ci'
  args:
    required: false
runs:
  using: "composite"
  steps:
    - name: Get last successful commit
      uses: nrwl/nx-set-shas@v4
    - name: Run affected command
      shell: bash
      env:
        GITHUB_DATA: ${{ github.event.pull_request.title || github.event.head_commit.message || github.ref_name }}
        echo "Processing: $GITHUB_DATA"