/*
 * _____                    _
 *|_   _|_      _____ _ __ | |_ _   _
 *  | | \ \ /\ / / _ \ '_ \| __| | | | Auto-generated file
 *  | |  \ V  V /  __/ | | | |_| |_| | Any edits to this will be overridden
 *  |_|   \_/\_/ \___|_| |_|\__|\__, | Generated by: npx nx version:bump twenty-server
 *                              |___/
 */

export const TWENTY_PREVIOUS_VERSIONS = [
  '1.21.0',
  '1.22.0',
  '1.23.0',
  '2.0.0',
  '2.1.0',
  '2.2.0',
  '2.3.0',
  '2.4.0',
  '2.5.0',
] as const;
