export enum CHART_CONFIGURATION_SETTING_IDS {
  SOURCE = 'SOURCE',
  DATA_LABELS = 'DATA_LABELS',
  COLORS = 'COLORS',
  FILTER = 'FILTER',
  GROUP_BY = 'GROUP_BY',
  SORT_BY_X = 'SORT_BY_X',
  SORT_BY_GROUP_BY_FIELD = 'SORT_BY_GROUP_BY_FIELD',
  SORT_BY = 'SORT_BY',
  DATA_ON_DISPLAY_X = 'DATA_ON_DISPLAY_X',
  DATA_ON_DISPLAY_Y = 'DATA_ON_DISPLAY_Y',
  DATA_ON_DISPLAY_PIE_CHART = 'DATA_ON_DISPLAY_PIE_CHART',
  DATA_ON_DISPLAY_AGGREGATE = 'DATA_ON_DISPLAY_AGGREGATE',
  EACH_SLICE_REPRESENTS = 'EACH_SLICE_REPRESENTS',
  AXIS_NAME = 'AXIS_NAME',
  STACKED_BARS = 'STACKED_BARS',
  OMIT_NULL_VALUES = 'OMIT_NULL_VALUES',
  MIN_RANGE = 'MIN_RANGE',
  MAX_RANGE = 'MAX_RANGE',
  DATE_GRANULARITY_X = 'DATE_GRANULARITY_X',
  DATE_GRANULARITY_Y = 'DATE_GRANULARITY_Y',
  DATE_GRANULARITY = 'DATE_GRANULARITY',
}

export const CHART_CONFIGURATION_SETTING_TO_CONFIG_KEY_MAP = {
  [CHART_CONFIGURATION_SETTING_IDS.DATA_LABELS]: 'displayDataLabel',
  [CHART_CONFIGURATION_SETTING_IDS.STACKED_BARS]: 'groupMode',
  [CHART_CONFIGURATION_SETTING_IDS.OMIT_NULL_VALUES]: 'omitNullValues',
  [CHART_CONFIGURATION_SETTING_IDS.MIN_RANGE]: 'rangeMin',
  [CHART_CONFIGURATION_SETTING_IDS.MAX_RANGE]: 'rangeMax',
  [CHART_CONFIGURATION_SETTING_IDS.DATE_GRANULARITY_X]:
    'primaryAxisDateGranularity',
  [CHART_CONFIGURATION_SETTING_IDS.DATE_GRANULARITY_Y]:
    'secondaryAxisGroupByDateGranularity',
  [CHART_CONFIGURATION_SETTING_IDS.DATE_GRANULARITY]: 'dateGranularity',
} as const;
