export enum CHART_CONFIGURATION_SETTING_IDS {
  SOURCE = 'SOURCE',
  DATA_LABELS = 'DATA_LABELS',
  COLORS = 'COLORS',
  FILTER = 'FILTER',
  GROUP_BY = 'GROUP_BY',
  SORT_BY_X = 'SORT_BY_X',
  SORT_BY_GROUP_BY_FIELD = 'SORT_BY_GROUP_BY_FIELD',
  SORT_BY = 'SORT_BY',
  DATA_ON_DISPLAY_X = 'DATA_ON_DISPLAY_X',
  DATA_ON_DISPLAY_Y = 'DATA_ON_DISPLAY_Y',
  DATA_ON_DISPLAY_PIE_CHART = 'DATA_ON_DISPLAY_PIE_CHART',
  EACH_SLICE_REPRESENTS = 'EACH_SLICE_REPRESENTS',
  AXIS_NAME = 'AXIS_NAME',
}

export const CHART_CONFIGURATION_SETTING_TO_CONFIG_KEY_MAP = {
  [CHART_CONFIGURATION_SETTING_IDS.DATA_LABELS]: 'displayDataLabel',
} as const;
