import { OrderStatus, SINVOICE_STATUS } from 'src/mkt-core/order/constants';

type MktOrderDataSeed = {
  id: string;
  name: string;
  position: number;
  orderCode: string;
  status: OrderStatus;
  subtotal: number;
  tax: number;
  discount: number;
  totalAmount: number;
  currency: string;
  note: string;
  requireContract: boolean;
  sInvoiceStatus: SINVOICE_STATUS;

  createdBySource: string;
  createdByWorkspaceMemberId: string | null;
  createdByName: string;
};

// prettier-ignore
export const MKT_ORDER_DATA_SEED_COLUMNS: (keyof MktOrderDataSeed)[] = [
  'id',
  'name',
  'position',
  'orderCode',
  'status',
  'subtotal',
  'tax',
  'discount',
  'totalAmount',
  'currency',
  'note',
  'requireContract',
  'sInvoiceStatus',
  'createdBySource',
  'createdByWorkspaceMemberId',
  'createdByName',
];

//prettier-ignore
export const MKT_ORDER_DATA_SEEDS_IDS = {
  ID_1: '774f7b42-e0e6-45b7-9804-ea6b89c0bf8b',
  ID_2: '09f33908-d459-44c3-999e-97f42faf6d30',
  ID_3: '0200e865-6bb2-4645-904c-1ee9fc021c1e',
  ID_4: 'd4a05376-ec12-4f11-92d9-cd5722d70c0b',
  ID_5: '8a361cb9-f40a-4b03-8e02-fdd6e13e8f29',
  ID_6: 'd7cfdf7f-97c8-47ee-a2f9-5eaa8d3af929',
  ID_7: '642c3b7b-6fff-4fbb-a096-7f5432260ed8',
  ID_8: '52dd35b6-2b2a-42e1-be7c-589295a83868',
  ID_9: '28e054f6-4ce2-48aa-93cc-89519a3cf267',
  ID_10: '1899837e-f89f-44ee-8aea-b9a4647cdae7',
  ID_11: '7359947a-4a39-4b45-897f-6fa031b8eab6',
  ID_12: '611d615e-6c3b-4652-9087-e50043ddf260',
  ID_13: 'b9433b83-0e42-4c58-a380-dfd0a69905d7'
};

// prettier-ignore
export const MKT_ORDER_DATA_SEEDS: MktOrderDataSeed[] = [
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_1,
    name: 'Đơn hàng MKT Care Package - Gói chăm sóc Facebook',
    position: 1,
    orderCode: 'MKT-CARE-2024-001',
    status: OrderStatus.PAID,
    subtotal: 11000000,
    tax: 1100000,
    discount: 0,
    totalAmount: 12100000,
    currency: 'VND',
    note: 'Đơn hàng gói MKT Care Basic 1 năm và 2 năm cho khách hàng doanh nghiệp',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'John Doe',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_2,
    name: 'Đơn hàng MKT Viral Package - Gói viral video',
    position: 2,
    orderCode: 'MKT-VIRAL-2024-002',
    status: OrderStatus.PAID,
    subtotal: 16000000,
    tax: 1600000,
    discount: 500000,
    totalAmount: 17100000,
    currency: 'VND',
    note: 'Đơn hàng gói MKT Viral Basic 1 năm (2 license) và vĩnh viễn cho agency marketing',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Jane Smith',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_3,
    name: 'Đơn hàng MKT UID Package - Gói phân tích data',
    position: 3,
    orderCode: 'MKT-UID-2024-003',
    status: OrderStatus.ON_HOLD,
    subtotal: 6000000,
    tax: 600000,
    discount: 0,
    totalAmount: 6600000,
    currency: 'VND',
    note: 'Đơn hàng 3 license MKT UID Basic 1 năm cho team phân tích dữ liệu',
    requireContract: false,
    sInvoiceStatus: SINVOICE_STATUS.PENDING,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Mike Johnson',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_4,
    name: 'Đơn hàng MKT Insta Package - Gói Instagram marketing',
    position: 4,
    orderCode: 'MKT-INSTA-2024-004',
    status: OrderStatus.PAID,
    subtotal: 15000000,
    tax: 1500000,
    discount: 0,
    totalAmount: 16500000,
    currency: 'VND',
    note: 'Đơn hàng gói MKT Insta Basic 2 năm và vĩnh viễn cho influencer marketing',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'John Doe',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_5,
    name: 'Đơn hàng MKT Tube Package - Gói quản lý YouTube',
    position: 5,
    orderCode: 'MKT-TUBE-2024-005',
    status: OrderStatus.PAID,
    subtotal: 9000000,
    tax: 900000,
    discount: 0,
    totalAmount: 9900000,
    currency: 'VND',
    note: 'Đơn hàng gói MKT Tube Basic 1 năm (2 license) và vĩnh viễn cho MCN',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Jane Smith',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_6,
    name: 'Đơn hàng MKT Post Package - Gói đăng bài Facebook',
    position: 6,
    orderCode: 'MKT-POST-2024-006',
    status: OrderStatus.FULFILLED,
    subtotal: 3000000,
    tax: 300000,
    discount: 0,
    totalAmount: 3300000,
    currency: 'VND',
    note: 'Đơn hàng MKT Post Basic 1 năm cho shop bán hàng online',
    requireContract: false,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Mike Johnson',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_7,
    name: 'Đơn hàng MKT Zalo Package - Gói marketing Zalo',
    position: 7,
    orderCode: 'MKT-ZALO-2024-007',
    status: OrderStatus.PAID,
    subtotal: 5000000,
    tax: 500000,
    discount: 0,
    totalAmount: 5500000,
    currency: 'VND',
    note: 'Đơn hàng MKT Zalo Basic 2 năm cho doanh nghiệp B2B',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'John Doe',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_8,
    name: 'Đơn hàng MKT Group Package - Gói quản lý Group Facebook',
    position: 8,
    orderCode: 'MKT-GROUP-2024-008',
    status: OrderStatus.PAID,
    subtotal: 16000000,
    tax: 1600000,
    discount: 1000000,
    totalAmount: 17600000,
    currency: 'VND',
    note: 'Đơn hàng gói MKT Group Basic 1 năm (2 license) và vĩnh viễn cho community manager',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Jane Smith',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_9,
    name: 'Đơn hàng MKT Twitter Package - Gói marketing Twitter/X',
    position: 9,
    orderCode: 'MKT-TWITTER-2024-009',
    status: OrderStatus.FAILED,
    subtotal: 3000000,
    tax: 300000,
    discount: 0,
    totalAmount: 3300000,
    currency: 'VND',
    note: 'Đơn hàng MKT Twitter Basic 1 năm - thanh toán thất bại',
    requireContract: false,
    sInvoiceStatus: SINVOICE_STATUS.FAILED,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Mike Johnson',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_10,
    name: 'Đơn hàng MKT Page Package - Gói quản lý Fanpage',
    position: 10,
    orderCode: 'MKT-PAGE-2024-010',
    status: OrderStatus.PAID,
    subtotal: 5000000,
    tax: 500000,
    discount: 0,
    totalAmount: 5500000,
    currency: 'VND',
    note: 'Đơn hàng MKT Page Basic 2 năm cho agency quản lý fanpage',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'John Doe',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_11,
    name: 'Đơn hàng MKT Maps Package - Gói scan Google Maps',
    position: 11,
    orderCode: 'MKT-MAPS-2024-011',
    status: OrderStatus.PAID,
    subtotal: 9000000,
    tax: 900000,
    discount: 0,
    totalAmount: 9900000,
    currency: 'VND',
    note: 'Đơn hàng 3 license MKT Maps Basic 1 năm cho team lead generation',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Jane Smith',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_12,
    name: 'Đơn hàng MKT Maps Forever - Gói vĩnh viễn Google Maps',
    position: 12,
    orderCode: 'MKT-MAPS-FOREVER-2024-012',
    status: OrderStatus.PAID,
    subtotal: 10000000,
    tax: 1000000,
    discount: 0,
    totalAmount: 11000000,
    currency: 'VND',
    note: 'Đơn hàng MKT Maps Basic vĩnh viễn cho doanh nghiệp lớn',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Mike Johnson',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_13,
    name: 'Đơn hàng Combo Package - Gói tổng hợp UID + Post',
    position: 13,
    orderCode: 'MKT-COMBO-2024-013',
    status: OrderStatus.CANCELLED,
    subtotal: 8500000,
    tax: 850000,
    discount: 0,
    totalAmount: 9350000,
    currency: 'VND',
    note: 'Đơn hàng combo MKT UID Basic 2 năm + MKT Post Basic 2 năm - đã hủy',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.PENDING,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'John Doe',
  },
];
