type MktOrderDataSeed = {
  id: string;
  name: string;
  position: number;
  orderCode: string;
  status: OrderStatus;
  totalAmount: number;
  currency: string;
  note: string;
  requireContract: boolean;
  createdBySource: string;
  createdByWorkspaceMemberId: string | null;
  createdByName: string;
};

export enum OrderStatus {
    PENDING = 'pending',
    PAID = 'paid',
    FAILED = 'failed',
    CANCELLED = 'cancelled',
    FULFILLED = 'fulfilled',
  }

// prettier-ignore
export const MKT_ORDER_DATA_SEED_COLUMNS: (keyof MktOrderDataSeed)[] = [
  'id',
  'name',
  'position',
  'orderCode',
  'status',
  'totalAmount',
  'currency',
  'note',
  'requireContract',
  'createdBySource',
  'createdByWorkspaceMemberId',
  'createdByName',
];

//prettier-ignore
export const MKT_ORDER_DATA_SEEDS_IDS = {
  ID_1: '774f7b42-e0e6-45b7-9804-ea6b89c0bf8b',
  ID_2: '09f33908-d459-44c3-999e-97f42faf6d30',
  ID_3: '0200e865-6bb2-4645-904c-1ee9fc021c1e',
  ID_4: 'd4a05376-ec12-4f11-92d9-cd5722d70c0b',
  ID_5: '8a361cb9-f40a-4b03-8e02-fdd6e13e8f29',
  ID_6: 'd7cfdf7f-97c8-47ee-a2f9-5eaa8d3af929',
  ID_7: '642c3b7b-6fff-4fbb-a096-7f5432260ed8',
  ID_8: '52dd35b6-2b2a-42e1-be7c-589295a83868',
  ID_9: '28e054f6-4ce2-48aa-93cc-89519a3cf267',
  ID_10: '1899837e-f89f-44ee-8aea-b9a4647cdae7',
  ID_11: '7359947a-4a39-4b45-897f-6fa031b8eab6',
  ID_12: '611d615e-6c3b-4652-9087-e50043ddf260',
  ID_13: 'b9433b83-0e42-4c58-a380-dfd0a69905d7'
};

// prettier-ignore
export const MKT_ORDER_DATA_SEEDS: MktOrderDataSeed[] = [
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_1,
    name: 'Enterprise Software License Renewal',
    position: 1,
    orderCode: 'ENT-2024-001',
    status: OrderStatus.PENDING,
    totalAmount: 25000,
    currency: 'USD',
    note: 'Annual license renewal for enterprise software suite',
    requireContract: true,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'John Doe',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_2,
    name: 'Cloud Infrastructure Setup',
    position: 2,
    orderCode: 'CLOUD-2024-002',
    status: OrderStatus.PENDING,
    totalAmount: 15000,
    currency: 'USD',
    note: 'Initial cloud infrastructure setup and configuration',
    requireContract: true,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Jane Smith',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_3,
    name: 'Marketing Automation Platform',
    position: 3,
    orderCode: 'MKT-2024-003',
    status: OrderStatus.PENDING,
    totalAmount: 8500,
    currency: 'USD',
    note: 'Marketing automation platform subscription',
    requireContract: false,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Mike Johnson',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_4,
    name: 'Customer Support System',
    position: 4,
    orderCode: 'SUPPORT-2024-004',
    status: OrderStatus.PENDING,
    totalAmount: 12000,
    currency: 'USD',
    note: 'Customer support ticketing system implementation',
    requireContract: true,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'John Doe',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_5,
    name: 'Data Analytics Dashboard',
    position: 5,
    orderCode: 'ANALYTICS-2024-005',
    status: OrderStatus.PENDING,
    totalAmount: 7500,
    currency: 'USD',
    note: 'Custom data analytics dashboard development',
    requireContract: true,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Jane Smith',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_6,
    name: 'E-commerce Platform Integration',
    position: 6,
    orderCode: 'ECOMM-2024-006',
    status: OrderStatus.PENDING,
    totalAmount: 18000,
    currency: 'USD',
    note: 'E-commerce platform integration and customization',
    requireContract: true,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Mike Johnson',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_7,
    name: 'Mobile App Development',
    position: 7,
    orderCode: 'MOBILE-2024-007',
    status: OrderStatus.PENDING,
    totalAmount: 35000,
    currency: 'USD',
    note: 'Cross-platform mobile application development',
    requireContract: true,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'John Doe',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_8,
    name: 'Security Audit Services',
    position: 8,
    orderCode: 'SECURITY-2024-008',
    status: OrderStatus.PENDING,
    totalAmount: 9500,
    currency: 'USD',
    note: 'Comprehensive security audit and penetration testing',
    requireContract: true,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Jane Smith',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_9,
    name: 'Content Management System',
    position: 9,
    orderCode: 'CMS-2024-009',
    status: OrderStatus.PENDING,
    totalAmount: 6500,
    currency: 'USD',
    note: 'Content management system setup and training',
    requireContract: false,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Mike Johnson',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_10,
    name: 'API Gateway Implementation',
    position: 10,
    orderCode: 'API-2024-010',
    status: OrderStatus.PENDING,
    totalAmount: 11000,
    currency: 'USD',
    note: 'API gateway setup and microservices integration',
    requireContract: true,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'John Doe',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_11,
    name: 'Business Intelligence Tools',
    position: 11,
    orderCode: 'BI-2024-011',
    status: OrderStatus.PENDING,
    totalAmount: 22000,
    currency: 'USD',
    note: 'Business intelligence and reporting tools license',
    requireContract: true,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Jane Smith',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_12,
    name: 'DevOps Pipeline Setup',
    position: 12,
    orderCode: 'DEVOPS-2024-012',
    status: OrderStatus.PENDING,
    totalAmount: 13500,
    currency: 'USD',
    note: 'CI/CD pipeline and DevOps infrastructure setup',
    requireContract: true,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Mike Johnson',
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_13,
    name: 'Training and Certification',
    position: 13,
    orderCode: 'TRAINING-2024-013',
    status: OrderStatus.PENDING,
    totalAmount: 4800,
    currency: 'USD',
    note: 'Team training and certification program',
    requireContract: false,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'John Doe',
  },
];
