import {
  MKT_CUSTOMER_LIFECYCLE_STAGE,
  MKT_CUSTOMER_STATUS,
  MKT_CUSTOMER_TAGS,
  MKT_CUSTOMER_TIER,
  MKT_CUSTOMER_TYPE,
} from 'src/mkt-core/customer/constants/mkt-customer.constant';

// prettier-ignore
export type MKT_CUSTOMER_DATA_SEED = {
  id: string;
  name: string;
  type: MKT_CUSTOMER_TYPE;
  email: string;
  phone: string;
  taxCode: string;
  companyName: string;
  address: string;
  status: MKT_CUSTOMER_STATUS;
  tier: MKT_CUSTOMER_TIER;
  lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE;
  // salesId: string | null;
  // supportId: string | null;
  // affiliateId: string | null;
  registrationDate: string;
  totalOrderValue: number;
  churnRiskScore: number;
  engagementScore: number;
  tags: MKT_CUSTOMER_TAGS[];
};

// prettier-ignore
export const MKT_CUSTOMER_DATA_SEED_COLUMNS: (keyof MKT_CUSTOMER_DATA_SEED)[] = [
  'id',
  'name',
  'type',
  'email',
  'phone',
  'taxCode',
  'companyName',
  'address',
  'status',
  'tier',
  'lifecycleStage',
  'registrationDate',
  'totalOrderValue',
  'churnRiskScore',
  'engagementScore',
  'tags',
];
// prettier-ignore
export const MKT_CUSTOMER_DATA_SEEDS_IDS = {
  ID_1: 'ac4bd356-733b-4c95-ade5-73f0deb64447',
  ID_2: 'ff34a9a6-586e-4d28-96f6-19fdf4cc732a',
  ID_3: 'a5699a8d-76fb-48fe-927e-04ce3a8b990c',
  ID_4: '243e6b3e-14ea-437c-9be3-65a592bbbb7a',
  ID_5: '8dfe2a53-cafc-4c13-9c41-fce995cc4e8e',
  ID_6: '22f1c007-ce0c-4bcf-b7aa-b3ce418db5c8',
  ID_7: 'e2930ee6-4cde-4bd3-b899-a2eb4ebf4a9c',
  ID_8: 'c08e6466-a39d-4a10-8e8e-cbf44592a72d',
  ID_9: 'd97d0f6e-9609-48cf-8036-813b3e3a9a62',
  ID_10: 'e010f008-93aa-43cc-bd2a-8bb44d08b2ca',
  ID_11: '5b26d71b-6f3a-4a0f-a4b8-7936248fd403',
  ID_12: 'd958f385-0714-443c-84a9-50072f571874',
  ID_13: 'd52e30df-7e81-49bd-a7ee-199c35ba0ef8',
  ID_14: '081f1744-cd6d-49e2-923b-d7182031e860',
  ID_15: 'b6b2aafa-33f3-4d47-be4b-0cc2936db557',
};

// prettier-ignore
export const MKT_CUSTOMER_DATA_SEEDS: MKT_CUSTOMER_DATA_SEED[] = [
  {
    id: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_1,
    name: 'Alice Johnson',
    type: MKT_CUSTOMER_TYPE.INDIVIDUAL,
    email: 'alice.johnson@example.com',
    phone: '1234567890',
    taxCode: '1234567890',
    companyName: 'Alice Johnson Inc.',
    address: 'address other 1',
    status: MKT_CUSTOMER_STATUS.ACTIVE,
    tier: MKT_CUSTOMER_TIER.INDIVIDUAL,
    lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE.PROSPECTIVE,
    registrationDate: '2021-01-01',
    totalOrderValue: 1000,
    churnRiskScore: 0.5,
    engagementScore: 0.5,
    tags: [MKT_CUSTOMER_TAGS.VIP],
  },
  {
    id: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_2,
    name: 'Michael Smith',
    type: MKT_CUSTOMER_TYPE.INDIVIDUAL,
    email: 'michael.smith@example.com',
    phone: '0987654321',
    taxCode: '9876543210',
    companyName: 'Michael Smith Inc.',
    address: 'address other 2',
    status: MKT_CUSTOMER_STATUS.ACTIVE,
    tier: MKT_CUSTOMER_TIER.SMALL,
    lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE.PROSPECTIVE,
    registrationDate: '2021-01-01',
    totalOrderValue: 1000,
    churnRiskScore: 0.5,
    engagementScore: 0.5,
    tags: [MKT_CUSTOMER_TAGS.HIGH_VALUE],
  },
  {
    id: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_3,
    name: 'Sophia Brown',
    type: MKT_CUSTOMER_TYPE.INDIVIDUAL,
    email: 'sophia.brown@example.com',
    phone: '1234567890',
    taxCode: '1234567890',
    companyName: 'Sophia Brown Inc.',
    address: 'address other 3',
    status: MKT_CUSTOMER_STATUS.ACTIVE,
    tier: MKT_CUSTOMER_TIER.MEDIUM,
    lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE.TRIAL,
    registrationDate: '2021-01-01',
    totalOrderValue: 1000,
    churnRiskScore: 0.5,
    engagementScore: 0.5,
    tags: [MKT_CUSTOMER_TAGS.POTENTIAL_CHURN],
  },
  {
    id: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_4,
    name: 'Daniel Williams',
    type: MKT_CUSTOMER_TYPE.INDIVIDUAL,
    email: 'daniel.williams@example.com',
    phone: '1234567890',
    taxCode: '1234567890',
    companyName: 'Daniel Williams Inc.',
    address: 'address other 4',
    status: MKT_CUSTOMER_STATUS.ACTIVE,
    tier: MKT_CUSTOMER_TIER.ENTERPRISE,
    lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE.LOYAL,
    registrationDate: '2021-01-01',
    totalOrderValue: 1000,
    churnRiskScore: 0.5,
    engagementScore: 0.5,
    tags: [MKT_CUSTOMER_TAGS.SUPPORT_INTENSIVE],
  },
  {
    id: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_5,
    name: 'Emily Davis',
    type: MKT_CUSTOMER_TYPE.INDIVIDUAL,
    email: 'emily.davis@example.com',
    phone: '1234567890',
    taxCode: '1234567890',
    companyName: 'Emily Davis Inc.',
    address: 'address other 5',
    status: MKT_CUSTOMER_STATUS.ACTIVE,
    tier: MKT_CUSTOMER_TIER.OTHER,
    lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE.LOYAL,
    registrationDate: '2021-01-01',
    totalOrderValue: 1000,
    churnRiskScore: 0.5,
    engagementScore: 0.5,
    tags: [MKT_CUSTOMER_TAGS.REFERRAL_SOURCE],
  },
  {
    id: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_6,
    name: 'Christopher Miller',
    type: MKT_CUSTOMER_TYPE.INDIVIDUAL,
    email: 'christopher.miller@example.com',
    phone: '1234567890',
    taxCode: '1234567890',
    companyName: 'Christopher Miller Inc.',
    address: 'address other 6',
    status: MKT_CUSTOMER_STATUS.ACTIVE,
    tier: MKT_CUSTOMER_TIER.OTHER,
    lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE.LOYAL,
    registrationDate: '2021-01-01',
    totalOrderValue: 1000,
    churnRiskScore: 0.5,
    engagementScore: 0.5,
    tags: [MKT_CUSTOMER_TAGS.QUICK_PAYER],
  },
  {
    id: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_7,
    name: 'Olivia Wilson',
    type: MKT_CUSTOMER_TYPE.INDIVIDUAL,
    email: 'olivia.wilson@example.com',
    phone: '1234567890',
    taxCode: '1234567890',
    companyName: 'Olivia Wilson Inc.',
    address: 'address other 7',
    status: MKT_CUSTOMER_STATUS.ACTIVE,
    tier: MKT_CUSTOMER_TIER.OTHER,
    lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE.LOYAL,
    registrationDate: '2021-01-01',
    totalOrderValue: 1000,
    churnRiskScore: 0.5,
    engagementScore: 0.5,
    tags: [MKT_CUSTOMER_TAGS.NEGOTIATOR],
  },
  {
    id: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_8,
    name: 'Matthew Taylor',
    type: MKT_CUSTOMER_TYPE.INDIVIDUAL,
    email: 'matthew.taylor@example.com',
    phone: '1234567890',
    taxCode: '1234567890',
    companyName: 'Matthew Taylor Inc.',
    address: 'address other 8',
    status: MKT_CUSTOMER_STATUS.ACTIVE,
    tier: MKT_CUSTOMER_TIER.OTHER,
    lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE.LOYAL,
    registrationDate: '2021-01-01',
    totalOrderValue: 1000,
    churnRiskScore: 0.5,
    engagementScore: 0.5,
    tags: [MKT_CUSTOMER_TAGS.ENTERPRISE_PROSPECT],
  },
  {
    id: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_9,
    name: 'Isabella Anderson',
    type: MKT_CUSTOMER_TYPE.INDIVIDUAL,
    email: 'isabella.anderson@example.com',
    phone: '1234567890',
    taxCode: '1234567890',
    companyName: 'Isabella Anderson Inc.',
    address: 'address other 9',
    status: MKT_CUSTOMER_STATUS.ACTIVE,
    tier: MKT_CUSTOMER_TIER.OTHER,
    lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE.LOYAL,
    registrationDate: '2021-01-01',
    totalOrderValue: 1000,
    churnRiskScore: 0.5,
    engagementScore: 0.5,
    tags: [MKT_CUSTOMER_TAGS.POTENTIAL_CHURN],
  },
  {
    id: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_10,
    name: 'James Thomas',
    type: MKT_CUSTOMER_TYPE.INDIVIDUAL,
    email: 'james.thomas@example.com',
    phone: '1234567890',
    taxCode: '1234567890',
    companyName: 'James Thomas Inc.',
    address: 'address other 10',
    status: MKT_CUSTOMER_STATUS.ACTIVE,
    tier: MKT_CUSTOMER_TIER.OTHER,
    lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE.LOYAL,
    registrationDate: '2021-01-01',
    totalOrderValue: 1000,
    churnRiskScore: 0.5,
    engagementScore: 0.5,
    tags: [MKT_CUSTOMER_TAGS.QUICK_PAYER],
  },
  {
    id: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_11,
    name: 'Charlotte Moore',
    type: MKT_CUSTOMER_TYPE.INDIVIDUAL,
    email: 'charlotte.moore@example.com',
    phone: '1234567890',
    taxCode: '1234567890',
    companyName: 'Charlotte Moore Inc.',
    address: 'address other 11',
    status: MKT_CUSTOMER_STATUS.ACTIVE,
    tier: MKT_CUSTOMER_TIER.OTHER,
    lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE.LOYAL,

    registrationDate: '2021-01-01',
    totalOrderValue: 1000,
    churnRiskScore: 0.5,
    engagementScore: 0.5,
    tags: [MKT_CUSTOMER_TAGS.REFERRAL_SOURCE],
  },
  {
    id: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_12,
    name: 'Benjamin Jackson',
    type: MKT_CUSTOMER_TYPE.INDIVIDUAL,
    email: 'benjamin.jackson@example.com',
    phone: '1234567890',
    taxCode: '1234567890',
    companyName: 'Benjamin Jackson Inc.',
    address: 'address other 12',
    status: MKT_CUSTOMER_STATUS.ACTIVE,
    tier: MKT_CUSTOMER_TIER.OTHER,
    lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE.LOYAL,
    registrationDate: '2021-01-01',
    totalOrderValue: 1000,
    churnRiskScore: 0.5,
    engagementScore: 0.5,
    tags: [MKT_CUSTOMER_TAGS.NEGOTIATOR],
  },
  {
    id: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_13,
    name: 'Amelia White',
    type: MKT_CUSTOMER_TYPE.INDIVIDUAL,
    email: 'amelia.white@example.com',
    phone: '1234567890',
    taxCode: '1234567890',
    companyName: 'Amelia White Inc.',
    address: 'address other 13',
    status: MKT_CUSTOMER_STATUS.ACTIVE,
    tier: MKT_CUSTOMER_TIER.OTHER,
    lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE.LOYAL,

    registrationDate: '2021-01-01',
    totalOrderValue: 1000,
    churnRiskScore: 0.5,
    engagementScore: 0.5,
    tags: [MKT_CUSTOMER_TAGS.ENTERPRISE_PROSPECT],
  },
  {
    id: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_14,
    name: 'Ethan Harris',
    type: MKT_CUSTOMER_TYPE.INDIVIDUAL,
    email: 'ethan.harris@example.com',
    phone: '1234567890',
    taxCode: '1234567890',
    companyName: 'Ethan Harris Inc.',
    address: 'address other 14',
    status: MKT_CUSTOMER_STATUS.ACTIVE,
    tier: MKT_CUSTOMER_TIER.OTHER,
    lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE.LOYAL,

    registrationDate: '2021-01-01',
    totalOrderValue: 1000,
    churnRiskScore: 0.5,
    engagementScore: 0.5,
    tags: [MKT_CUSTOMER_TAGS.POTENTIAL_CHURN],
  },
  {
    id: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_15,
    name: 'Mia Martin',
    type: MKT_CUSTOMER_TYPE.INDIVIDUAL,
    email: 'mia.martin@example.com',
    phone: '1234567890',
    taxCode: '1234567890',
    companyName: 'Mia Martin Inc.',
    address: 'address other 15',
    status: MKT_CUSTOMER_STATUS.ACTIVE,
    tier: MKT_CUSTOMER_TIER.OTHER,
    lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE.LOYAL,

    registrationDate: '2021-01-01',
    totalOrderValue: 1000,
    churnRiskScore: 0.5,
    engagementScore: 0.5,
    tags: [MKT_CUSTOMER_TAGS.POTENTIAL_CHURN],
  },
];
