export enum MktDepartmentCode {
  SALES = 'SALES',
  SUPPORT = 'SUPPORT',
  ACCOUNTING = 'ACCOUNTING',
  HR = 'HR',
  TECH = 'TECH',
  ADMIN = 'ADMIN',
  // Level 2 departments
  SALES_DOMESTIC = 'SALES_DOMESTIC',
  SALES_EXPORT = 'SALES_EXPORT',
  TECH_FRONTEND = 'TECH_FRONTEND',
  TECH_BACKEND = 'TECH_BACKEND',
  // Level 3 departments
  SALES_NORTH = 'SALES_NORTH',
  SALES_SOUTH = 'SALES_SOUTH',
  SALES_EU = 'SALES_EU',
  SALES_ASIA = 'SALES_ASIA',
  TECH_REACT = 'TECH_REACT',
  TECH_MOBILE = 'TECH_MOBILE',
  TECH_API = 'TECH_API',
  TECH_DATABASE = 'TECH_DATABASE',
  // Level 4 departments
  SALES_HANOI = 'SALES_HANOI',
  SALES_HCMC = 'SALES_HCMC',
  SALES_GERMANY = 'SALES_GERMANY',
  SALES_JAPAN = 'SALES_JAPAN',
  TECH_WEB = 'TECH_WEB',
  TECH_COMPONENTS = 'TECH_COMPONENTS',
  TECH_IOS = 'TECH_IOS',
  TECH_ANDROID = 'TECH_ANDROID',
  // Level 5 departments
  SALES_HANOI_RETAIL = 'SALES_HANOI_RETAIL',
  SALES_HANOI_B2B = 'SALES_HANOI_B2B',
  SALES_HCMC_RETAIL = 'SALES_HCMC_RETAIL',
  SALES_HCMC_B2B = 'SALES_HCMC_B2B',
  TECH_UI_LIBRARY = 'TECH_UI_LIBRARY',
  TECH_DESIGN_SYSTEM = 'TECH_DESIGN_SYSTEM',
  // Level 6 departments
  SALES_HANOI_RETAIL_ONLINE = 'SALES_HANOI_RETAIL_ONLINE',
  SALES_HANOI_RETAIL_OFFLINE = 'SALES_HANOI_RETAIL_OFFLINE',
  TECH_COMPONENT_LIB = 'TECH_COMPONENT_LIB',
  TECH_THEME_SYSTEM = 'TECH_THEME_SYSTEM',
  // Level 7 departments
  SALES_HANOI_ECOMMERCE = 'SALES_HANOI_ECOMMERCE',
  SALES_HANOI_SOCIAL = 'SALES_HANOI_SOCIAL',
}

type MktDepartmentDataSeed = {
  id: string;
  departmentCode: MktDepartmentCode;
  departmentName: string;
  departmentNameEn?: string;
  description?: string;
  budgetCode?: string;
  costCenter?: string;
  requiresKpiTracking?: boolean;
  allowsCrossDepartmentAccess?: boolean;
  defaultKpiCategory?: string;
  displayOrder: number;
  colorCode?: string;
  iconName?: string;
  isActive?: boolean;
  position: number;
  createdBySource: string;
  createdByWorkspaceMemberId: string | null;
  createdByName: string;
};

export const MKT_DEPARTMENT_DATA_SEED_COLUMNS: (keyof MktDepartmentDataSeed)[] =
  [
    'id',
    'departmentCode',
    'departmentName',
    'departmentNameEn',
    'description',
    'budgetCode',
    'costCenter',
    'requiresKpiTracking',
    'allowsCrossDepartmentAccess',
    'defaultKpiCategory',
    'displayOrder',
    'colorCode',
    'iconName',
    'isActive',
    'position',
    'createdBySource',
    'createdByWorkspaceMemberId',
    'createdByName',
  ];

export const MKT_DEPARTMENT_DATA_SEEDS_IDS = {
  SALES: '1d2e3f4a-5b6c-7d8e-9f0a-1b2c3d4e5f6a',
  SUPPORT: '2e3f4a5b-6c7d-8e9f-0a1b-2c3d4e5f6a7b',
  ACCOUNTING: '3f4a5b6c-7d8e-9f0a-1b2c-3d4e5f6a7b8c',
  HR: '4a5b6c7d-8e9f-0a1b-2c3d-4e5f6a7b8c9d',
  TECH: '5b6c7d8e-9f0a-1b2c-3d4e-5f6a7b8c9d0e',
  ADMIN: '6c7d8e9f-0a1b-2c3d-4e5f-6a7b8c9d0e1f',
  // Level 2 departments
  SALES_DOMESTIC: '7d8e9f0a-1b2c-3d4e-5f6a-7b8c9d0e1f2a',
  SALES_EXPORT: '8e9f0a1b-2c3d-4e5f-6a7b-8c9d0e1f2a3b',
  TECH_FRONTEND: '9f0a1b2c-3d4e-5f6a-7b8c-9d0e1f2a3b4c',
  TECH_BACKEND: 'a0b1c2d3-4e5f-6a7b-8c9d-0e1f2a3b4c5d',
  // Level 3 departments
  SALES_NORTH: 'b1c2d3e4-5f6a-7b8c-9d0e-1f2a3b4c5d6e',
  SALES_SOUTH: 'c2d3e4f5-6a7b-8c9d-0e1f-2a3b4c5d6e7f',
  SALES_EU: 'd3e4f5a6-7b8c-9d0e-1f2a-3b4c5d6e7f8a',
  SALES_ASIA: 'e4f5a6b7-8c9d-0e1f-2a3b-4c5d6e7f8a9b',
  TECH_REACT: 'f5a6b7c8-9d0e-1f2a-3b4c-5d6e7f8a9b0c',
  TECH_MOBILE: 'a6b7c8d9-0e1f-2a3b-4c5d-6e7f8a9b0c1d',
  TECH_API: 'b7c8d9e0-1f2a-3b4c-5d6e-7f8a9b0c1d2e',
  TECH_DATABASE: 'c8d9e0f1-2a3b-4c5d-6e7f-8a9b0c1d2e3f',
  // Level 4 departments
  SALES_HANOI: 'd9e0f1a2-3b4c-5d6e-7f8a-9b0c1d2e3f4a',
  SALES_HCMC: 'e0f1a2b3-4c5d-6e7f-8a9b-0c1d2e3f4a5b',
  SALES_GERMANY: 'f1a2b3c4-5d6e-7f8a-9b0c-1d2e3f4a5b6c',
  SALES_JAPAN: 'a2b3c4d5-6e7f-8a9b-0c1d-2e3f4a5b6c7d',
  TECH_WEB: 'b3c4d5e6-7f8a-9b0c-1d2e-3f4a5b6c7d8e',
  TECH_COMPONENTS: 'c4d5e6f7-8a9b-0c1d-2e3f-4a5b6c7d8e9f',
  TECH_IOS: 'd5e6f7a8-9b0c-1d2e-3f4a-5b6c7d8e9f0a',
  TECH_ANDROID: 'e6f7a8b9-0c1d-2e3f-4a5b-6c7d8e9f0a1b',
  // Level 5 departments
  SALES_HANOI_RETAIL: 'f7a8b9c0-1d2e-3f4a-5b6c-7d8e9f0a1b2c',
  SALES_HANOI_B2B: 'a8b9c0d1-2e3f-4a5b-6c7d-8e9f0a1b2c3d',
  SALES_HCMC_RETAIL: 'b9c0d1e2-3f4a-5b6c-7d8e-9f0a1b2c3d4e',
  SALES_HCMC_B2B: 'c0d1e2f3-4a5b-6c7d-8e9f-0a1b2c3d4e5f',
  TECH_UI_LIBRARY: 'd1e2f3a4-5b6c-7d8e-9f0a-1b2c3d4e5f6a',
  TECH_DESIGN_SYSTEM: 'e2f3a4b5-6c7d-8e9f-0a1b-2c3d4e5f6a7b',
  // Level 6 departments
  SALES_HANOI_RETAIL_ONLINE: 'f3a4b5c6-7d8e-9f0a-1b2c-3d4e5f6a7b8c',
  SALES_HANOI_RETAIL_OFFLINE: 'a4b5c6d7-8e9f-0a1b-2c3d-4e5f6a7b8c9d',
  TECH_COMPONENT_LIB: 'b5c6d7e8-9f0a-1b2c-3d4e-5f6a7b8c9d0e',
  TECH_THEME_SYSTEM: 'c6d7e8f9-0a1b-2c3d-4e5f-6a7b8c9d0e1f',
  // Level 7 departments
  SALES_HANOI_ECOMMERCE: 'd7e8f9a0-1b2c-3d4e-5f6a-7b8c9d0e1f2a',
  SALES_HANOI_SOCIAL: 'e8f9a0b1-2c3d-4e5f-6a7b-8c9d0e1f2a3b',
};

export const MKT_DEPARTMENT_DATA_SEEDS: MktDepartmentDataSeed[] = [
  // Sales Department
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.SALES,
    departmentCode: MktDepartmentCode.SALES,
    departmentName: 'Phòng Kinh doanh',
    departmentNameEn: 'Sales Department',
    description:
      'Phụ trách bán hàng, tìm kiếm khách hàng và phát triển thị trường',
    budgetCode: 'BUD-SALES-2024',
    costCenter: 'CC-SALES',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: true,
    defaultKpiCategory: 'SALES_PERFORMANCE',
    displayOrder: 1,
    colorCode: '#2196F3', // Blue
    iconName: 'IconTrendingUp',
    isActive: true,
    position: 1,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Support Department
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.SUPPORT,
    departmentCode: MktDepartmentCode.SUPPORT,
    departmentName: 'Phòng Hỗ trợ khách hàng',
    departmentNameEn: 'Customer Support Department',
    description: 'Hỗ trợ khách hàng sử dụng sản phẩm và giải quyết vấn đề',
    budgetCode: 'BUD-SUPPORT-2024',
    costCenter: 'CC-SUPPORT',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'SUPPORT_PERFORMANCE',
    displayOrder: 2,
    colorCode: '#4CAF50', // Green
    iconName: 'IconHeadphones',
    isActive: true,
    position: 2,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Accounting Department
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.ACCOUNTING,
    departmentCode: MktDepartmentCode.ACCOUNTING,
    departmentName: 'Phòng Kế toán',
    departmentNameEn: 'Accounting Department',
    description: 'Quản lý tài chính, kế toán và báo cáo tài chính',
    budgetCode: 'BUD-ACC-2024',
    costCenter: 'CC-ACCOUNTING',
    requiresKpiTracking: false,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'FINANCIAL_PERFORMANCE',
    displayOrder: 3,
    colorCode: '#FF9800', // Orange
    iconName: 'IconCalculator',
    isActive: true,
    position: 3,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // HR Department
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.HR,
    departmentCode: MktDepartmentCode.HR,
    departmentName: 'Phòng Nhân sự',
    departmentNameEn: 'Human Resources Department',
    description: 'Quản lý nhân sự, tuyển dụng và phát triển nguồn nhân lực',
    budgetCode: 'BUD-HR-2024',
    costCenter: 'CC-HR',
    requiresKpiTracking: false,
    allowsCrossDepartmentAccess: true,
    defaultKpiCategory: 'HR_PERFORMANCE',
    displayOrder: 4,
    colorCode: '#9C27B0', // Purple
    iconName: 'IconUsers',
    isActive: true,
    position: 4,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Tech Department
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.TECH,
    departmentCode: MktDepartmentCode.TECH,
    departmentName: 'Phòng Kỹ thuật',
    departmentNameEn: 'Technology Department',
    description: 'Phát triển sản phẩm, bảo trì hệ thống và hỗ trợ kỹ thuật',
    budgetCode: 'BUD-TECH-2024',
    costCenter: 'CC-TECH',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: true,
    defaultKpiCategory: 'TECH_PERFORMANCE',
    displayOrder: 5,
    colorCode: '#607D8B', // Blue Grey
    iconName: 'IconCode',
    isActive: true,
    position: 5,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Admin Department
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.ADMIN,
    departmentCode: MktDepartmentCode.ADMIN,
    departmentName: 'Phòng Hành chính',
    departmentNameEn: 'Administration Department',
    description: 'Quản lý hành chính, pháp chế và các vấn đề tổng hợp',
    budgetCode: 'BUD-ADMIN-2024',
    costCenter: 'CC-ADMIN',
    requiresKpiTracking: false,
    allowsCrossDepartmentAccess: true,
    defaultKpiCategory: 'ADMIN_PERFORMANCE',
    displayOrder: 6,
    colorCode: '#795548', // Brown
    iconName: 'IconBriefcase',
    isActive: true,
    position: 6,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // ================= LEVEL 2 DEPARTMENTS =================

  // Sales Domestic (Level 2 under Sales)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.SALES_DOMESTIC,
    departmentCode: MktDepartmentCode.SALES_DOMESTIC,
    departmentName: 'Phòng Kinh doanh Nội địa',
    departmentNameEn: 'Domestic Sales Department',
    description: 'Phụ trách bán hàng thị trường trong nước',
    budgetCode: 'BUD-SALES-DOM-2024',
    costCenter: 'CC-SALES-DOM',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'SALES_DOMESTIC',
    displayOrder: 11,
    colorCode: '#1976D2',
    iconName: 'IconHome',
    isActive: true,
    position: 11,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Sales Export (Level 2 under Sales)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.SALES_EXPORT,
    departmentCode: MktDepartmentCode.SALES_EXPORT,
    departmentName: 'Phòng Kinh doanh Xuất khẩu',
    departmentNameEn: 'Export Sales Department',
    description: 'Phụ trách bán hàng thị trường xuất khẩu',
    budgetCode: 'BUD-SALES-EXP-2024',
    costCenter: 'CC-SALES-EXP',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'SALES_EXPORT',
    displayOrder: 12,
    colorCode: '#1565C0',
    iconName: 'IconWorld',
    isActive: true,
    position: 12,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Tech Frontend (Level 2 under Tech)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.TECH_FRONTEND,
    departmentCode: MktDepartmentCode.TECH_FRONTEND,
    departmentName: 'Phòng Kỹ thuật Frontend',
    departmentNameEn: 'Frontend Technology Department',
    description: 'Phụ trách phát triển giao diện người dùng',
    budgetCode: 'BUD-TECH-FE-2024',
    costCenter: 'CC-TECH-FE',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'TECH_FRONTEND',
    displayOrder: 13,
    colorCode: '#455A64',
    iconName: 'IconBrowser',
    isActive: true,
    position: 13,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Tech Backend (Level 2 under Tech)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.TECH_BACKEND,
    departmentCode: MktDepartmentCode.TECH_BACKEND,
    departmentName: 'Phòng Kỹ thuật Backend',
    departmentNameEn: 'Backend Technology Department',
    description: 'Phụ trách phát triển hệ thống backend và API',
    budgetCode: 'BUD-TECH-BE-2024',
    costCenter: 'CC-TECH-BE',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'TECH_BACKEND',
    displayOrder: 14,
    colorCode: '#37474F',
    iconName: 'IconServer',
    isActive: true,
    position: 14,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // ================= LEVEL 3 DEPARTMENTS =================

  // Sales North (Level 3 under Sales Domestic)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.SALES_NORTH,
    departmentCode: MktDepartmentCode.SALES_NORTH,
    departmentName: 'Phòng Kinh doanh Miền Bắc',
    departmentNameEn: 'Northern Sales Department',
    description: 'Phụ trách bán hàng khu vực miền Bắc',
    budgetCode: 'BUD-SALES-NORTH-2024',
    costCenter: 'CC-SALES-NORTH',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'SALES_REGIONAL',
    displayOrder: 21,
    colorCode: '#0277BD',
    iconName: 'IconMapPin',
    isActive: true,
    position: 21,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Sales South (Level 3 under Sales Domestic)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.SALES_SOUTH,
    departmentCode: MktDepartmentCode.SALES_SOUTH,
    departmentName: 'Phòng Kinh doanh Miền Nam',
    departmentNameEn: 'Southern Sales Department',
    description: 'Phụ trách bán hàng khu vực miền Nam',
    budgetCode: 'BUD-SALES-SOUTH-2024',
    costCenter: 'CC-SALES-SOUTH',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'SALES_REGIONAL',
    displayOrder: 22,
    colorCode: '#0288D1',
    iconName: 'IconMapPin',
    isActive: true,
    position: 22,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Sales EU (Level 3 under Sales Export)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.SALES_EU,
    departmentCode: MktDepartmentCode.SALES_EU,
    departmentName: 'Phòng Kinh doanh Châu Âu',
    departmentNameEn: 'European Sales Department',
    description: 'Phụ trách bán hàng thị trường châu Âu',
    budgetCode: 'BUD-SALES-EU-2024',
    costCenter: 'CC-SALES-EU',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'SALES_INTERNATIONAL',
    displayOrder: 23,
    colorCode: '#039BE5',
    iconName: 'IconWorld',
    isActive: true,
    position: 23,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Sales Asia (Level 3 under Sales Export)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.SALES_ASIA,
    departmentCode: MktDepartmentCode.SALES_ASIA,
    departmentName: 'Phòng Kinh doanh Châu Á',
    departmentNameEn: 'Asian Sales Department',
    description: 'Phụ trách bán hàng thị trường châu Á',
    budgetCode: 'BUD-SALES-ASIA-2024',
    costCenter: 'CC-SALES-ASIA',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'SALES_INTERNATIONAL',
    displayOrder: 24,
    colorCode: '#03A9F4',
    iconName: 'IconWorld',
    isActive: true,
    position: 24,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Tech React (Level 3 under Tech Frontend)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.TECH_REACT,
    departmentCode: MktDepartmentCode.TECH_REACT,
    departmentName: 'Phòng React Development',
    departmentNameEn: 'React Development Department',
    description: 'Phụ trách phát triển ứng dụng React',
    budgetCode: 'BUD-TECH-REACT-2024',
    costCenter: 'CC-TECH-REACT',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'TECH_FRONTEND',
    displayOrder: 25,
    colorCode: '#263238',
    iconName: 'IconBrandReact',
    isActive: true,
    position: 25,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Tech Mobile (Level 3 under Tech Frontend)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.TECH_MOBILE,
    departmentCode: MktDepartmentCode.TECH_MOBILE,
    departmentName: 'Phòng Mobile Development',
    departmentNameEn: 'Mobile Development Department',
    description: 'Phụ trách phát triển ứng dụng di động',
    budgetCode: 'BUD-TECH-MOBILE-2024',
    costCenter: 'CC-TECH-MOBILE',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'TECH_MOBILE',
    displayOrder: 26,
    colorCode: '#2E3440',
    iconName: 'IconDeviceMobile',
    isActive: true,
    position: 26,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Tech API (Level 3 under Tech Backend)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.TECH_API,
    departmentCode: MktDepartmentCode.TECH_API,
    departmentName: 'Phòng API Development',
    departmentNameEn: 'API Development Department',
    description: 'Phụ trách phát triển API và microservices',
    budgetCode: 'BUD-TECH-API-2024',
    costCenter: 'CC-TECH-API',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'TECH_BACKEND',
    displayOrder: 27,
    colorCode: '#3F4E5F',
    iconName: 'IconApi',
    isActive: true,
    position: 27,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Tech Database (Level 3 under Tech Backend)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.TECH_DATABASE,
    departmentCode: MktDepartmentCode.TECH_DATABASE,
    departmentName: 'Phòng Database Management',
    departmentNameEn: 'Database Management Department',
    description: 'Phụ trách quản lý cơ sở dữ liệu và data warehouse',
    budgetCode: 'BUD-TECH-DB-2024',
    costCenter: 'CC-TECH-DB',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'TECH_DATABASE',
    displayOrder: 28,
    colorCode: '#4A5568',
    iconName: 'IconDatabase',
    isActive: true,
    position: 28,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // ================= LEVEL 4 DEPARTMENTS =================

  // Sales Hanoi (Level 4 under Sales North)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.SALES_HANOI,
    departmentCode: MktDepartmentCode.SALES_HANOI,
    departmentName: 'Phòng Kinh doanh Hà Nội',
    departmentNameEn: 'Hanoi Sales Department',
    description: 'Phụ trách bán hàng khu vực Hà Nội và các tỉnh lân cận',
    budgetCode: 'BUD-SALES-HN-2024',
    costCenter: 'CC-SALES-HN',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'SALES_CITY',
    displayOrder: 31,
    colorCode: '#0288D1',
    iconName: 'IconBuilding',
    isActive: true,
    position: 31,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Sales HCMC (Level 4 under Sales South)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.SALES_HCMC,
    departmentCode: MktDepartmentCode.SALES_HCMC,
    departmentName: 'Phòng Kinh doanh TP.HCM',
    departmentNameEn: 'Ho Chi Minh City Sales Department',
    description: 'Phụ trách bán hàng khu vực TP.HCM và các tỉnh lân cận',
    budgetCode: 'BUD-SALES-HCM-2024',
    costCenter: 'CC-SALES-HCM',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'SALES_CITY',
    displayOrder: 32,
    colorCode: '#0277BD',
    iconName: 'IconBuilding',
    isActive: true,
    position: 32,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Sales Germany (Level 4 under Sales EU)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.SALES_GERMANY,
    departmentCode: MktDepartmentCode.SALES_GERMANY,
    departmentName: 'Phòng Kinh doanh Đức',
    departmentNameEn: 'Germany Sales Department',
    description: 'Phụ trách bán hàng thị trường Đức',
    budgetCode: 'BUD-SALES-DE-2024',
    costCenter: 'CC-SALES-DE',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'SALES_COUNTRY',
    displayOrder: 33,
    colorCode: '#01579B',
    iconName: 'IconFlag',
    isActive: true,
    position: 33,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Sales Japan (Level 4 under Sales Asia)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.SALES_JAPAN,
    departmentCode: MktDepartmentCode.SALES_JAPAN,
    departmentName: 'Phòng Kinh doanh Nhật Bản',
    departmentNameEn: 'Japan Sales Department',
    description: 'Phụ trách bán hàng thị trường Nhật Bản',
    budgetCode: 'BUD-SALES-JP-2024',
    costCenter: 'CC-SALES-JP',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'SALES_COUNTRY',
    displayOrder: 34,
    colorCode: '#006064',
    iconName: 'IconFlag',
    isActive: true,
    position: 34,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Tech Web (Level 4 under Tech React)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.TECH_WEB,
    departmentCode: MktDepartmentCode.TECH_WEB,
    departmentName: 'Phòng Web Development',
    departmentNameEn: 'Web Development Team',
    description: 'Phụ trách phát triển ứng dụng web React',
    budgetCode: 'BUD-TECH-WEB-2024',
    costCenter: 'CC-TECH-WEB',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'TECH_WEB',
    displayOrder: 35,
    colorCode: '#1A1A2E',
    iconName: 'IconWorld',
    isActive: true,
    position: 35,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Tech Components (Level 4 under Tech React)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.TECH_COMPONENTS,
    departmentCode: MktDepartmentCode.TECH_COMPONENTS,
    departmentName: 'Phòng Component Development',
    departmentNameEn: 'Component Development Team',
    description: 'Phụ trách phát triển thư viện component React',
    budgetCode: 'BUD-TECH-COMP-2024',
    costCenter: 'CC-TECH-COMP',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'TECH_COMPONENTS',
    displayOrder: 36,
    colorCode: '#16213E',
    iconName: 'IconComponents',
    isActive: true,
    position: 36,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Tech iOS (Level 4 under Tech Mobile)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.TECH_IOS,
    departmentCode: MktDepartmentCode.TECH_IOS,
    departmentName: 'Phòng iOS Development',
    departmentNameEn: 'iOS Development Team',
    description: 'Phụ trách phát triển ứng dụng iOS',
    budgetCode: 'BUD-TECH-IOS-2024',
    costCenter: 'CC-TECH-IOS',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'TECH_MOBILE',
    displayOrder: 37,
    colorCode: '#0F3460',
    iconName: 'IconBrandApple',
    isActive: true,
    position: 37,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Tech Android (Level 4 under Tech Mobile)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.TECH_ANDROID,
    departmentCode: MktDepartmentCode.TECH_ANDROID,
    departmentName: 'Phòng Android Development',
    departmentNameEn: 'Android Development Team',
    description: 'Phụ trách phát triển ứng dụng Android',
    budgetCode: 'BUD-TECH-ANDROID-2024',
    costCenter: 'CC-TECH-ANDROID',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'TECH_MOBILE',
    displayOrder: 38,
    colorCode: '#533A7B',
    iconName: 'IconBrandAndroid',
    isActive: true,
    position: 38,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // ================= LEVEL 5 DEPARTMENTS =================

  // Sales Hanoi Retail (Level 5 under Sales Hanoi)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.SALES_HANOI_RETAIL,
    departmentCode: MktDepartmentCode.SALES_HANOI_RETAIL,
    departmentName: 'Phòng Bán lẻ Hà Nội',
    departmentNameEn: 'Hanoi Retail Sales Team',
    description: 'Phụ trách bán lẻ khu vực Hà Nội',
    budgetCode: 'BUD-SALES-HN-RETAIL-2024',
    costCenter: 'CC-SALES-HN-RETAIL',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'SALES_RETAIL',
    displayOrder: 41,
    colorCode: '#1A237E',
    iconName: 'IconShoppingCart',
    isActive: true,
    position: 41,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Sales Hanoi B2B (Level 5 under Sales Hanoi)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.SALES_HANOI_B2B,
    departmentCode: MktDepartmentCode.SALES_HANOI_B2B,
    departmentName: 'Phòng B2B Hà Nội',
    departmentNameEn: 'Hanoi B2B Sales Team',
    description: 'Phụ trách bán hàng B2B khu vực Hà Nội',
    budgetCode: 'BUD-SALES-HN-B2B-2024',
    costCenter: 'CC-SALES-HN-B2B',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'SALES_B2B',
    displayOrder: 42,
    colorCode: '#283593',
    iconName: 'IconBusinessplan',
    isActive: true,
    position: 42,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Sales HCMC Retail (Level 5 under Sales HCMC)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.SALES_HCMC_RETAIL,
    departmentCode: MktDepartmentCode.SALES_HCMC_RETAIL,
    departmentName: 'Phòng Bán lẻ TP.HCM',
    departmentNameEn: 'HCMC Retail Sales Team',
    description: 'Phụ trách bán lẻ khu vực TP.HCM',
    budgetCode: 'BUD-SALES-HCM-RETAIL-2024',
    costCenter: 'CC-SALES-HCM-RETAIL',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'SALES_RETAIL',
    displayOrder: 43,
    colorCode: '#303F9F',
    iconName: 'IconShoppingCart',
    isActive: true,
    position: 43,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Sales HCMC B2B (Level 5 under Sales HCMC)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.SALES_HCMC_B2B,
    departmentCode: MktDepartmentCode.SALES_HCMC_B2B,
    departmentName: 'Phòng B2B TP.HCM',
    departmentNameEn: 'HCMC B2B Sales Team',
    description: 'Phụ trách bán hàng B2B khu vực TP.HCM',
    budgetCode: 'BUD-SALES-HCM-B2B-2024',
    costCenter: 'CC-SALES-HCM-B2B',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'SALES_B2B',
    displayOrder: 44,
    colorCode: '#3949AB',
    iconName: 'IconBusinessplan',
    isActive: true,
    position: 44,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Tech UI Library (Level 5 under Tech Components)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.TECH_UI_LIBRARY,
    departmentCode: MktDepartmentCode.TECH_UI_LIBRARY,
    departmentName: 'Phòng UI Library',
    departmentNameEn: 'UI Library Team',
    description: 'Phụ trách phát triển thư viện UI components',
    budgetCode: 'BUD-TECH-UI-2024',
    costCenter: 'CC-TECH-UI',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'TECH_UI',
    displayOrder: 45,
    colorCode: '#3F51B5',
    iconName: 'IconPalette',
    isActive: true,
    position: 45,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Tech Design System (Level 5 under Tech Components)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.TECH_DESIGN_SYSTEM,
    departmentCode: MktDepartmentCode.TECH_DESIGN_SYSTEM,
    departmentName: 'Phòng Design System',
    departmentNameEn: 'Design System Team',
    description: 'Phụ trách phát triển hệ thống thiết kế',
    budgetCode: 'BUD-TECH-DESIGN-2024',
    costCenter: 'CC-TECH-DESIGN',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'TECH_DESIGN',
    displayOrder: 46,
    colorCode: '#5C6BC0',
    iconName: 'IconBrush',
    isActive: true,
    position: 46,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // ================= LEVEL 6 DEPARTMENTS =================

  // Sales Hanoi Retail Online (Level 6 under Sales Hanoi Retail)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.SALES_HANOI_RETAIL_ONLINE,
    departmentCode: MktDepartmentCode.SALES_HANOI_RETAIL_ONLINE,
    departmentName: 'Phòng Bán lẻ Online Hà Nội',
    departmentNameEn: 'Hanoi Online Retail Team',
    description: 'Phụ trách bán lẻ online khu vực Hà Nội',
    budgetCode: 'BUD-SALES-HN-ONLINE-2024',
    costCenter: 'CC-SALES-HN-ONLINE',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'SALES_ONLINE',
    displayOrder: 51,
    colorCode: '#7986CB',
    iconName: 'IconDeviceDesktop',
    isActive: true,
    position: 51,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Sales Hanoi Retail Offline (Level 6 under Sales Hanoi Retail)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.SALES_HANOI_RETAIL_OFFLINE,
    departmentCode: MktDepartmentCode.SALES_HANOI_RETAIL_OFFLINE,
    departmentName: 'Phòng Bán lẻ Offline Hà Nội',
    departmentNameEn: 'Hanoi Offline Retail Team',
    description: 'Phụ trách bán lẻ offline khu vực Hà Nội',
    budgetCode: 'BUD-SALES-HN-OFFLINE-2024',
    costCenter: 'CC-SALES-HN-OFFLINE',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'SALES_OFFLINE',
    displayOrder: 52,
    colorCode: '#9575CD',
    iconName: 'IconStore',
    isActive: true,
    position: 52,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Tech Component Library (Level 6 under Tech UI Library)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.TECH_COMPONENT_LIB,
    departmentCode: MktDepartmentCode.TECH_COMPONENT_LIB,
    departmentName: 'Phòng Component Library',
    departmentNameEn: 'Component Library Team',
    description: 'Phụ trách phát triển thư viện component cơ bản',
    budgetCode: 'BUD-TECH-COMPLIB-2024',
    costCenter: 'CC-TECH-COMPLIB',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'TECH_LIBRARY',
    displayOrder: 53,
    colorCode: '#B39DDB',
    iconName: 'IconBook',
    isActive: true,
    position: 53,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Tech Theme System (Level 6 under Tech Design System)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.TECH_THEME_SYSTEM,
    departmentCode: MktDepartmentCode.TECH_THEME_SYSTEM,
    departmentName: 'Phòng Theme System',
    departmentNameEn: 'Theme System Team',
    description: 'Phụ trách phát triển hệ thống theme và styling',
    budgetCode: 'BUD-TECH-THEME-2024',
    costCenter: 'CC-TECH-THEME',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'TECH_THEME',
    displayOrder: 54,
    colorCode: '#CE93D8',
    iconName: 'IconColorSwatch',
    isActive: true,
    position: 54,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // ================= LEVEL 7 DEPARTMENTS =================

  // Sales Hanoi E-commerce (Level 7 under Sales Hanoi Retail Online)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.SALES_HANOI_ECOMMERCE,
    departmentCode: MktDepartmentCode.SALES_HANOI_ECOMMERCE,
    departmentName: 'Phòng E-commerce Hà Nội',
    departmentNameEn: 'Hanoi E-commerce Team',
    description: 'Phụ trách bán hàng e-commerce khu vực Hà Nội',
    budgetCode: 'BUD-SALES-HN-ECOM-2024',
    costCenter: 'CC-SALES-HN-ECOM',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'SALES_ECOMMERCE',
    displayOrder: 61,
    colorCode: '#F48FB1',
    iconName: 'IconShoppingBag',
    isActive: true,
    position: 61,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },

  // Sales Hanoi Social Commerce (Level 7 under Sales Hanoi Retail Online)
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS.SALES_HANOI_SOCIAL,
    departmentCode: MktDepartmentCode.SALES_HANOI_SOCIAL,
    departmentName: 'Phòng Social Commerce Hà Nội',
    departmentNameEn: 'Hanoi Social Commerce Team',
    description: 'Phụ trách bán hàng qua mạng xã hội khu vực Hà Nội',
    budgetCode: 'BUD-SALES-HN-SOCIAL-2024',
    costCenter: 'CC-SALES-HN-SOCIAL',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'SALES_SOCIAL',
    displayOrder: 62,
    colorCode: '#F8BBD9',
    iconName: 'IconBrandFacebook',
    isActive: true,
    position: 62,
    createdBySource: 'MANUAL',
    createdByWorkspaceMemberId: null,
    createdByName: 'Admin User',
  },
];
