import { MKT_CUSTOMER_DATA_SEEDS_IDS as MKT_CUSTOMER_DATA_SEEDS_IDS_SYNC } from 'src/mkt-core/dev-seeder/constants/mkt-customer-data-seeds.constants';

type MktLicenseDataSeed = {
  id: string;
  name: string;
  licenseKey: string;
  status: MKT_LICENSE_STATUS;
  activatedAt: Date;
  expiresAt: Date;
  lastLoginAt: Date;
  deviceInfo: string;
  notes: string;

  mktOrderId: string;
  mktVariantId: string;
  mktCustomerId: string;

  position: number;
  createdBySource: string;
  createdByWorkspaceMemberId: string | null;
  createdByName: string;
};

// prettier-ignore
export enum MKT_LICENSE_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
  ERROR = 'ERROR',
  DELETED = 'DELETED',
  PENDING = 'PENDING',
  OTHER = 'OTHER',
}

export const MKT_CUSTOMER_DATA_SEEDS_IDS = {
  ID_1: MKT_CUSTOMER_DATA_SEEDS_IDS_SYNC.TECH_CORP,
  ID_2: MKT_CUSTOMER_DATA_SEEDS_IDS_SYNC.FINANCE_LTD,
  ID_3: MKT_CUSTOMER_DATA_SEEDS_IDS_SYNC.HEALTH_CARE,
  ID_4: MKT_CUSTOMER_DATA_SEEDS_IDS_SYNC.MARKETING_AGENCY,
  ID_5: MKT_CUSTOMER_DATA_SEEDS_IDS_SYNC.CONSULTING_FIRM,
  ID_6: MKT_CUSTOMER_DATA_SEEDS_IDS_SYNC.RETAIL_CHAIN,
  ID_7: MKT_CUSTOMER_DATA_SEEDS_IDS_SYNC.STARTUP_TECH,
  ID_8: MKT_CUSTOMER_DATA_SEEDS_IDS_SYNC.LOCAL_RESTAURANT,
  ID_9: MKT_CUSTOMER_DATA_SEEDS_IDS_SYNC.FREELANCE_DESIGNER,
  ID_10: MKT_CUSTOMER_DATA_SEEDS_IDS_SYNC.CONSULTING_FIRM,
  ID_11: MKT_CUSTOMER_DATA_SEEDS_IDS_SYNC.RETAIL_CHAIN,
  ID_12: MKT_CUSTOMER_DATA_SEEDS_IDS_SYNC.STARTUP_TECH,
  ID_13: MKT_CUSTOMER_DATA_SEEDS_IDS_SYNC.LOCAL_RESTAURANT,
  ID_14: MKT_CUSTOMER_DATA_SEEDS_IDS_SYNC.FREELANCE_DESIGNER,
  ID_15: MKT_CUSTOMER_DATA_SEEDS_IDS_SYNC.CONSULTING_FIRM,
};

// prettier-ignore
export const MKT_LICENSE_DATA_SEED_COLUMNS: (keyof MktLicenseDataSeed)[] = [
  'id',
  'name',
  'licenseKey',
  'status',
  'activatedAt',
  'expiresAt',
  'lastLoginAt',
  'deviceInfo',
  'notes',
  'mktOrderId',
  'mktVariantId',
  'mktCustomerId',
  'position',
  'createdBySource',
  'createdByWorkspaceMemberId',
  'createdByName',
];

// prettier-ignore
export const MKT_LICENSE_DATA_SEEDS_IDS = {
  ID_1: 'e8f55f59-dcda-4e17-8660-930617781a14',
  ID_2: 'f852a725-c8a3-4683-902f-1a048b6aa279',
  ID_3: 'a753a07b-b3d0-4c5c-8ec4-1e525bf0a688',
  ID_4: 'a4a211cb-952e-4590-961d-3e46bef22244',
  ID_5: '348228e0-e448-4589-8fe0-a8dd90059f8b',
  ID_6: '77e87693-e663-43e5-9681-ef89a5f1de49',
  ID_7: '899a53f1-918d-4070-b745-b59af53a9ae9',
  ID_8: '4994533e-467a-41d3-b507-00e24b30cef4',
  ID_9: 'da2e10a2-ce9e-4b49-a8af-44270de73d07',
  ID_10: '54c2f9c5-7104-43a0-b812-064401bf032d',
  ID_11: 'f7ccd13e-bda7-4689-bdc8-cba551c1953b',
  ID_12: '5148f2b8-9300-4b77-80bd-3faff86e6467',
  ID_13: '525cf2dc-4549-4aca-96c2-0591a9150994',
  ID_14: 'e15e5f52-a63b-4b3f-b87d-6a4212dcfb44',
  ID_15: '0945f961-de47-4e33-aa67-5a4257b54874',
};

// prettier-ignore
export const MKT_LICENSE_DATA_SEEDS: MktLicenseDataSeed[] = [
  // {
  //   id: MKT_LICENSE_DATA_SEEDS_IDS.ID_1,
  //   name: 'Wireless Bluetooth Headphones License',
  //   licenseKey: 'ELEC-BTH-001-LIC',
  //   status: MKT_LICENSE_STATUS.ACTIVE,
  //   activatedAt: new Date('2024-01-15T00:00:00.000Z'),
  //   expiresAt: new Date('2025-01-15T00:00:00.000Z'),
  //   lastLoginAt: new Date('2024-01-15T00:00:00.000Z'),
  //   deviceInfo: 'Device Info 1',
  //   notes: 'Notes 1',
  //   mktOrderId: MKT_ORDER_DATA_SEEDS_IDS.ID_1,
  //   mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_1,
  //   mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_1,
  //   position: 1,
  //   createdBySource: 'API',
  //   createdByWorkspaceMemberId: null,
  //   createdByName: 'Sarah Johnson',
  // },
  // {
  //   id: MKT_LICENSE_DATA_SEEDS_IDS.ID_2,
  //   name: 'Organic Coffee Beans Distribution License',
  //   licenseKey: 'FOOD-CFE-002-LIC',
  //   status: MKT_LICENSE_STATUS.ACTIVE,
  //   activatedAt: new Date('2024-02-01T00:00:00.000Z'),
  //   expiresAt: new Date('2025-02-01T00:00:00.000Z'),
  //   lastLoginAt: new Date('2024-02-01T00:00:00.000Z'),
  //   deviceInfo: 'Device Info 2',
  //   notes: 'Notes 2',
  //   mktOrderId: MKT_ORDER_DATA_SEEDS_IDS.ID_2,
  //   mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_2,
  //   mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_2,
  //   position: 2,
  //   createdBySource: 'API',
  //   createdByWorkspaceMemberId: null,
  //   createdByName: 'Michael Chen',
  // },
  // {
  //   id: MKT_LICENSE_DATA_SEEDS_IDS.ID_3,
  //   name: 'Ergonomic Office Chair Reseller License',
  //   licenseKey: 'FURN-CHR-003-LIC',
  //   status: MKT_LICENSE_STATUS.EXPIRED,
  //   activatedAt: new Date('2023-03-10T00:00:00.000Z'),
  //   expiresAt: new Date('2024-03-10T00:00:00.000Z'),
  //   lastLoginAt: new Date('2023-03-10T00:00:00.000Z'),
  //   deviceInfo: 'Device Info 3',
  //   notes: 'Notes 3',
  //   mktOrderId: MKT_ORDER_DATA_SEEDS_IDS.ID_3,
  //   mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_3,
  //   mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_3,
  //   position: 3,
  //   createdBySource: 'API',
  //   createdByWorkspaceMemberId: null,
  //   createdByName: 'Emily Rodriguez',
  // },
  // {
  //   id: MKT_LICENSE_DATA_SEEDS_IDS.ID_4,
  //   name: 'Steel Water Bottle Brand License',
  //   licenseKey: 'OUTD-WBT-004-LIC',
  //   status: MKT_LICENSE_STATUS.ACTIVE,
  //   activatedAt: new Date('2024-01-20T00:00:00.000Z'),
  //   expiresAt: new Date('2025-01-20T00:00:00.000Z'),
  //   lastLoginAt: new Date('2024-01-20T00:00:00.000Z'),
  //   deviceInfo: 'Device Info 4',
  //   notes: 'Notes 4',
  //   mktOrderId: MKT_ORDER_DATA_SEEDS_IDS.ID_4,
  //   mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_4,
  //   mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_4,
  //   position: 4,
  //   createdBySource: 'API',
  //   createdByWorkspaceMemberId: null,
  //   createdByName: 'David Kim',
  // },
  // {
  //   id: MKT_LICENSE_DATA_SEEDS_IDS.ID_5,
  //   name: 'LED Desk Lamp Technology License',
  //   licenseKey: 'HOME-LMP-005-LIC',
  //   status: MKT_LICENSE_STATUS.REVOKED,
  //   activatedAt: new Date('2024-01-05T00:00:00.000Z'),
  //   expiresAt: new Date('2025-01-05T00:00:00.000Z'),
  //   lastLoginAt: new Date('2024-01-05T00:00:00.000Z'),
  //   deviceInfo: 'Device Info 5',
  //   notes: 'Notes 5',
  //   mktOrderId: MKT_ORDER_DATA_SEEDS_IDS.ID_5,
  //   mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_5,
  //   mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_5,
  //   position: 5,
  //   createdBySource: 'API',
  //   createdByWorkspaceMemberId: null,
  //   createdByName: 'Lisa Wang',
  // },
  // {
  //   id: MKT_LICENSE_DATA_SEEDS_IDS.ID_6,
  //   name: 'Bluetooth Headphones Retail License',
  //   licenseKey: 'ELEC-BTH-006-LIC',
  //   status: MKT_LICENSE_STATUS.ACTIVE,
  //   activatedAt: new Date('2024-08-15T00:00:00.000Z'),
  //   expiresAt: new Date('2025-08-15T00:00:00.000Z'),
  //   lastLoginAt: new Date('2024-08-15T00:00:00.000Z'),
  //   deviceInfo: 'Device Info 6',
  //   notes: 'Notes 6',
  //   mktOrderId: MKT_ORDER_DATA_SEEDS_IDS.ID_1,
  //   mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_6,
  //   mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_6,
  //   position: 6,
  //   createdBySource: 'API',
  //   createdByWorkspaceMemberId: null,
  //   createdByName: 'Robert Taylor',
  // },
  // {
  //   id: MKT_LICENSE_DATA_SEEDS_IDS.ID_7,
  //   name: 'Coffee Beans Export License',
  //   licenseKey: 'FOOD-CFE-007-LIC',
  //   status: MKT_LICENSE_STATUS.ACTIVE,
  //   activatedAt: new Date('2024-06-01T00:00:00.000Z'),
  //   expiresAt: new Date('2025-06-01T00:00:00.000Z'),
  //   lastLoginAt: new Date('2024-06-01T00:00:00.000Z'),
  //   deviceInfo: 'Device Info 7',
  //   notes: 'Notes 7',
  //   mktOrderId: MKT_ORDER_DATA_SEEDS_IDS.ID_2,
  //   mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_7,
  //   mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_7,
  //   position: 7,
  //   createdBySource: 'API',
  //   createdByWorkspaceMemberId: null,
  //   createdByName: 'Jessica Brown',
  // },
  // {
  //   id: MKT_LICENSE_DATA_SEEDS_IDS.ID_8,
  //   name: 'Office Chair Manufacturing License',
  //   licenseKey: 'FURN-CHR-008-LIC',
  //   status: MKT_LICENSE_STATUS.INACTIVE,
  //   activatedAt: new Date('2023-11-10T00:00:00.000Z'),
  //   expiresAt: new Date('2026-11-10T00:00:00.000Z'),
  //   lastLoginAt: new Date('2023-11-10T00:00:00.000Z'),
  //   deviceInfo: 'Device Info 8',
  //   notes: 'Notes 8',
  //   mktOrderId: MKT_ORDER_DATA_SEEDS_IDS.ID_3,
  //   mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_8,
  //   mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_8,
  //   position: 8,
  //   createdBySource: 'API',
  //   createdByWorkspaceMemberId: null,
  //   createdByName: 'Mark Wilson',
  // },
  // {
  //   id: MKT_LICENSE_DATA_SEEDS_IDS.ID_9,
  //   name: 'Water Bottle Design License',
  //   licenseKey: 'OUTD-WBT-009-LIC',
  //   status: MKT_LICENSE_STATUS.ACTIVE,
  //   activatedAt: new Date('2024-03-15T00:00:00.000Z'),
  //   expiresAt: new Date('2025-03-15T00:00:00.000Z'),
  //   lastLoginAt: new Date('2024-03-15T00:00:00.000Z'),
  //   deviceInfo: 'Device Info 9',
  //   notes: 'Notes 9',
  //   mktOrderId: MKT_ORDER_DATA_SEEDS_IDS.ID_4,
  //   mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_9,
  //   mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_9,
  //   position: 9,
  //   createdBySource: 'API',
  //   createdByWorkspaceMemberId: null,
  //   createdByName: 'Jennifer Davis',
  // },
  // {
  //   id: MKT_LICENSE_DATA_SEEDS_IDS.ID_10,
  //   name: 'LED Lamp Patent License',
  //   licenseKey: 'HOME-LMP-010-LIC',
  //   status: MKT_LICENSE_STATUS.ACTIVE,
  //   activatedAt: new Date('2024-07-01T00:00:00.000Z'),
  //   expiresAt: new Date('2025-07-01T00:00:00.000Z'),
  //   lastLoginAt: new Date('2024-07-01T00:00:00.000Z'),
  //   deviceInfo: 'Device Info 10',
  //   notes: 'Notes 10',
  //   mktOrderId: MKT_ORDER_DATA_SEEDS_IDS.ID_5,
  //   mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_10,
  //   mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_10,
  //   position: 10,
  //   createdBySource: 'API',
  //   createdByWorkspaceMemberId: null,
  //   createdByName: 'Christopher Martinez',
  // },
  // {
  //   id: MKT_LICENSE_DATA_SEEDS_IDS.ID_11,
  //   name: 'Headphones Audio Technology License',
  //   licenseKey: 'ELEC-BTH-011-LIC',
  //   status: MKT_LICENSE_STATUS.EXPIRED,
  //   activatedAt: new Date('2022-12-01T00:00:00.000Z'),
  //   expiresAt: new Date('2023-12-01T00:00:00.000Z'),
  //   lastLoginAt: new Date('2022-12-01T00:00:00.000Z'),
  //   deviceInfo: 'Device Info 11',
  //   notes: 'Notes 11',
  //   mktOrderId: MKT_ORDER_DATA_SEEDS_IDS.ID_6,
  //   mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_11,
  //   mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_11,
  //   position: 11,
  //   createdBySource: 'API',
  //   createdByWorkspaceMemberId: null,
  //   createdByName: 'Amanda Lopez',
  // },
  // {
  //   id: MKT_LICENSE_DATA_SEEDS_IDS.ID_12,
  //   name: 'Premium Coffee Roasting License',
  //   licenseKey: 'FOOD-CFE-012-LIC',
  //   status: MKT_LICENSE_STATUS.ACTIVE,
  //   activatedAt: new Date('2024-05-20T00:00:00.000Z'),
  //   expiresAt: new Date('2025-05-20T00:00:00.000Z'),
  //   lastLoginAt: new Date('2024-05-20T00:00:00.000Z'),
  //   deviceInfo: 'Device Info 12',
  //   notes: 'Notes 12',
  //   mktOrderId: MKT_ORDER_DATA_SEEDS_IDS.ID_7,
  //   mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.MKT_CARE_BASIC_6_MONTHS_ID,
  //   mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_12,
  //   position: 12,
  //   createdBySource: 'API',
  //   createdByWorkspaceMemberId: null,
  //   createdByName: 'Kevin Anderson',
  // },
  // {
  //   id: MKT_LICENSE_DATA_SEEDS_IDS.ID_13,
  //   name: 'Ergonomic Furniture Design License',
  //   licenseKey: 'FURN-CHR-013-LIC',
  //   status: MKT_LICENSE_STATUS.ACTIVE,
  //   activatedAt: new Date('2024-09-01T00:00:00.000Z'),
  //   expiresAt: new Date('2026-09-01T00:00:00.000Z'),
  //   lastLoginAt: new Date('2024-09-01T00:00:00.000Z'),
  //   deviceInfo: 'Device Info 13',
  //   notes: 'Notes 13',
  //   mktOrderId: MKT_ORDER_DATA_SEEDS_IDS.ID_8,
  //   mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.MKT_CARE_BASIC_12_MONTHS_ID,
  //   mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_13,
  //   position: 13,
  //   createdBySource: 'API',
  //   createdByWorkspaceMemberId: null,
  //   createdByName: 'Michelle Garcia',
  // },
  // {
  //   id: MKT_LICENSE_DATA_SEEDS_IDS.ID_14,
  //   name: 'Insulated Bottle Technology License',
  //   licenseKey: 'OUTD-WBT-014-LIC',
  //   status: MKT_LICENSE_STATUS.REVOKED,
  //   activatedAt: new Date('2024-04-10T00:00:00.000Z'),
  //   expiresAt: new Date('2025-04-10T00:00:00.000Z'),
  //   lastLoginAt: new Date('2024-04-10T00:00:00.000Z'),
  //   deviceInfo: 'Device Info 14',
  //   notes: 'Notes 14',
  //   mktOrderId: MKT_ORDER_DATA_SEEDS_IDS.ID_9,
  //   mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.MKT_CARE_PREMIUM_12_MONTHS_ID,
  //   mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_14,
  //   position: 14,
  //   createdBySource: 'API',
  //   createdByWorkspaceMemberId: null,
  //   createdByName: 'Daniel Thompson',
  // },
  // {
  //   id: MKT_LICENSE_DATA_SEEDS_IDS.ID_15,
  //   name: 'Smart Lighting System License',
  //   licenseKey: 'HOME-LMP-015-LIC',
  //   status: MKT_LICENSE_STATUS.ACTIVE,
  //   activatedAt: new Date('2024-10-15T00:00:00.000Z'),
  //   expiresAt: new Date('2025-10-15T00:00:00.000Z'),
  //   lastLoginAt: new Date('2024-10-15T00:00:00.000Z'),
  //   deviceInfo: 'Device Info 15',
  //   notes: 'Notes 15',
  //   mktOrderId: MKT_ORDER_DATA_SEEDS_IDS.ID_10,
  //   mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.MKT_EMAIL_PLUS_VN_ID,
  //   mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.ID_15,
  //   position: 15,
  //   createdBySource: 'API',
  //   createdByWorkspaceMemberId: null,
  //   createdByName: 'Rachel White',
  // },
];
