import * as fs from 'fs-extra';
import { join } from 'path';
import { v4 } from 'uuid';

export const copyBaseApplicationProject = async ({
  appName,
  appDisplayName,
  appDescription,
  appDirectory,
}: {
  appName: string;
  appDisplayName: string;
  appDescription: string;
  appDirectory: string;
}) => {
  await createPackageJson({ appName, appDirectory });

  await createYarnLock(appDirectory);

  await createYarnRc(appDirectory);

  await createNvmRc(appDirectory);

  await createTsConfig(appDirectory);

  await createApplicationConfig({
    displayName: appDisplayName,
    description: appDescription,
    appDirectory,
  });

  await createReadmeContent({
    displayName: appDisplayName,
    appDescription,
    appDirectory,
  });
};

const createYarnLock = async (appDirectory: string) => {
  const yarnLockContent = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1
`;

  await fs.writeFile(join(appDirectory, 'yarn.lock'), yarnLockContent);
};

const createYarnRc = async (appDirectory: string) => {
  const yarnRcContent = `nodeLinker: node-modules
`;

  await fs.writeFile(join(appDirectory, '.yarnrc.yml'), yarnRcContent);
};

const createNvmRc = async (appDirectory: string) => {
  const nvmRcContent = `24.5.0
`;

  await fs.writeFile(join(appDirectory, '.nvmrc'), nvmRcContent);
};

const createTsConfig = async (appDirectory: string) => {
  const tsConfigJson = {
    compileOnSave: false,
    compilerOptions: {
      sourceMap: true,
      declaration: true,
      outDir: './dist',
      rootDir: '.',
      moduleResolution: 'node',
      allowSyntheticDefaultImports: true,
      emitDecoratorMetadata: true,
      experimentalDecorators: true,
      importHelpers: true,
      allowUnreachableCode: false,
      strictNullChecks: true,
      alwaysStrict: true,
      noImplicitAny: true,
      strictBindCallApply: false,
      target: 'es2018',
      module: 'esnext',
      lib: ['es2020', 'dom'],
      skipLibCheck: true,
      skipDefaultLibCheck: true,
      resolveJsonModule: true,
    },

    exclude: ['node_modules', 'dist', '**/*.test.ts', '**/*.spec.ts'],
  };

  await fs.writeFile(
    join(appDirectory, 'tsconfig.json'),
    JSON.stringify(tsConfigJson, null, 2),
    'utf8',
  );
};

const createApplicationConfig = async ({
  displayName,
  description,
  appDirectory,
}: {
  displayName: string;
  description?: string;
  appDirectory: string;
}) => {
  const content = `import { type ApplicationConfig } from 'twenty-sdk';

const config: ApplicationConfig = {
  universalIdentifier: '${v4()}',
  displayName: '${displayName}',
  description: '${description ?? ''}',
};

export default config;
`;

  await fs.writeFile(join(appDirectory, 'application.config.ts'), content);
};

const createPackageJson = async ({
  appName,
  appDirectory,
}: {
  appName: string;
  appDirectory: string;
}) => {
  const packageJson = {
    name: appName,
    version: '0.0.1',
    license: 'MIT',
    engines: {
      node: '^24.5.0',
      npm: 'please-use-yarn',
      yarn: '>=4.0.2',
    },
    packageManager: 'yarn@4.9.2',
    scripts: {
      'create-entity': 'twenty app add',
      dev: 'twenty app dev',
      generate: 'twenty app generate',
      sync: 'twenty app sync',
      uninstall: 'twenty app uninstall',
      auth: 'twenty auth login',
    },
    dependencies: {
      'twenty-sdk': '0.1.0',
    },
    devDependencies: {
      '@types/node': '^24.7.2',
      typescript: '^5.9.3',
    },
  };

  await fs.writeFile(
    join(appDirectory, 'package.json'),
    JSON.stringify(packageJson, null, 2),
    'utf8',
  );
};

const createReadmeContent = async ({
  displayName,
  appDescription,
  appDirectory,
}: {
  displayName: string;
  appDescription: string;
  appDirectory: string;
}) => {
  const readmeContent = `# ${displayName}

${appDescription}
`;

  await fs.writeFile(join(appDirectory, 'README.md'), readmeContent);
};
