export const WIDGET_CONFIGURATION_GQL_FIELDS = `
  ... on BarChartConfiguration {
    graphType
    aggregateFieldMetadataId
    aggregateOperation
    primaryAxisGroupByFieldMetadataId
    primaryAxisGroupBySubFieldName
    primaryAxisDateGranularity
    primaryAxisOrderBy
    secondaryAxisGroupByFieldMetadataId
    secondaryAxisGroupBySubFieldName
    secondaryAxisGroupByDateGranularity
    secondaryAxisOrderBy
    omitNullValues
    axisNameDisplay
    displayDataLabel
    displayLegend
    rangeMin
    rangeMax
    color
    description
    filter
    groupMode
    layout
    isCumulative
    timezone
    firstDayOfTheWeek
  }
  ... on LineChartConfiguration {
    graphType
    aggregateFieldMetadataId
    aggregateOperation
    primaryAxisGroupByFieldMetadataId
    primaryAxisGroupBySubFieldName
    primaryAxisDateGranularity
    primaryAxisOrderBy
    secondaryAxisGroupByFieldMetadataId
    secondaryAxisGroupBySubFieldName
    secondaryAxisGroupByDateGranularity
    secondaryAxisOrderBy
    omitNullValues
    axisNameDisplay
    displayDataLabel
    displayLegend
    rangeMin
    rangeMax
    color
    description
    filter
    isStacked
    isCumulative
    timezone
    firstDayOfTheWeek
  }
  ... on PieChartConfiguration {
    graphType
    groupByFieldMetadataId
    aggregateFieldMetadataId
    aggregateOperation
    groupBySubFieldName
    dateGranularity
    orderBy
    displayDataLabel
    showCenterMetric
    displayLegend
    color
    description
    filter
    timezone
    firstDayOfTheWeek
  }
  ... on AggregateChartConfiguration {
    graphType
    aggregateFieldMetadataId
    aggregateOperation
    label
    displayDataLabel
    format
    description
    filter
    prefix
    suffix
    timezone
    firstDayOfTheWeek
  }
  ... on GaugeChartConfiguration {
    graphType
    aggregateFieldMetadataId
    aggregateOperation
    displayDataLabel
    color
    description
    filter
    timezone
    firstDayOfTheWeek
  }
  ... on IframeConfiguration {
    url
  }
  ... on StandaloneRichTextConfiguration {
    body {
      blocknote
      markdown
    }
  }
`;
