import {
  defineField,
  FieldType,
  STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS,
} from 'twenty-sdk/define';

import {
  PDL_FIELD_UNIVERSAL_IDENTIFIERS,
  PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS,
} from 'src/constants/universal-identifiers';

export default defineField({
  universalIdentifier:
    PDL_FIELD_UNIVERSAL_IDENTIFIERS.company.pdlLatestFundingStage,
  objectUniversalIdentifier:
    STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.company.universalIdentifier,
  type: FieldType.SELECT,
  name: 'pdlLatestFundingStage',
  label: 'Latest Funding Stage',
  description: 'People Data Labs canonical latest funding stage.',
  isNullable: true,
  options: [
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.angel,
      value: 'ANGEL',
      label: 'Angel',
      color: 'yellow',
      position: 0,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.convertibleNote,
      value: 'CONVERTIBLE_NOTE',
      label: 'Convertible Note',
      color: 'orange',
      position: 1,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.corporateRound,
      value: 'CORPORATE_ROUND',
      label: 'Corporate Round',
      color: 'blue',
      position: 2,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.debtFinancing,
      value: 'DEBT_FINANCING',
      label: 'Debt Financing',
      color: 'gray',
      position: 3,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage
        .equityCrowdfunding,
      value: 'EQUITY_CROWDFUNDING',
      label: 'Equity Crowdfunding',
      color: 'turquoise',
      position: 4,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.fundingRound,
      value: 'FUNDING_ROUND',
      label: 'Funding Round',
      color: 'sky',
      position: 5,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.grant,
      value: 'GRANT',
      label: 'Grant',
      color: 'green',
      position: 6,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage
        .initialCoinOffering,
      value: 'INITIAL_COIN_OFFERING',
      label: 'Initial Coin Offering',
      color: 'purple',
      position: 7,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage
        .nonEquityAssistance,
      value: 'NON_EQUITY_ASSISTANCE',
      label: 'Non-Equity Assistance',
      color: 'pink',
      position: 8,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.postIpoDebt,
      value: 'POST_IPO_DEBT',
      label: 'Post-IPO Debt',
      color: 'red',
      position: 9,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.postIpoEquity,
      value: 'POST_IPO_EQUITY',
      label: 'Post-IPO Equity',
      color: 'yellow',
      position: 10,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.postIpoSecondary,
      value: 'POST_IPO_SECONDARY',
      label: 'Post-IPO Secondary',
      color: 'orange',
      position: 11,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.preSeed,
      value: 'PRE_SEED',
      label: 'Pre-Seed',
      color: 'blue',
      position: 12,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.privateEquity,
      value: 'PRIVATE_EQUITY',
      label: 'Private Equity',
      color: 'gray',
      position: 13,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage
        .productCrowdfunding,
      value: 'PRODUCT_CROWDFUNDING',
      label: 'Product Crowdfunding',
      color: 'turquoise',
      position: 14,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.secondaryMarket,
      value: 'SECONDARY_MARKET',
      label: 'Secondary Market',
      color: 'sky',
      position: 15,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.seed,
      value: 'SEED',
      label: 'Seed',
      color: 'green',
      position: 16,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.seriesA,
      value: 'SERIES_A',
      label: 'Series A',
      color: 'purple',
      position: 17,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.seriesB,
      value: 'SERIES_B',
      label: 'Series B',
      color: 'pink',
      position: 18,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.seriesC,
      value: 'SERIES_C',
      label: 'Series C',
      color: 'red',
      position: 19,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.seriesD,
      value: 'SERIES_D',
      label: 'Series D',
      color: 'yellow',
      position: 20,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.seriesE,
      value: 'SERIES_E',
      label: 'Series E',
      color: 'orange',
      position: 21,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.seriesF,
      value: 'SERIES_F',
      label: 'Series F',
      color: 'blue',
      position: 22,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.seriesG,
      value: 'SERIES_G',
      label: 'Series G',
      color: 'gray',
      position: 23,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.seriesH,
      value: 'SERIES_H',
      label: 'Series H',
      color: 'turquoise',
      position: 24,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.seriesI,
      value: 'SERIES_I',
      label: 'Series I',
      color: 'sky',
      position: 25,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.seriesJ,
      value: 'SERIES_J',
      label: 'Series J',
      color: 'green',
      position: 26,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.seriesUnknown,
      value: 'SERIES_UNKNOWN',
      label: 'Series Unknown',
      color: 'purple',
      position: 27,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.fundingStage.undisclosed,
      value: 'UNDISCLOSED',
      label: 'Undisclosed',
      color: 'gray',
      position: 28,
    },
  ],
});
