export const PAGE_LAYOUT_TAB_SEEDS = {
  SALES_OVERVIEW: 'SALES_OVERVIEW_TAB',
  SALES_DETAILS: 'SALES_DETAILS_TAB',
  CUSTOMER_OVERVIEW: 'CUSTOMER_OVERVIEW_TAB',
  CUSTOMER_ANALYTICS: 'CUSTOMER_ANALYTICS_TAB',
  TEAM_OVERVIEW: 'TEAM_OVERVIEW_TAB',
  TEAM_METRICS: 'TEAM_METRICS_TAB',
};
