import * as RadixColors from '@radix-ui/colors';
import { GRAY_SCALE_LIGHT } from '@ui/theme/constants/GrayScaleLight';

export const SECONDARY_COLORS_DARK = {
  yellow1: RadixColors.yellowDarkP3.yellow1,
  yellow2: RadixColors.yellowDarkP3.yellow2,
  yellow3: RadixColors.yellowDarkP3.yellow3,
  yellow4: RadixColors.yellowDarkP3.yellow4,
  yellow5: RadixColors.yellowP3.yellow5,
  yellow6: RadixColors.yellowDarkP3.yellow6,
  yellow7: RadixColors.yellowDarkP3.yellow7,
  yellow8: RadixColors.yellowP3.yellow8,
  yellow9: RadixColors.yellowP3.yellow9,
  yellow10: RadixColors.yellowDarkP3.yellow10,
  yellow11: RadixColors.yellowDarkP3.yellow11,
  yellow12: RadixColors.yellowDarkP3.yellow12,

  green1: RadixColors.greenDarkP3.green1,
  green2: RadixColors.greenDarkP3.green2,
  green3: RadixColors.greenDarkP3.green3,
  green4: RadixColors.greenDarkP3.green4,
  green5: RadixColors.greenDarkP3.green5,
  green6: RadixColors.greenDarkP3.green6,
  green7: RadixColors.greenDarkP3.green7,
  green8: RadixColors.greenDarkP3.green8,
  green9: RadixColors.greenDarkP3.green9,
  green10: RadixColors.greenDarkP3.green10,
  green11: RadixColors.greenDarkP3.green11,
  green12: RadixColors.greenDarkP3.green12,

  turquoise1: RadixColors.tealDarkP3.teal1,
  turquoise2: RadixColors.tealDarkP3.teal2,
  turquoise3: RadixColors.tealDarkP3.teal3,
  turquoise4: RadixColors.tealDarkP3.teal4,
  turquoise5: RadixColors.tealDarkP3.teal5,
  turquoise6: RadixColors.tealDarkP3.teal6,
  turquoise7: RadixColors.tealDarkP3.teal7,
  turquoise8: RadixColors.tealDarkP3.teal8,
  turquoise9: RadixColors.tealDarkP3.teal9,
  turquoise10: RadixColors.tealDarkP3.teal10,
  turquoise11: RadixColors.tealDarkP3.teal11,
  turquoise12: RadixColors.tealDarkP3.teal12,

  sky1: RadixColors.skyDarkP3.sky1,
  sky2: RadixColors.skyDarkP3.sky2,
  sky3: RadixColors.skyDarkP3.sky3,
  sky4: RadixColors.skyDarkP3.sky4,
  sky5: RadixColors.skyDarkP3.sky5,
  sky6: RadixColors.skyDarkP3.sky6,
  sky7: RadixColors.skyDarkP3.sky7,
  sky8: RadixColors.skyDarkP3.sky8,
  sky9: RadixColors.skyP3.sky9,
  sky10: RadixColors.skyDarkP3.sky10,
  sky11: RadixColors.skyDarkP3.sky11,
  sky12: RadixColors.skyDarkP3.sky12,

  blue1: RadixColors.indigoDarkP3.indigo1,
  blue2: RadixColors.indigoDarkP3.indigo2,
  blue3: RadixColors.indigoDarkP3.indigo3,
  blue4: RadixColors.indigoDarkP3.indigo4,
  blue5: RadixColors.indigoDarkP3.indigo5,
  blue6: RadixColors.indigoDarkP3.indigo6,
  blue7: RadixColors.indigoDarkP3.indigo7,
  blue8: RadixColors.indigoDarkP3.indigo8,
  blue9: RadixColors.indigoDarkP3.indigo9,
  blue10: RadixColors.indigoDarkP3.indigo10,
  blue11: RadixColors.indigoDarkP3.indigo11,
  blue12: RadixColors.indigoDarkP3.indigo12,

  purple1: RadixColors.violetDarkP3.violet1,
  purple2: RadixColors.violetDarkP3.violet2,
  purple3: RadixColors.violetDarkP3.violet3,
  purple4: RadixColors.violetDarkP3.violet4,
  purple5: RadixColors.violetDarkP3.violet5,
  purple6: RadixColors.violetDarkP3.violet6,
  purple7: RadixColors.violetDarkP3.violet7,
  purple8: RadixColors.violetDarkP3.violet8,
  purple9: RadixColors.violetDarkP3.violet9,
  purple10: RadixColors.violetDarkP3.violet10,
  purple11: RadixColors.violetDarkP3.violet11,
  purple12: RadixColors.violetDarkP3.violet12,

  pink1: RadixColors.pinkDarkP3.pink1,
  pink2: RadixColors.pinkDarkP3.pink2,
  pink3: RadixColors.pinkDarkP3.pink3,
  pink4: RadixColors.pinkDarkP3.pink4,
  pink5: RadixColors.pinkDarkP3.pink5,
  pink6: RadixColors.pinkDarkP3.pink6,
  pink7: RadixColors.pinkDarkP3.pink7,
  pink8: RadixColors.pinkDarkP3.pink8,
  pink9: RadixColors.pinkDarkP3.pink9,
  pink10: RadixColors.pinkDarkP3.pink10,
  pink11: RadixColors.pinkDarkP3.pink11,
  pink12: RadixColors.pinkDarkP3.pink12,

  red1: RadixColors.redDarkP3.red1,
  red2: RadixColors.redDarkP3.red2,
  red3: RadixColors.redDarkP3.red3,
  red4: RadixColors.redDarkP3.red4,
  red5: RadixColors.redDarkP3.red5,
  red6: RadixColors.redDarkP3.red6,
  red7: RadixColors.redDarkP3.red7,
  red8: RadixColors.redDarkP3.red8,
  red9: RadixColors.redDarkP3.red9,
  red10: RadixColors.redDarkP3.red10,
  red11: RadixColors.redDarkP3.red11,
  red12: RadixColors.redDarkP3.red12,

  orange1: RadixColors.orangeDarkP3.orange1,
  orange2: RadixColors.orangeDarkP3.orange2,
  orange3: RadixColors.orangeDarkP3.orange3,
  orange4: RadixColors.orangeDarkP3.orange4,
  orange5: RadixColors.orangeDarkP3.orange5,
  orange6: RadixColors.orangeDarkP3.orange6,
  orange7: RadixColors.orangeDarkP3.orange7,
  orange8: RadixColors.orangeDarkP3.orange8,
  orange9: RadixColors.orangeDarkP3.orange9,
  orange10: RadixColors.orangeDarkP3.orange10,
  orange11: RadixColors.orangeDarkP3.orange11,
  orange12: RadixColors.orangeDarkP3.orange12,

  gray1: GRAY_SCALE_LIGHT.gray1,
  gray2: GRAY_SCALE_LIGHT.gray2,
  gray3: GRAY_SCALE_LIGHT.gray3,
  gray4: GRAY_SCALE_LIGHT.gray4,
  gray5: GRAY_SCALE_LIGHT.gray5,
  gray6: GRAY_SCALE_LIGHT.gray6,
  gray7: GRAY_SCALE_LIGHT.gray7,
  gray8: GRAY_SCALE_LIGHT.gray8,
  gray9: GRAY_SCALE_LIGHT.gray9,
  gray10: GRAY_SCALE_LIGHT.gray10,
  gray11: GRAY_SCALE_LIGHT.gray11,
  gray12: GRAY_SCALE_LIGHT.gray12,

  blueAccent1: RadixColors.blueDarkP3.blue1,
  blueAccent2: RadixColors.blueDarkP3.blue2,
  blueAccent3: RadixColors.blueDarkP3.blue3,
  blueAccent4: RadixColors.blueDarkP3.blue4,
  blueAccent5: RadixColors.blueDarkP3.blue5,
  blueAccent6: RadixColors.blueDarkP3.blue6,
  blueAccent7: RadixColors.blueDarkP3.blue7,
  blueAccent8: RadixColors.blueDarkP3.blue8,
  blueAccent9: RadixColors.blueDarkP3.blue9,
  blueAccent10: RadixColors.blueDarkP3.blue10,
  blueAccent11: RadixColors.blueDarkP3.blue11,
  blueAccent12: RadixColors.blueDarkP3.blue12,
};
