import { COLOR_DARK } from '@ui/theme/constants/ColorsDark';

export const TAG_DARK = {
  text: {
    gray: COLOR_DARK.gray11,
    mauve: COLOR_DARK.mauve11,
    slate: COLOR_DARK.slate11,
    sage: COLOR_DARK.sage11,
    olive: COLOR_DARK.olive11,
    sand: COLOR_DARK.sand11,
    tomato: COLOR_DARK.tomato11,
    red: COLOR_DARK.red11,
    ruby: COLOR_DARK.ruby11,
    crimson: COLOR_DARK.crimson11,
    pink: COLOR_DARK.pink11,
    plum: COLOR_DARK.plum11,
    purple: COLOR_DARK.purple11,
    violet: COLOR_DARK.violet11,
    iris: COLOR_DARK.iris11,
    cyan: COLOR_DARK.cyan11,
    turquoise: COLOR_DARK.turquoise11,
    sky: COLOR_DARK.sky11,
    blue: COLOR_DARK.blue11,
    jade: COLOR_DARK.jade11,
    green: COLOR_DARK.green11,
    grass: COLOR_DARK.grass11,
    mint: COLOR_DARK.mint11,
    lime: COLOR_DARK.lime11,
    bronze: COLOR_DARK.bronze11,
    gold: COLOR_DARK.gold11,
    brown: COLOR_DARK.brown11,
    orange: COLOR_DARK.orange11,
    amber: COLOR_DARK.amber11,
    yellow: COLOR_DARK.yellow11,
  },
  background: {
    gray: COLOR_DARK.gray4,
    mauve: COLOR_DARK.mauve4,
    slate: COLOR_DARK.slate4,
    sage: COLOR_DARK.sage4,
    olive: COLOR_DARK.olive4,
    sand: COLOR_DARK.sand4,
    tomato: COLOR_DARK.tomato4,
    red: COLOR_DARK.red4,
    ruby: COLOR_DARK.ruby4,
    crimson: COLOR_DARK.crimson4,
    pink: COLOR_DARK.pink4,
    plum: COLOR_DARK.plum4,
    purple: COLOR_DARK.purple4,
    violet: COLOR_DARK.violet4,
    iris: COLOR_DARK.iris4,
    cyan: COLOR_DARK.cyan4,
    turquoise: COLOR_DARK.turquoise4,
    sky: COLOR_DARK.sky4,
    blue: COLOR_DARK.blue4,
    jade: COLOR_DARK.jade4,
    green: COLOR_DARK.green4,
    grass: COLOR_DARK.grass4,
    mint: COLOR_DARK.mint4,
    lime: COLOR_DARK.lime4,
    bronze: COLOR_DARK.bronze4,
    gold: COLOR_DARK.gold4,
    brown: COLOR_DARK.brown4,
    orange: COLOR_DARK.orange4,
    amber: COLOR_DARK.amber4,
    yellow: COLOR_DARK.yellow4,
  },
};
