import { COLOR_LIGHT } from '@ui/theme/constants/ColorsLight';

export const TAG_LIGHT = {
  text: {
    gray: COLOR_LIGHT.gray11,
    mauve: COLOR_LIGHT.mauve11,
    slate: COLOR_LIGHT.slate11,
    sage: COLOR_LIGHT.sage11,
    olive: COLOR_LIGHT.olive11,
    sand: COLOR_LIGHT.sand11,
    tomato: COLOR_LIGHT.tomato11,
    red: COLOR_LIGHT.red11,
    ruby: COLOR_LIGHT.ruby11,
    crimson: COLOR_LIGHT.crimson11,
    pink: COLOR_LIGHT.pink11,
    plum: COLOR_LIGHT.plum11,
    purple: COLOR_LIGHT.purple11,
    violet: COLOR_LIGHT.violet11,
    iris: COLOR_LIGHT.iris11,
    cyan: COLOR_LIGHT.cyan11,
    turquoise: COLOR_LIGHT.turquoise11,
    sky: COLOR_LIGHT.sky11,
    blue: COLOR_LIGHT.blue11,
    jade: COLOR_LIGHT.jade11,
    green: COLOR_LIGHT.green11,
    grass: COLOR_LIGHT.grass11,
    mint: COLOR_LIGHT.mint11,
    lime: COLOR_LIGHT.lime11,
    bronze: COLOR_LIGHT.bronze11,
    gold: COLOR_LIGHT.gold11,
    brown: COLOR_LIGHT.brown11,
    orange: COLOR_LIGHT.orange11,
    amber: COLOR_LIGHT.amber11,
    yellow: COLOR_LIGHT.yellow11,
  },
  background: {
    gray: COLOR_LIGHT.gray4,
    mauve: COLOR_LIGHT.mauve4,
    slate: COLOR_LIGHT.slate4,
    sage: COLOR_LIGHT.sage4,
    olive: COLOR_LIGHT.olive4,
    sand: COLOR_LIGHT.sand4,
    tomato: COLOR_LIGHT.tomato4,
    red: COLOR_LIGHT.red4,
    ruby: COLOR_LIGHT.ruby4,
    crimson: COLOR_LIGHT.crimson4,
    pink: COLOR_LIGHT.pink4,
    plum: COLOR_LIGHT.plum4,
    purple: COLOR_LIGHT.purple4,
    violet: COLOR_LIGHT.violet4,
    iris: COLOR_LIGHT.iris4,
    cyan: COLOR_LIGHT.cyan4,
    turquoise: COLOR_LIGHT.turquoise4,
    sky: COLOR_LIGHT.sky4,
    blue: COLOR_LIGHT.blue4,
    jade: COLOR_LIGHT.jade4,
    green: COLOR_LIGHT.green4,
    grass: COLOR_LIGHT.grass4,
    mint: COLOR_LIGHT.mint4,
    lime: COLOR_LIGHT.lime4,
    bronze: COLOR_LIGHT.bronze4,
    gold: COLOR_LIGHT.gold4,
    brown: COLOR_LIGHT.brown4,
    orange: COLOR_LIGHT.orange4,
    amber: COLOR_LIGHT.amber4,
    yellow: COLOR_LIGHT.yellow4,
  },
};
