import * as RadixColors from '@radix-ui/colors';
import { GRAY_SCALE_DARK_ALPHA } from '@ui/theme/constants/GrayScaleDarkAlpha';

export const TRANSPARENT_COLORS_DARK = {
  green1: RadixColors.greenDarkA.greenA1,
  green2: RadixColors.greenDarkA.greenA2,
  green3: RadixColors.greenDarkA.greenA3,
  green4: RadixColors.greenDarkA.greenA4,
  green5: RadixColors.greenDarkA.greenA5,
  green6: RadixColors.greenDarkA.greenA6,
  green7: RadixColors.greenDarkA.greenA7,
  green8: RadixColors.greenDarkA.greenA8,
  green9: RadixColors.greenDarkA.greenA9,
  green10: RadixColors.greenDarkA.greenA10,
  green11: RadixColors.greenDarkA.greenA11,
  green12: RadixColors.greenDarkA.greenA12,

  turquoise1: RadixColors.tealDarkA.tealA1,
  turquoise2: RadixColors.tealDarkA.tealA2,
  turquoise3: RadixColors.tealDarkA.tealA3,
  turquoise4: RadixColors.tealDarkA.tealA4,
  turquoise5: RadixColors.tealDarkA.tealA5,
  turquoise6: RadixColors.tealDarkA.tealA6,
  turquoise7: RadixColors.tealDarkA.tealA7,
  turquoise8: RadixColors.tealDarkA.tealA8,
  turquoise9: RadixColors.tealDarkA.tealA9,
  turquoise10: RadixColors.tealDarkA.tealA10,
  turquoise11: RadixColors.tealDarkA.tealA11,
  turquoise12: RadixColors.tealDarkA.tealA12,

  sky1: RadixColors.skyDarkA.skyA1,
  sky2: RadixColors.skyDarkA.skyA2,
  sky3: RadixColors.skyDarkA.skyA3,
  sky4: RadixColors.skyDarkA.skyA4,
  sky5: RadixColors.skyDarkA.skyA5,
  sky6: RadixColors.skyDarkA.skyA6,
  sky7: RadixColors.skyDarkA.skyA7,
  sky8: RadixColors.skyDarkA.skyA8,
  sky9: RadixColors.skyDarkA.skyA9,
  sky10: RadixColors.skyDarkA.skyA10,
  sky11: RadixColors.skyDarkA.skyA11,
  sky12: RadixColors.skyDarkA.skyA12,

  blue1: RadixColors.indigoDarkA.indigoA1,
  blue2: RadixColors.indigoDarkA.indigoA2,
  blue3: RadixColors.indigoDarkA.indigoA3,
  blue4: RadixColors.indigoDarkA.indigoA4,
  blue5: RadixColors.indigoDarkA.indigoA5,
  blue6: RadixColors.indigoDarkA.indigoA6,
  blue7: RadixColors.indigoDarkA.indigoA7,
  blue8: RadixColors.indigoDarkA.indigoA8,
  blue9: RadixColors.indigoDarkA.indigoA9,
  blue10: RadixColors.indigoDarkA.indigoA10,
  blue11: RadixColors.indigoDarkA.indigoA11,
  blue12: RadixColors.indigoDarkA.indigoA12,

  purple1: RadixColors.violetDarkA.violetA1,
  purple2: RadixColors.violetDarkA.violetA2,
  purple3: RadixColors.violetDarkA.violetA3,
  purple4: RadixColors.violetDarkA.violetA4,
  purple5: RadixColors.violetDarkA.violetA5,
  purple6: RadixColors.violetDarkA.violetA6,
  purple7: RadixColors.violetDarkA.violetA7,
  purple8: RadixColors.violetDarkA.violetA8,
  purple9: RadixColors.violetDarkA.violetA9,
  purple10: RadixColors.violetDarkA.violetA10,
  purple11: RadixColors.violetDarkA.violetA11,
  purple12: RadixColors.violetDarkA.violetA12,

  pink1: RadixColors.pinkDarkA.pinkA1,
  pink2: RadixColors.pinkDarkA.pinkA2,
  pink3: RadixColors.pinkDarkA.pinkA3,
  pink4: RadixColors.pinkDarkA.pinkA4,
  pink5: RadixColors.pinkDarkA.pinkA5,
  pink6: RadixColors.pinkDarkA.pinkA6,
  pink7: RadixColors.pinkDarkA.pinkA7,
  pink8: RadixColors.pinkDarkA.pinkA8,
  pink9: RadixColors.pinkDarkA.pinkA9,
  pink10: RadixColors.pinkDarkA.pinkA10,
  pink11: RadixColors.pinkDarkA.pinkA11,
  pink12: RadixColors.pinkDarkA.pinkA12,

  red1: RadixColors.redDarkA.redA1,
  red2: RadixColors.redDarkA.redA2,
  red3: RadixColors.redDarkA.redA3,
  red4: RadixColors.redDarkA.redA4,
  red5: RadixColors.redDarkA.redA5,
  red6: RadixColors.redDarkA.redA6,
  red7: RadixColors.redDarkA.redA7,
  red8: RadixColors.redDarkA.redA8,
  red9: RadixColors.redDarkA.redA9,
  red10: RadixColors.redDarkA.redA10,
  red11: RadixColors.redDarkA.redA11,
  red12: RadixColors.redDarkA.redA12,

  orange1: RadixColors.orangeDarkA.orangeA1,
  orange2: RadixColors.orangeDarkA.orangeA2,
  orange3: RadixColors.orangeDarkA.orangeA3,
  orange4: RadixColors.orangeDarkA.orangeA4,
  orange5: RadixColors.orangeDarkA.orangeA5,
  orange6: RadixColors.orangeDarkA.orangeA6,
  orange7: RadixColors.orangeDarkA.orangeA7,
  orange8: RadixColors.orangeDarkA.orangeA8,
  orange9: RadixColors.orangeDarkA.orangeA9,
  orange10: RadixColors.orangeDarkA.orangeA10,
  orange11: RadixColors.orangeDarkA.orangeA11,
  orange12: RadixColors.orangeDarkA.orangeA12,

  yellow1: RadixColors.yellowDarkA.yellowA1,
  yellow2: RadixColors.yellowDarkA.yellowA2,
  yellow3: RadixColors.yellowDarkA.yellowA3,
  yellow4: RadixColors.yellowDarkA.yellowA4,
  yellow5: RadixColors.yellowDarkA.yellowA5,
  yellow6: RadixColors.yellowDarkA.yellowA6,
  yellow7: RadixColors.yellowDarkA.yellowA7,
  yellow8: RadixColors.yellowDarkA.yellowA8,
  yellow9: RadixColors.yellowDarkA.yellowA9,
  yellow10: RadixColors.yellowDarkA.yellowA10,
  yellow11: RadixColors.yellowDarkA.yellowA11,
  yellow12: RadixColors.yellowDarkA.yellowA12,

  blueAccent1: RadixColors.blueDarkA.blueA1,
  blueAccent2: RadixColors.blueDarkA.blueA2,
  blueAccent3: RadixColors.blueDarkA.blueA3,
  blueAccent4: RadixColors.blueDarkA.blueA4,
  blueAccent5: RadixColors.blueDarkA.blueA5,
  blueAccent6: RadixColors.blueDarkA.blueA6,
  blueAccent7: RadixColors.blueDarkA.blueA7,
  blueAccent8: RadixColors.blueDarkA.blueA8,
  blueAccent9: RadixColors.blueDarkA.blueA9,
  blueAccent10: RadixColors.blueDarkA.blueA10,
  blueAccent11: RadixColors.blueDarkA.blueA11,
  blueAccent12: RadixColors.blueDarkA.blueA12,

  gray1: GRAY_SCALE_DARK_ALPHA.gray1,
  gray2: GRAY_SCALE_DARK_ALPHA.gray2,
  gray3: GRAY_SCALE_DARK_ALPHA.gray3,
  gray4: GRAY_SCALE_DARK_ALPHA.gray4,
  gray5: GRAY_SCALE_DARK_ALPHA.gray5,
  gray6: GRAY_SCALE_DARK_ALPHA.gray6,
  gray7: GRAY_SCALE_DARK_ALPHA.gray7,
  gray8: GRAY_SCALE_DARK_ALPHA.gray8,
  gray9: GRAY_SCALE_DARK_ALPHA.gray9,
  gray10: GRAY_SCALE_DARK_ALPHA.gray10,
  gray11: GRAY_SCALE_DARK_ALPHA.gray11,
  gray12: GRAY_SCALE_DARK_ALPHA.gray12,
};
