export const STANDARD_FRONT_COMPONENTS = {
  navigateToNextRecord: {
    universalIdentifier: '20202020-fc01-4c01-8c01-c0aba11fc001',
    name: 'Navigate to next record',
    componentName: 'NavigateToNextRecordSingleRecordAction',
    sourceComponentPath: 'action-menu/actions/record-actions/single-record',
    builtComponentPath: 'action-menu/actions/record-actions/single-record',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  navigateToPreviousRecord: {
    universalIdentifier: '20202020-fc02-4c02-8c02-c0aba11fc002',
    name: 'Navigate to previous record',
    componentName: 'NavigateToPreviousRecordSingleRecordAction',
    sourceComponentPath: 'action-menu/actions/record-actions/single-record',
    builtComponentPath: 'action-menu/actions/record-actions/single-record',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  createNewRecord: {
    universalIdentifier: '20202020-fc03-4c03-8c03-c0aba11fc003',
    name: 'Create new record',
    componentName: 'CreateNewIndexRecordNoSelectionRecordAction',
    sourceComponentPath: 'action-menu/actions/record-actions/no-selection',
    builtComponentPath: 'action-menu/actions/record-actions/no-selection',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  deleteSingleRecord: {
    universalIdentifier: '20202020-fc04-4c04-8c04-c0aba11fc004',
    name: 'Delete single record',
    componentName: 'DeleteSingleRecordAction',
    sourceComponentPath: 'action-menu/actions/record-actions/single-record',
    builtComponentPath: 'action-menu/actions/record-actions/single-record',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  deleteMultipleRecords: {
    universalIdentifier: '20202020-fc05-4c05-8c05-c0aba11fc005',
    name: 'Delete multiple records',
    componentName: 'DeleteMultipleRecordsAction',
    sourceComponentPath: 'action-menu/actions/record-actions/multiple-records',
    builtComponentPath: 'action-menu/actions/record-actions/multiple-records',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  restoreSingleRecord: {
    universalIdentifier: '20202020-fc06-4c06-8c06-c0aba11fc006',
    name: 'Restore single record',
    componentName: 'RestoreSingleRecordAction',
    sourceComponentPath: 'action-menu/actions/record-actions/single-record',
    builtComponentPath: 'action-menu/actions/record-actions/single-record',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  restoreMultipleRecords: {
    universalIdentifier: '20202020-fc07-4c07-8c07-c0aba11fc007',
    name: 'Restore multiple records',
    componentName: 'RestoreMultipleRecordsAction',
    sourceComponentPath: 'action-menu/actions/record-actions/multiple-records',
    builtComponentPath: 'action-menu/actions/record-actions/multiple-records',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  destroySingleRecord: {
    universalIdentifier: '20202020-fc08-4c08-8c08-c0aba11fc008',
    name: 'Destroy single record',
    componentName: 'DestroySingleRecordAction',
    sourceComponentPath: 'action-menu/actions/record-actions/single-record',
    builtComponentPath: 'action-menu/actions/record-actions/single-record',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  destroyMultipleRecords: {
    universalIdentifier: '20202020-fc09-4c09-8c09-c0aba11fc009',
    name: 'Destroy multiple records',
    componentName: 'DestroyMultipleRecordsAction',
    sourceComponentPath: 'action-menu/actions/record-actions/multiple-records',
    builtComponentPath: 'action-menu/actions/record-actions/multiple-records',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  addToFavorites: {
    universalIdentifier: '20202020-fc0a-4c0a-8c0a-c0aba11fc00a',
    name: 'Add to favorites',
    componentName: 'AddToFavoritesSingleRecordAction',
    sourceComponentPath: 'action-menu/actions/record-actions/single-record',
    builtComponentPath: 'action-menu/actions/record-actions/single-record',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  removeFromFavorites: {
    universalIdentifier: '20202020-fc0b-4c0b-8c0b-c0aba11fc00b',
    name: 'Remove from favorites',
    componentName: 'RemoveFromFavoritesSingleRecordAction',
    sourceComponentPath: 'action-menu/actions/record-actions/single-record',
    builtComponentPath: 'action-menu/actions/record-actions/single-record',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  exportNoteToPdf: {
    universalIdentifier: '20202020-fc0c-4c0c-8c0c-c0aba11fc00c',
    name: 'Export note to PDF',
    componentName: 'ExportNoteActionSingleRecordAction',
    sourceComponentPath: 'action-menu/actions/record-actions/single-record',
    builtComponentPath: 'action-menu/actions/record-actions/single-record',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  exportFromRecordIndex: {
    universalIdentifier: '20202020-fc0d-4c0d-8c0d-c0aba11fc00d',
    name: 'Export from record index',
    componentName: 'ExportMultipleRecordsAction',
    sourceComponentPath: 'action-menu/actions/record-actions/multiple-records',
    builtComponentPath: 'action-menu/actions/record-actions/multiple-records',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  exportFromRecordShow: {
    universalIdentifier: '20202020-fc0e-4c0e-8c0e-c0aba11fc00e',
    name: 'Export from record show',
    componentName: 'ExportSingleRecordAction',
    sourceComponentPath: 'action-menu/actions/record-actions/single-record',
    builtComponentPath: 'action-menu/actions/record-actions/single-record',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  updateMultipleRecords: {
    universalIdentifier: '20202020-fc0f-4c0f-8c0f-c0aba11fc00f',
    name: 'Update multiple records',
    componentName: 'UpdateMultipleRecordsAction',
    sourceComponentPath: 'action-menu/actions/record-actions/multiple-records',
    builtComponentPath: 'action-menu/actions/record-actions/multiple-records',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  mergeMultipleRecords: {
    universalIdentifier: '20202020-fc10-4c10-8c10-c0aba11fc010',
    name: 'Merge multiple records',
    componentName: 'MergeMultipleRecordsAction',
    sourceComponentPath: 'action-menu/actions/record-actions/multiple-records',
    builtComponentPath: 'action-menu/actions/record-actions/multiple-records',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  exportMultipleRecords: {
    universalIdentifier: '20202020-fc11-4c11-8c11-c0aba11fc011',
    name: 'Export multiple records',
    componentName: 'ExportMultipleRecordsAction',
    sourceComponentPath: 'action-menu/actions/record-actions/multiple-records',
    builtComponentPath: 'action-menu/actions/record-actions/multiple-records',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  importRecords: {
    universalIdentifier: '20202020-fc12-4c12-8c12-c0aba11fc012',
    name: 'Import records',
    componentName: 'ImportRecordsNoSelectionRecordAction',
    sourceComponentPath: 'action-menu/actions/record-actions/no-selection',
    builtComponentPath: 'action-menu/actions/record-actions/no-selection',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  exportView: {
    universalIdentifier: '20202020-fc13-4c13-8c13-c0aba11fc013',
    name: 'Export view',
    componentName: 'ExportMultipleRecordsAction',
    sourceComponentPath: 'action-menu/actions/record-actions/multiple-records',
    builtComponentPath: 'action-menu/actions/record-actions/multiple-records',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  seeDeletedRecords: {
    universalIdentifier: '20202020-fc14-4c14-8c14-c0aba11fc014',
    name: 'See deleted records',
    componentName: 'SeeDeletedRecordsNoSelectionRecordAction',
    sourceComponentPath: 'action-menu/actions/record-actions/no-selection',
    builtComponentPath: 'action-menu/actions/record-actions/no-selection',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  createNewView: {
    universalIdentifier: '20202020-fc15-4c15-8c15-c0aba11fc015',
    name: 'Create view',
    componentName: 'CreateNewViewNoSelectionRecord',
    sourceComponentPath: 'action-menu/actions/record-actions/no-selection',
    builtComponentPath: 'action-menu/actions/record-actions/no-selection',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  hideDeletedRecords: {
    universalIdentifier: '20202020-fc16-4c16-8c16-c0aba11fc016',
    name: 'Hide deleted records',
    componentName: 'HideDeletedRecordsNoSelectionRecordAction',
    sourceComponentPath: 'action-menu/actions/record-actions/no-selection',
    builtComponentPath: 'action-menu/actions/record-actions/no-selection',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  goToPeople: {
    universalIdentifier: '20202020-fc17-4c17-8c17-c0aba11fc017',
    name: 'Go to People',
    componentName: 'ActionLink',
    sourceComponentPath: 'action-menu/actions/components',
    builtComponentPath: 'action-menu/actions/components',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  goToCompanies: {
    universalIdentifier: '20202020-fc18-4c18-8c18-c0aba11fc018',
    name: 'Go to Companies',
    componentName: 'ActionLink',
    sourceComponentPath: 'action-menu/actions/components',
    builtComponentPath: 'action-menu/actions/components',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  goToDashboards: {
    universalIdentifier: '20202020-fc19-4c19-8c19-c0aba11fc019',
    name: 'Go to Dashboards',
    componentName: 'ActionLink',
    sourceComponentPath: 'action-menu/actions/components',
    builtComponentPath: 'action-menu/actions/components',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  goToOpportunities: {
    universalIdentifier: '20202020-fc1a-4c1a-8c1a-c0aba11fc01a',
    name: 'Go to Opportunities',
    componentName: 'ActionLink',
    sourceComponentPath: 'action-menu/actions/components',
    builtComponentPath: 'action-menu/actions/components',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  goToSettings: {
    universalIdentifier: '20202020-fc1b-4c1b-8c1b-c0aba11fc01b',
    name: 'Go to Settings',
    componentName: 'ActionLink',
    sourceComponentPath: 'action-menu/actions/components',
    builtComponentPath: 'action-menu/actions/components',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  goToTasks: {
    universalIdentifier: '20202020-fc1c-4c1c-8c1c-c0aba11fc01c',
    name: 'Go to Tasks',
    componentName: 'ActionLink',
    sourceComponentPath: 'action-menu/actions/components',
    builtComponentPath: 'action-menu/actions/components',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  goToNotes: {
    universalIdentifier: '20202020-fc1d-4c1d-8c1d-c0aba11fc01d',
    name: 'Go to Notes',
    componentName: 'ActionLink',
    sourceComponentPath: 'action-menu/actions/components',
    builtComponentPath: 'action-menu/actions/components',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  editRecordPageLayout: {
    universalIdentifier: '20202020-fc1e-4c1e-8c1e-c0aba11fc01e',
    name: 'Edit record page layout',
    componentName: 'EditRecordPageLayoutSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/record-page-layout-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/record-page-layout-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  saveRecordPageLayout: {
    universalIdentifier: '20202020-fc1f-4c1f-8c1f-c0aba11fc01f',
    name: 'Save record page layout',
    componentName: 'SaveRecordPageLayoutSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/record-page-layout-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/record-page-layout-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  cancelRecordPageLayout: {
    universalIdentifier: '20202020-fc20-4c20-8c20-c0aba11fc020',
    name: 'Cancel record page layout edition',
    componentName: 'CancelRecordPageLayoutSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/record-page-layout-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/record-page-layout-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  editDashboardLayout: {
    universalIdentifier: '20202020-fc21-4c21-8c21-c0aba11fc021',
    name: 'Edit dashboard layout',
    componentName: 'EditDashboardSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/dashboard-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/dashboard-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  saveDashboardLayout: {
    universalIdentifier: '20202020-fc22-4c22-8c22-c0aba11fc022',
    name: 'Save dashboard layout',
    componentName: 'SaveDashboardSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/dashboard-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/dashboard-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  cancelDashboardLayout: {
    universalIdentifier: '20202020-fc23-4c23-8c23-c0aba11fc023',
    name: 'Cancel dashboard layout edition',
    componentName: 'CancelDashboardSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/dashboard-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/dashboard-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  duplicateDashboard: {
    universalIdentifier: '20202020-fc24-4c24-8c24-c0aba11fc024',
    name: 'Duplicate dashboard',
    componentName: 'DuplicateDashboardSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/dashboard-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/dashboard-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  goToWorkflows: {
    universalIdentifier: '20202020-fc29-4c29-8c29-c0aba11fc029',
    name: 'Go to Workflows',
    componentName: 'ActionLink',
    sourceComponentPath: 'action-menu/actions/components',
    builtComponentPath: 'action-menu/actions/components',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  activateWorkflow: {
    universalIdentifier: '20202020-fc2a-4c2a-8c2a-c0aba11fc02a',
    name: 'Activate workflow',
    componentName: 'ActivateWorkflowSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  deactivateWorkflow: {
    universalIdentifier: '20202020-fc2b-4c2b-8c2b-c0aba11fc02b',
    name: 'Deactivate workflow',
    componentName: 'DeactivateWorkflowSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  discardDraftWorkflow: {
    universalIdentifier: '20202020-fc2c-4c2c-8c2c-c0aba11fc02c',
    name: 'Discard draft workflow',
    componentName: 'DiscardDraftWorkflowSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  testWorkflow: {
    universalIdentifier: '20202020-fc2d-4c2d-8c2d-c0aba11fc02d',
    name: 'Test workflow',
    componentName: 'TestWorkflowSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  seeActiveVersionWorkflow: {
    universalIdentifier: '20202020-fc2e-4c2e-8c2e-c0aba11fc02e',
    name: 'See active version',
    componentName: 'SeeActiveVersionWorkflowSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  seeRunsWorkflow: {
    universalIdentifier: '20202020-fc2f-4c2f-8c2f-c0aba11fc02f',
    name: 'See runs',
    componentName: 'SeeRunsWorkflowSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  seeVersionsWorkflow: {
    universalIdentifier: '20202020-fc30-4c30-8c30-c0aba11fc030',
    name: 'See versions history',
    componentName: 'SeeVersionsWorkflowSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  addNodeWorkflow: {
    universalIdentifier: '20202020-fc31-4c31-8c31-c0aba11fc031',
    name: 'Add a node',
    componentName: 'AddNodeWorkflowSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  tidyUpWorkflow: {
    universalIdentifier: '20202020-fc32-4c32-8c32-c0aba11fc032',
    name: 'Tidy up workflow',
    componentName: 'TidyUpWorkflowSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  duplicateWorkflow: {
    universalIdentifier: '20202020-fc33-4c33-8c33-c0aba11fc033',
    name: 'Duplicate workflow',
    componentName: 'DuplicateWorkflowSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  goToRuns: {
    universalIdentifier: '20202020-fc34-4c34-8c34-c0aba11fc034',
    name: 'Go to runs',
    componentName: 'ActionLink',
    sourceComponentPath: 'action-menu/actions/components',
    builtComponentPath: 'action-menu/actions/components',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  seeVersionWorkflowRun: {
    universalIdentifier: '20202020-fc35-4c35-8c35-c0aba11fc035',
    name: 'See version (workflow run)',
    componentName: 'SeeVersionWorkflowRunSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-run-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-run-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  seeWorkflowWorkflowRun: {
    universalIdentifier: '20202020-fc36-4c36-8c36-c0aba11fc036',
    name: 'See workflow (workflow run)',
    componentName: 'SeeWorkflowWorkflowRunSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-run-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-run-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  stopWorkflowRun: {
    universalIdentifier: '20202020-fc37-4c37-8c37-c0aba11fc037',
    name: 'Stop workflow run',
    componentName: 'StopWorkflowRunSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-run-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-run-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  seeRunsWorkflowVersion: {
    universalIdentifier: '20202020-fc38-4c38-8c38-c0aba11fc038',
    name: 'See runs (workflow version)',
    componentName: 'SeeRunsWorkflowVersionSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-version-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-version-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  seeWorkflowWorkflowVersion: {
    universalIdentifier: '20202020-fc39-4c39-8c39-c0aba11fc039',
    name: 'See workflow (workflow version)',
    componentName: 'SeeWorkflowWorkflowVersionSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-version-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-version-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  useAsDraftWorkflowVersion: {
    universalIdentifier: '20202020-fc3a-4c3a-8c3a-c0aba11fc03a',
    name: 'Use as draft (workflow version)',
    componentName: 'UseAsDraftWorkflowVersionSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-version-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-version-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  seeVersionsWorkflowVersion: {
    universalIdentifier: '20202020-fc3b-4c3b-8c3b-c0aba11fc03b',
    name: 'See versions history (workflow version)',
    componentName: 'SeeVersionsWorkflowVersionSingleRecordAction',
    sourceComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-version-actions',
    builtComponentPath:
      'action-menu/actions/record-actions/single-record/workflow-version-actions',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: true,
  },
  searchRecords: {
    universalIdentifier: '20202020-fc25-4c25-8c25-c0aba11fc025',
    name: 'Search records',
    componentName: 'ActionOpenSidePanelPage',
    sourceComponentPath: 'action-menu/actions/components',
    builtComponentPath: 'action-menu/actions/components',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: false,
  },
  searchRecordsFallback: {
    universalIdentifier: '20202020-fc26-4c26-8c26-c0aba11fc026',
    name: 'Search records fallback',
    componentName: 'ActionOpenSidePanelPage',
    sourceComponentPath: 'action-menu/actions/components',
    builtComponentPath: 'action-menu/actions/components',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: false,
  },
  askAi: {
    universalIdentifier: '20202020-fc27-4c27-8c27-c0aba11fc027',
    name: 'Ask AI',
    componentName: 'ActionOpenSidePanelPage',
    sourceComponentPath: 'action-menu/actions/components',
    builtComponentPath: 'action-menu/actions/components',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: false,
  },
  viewPreviousAiChats: {
    universalIdentifier: '20202020-fc28-4c28-8c28-c0aba11fc028',
    name: 'View previous AI chats',
    componentName: 'ActionOpenSidePanelPage',
    sourceComponentPath: 'action-menu/actions/components',
    builtComponentPath: 'action-menu/actions/components',
    builtComponentChecksum: 'standard-built-in',
    isHeadless: false,
  },
} as const;
