import {
  STANDARD_BLOCKLIST_PAGE_LAYOUT_CONFIG,
  STANDARD_CALENDAR_CHANNEL_EVENT_ASSOCIATION_PAGE_LAYOUT_CONFIG,
  STANDARD_CALENDAR_CHANNEL_PAGE_LAYOUT_CONFIG,
  STANDARD_CALENDAR_EVENT_PARTICIPANT_PAGE_LAYOUT_CONFIG,
  STANDARD_COMPANY_PAGE_LAYOUT_CONFIG,
  STANDARD_CONNECTED_ACCOUNT_PAGE_LAYOUT_CONFIG,
  STANDARD_DASHBOARD_PAGE_LAYOUT_CONFIG,
  STANDARD_FAVORITE_FOLDER_PAGE_LAYOUT_CONFIG,
  STANDARD_FAVORITE_PAGE_LAYOUT_CONFIG,
  STANDARD_MESSAGE_CHANNEL_MESSAGE_ASSOCIATION_MESSAGE_FOLDER_PAGE_LAYOUT_CONFIG,
  STANDARD_MESSAGE_CHANNEL_MESSAGE_ASSOCIATION_PAGE_LAYOUT_CONFIG,
  STANDARD_MESSAGE_CHANNEL_PAGE_LAYOUT_CONFIG,
  STANDARD_MESSAGE_FOLDER_PAGE_LAYOUT_CONFIG,
  STANDARD_MESSAGE_PARTICIPANT_PAGE_LAYOUT_CONFIG,
  STANDARD_MESSAGE_THREAD_PAGE_LAYOUT_CONFIG,
  STANDARD_NOTE_PAGE_LAYOUT_CONFIG,
  STANDARD_OPPORTUNITY_PAGE_LAYOUT_CONFIG,
  STANDARD_PERSON_PAGE_LAYOUT_CONFIG,
  STANDARD_TASK_PAGE_LAYOUT_CONFIG,
  STANDARD_WORKFLOW_AUTOMATED_TRIGGER_PAGE_LAYOUT_CONFIG,
  STANDARD_WORKFLOW_PAGE_LAYOUT_CONFIG,
  STANDARD_WORKFLOW_RUN_PAGE_LAYOUT_CONFIG,
  STANDARD_WORKFLOW_VERSION_PAGE_LAYOUT_CONFIG,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/page-layout-config';
import { type StandardRecordPageLayouts } from 'src/engine/workspace-manager/twenty-standard-application/utils/page-layout-config/standard-page-layout-config.type';

export const STANDARD_PAGE_LAYOUTS = {
  myFirstDashboard: STANDARD_DASHBOARD_PAGE_LAYOUT_CONFIG,
  blocklistRecordPage: STANDARD_BLOCKLIST_PAGE_LAYOUT_CONFIG,
  calendarChannelRecordPage: STANDARD_CALENDAR_CHANNEL_PAGE_LAYOUT_CONFIG,
  calendarChannelEventAssociationRecordPage:
    STANDARD_CALENDAR_CHANNEL_EVENT_ASSOCIATION_PAGE_LAYOUT_CONFIG,
  calendarEventParticipantRecordPage:
    STANDARD_CALENDAR_EVENT_PARTICIPANT_PAGE_LAYOUT_CONFIG,
  companyRecordPage: STANDARD_COMPANY_PAGE_LAYOUT_CONFIG,
  connectedAccountRecordPage: STANDARD_CONNECTED_ACCOUNT_PAGE_LAYOUT_CONFIG,
  favoriteRecordPage: STANDARD_FAVORITE_PAGE_LAYOUT_CONFIG,
  favoriteFolderRecordPage: STANDARD_FAVORITE_FOLDER_PAGE_LAYOUT_CONFIG,
  messageChannelRecordPage: STANDARD_MESSAGE_CHANNEL_PAGE_LAYOUT_CONFIG,
  messageChannelMessageAssociationRecordPage:
    STANDARD_MESSAGE_CHANNEL_MESSAGE_ASSOCIATION_PAGE_LAYOUT_CONFIG,
  messageChannelMessageAssociationMessageFolderRecordPage:
    STANDARD_MESSAGE_CHANNEL_MESSAGE_ASSOCIATION_MESSAGE_FOLDER_PAGE_LAYOUT_CONFIG,
  messageFolderRecordPage: STANDARD_MESSAGE_FOLDER_PAGE_LAYOUT_CONFIG,
  messageParticipantRecordPage: STANDARD_MESSAGE_PARTICIPANT_PAGE_LAYOUT_CONFIG,
  messageThreadRecordPage: STANDARD_MESSAGE_THREAD_PAGE_LAYOUT_CONFIG,
  noteRecordPage: STANDARD_NOTE_PAGE_LAYOUT_CONFIG,
  opportunityRecordPage: STANDARD_OPPORTUNITY_PAGE_LAYOUT_CONFIG,
  personRecordPage: STANDARD_PERSON_PAGE_LAYOUT_CONFIG,
  taskRecordPage: STANDARD_TASK_PAGE_LAYOUT_CONFIG,
  workflowRecordPage: STANDARD_WORKFLOW_PAGE_LAYOUT_CONFIG,
  workflowAutomatedTriggerRecordPage:
    STANDARD_WORKFLOW_AUTOMATED_TRIGGER_PAGE_LAYOUT_CONFIG,
  workflowVersionRecordPage: STANDARD_WORKFLOW_VERSION_PAGE_LAYOUT_CONFIG,
  workflowRunRecordPage: STANDARD_WORKFLOW_RUN_PAGE_LAYOUT_CONFIG,
} as const;

const { myFirstDashboard: _myFirstDashboard, ...recordPageLayouts } =
  STANDARD_PAGE_LAYOUTS;

export const STANDARD_RECORD_PAGE_LAYOUTS =
  recordPageLayouts satisfies StandardRecordPageLayouts;
