import { CommandMenuItemAvailabilityType } from 'src/engine/metadata-modules/command-menu-item/entities/command-menu-item.entity';

import { STANDARD_FRONT_COMPONENTS } from './standard-front-component.constant';

export const STANDARD_COMMAND_MENU_ITEMS = {
  navigateToNextRecord: {
    universalIdentifier: '20202020-cm01-4c01-8c01-c0aba11cm001',
    label: 'Navigate to next record',
    shortLabel: null,
    icon: 'IconChevronDown',
    position: 0,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.navigateToNextRecord.universalIdentifier,
  },
  navigateToPreviousRecord: {
    universalIdentifier: '20202020-cm02-4c02-8c02-c0aba11cm002',
    label: 'Navigate to previous record',
    shortLabel: null,
    icon: 'IconChevronUp',
    position: 1,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.navigateToPreviousRecord.universalIdentifier,
  },
  createNewRecord: {
    universalIdentifier: '20202020-cm03-4c03-8c03-c0aba11cm003',
    label: 'Create new record',
    shortLabel: 'New record',
    icon: 'IconPlus',
    position: 2,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.createNewRecord.universalIdentifier,
  },
  deleteSingleRecord: {
    universalIdentifier: '20202020-cm04-4c04-8c04-c0aba11cm004',
    label: 'Delete',
    shortLabel: 'Delete',
    icon: 'IconTrash',
    position: 3,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.deleteSingleRecord.universalIdentifier,
  },
  deleteMultipleRecords: {
    universalIdentifier: '20202020-cm05-4c05-8c05-c0aba11cm005',
    label: 'Delete records',
    shortLabel: 'Delete',
    icon: 'IconTrash',
    position: 4,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.deleteMultipleRecords.universalIdentifier,
  },
  restoreSingleRecord: {
    universalIdentifier: '20202020-cm06-4c06-8c06-c0aba11cm006',
    label: 'Restore record',
    shortLabel: 'Restore',
    icon: 'IconRefresh',
    position: 5,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.restoreSingleRecord.universalIdentifier,
  },
  restoreMultipleRecords: {
    universalIdentifier: '20202020-cm07-4c07-8c07-c0aba11cm007',
    label: 'Restore records',
    shortLabel: 'Restore',
    icon: 'IconRefresh',
    position: 6,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.restoreMultipleRecords.universalIdentifier,
  },
  destroySingleRecord: {
    universalIdentifier: '20202020-cm08-4c08-8c08-c0aba11cm008',
    label: 'Permanently destroy record',
    shortLabel: 'Destroy',
    icon: 'IconTrashX',
    position: 7,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.destroySingleRecord.universalIdentifier,
  },
  destroyMultipleRecords: {
    universalIdentifier: '20202020-cm09-4c09-8c09-c0aba11cm009',
    label: 'Permanently destroy records',
    shortLabel: 'Destroy',
    icon: 'IconTrashX',
    position: 8,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.destroyMultipleRecords.universalIdentifier,
  },
  addToFavorites: {
    universalIdentifier: '20202020-cm0a-4c0a-8c0a-c0aba11cm00a',
    label: 'Add to favorites',
    shortLabel: 'Add to favorites',
    icon: 'IconHeart',
    position: 9,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.addToFavorites.universalIdentifier,
  },
  removeFromFavorites: {
    universalIdentifier: '20202020-cm0b-4c0b-8c0b-c0aba11cm00b',
    label: 'Remove from favorites',
    shortLabel: 'Remove from favorites',
    icon: 'IconHeartOff',
    position: 10,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.removeFromFavorites.universalIdentifier,
  },
  exportNoteToPdf: {
    universalIdentifier: '20202020-cm0c-4c0c-8c0c-c0aba11cm00c',
    label: 'Export to PDF',
    shortLabel: 'Export',
    icon: 'IconFileExport',
    position: 11,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.exportNoteToPdf.universalIdentifier,
  },
  exportFromRecordIndex: {
    universalIdentifier: '20202020-cm0d-4c0d-8c0d-c0aba11cm00d',
    label: 'Export',
    shortLabel: 'Export',
    icon: 'IconFileExport',
    position: 12,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.exportFromRecordIndex.universalIdentifier,
  },
  exportFromRecordShow: {
    universalIdentifier: '20202020-cm0e-4c0e-8c0e-c0aba11cm00e',
    label: 'Export',
    shortLabel: 'Export',
    icon: 'IconFileExport',
    position: 13,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.exportFromRecordShow.universalIdentifier,
  },
  updateMultipleRecords: {
    universalIdentifier: '20202020-cm0f-4c0f-8c0f-c0aba11cm00f',
    label: 'Update records',
    shortLabel: 'Update',
    icon: 'IconEdit',
    position: 14,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.updateMultipleRecords.universalIdentifier,
  },
  mergeMultipleRecords: {
    universalIdentifier: '20202020-cm10-4c10-8c10-c0aba11cm010',
    label: 'Merge records',
    shortLabel: 'Merge',
    icon: 'IconArrowMerge',
    position: 15,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.mergeMultipleRecords.universalIdentifier,
  },
  exportMultipleRecords: {
    universalIdentifier: '20202020-cm11-4c11-8c11-c0aba11cm011',
    label: 'Export records',
    shortLabel: 'Export',
    icon: 'IconFileExport',
    position: 16,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.exportMultipleRecords.universalIdentifier,
  },
  importRecords: {
    universalIdentifier: '20202020-cm12-4c12-8c12-c0aba11cm012',
    label: 'Import records',
    shortLabel: 'Import',
    icon: 'IconFileImport',
    position: 17,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.importRecords.universalIdentifier,
  },
  exportView: {
    universalIdentifier: '20202020-cm13-4c13-8c13-c0aba11cm013',
    label: 'Export view',
    shortLabel: 'Export',
    icon: 'IconFileExport',
    position: 18,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.exportView.universalIdentifier,
  },
  seeDeletedRecords: {
    universalIdentifier: '20202020-cm14-4c14-8c14-c0aba11cm014',
    label: 'See deleted records',
    shortLabel: 'Deleted records',
    icon: 'IconRotate2',
    position: 19,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.seeDeletedRecords.universalIdentifier,
  },
  createNewView: {
    universalIdentifier: '20202020-cm15-4c15-8c15-c0aba11cm015',
    label: 'Create View',
    shortLabel: 'Create View',
    icon: 'IconLayout',
    position: 20,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.createNewView.universalIdentifier,
  },
  hideDeletedRecords: {
    universalIdentifier: '20202020-cm16-4c16-8c16-c0aba11cm016',
    label: 'Hide deleted records',
    shortLabel: 'Hide deleted',
    icon: 'IconEyeOff',
    position: 21,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.hideDeletedRecords.universalIdentifier,
  },
  goToPeople: {
    universalIdentifier: '20202020-cm17-4c17-8c17-c0aba11cm017',
    label: 'Go to People',
    shortLabel: 'People',
    icon: 'IconUser',
    position: 23,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.goToPeople.universalIdentifier,
  },
  goToCompanies: {
    universalIdentifier: '20202020-cm18-4c18-8c18-c0aba11cm018',
    label: 'Go to Companies',
    shortLabel: 'Companies',
    icon: 'IconBuildingSkyscraper',
    position: 24,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.goToCompanies.universalIdentifier,
  },
  goToDashboards: {
    universalIdentifier: '20202020-cm19-4c19-8c19-c0aba11cm019',
    label: 'Go to Dashboards',
    shortLabel: 'Dashboards',
    icon: 'IconLayoutDashboard',
    position: 25,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.goToDashboards.universalIdentifier,
  },
  goToOpportunities: {
    universalIdentifier: '20202020-cm1a-4c1a-8c1a-c0aba11cm01a',
    label: 'Go to Opportunities',
    shortLabel: 'Opportunities',
    icon: 'IconTargetArrow',
    position: 26,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.goToOpportunities.universalIdentifier,
  },
  goToSettings: {
    universalIdentifier: '20202020-cm1b-4c1b-8c1b-c0aba11cm01b',
    label: 'Go to Settings',
    shortLabel: 'Settings',
    icon: 'IconSettings',
    position: 27,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.goToSettings.universalIdentifier,
  },
  goToTasks: {
    universalIdentifier: '20202020-cm1c-4c1c-8c1c-c0aba11cm01c',
    label: 'Go to Tasks',
    shortLabel: 'Tasks',
    icon: 'IconCheckbox',
    position: 28,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.goToTasks.universalIdentifier,
  },
  goToNotes: {
    universalIdentifier: '20202020-cm1d-4c1d-8c1d-c0aba11cm01d',
    label: 'Go to Notes',
    shortLabel: 'Notes',
    icon: 'IconCheckbox',
    position: 29,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.goToNotes.universalIdentifier,
  },
  editRecordPageLayout: {
    universalIdentifier: '20202020-cm1e-4c1e-8c1e-c0aba11cm01e',
    label: 'Edit Page Layout',
    shortLabel: 'Edit Layout',
    icon: 'IconPencil',
    position: 30,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.editRecordPageLayout.universalIdentifier,
  },
  saveRecordPageLayout: {
    universalIdentifier: '20202020-cm1f-4c1f-8c1f-c0aba11cm01f',
    label: 'Save Page Layout',
    shortLabel: 'Save',
    icon: 'IconDeviceFloppy',
    position: 31,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.saveRecordPageLayout.universalIdentifier,
  },
  cancelRecordPageLayout: {
    universalIdentifier: '20202020-cm20-4c20-8c20-c0aba11cm020',
    label: 'Cancel Edition',
    shortLabel: 'Cancel',
    icon: 'IconCancel',
    position: 32,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.cancelRecordPageLayout.universalIdentifier,
  },
  editDashboardLayout: {
    universalIdentifier: '20202020-cm21-4c21-8c21-c0aba11cm021',
    label: 'Edit Dashboard',
    shortLabel: 'Edit',
    icon: 'IconPencil',
    position: 33,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.editDashboardLayout.universalIdentifier,
  },
  saveDashboardLayout: {
    universalIdentifier: '20202020-cm22-4c22-8c22-c0aba11cm022',
    label: 'Save Dashboard',
    shortLabel: 'Save',
    icon: 'IconDeviceFloppy',
    position: 34,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.saveDashboardLayout.universalIdentifier,
  },
  cancelDashboardLayout: {
    universalIdentifier: '20202020-cm23-4c23-8c23-c0aba11cm023',
    label: 'Cancel Edition',
    shortLabel: 'Cancel',
    icon: 'IconCancel',
    position: 35,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.cancelDashboardLayout.universalIdentifier,
  },
  duplicateDashboard: {
    universalIdentifier: '20202020-cm24-4c24-8c24-c0aba11cm024',
    label: 'Duplicate Dashboard',
    shortLabel: 'Duplicate',
    icon: 'IconCopyPlus',
    position: 36,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.duplicateDashboard.universalIdentifier,
  },
  goToWorkflows: {
    universalIdentifier: '20202020-cm29-4c29-8c29-c0aba11cm029',
    label: 'Go to Workflows',
    shortLabel: 'Workflows',
    icon: 'IconSettingsAutomation',
    position: 41,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.goToWorkflows.universalIdentifier,
  },
  activateWorkflow: {
    universalIdentifier: '20202020-cm2a-4c2a-8c2a-c0aba11cm02a',
    label: 'Activate Workflow',
    shortLabel: 'Activate',
    icon: 'IconPower',
    position: 42,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.activateWorkflow.universalIdentifier,
  },
  deactivateWorkflow: {
    universalIdentifier: '20202020-cm2b-4c2b-8c2b-c0aba11cm02b',
    label: 'Deactivate Workflow',
    shortLabel: 'Deactivate',
    icon: 'IconPlayerPause',
    position: 43,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.deactivateWorkflow.universalIdentifier,
  },
  discardDraftWorkflow: {
    universalIdentifier: '20202020-cm2c-4c2c-8c2c-c0aba11cm02c',
    label: 'Discard Draft',
    shortLabel: 'Discard Draft',
    icon: 'IconNoteOff',
    position: 44,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.discardDraftWorkflow.universalIdentifier,
  },
  testWorkflow: {
    universalIdentifier: '20202020-cm2d-4c2d-8c2d-c0aba11cm02d',
    label: 'Test Workflow',
    shortLabel: 'Test',
    icon: 'IconPlayerPlay',
    position: 45,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.testWorkflow.universalIdentifier,
  },
  seeActiveVersionWorkflow: {
    universalIdentifier: '20202020-cm2e-4c2e-8c2e-c0aba11cm02e',
    label: 'See active version',
    shortLabel: 'See active version',
    icon: 'IconVersions',
    position: 46,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.seeActiveVersionWorkflow.universalIdentifier,
  },
  seeRunsWorkflow: {
    universalIdentifier: '20202020-cm2f-4c2f-8c2f-c0aba11cm02f',
    label: 'See runs',
    shortLabel: 'See runs',
    icon: 'IconHistoryToggle',
    position: 47,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.seeRunsWorkflow.universalIdentifier,
  },
  seeVersionsWorkflow: {
    universalIdentifier: '20202020-cm30-4c30-8c30-c0aba11cm030',
    label: 'See versions history',
    shortLabel: 'See versions',
    icon: 'IconVersions',
    position: 48,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.seeVersionsWorkflow.universalIdentifier,
  },
  addNodeWorkflow: {
    universalIdentifier: '20202020-cm31-4c31-8c31-c0aba11cm031',
    label: 'Add a node',
    shortLabel: 'Add a node',
    icon: 'IconPlus',
    position: 49,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.addNodeWorkflow.universalIdentifier,
  },
  tidyUpWorkflow: {
    universalIdentifier: '20202020-cm32-4c32-8c32-c0aba11cm032',
    label: 'Tidy up workflow',
    shortLabel: 'Tidy up',
    icon: 'IconReorder',
    position: 50,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.tidyUpWorkflow.universalIdentifier,
  },
  duplicateWorkflow: {
    universalIdentifier: '20202020-cm33-4c33-8c33-c0aba11cm033',
    label: 'Duplicate Workflow',
    shortLabel: 'Duplicate',
    icon: 'IconCopy',
    position: 51,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.duplicateWorkflow.universalIdentifier,
  },
  goToRuns: {
    universalIdentifier: '20202020-cm34-4c34-8c34-c0aba11cm034',
    label: 'Go to runs',
    shortLabel: 'See runs',
    icon: 'IconHistoryToggle',
    position: 52,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.goToRuns.universalIdentifier,
  },
  seeVersionWorkflowRun: {
    universalIdentifier: '20202020-cm35-4c35-8c35-c0aba11cm035',
    label: 'See version',
    shortLabel: 'See version',
    icon: 'IconVersions',
    position: 53,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.seeVersionWorkflowRun.universalIdentifier,
  },
  seeWorkflowWorkflowRun: {
    universalIdentifier: '20202020-cm36-4c36-8c36-c0aba11cm036',
    label: 'See workflow',
    shortLabel: 'See workflow',
    icon: 'IconSettingsAutomation',
    position: 54,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.seeWorkflowWorkflowRun.universalIdentifier,
  },
  stopWorkflowRun: {
    universalIdentifier: '20202020-cm37-4c37-8c37-c0aba11cm037',
    label: 'Stop',
    shortLabel: 'Stop',
    icon: 'IconPlayerStop',
    position: 55,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.stopWorkflowRun.universalIdentifier,
  },
  seeRunsWorkflowVersion: {
    universalIdentifier: '20202020-cm38-4c38-8c38-c0aba11cm038',
    label: 'See runs',
    shortLabel: 'See runs',
    icon: 'IconHistoryToggle',
    position: 56,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.seeRunsWorkflowVersion.universalIdentifier,
  },
  seeWorkflowWorkflowVersion: {
    universalIdentifier: '20202020-cm39-4c39-8c39-c0aba11cm039',
    label: 'See workflow',
    shortLabel: 'See workflow',
    icon: 'IconSettingsAutomation',
    position: 57,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.seeWorkflowWorkflowVersion.universalIdentifier,
  },
  useAsDraftWorkflowVersion: {
    universalIdentifier: '20202020-cm3a-4c3a-8c3a-c0aba11cm03a',
    label: 'Use as draft',
    shortLabel: 'Use as draft',
    icon: 'IconPencil',
    position: 58,
    isPinned: true,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.useAsDraftWorkflowVersion.universalIdentifier,
  },
  seeVersionsWorkflowVersion: {
    universalIdentifier: '20202020-cm3b-4c3b-8c3b-c0aba11cm03b',
    label: 'See versions history',
    shortLabel: 'See versions',
    icon: 'IconVersions',
    position: 59,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.RECORD_SELECTION,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.seeVersionsWorkflowVersion.universalIdentifier,
  },
  searchRecords: {
    universalIdentifier: '20202020-cm25-4c25-8c25-c0aba11cm025',
    label: 'Search records',
    shortLabel: 'Search',
    icon: 'IconSearch',
    position: 60,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.searchRecords.universalIdentifier,
  },
  searchRecordsFallback: {
    universalIdentifier: '20202020-cm26-4c26-8c26-c0aba11cm026',
    label: 'Search records',
    shortLabel: 'Search',
    icon: 'IconSearch',
    position: 61,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.searchRecordsFallback.universalIdentifier,
  },
  askAi: {
    universalIdentifier: '20202020-cm27-4c27-8c27-c0aba11cm027',
    label: 'Ask AI',
    shortLabel: 'Ask AI',
    icon: 'IconSparkles',
    position: 62,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.askAi.universalIdentifier,
  },
  viewPreviousAiChats: {
    universalIdentifier: '20202020-cm28-4c28-8c28-c0aba11cm028',
    label: 'View Previous AI Chats',
    shortLabel: 'Previous AI Chats',
    icon: 'IconHistory',
    position: 63,
    isPinned: false,
    availabilityType: CommandMenuItemAvailabilityType.GLOBAL,
    frontComponentUniversalIdentifier:
      STANDARD_FRONT_COMPONENTS.viewPreviousAiChats.universalIdentifier,
  },
} as const;
