import { type PermissionFlagType } from 'twenty-shared/constants';

import { type PermissionFlagDefinitionPermissionType } from 'src/engine/metadata-modules/permission-flag-definition/constants/permission-flag-definition-permission-type.constant';

// Each entry maps a PermissionFlagType enum key to a stable universalIdentifier
// plus the metadata used to render the flag in the Roles UI. Adding a new
// built-in flag requires:
//   1. Adding it to PermissionFlagType in twenty-shared/src/constants/PermissionFlagType.ts
//   2. Adding an entry below with a fresh universalIdentifier
//   3. Running the upgrade migration so existing workspaces seed the new row.
// The Record<PermissionFlagType, ...> satisfies clause below makes step 2 a
// compile-time requirement — adding a new enum value without an entry will fail typecheck.

export type StandardPermissionFlagDefinitionMetadata = {
  universalIdentifier: string;
  label: string;
  description: string | null;
  iconKey: string | null;
  permissionType: PermissionFlagDefinitionPermissionType;
  isRelevantForAgents: boolean;
  isRelevantForUsers: boolean;
  isRelevantForApiKeys: boolean;
};

export const STANDARD_PERMISSION_FLAG_DEFINITION = {
  API_KEYS_AND_WEBHOOKS: {
    universalIdentifier: '20202021-1001-4001-9001-000000000001',
    label: 'API Keys and Webhooks',
    description: 'Manage API keys and webhooks',
    iconKey: 'IconApi',
    permissionType: 'settings',
    isRelevantForAgents: false,
    isRelevantForUsers: true,
    isRelevantForApiKeys: false,
  },
  WORKSPACE: {
    universalIdentifier: '20202021-1001-4001-9001-000000000002',
    label: 'Workspace',
    description: 'Manage workspace settings',
    iconKey: 'IconBuildingSkyscraper',
    permissionType: 'settings',
    isRelevantForAgents: false,
    isRelevantForUsers: true,
    isRelevantForApiKeys: false,
  },
  WORKSPACE_MEMBERS: {
    universalIdentifier: '20202021-1001-4001-9001-000000000003',
    label: 'Workspace Members',
    description: 'Manage workspace members',
    iconKey: 'IconUsers',
    permissionType: 'settings',
    isRelevantForAgents: false,
    isRelevantForUsers: true,
    isRelevantForApiKeys: false,
  },
  ROLES: {
    universalIdentifier: '20202021-1001-4001-9001-000000000004',
    label: 'Roles',
    description: 'Manage roles and permissions',
    iconKey: 'IconShieldLock',
    permissionType: 'settings',
    isRelevantForAgents: false,
    isRelevantForUsers: true,
    isRelevantForApiKeys: false,
  },
  DATA_MODEL: {
    universalIdentifier: '20202021-1001-4001-9001-000000000005',
    label: 'Data Model',
    description: 'Manage objects and fields',
    iconKey: 'IconHierarchy2',
    permissionType: 'settings',
    isRelevantForAgents: false,
    isRelevantForUsers: true,
    isRelevantForApiKeys: false,
  },
  SECURITY: {
    universalIdentifier: '20202021-1001-4001-9001-000000000006',
    label: 'Security',
    description: 'Manage security settings',
    iconKey: 'IconLock',
    permissionType: 'settings',
    isRelevantForAgents: false,
    isRelevantForUsers: true,
    isRelevantForApiKeys: false,
  },
  WORKFLOWS: {
    universalIdentifier: '20202021-1001-4001-9001-000000000007',
    label: 'Workflows',
    description: 'Manage workflows and logic functions',
    iconKey: 'IconSettingsAutomation',
    permissionType: 'settings',
    isRelevantForAgents: false,
    isRelevantForUsers: true,
    isRelevantForApiKeys: false,
  },
  IMPERSONATE: {
    universalIdentifier: '20202021-1001-4001-9001-000000000008',
    label: 'Impersonate',
    description: 'Impersonate other workspace members',
    iconKey: 'IconUser',
    permissionType: 'settings',
    isRelevantForAgents: false,
    isRelevantForUsers: true,
    isRelevantForApiKeys: false,
  },
  SSO_BYPASS: {
    universalIdentifier: '20202021-1001-4001-9001-000000000009',
    label: 'SSO Bypass',
    description: 'Bypass single sign-on requirements',
    iconKey: 'IconKey',
    permissionType: 'settings',
    isRelevantForAgents: false,
    isRelevantForUsers: true,
    isRelevantForApiKeys: false,
  },
  APPLICATIONS: {
    universalIdentifier: '20202021-1001-4001-9001-00000000000a',
    label: 'Applications',
    description: 'Manage installed applications',
    iconKey: 'IconApps',
    permissionType: 'settings',
    isRelevantForAgents: false,
    isRelevantForUsers: true,
    isRelevantForApiKeys: false,
  },
  MARKETPLACE_APPS: {
    universalIdentifier: '20202021-1001-4001-9001-00000000000b',
    label: 'Marketplace Apps',
    description: 'Browse and install marketplace apps',
    iconKey: 'IconShoppingBag',
    permissionType: 'settings',
    isRelevantForAgents: false,
    isRelevantForUsers: true,
    isRelevantForApiKeys: false,
  },
  LAYOUTS: {
    universalIdentifier: '20202021-1001-4001-9001-00000000000c',
    label: 'Layouts',
    description: 'Manage page layouts',
    iconKey: 'IconLayout',
    permissionType: 'settings',
    isRelevantForAgents: false,
    isRelevantForUsers: true,
    isRelevantForApiKeys: false,
  },
  BILLING: {
    universalIdentifier: '20202021-1001-4001-9001-00000000000d',
    label: 'Billing',
    description: 'Manage billing and subscriptions',
    iconKey: 'IconCreditCard',
    permissionType: 'settings',
    isRelevantForAgents: false,
    isRelevantForUsers: true,
    isRelevantForApiKeys: false,
  },
  AI_SETTINGS: {
    universalIdentifier: '20202021-1001-4001-9001-00000000000e',
    label: 'AI Settings',
    description: 'Manage AI provider settings',
    iconKey: 'IconBrain',
    permissionType: 'settings',
    isRelevantForAgents: false,
    isRelevantForUsers: true,
    isRelevantForApiKeys: false,
  },
  AI: {
    universalIdentifier: '20202021-1001-4001-9001-00000000000f',
    label: 'AI',
    description: 'Use AI features',
    iconKey: 'IconSparkles',
    permissionType: 'tool',
    isRelevantForAgents: true,
    isRelevantForUsers: true,
    isRelevantForApiKeys: true,
  },
  VIEWS: {
    universalIdentifier: '20202021-1001-4001-9001-000000000010',
    label: 'Views',
    description: 'Read and write views',
    iconKey: 'IconLayoutGrid',
    permissionType: 'tool',
    isRelevantForAgents: true,
    isRelevantForUsers: true,
    isRelevantForApiKeys: true,
  },
  UPLOAD_FILE: {
    universalIdentifier: '20202021-1001-4001-9001-000000000011',
    label: 'Upload File',
    description: 'Upload files to the workspace',
    iconKey: 'IconUpload',
    permissionType: 'tool',
    isRelevantForAgents: true,
    isRelevantForUsers: true,
    isRelevantForApiKeys: true,
  },
  DOWNLOAD_FILE: {
    universalIdentifier: '20202021-1001-4001-9001-000000000012',
    label: 'Download File',
    description: 'Download files from the workspace',
    iconKey: 'IconDownload',
    permissionType: 'tool',
    isRelevantForAgents: true,
    isRelevantForUsers: true,
    isRelevantForApiKeys: true,
  },
  SEND_EMAIL_TOOL: {
    universalIdentifier: '20202021-1001-4001-9001-000000000013',
    label: 'Send Email',
    description: 'Send emails on behalf of users',
    iconKey: 'IconAt',
    permissionType: 'tool',
    isRelevantForAgents: true,
    isRelevantForUsers: false,
    isRelevantForApiKeys: false,
  },
  HTTP_REQUEST_TOOL: {
    universalIdentifier: '20202021-1001-4001-9001-000000000014',
    label: 'HTTP Request',
    description: 'Make outbound HTTP requests',
    iconKey: 'IconApi',
    permissionType: 'tool',
    isRelevantForAgents: true,
    isRelevantForUsers: false,
    isRelevantForApiKeys: false,
  },
  CODE_INTERPRETER_TOOL: {
    universalIdentifier: '20202021-1001-4001-9001-000000000015',
    label: 'Code Interpreter',
    description: 'Run code to analyze files and data',
    iconKey: 'IconCode',
    permissionType: 'tool',
    isRelevantForAgents: true,
    isRelevantForUsers: true,
    isRelevantForApiKeys: false,
  },
  IMPORT_CSV: {
    universalIdentifier: '20202021-1001-4001-9001-000000000016',
    label: 'Import CSV',
    description: 'Import records from CSV files',
    iconKey: 'IconFileImport',
    permissionType: 'tool',
    isRelevantForAgents: false,
    isRelevantForUsers: true,
    isRelevantForApiKeys: false,
  },
  EXPORT_CSV: {
    universalIdentifier: '20202021-1001-4001-9001-000000000017',
    label: 'Export CSV',
    description: 'Export records to CSV files',
    iconKey: 'IconFileExport',
    permissionType: 'tool',
    isRelevantForAgents: false,
    isRelevantForUsers: true,
    isRelevantForApiKeys: false,
  },
  CONNECTED_ACCOUNTS: {
    universalIdentifier: '20202021-1001-4001-9001-000000000018',
    label: 'Connected Accounts',
    description: 'Read connected email and calendar accounts',
    iconKey: 'IconMail',
    permissionType: 'tool',
    isRelevantForAgents: true,
    isRelevantForUsers: false,
    isRelevantForApiKeys: false,
  },
  PROFILE_INFORMATION: {
    universalIdentifier: '20202021-1001-4001-9001-000000000019',
    label: 'Profile Information',
    description: 'Read profile information',
    iconKey: 'IconUser',
    permissionType: 'tool',
    isRelevantForAgents: true,
    isRelevantForUsers: false,
    isRelevantForApiKeys: false,
  },
} as const satisfies Record<
  PermissionFlagType,
  StandardPermissionFlagDefinitionMetadata
>;
