import { getRecordFromRecordNode } from '@/object-record/cache/utils/getRecordFromRecordNode';
import { type ObjectRecord } from '@/object-record/types/ObjectRecord';
import { isDefined } from 'twenty-shared/utils';

const FIND_MANY_COMPANIES_WITH_RELATION_QUERY_RESULT = {
  data: {
    companies: {
      __typename: 'CompanyConnection',
      totalCount: 13,
      pageInfo: {
        __typename: 'PageInfo',
        hasNextPage: false,
        hasPreviousPage: false,
        startCursor:
          'eyJwb3NpdGlvbiI6MSwiaWQiOiIyMDIwMjAyMC0zZWMzLTRmZTMtODk5Ny1iNzZhYTBiZmE0MDgifQ==',
        endCursor:
          'eyJwb3NpdGlvbiI6MTMsImlkIjoiMjAyMDIwMjAtMTQ1NS00YzU3LWFmYWYtZGQ1ZGMwODYzNjFkIn0=',
      },
      edges: [
        {
          __typename: 'CompanyEdge',
          cursor:
            'eyJwb3NpdGlvbiI6MSwiaWQiOiIyMDIwMjAyMC0zZWMzLTRmZTMtODk5Ny1iNzZhYTBiZmE0MDgifQ==',
          node: {
            __typename: 'Company',
            accountOwner: null,
            createdAt: '2025-02-16T08:21:51.715Z',
            deletedAt: null,
            employees: null,
            id: '20202020-3ec3-4fe3-8997-b76aa0bfa408',
            name: 'Linkedin',
            position: 1,
            address: {
              __typename: 'Address',
              addressStreet1: 'Eutaw Street',
              addressStreet2: null,
              addressCity: 'Dublin',
              addressState: null,
              addressCountry: 'Ireland',
              addressPostcode: null,
              addressLat: null,
              addressLng: null,
            },
            createdBy: {
              __typename: 'Actor',
              source: 'MANUAL',
              workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
              name: 'Tim Apple',
              context: {},
            },
            domainName: {
              __typename: 'Links',
              primaryLinkUrl: 'https://linkedin.com',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            linkedinLink: {
              __typename: 'Links',
              primaryLinkUrl: '',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            noteTargets: {
              __typename: 'NoteTargetConnection',
              edges: [],
            },
            taskTargets: {
              __typename: 'TaskTargetConnection',
              edges: [],
            },
            opportunities: {
              __typename: 'OpportunityConnection',
              edges: [
                {
                  __typename: 'OpportunityEdge',
                  node: {
                    __typename: 'Opportunity',
                    closeDate: '2025-02-16T08:21:51.764Z',
                    companyId: '20202020-3ec3-4fe3-8997-b76aa0bfa408',
                    createdAt: '2025-02-16T08:21:51.715Z',
                    deletedAt: null,
                    id: '20202020-be10-422b-a663-16bd3c2228e1',
                    name: 'Opportunity 1',
                    pointOfContactId: '20202020-1c0e-494c-a1b6-85b1c6fefaa5',
                    position: 1,
                    stage: 'NEW',
                    updatedAt: '2025-02-16T08:21:51.715Z',
                    amount: {
                      __typename: 'Currency',
                      amountMicros: 100000,
                      currencyCode: 'USD',
                    },
                    createdBy: {
                      __typename: 'Actor',
                      source: 'MANUAL',
                      workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
                      name: 'Tim Cook',
                      context: {},
                    },
                  },
                },
              ],
            },
            people: {
              __typename: 'PersonConnection',
              edges: [
                {
                  __typename: 'PersonEdge',
                  node: {
                    __typename: 'Person',
                    avatarUrl: '',
                    city: 'Seattle',
                    companyId: '20202020-3ec3-4fe3-8997-b76aa0bfa408',
                    createdAt: '2025-02-16T08:21:51.715Z',
                    deletedAt: null,
                    id: '20202020-1c0e-494c-a1b6-85b1c6fefaa5',
                    intro: '',
                    jobTitle: '',
                    performanceRating: null,
                    position: 1,
                    updatedAt: '2025-02-16T08:21:51.715Z',
                    workPreference: null,
                    createdBy: {
                      __typename: 'Actor',
                      source: 'MANUAL',
                      workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
                      name: 'Tim Apple',
                      context: {},
                    },
                    emails: {
                      __typename: 'Emails',
                      primaryEmail: 'christoph.calisto@linkedin.com',
                      additionalEmails: null,
                    },
                    linkedinLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                    name: {
                      __typename: 'FullName',
                      firstName: 'Christoph',
                      lastName: 'Callisto',
                    },
                    phones: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '789012345',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    whatsapp: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '789012345',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    xLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                  },
                },
                {
                  __typename: 'PersonEdge',
                  node: {
                    __typename: 'Person',
                    avatarUrl: '',
                    city: 'Los Angeles',
                    companyId: '20202020-3ec3-4fe3-8997-b76aa0bfa408',
                    createdAt: '2025-02-16T08:21:51.715Z',
                    deletedAt: null,
                    id: '20202020-ac73-4797-824e-87a1f5aea9e0',
                    intro: '',
                    jobTitle: '',
                    performanceRating: null,
                    position: 2,
                    updatedAt: '2025-02-16T08:21:51.715Z',
                    workPreference: null,
                    createdBy: {
                      __typename: 'Actor',
                      source: 'MANUAL',
                      workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
                      name: 'Tim Apple',
                      context: {},
                    },
                    emails: {
                      __typename: 'Emails',
                      primaryEmail: 'sylvie.palmer@linkedin.com',
                      additionalEmails: null,
                    },
                    linkedinLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                    name: {
                      __typename: 'FullName',
                      firstName: 'Sylvie',
                      lastName: 'Palmer',
                    },
                    phones: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '780123456',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    whatsapp: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '780123456',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    xLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                  },
                },
              ],
            },
          },
        },
        {
          __typename: 'CompanyEdge',
          cursor:
            'eyJwb3NpdGlvbiI6MiwiaWQiOiIyMDIwMjAyMC01ZDgxLTQ2ZDYtYmY4My1mN2ZkMzNlYTYxMDIifQ==',
          node: {
            __typename: 'Company',
            accountOwner: null,
            createdAt: '2025-02-16T08:21:51.715Z',
            deletedAt: null,
            employees: null,
            id: '20202020-5d81-46d6-bf83-f7fd33ea6102',
            name: 'Facebook',
            position: 2,
            people: {
              __typename: 'PersonConnection',
              edges: [],
            },
            address: {
              __typename: 'Address',
              addressStreet1: null,
              addressStreet2: null,
              addressCity: null,
              addressState: null,
              addressCountry: null,
              addressPostcode: null,
              addressLat: null,
              addressLng: null,
            },
            createdBy: {
              __typename: 'Actor',
              source: 'MANUAL',
              workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
              name: 'Tim Apple',
              context: {},
            },
            domainName: {
              __typename: 'Links',
              primaryLinkUrl: 'https://facebook.com',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            linkedinLink: {
              __typename: 'Links',
              primaryLinkUrl: '',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            noteTargets: {
              __typename: 'NoteTargetConnection',
              edges: [],
            },
            taskTargets: {
              __typename: 'TaskTargetConnection',
              edges: [],
            },
            opportunities: {
              __typename: 'OpportunityConnection',
              edges: [
                {
                  __typename: 'OpportunityEdge',
                  node: {
                    __typename: 'Opportunity',
                    closeDate: '2025-02-16T08:21:51.764Z',
                    companyId: '20202020-5d81-46d6-bf83-f7fd33ea6102',
                    createdAt: '2025-02-16T08:21:51.715Z',
                    deletedAt: null,
                    id: '20202020-0543-4cc2-9f96-95cc699960f2',
                    name: 'Opportunity 2',
                    pointOfContactId: '20202020-f517-42fd-80ae-14173b3b70ae',
                    position: 2,
                    stage: 'MEETING',
                    updatedAt: '2025-02-16T08:21:51.715Z',
                    amount: {
                      __typename: 'Currency',
                      amountMicros: 2000000,
                      currencyCode: 'USD',
                    },
                    createdBy: {
                      __typename: 'Actor',
                      source: 'MANUAL',
                      workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
                      name: 'Tim Cook',
                      context: {},
                    },
                  },
                },
              ],
            },
          },
        },
        {
          __typename: 'CompanyEdge',
          cursor:
            'eyJwb3NpdGlvbiI6MywiaWQiOiIyMDIwMjAyMC0wNzEzLTQwYTUtODIxNi04MjgwMjQwMWQzM2UifQ==',
          node: {
            __typename: 'Company',
            accountOwner: null,
            createdAt: '2025-02-16T08:21:51.715Z',
            deletedAt: null,
            employees: null,
            id: '20202020-0713-40a5-8216-82802401d33e',
            name: 'Anthropic',
            position: 3,
            opportunities: {
              __typename: 'OpportunityConnection',
              edges: [],
            },
            address: {
              __typename: 'Address',
              addressStreet1: '548 Market Street',
              addressStreet2: null,
              addressCity: 'San Francisco',
              addressState: null,
              addressCountry: 'United States',
              addressPostcode: '94104',
              addressLat: null,
              addressLng: null,
            },
            createdBy: {
              __typename: 'Actor',
              source: 'MANUAL',
              workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
              name: 'Tim Apple',
              context: {},
            },
            domainName: {
              __typename: 'Links',
              primaryLinkUrl: 'https://anthropic.com',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            linkedinLink: {
              __typename: 'Links',
              primaryLinkUrl: '',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            noteTargets: {
              __typename: 'NoteTargetConnection',
              edges: [],
            },
            taskTargets: {
              __typename: 'TaskTargetConnection',
              edges: [],
            },
            people: {
              __typename: 'PersonConnection',
              edges: [
                {
                  __typename: 'PersonEdge',
                  node: {
                    __typename: 'Person',
                    avatarUrl: '',
                    city: 'Seattle',
                    companyId: '20202020-0713-40a5-8216-82802401d33e',
                    createdAt: '2025-02-16T08:21:51.715Z',
                    deletedAt: null,
                    id: '20202020-f517-42fd-80ae-14173b3b70ae',
                    intro: '',
                    jobTitle: '',
                    performanceRating: null,
                    position: 3,
                    updatedAt: '2025-02-16T08:21:51.715Z',
                    workPreference: null,
                    createdBy: {
                      __typename: 'Actor',
                      source: 'MANUAL',
                      workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
                      name: 'Tim Apple',
                      context: {},
                    },
                    emails: {
                      __typename: 'Emails',
                      primaryEmail: 'christopher.gonzalez@anthropic.com',
                      additionalEmails: null,
                    },
                    linkedinLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                    name: {
                      __typename: 'FullName',
                      firstName: 'Christopher',
                      lastName: 'Gonzalez',
                    },
                    phones: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '789012345',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    whatsapp: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '789012345',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    xLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                  },
                },
                {
                  __typename: 'PersonEdge',
                  node: {
                    __typename: 'Person',
                    avatarUrl: '',
                    city: 'Los Angeles',
                    companyId: '20202020-0713-40a5-8216-82802401d33e',
                    createdAt: '2025-02-16T08:21:51.715Z',
                    deletedAt: null,
                    id: '20202020-eee1-4690-ad2c-8619e5b56a2e',
                    intro: '',
                    jobTitle: '',
                    performanceRating: null,
                    position: 4,
                    updatedAt: '2025-02-16T08:21:51.715Z',
                    workPreference: null,
                    createdBy: {
                      __typename: 'Actor',
                      source: 'MANUAL',
                      workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
                      name: 'Tim Apple',
                      context: {},
                    },
                    emails: {
                      __typename: 'Emails',
                      primaryEmail: 'ashley.parker@anthropic.com',
                      additionalEmails: null,
                    },
                    linkedinLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                    name: {
                      __typename: 'FullName',
                      firstName: 'Ashley',
                      lastName: 'Parker',
                    },
                    phones: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '780123456',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    whatsapp: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '780123456',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    xLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                  },
                },
              ],
            },
          },
        },
        {
          __typename: 'CompanyEdge',
          cursor:
            'eyJwb3NpdGlvbiI6NCwiaWQiOiIyMDIwMjAyMC1lZDg5LTQxM2EtYjMxYS05NjI5ODZlNjdiYjQifQ==',
          node: {
            __typename: 'Company',
            accountOwner: null,
            createdAt: '2025-02-16T08:21:51.715Z',
            deletedAt: null,
            employees: null,
            id: '20202020-ed89-413a-b31a-962986e67bb4',
            name: 'Microsoft',
            position: 4,
            address: {
              __typename: 'Address',
              addressStreet1: null,
              addressStreet2: null,
              addressCity: null,
              addressState: null,
              addressCountry: null,
              addressPostcode: null,
              addressLat: null,
              addressLng: null,
            },
            createdBy: {
              __typename: 'Actor',
              source: 'MANUAL',
              workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
              name: 'Tim Apple',
              context: {},
            },
            domainName: {
              __typename: 'Links',
              primaryLinkUrl: 'https://microsoft.com',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            linkedinLink: {
              __typename: 'Links',
              primaryLinkUrl: '',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            noteTargets: {
              __typename: 'NoteTargetConnection',
              edges: [],
            },
            taskTargets: {
              __typename: 'TaskTargetConnection',
              edges: [],
            },
            opportunities: {
              __typename: 'OpportunityConnection',
              edges: [
                {
                  __typename: 'OpportunityEdge',
                  node: {
                    __typename: 'Opportunity',
                    closeDate: '2025-02-16T08:21:51.764Z',
                    companyId: '20202020-ed89-413a-b31a-962986e67bb4',
                    createdAt: '2025-02-16T08:21:51.715Z',
                    deletedAt: null,
                    id: '20202020-2f89-406f-90ea-180f433b2445',
                    name: 'Opportunity 3',
                    pointOfContactId: '20202020-6784-4449-afdf-dc62cb8702f2',
                    position: 3,
                    stage: 'PROPOSAL',
                    updatedAt: '2025-02-16T08:21:51.715Z',
                    amount: {
                      __typename: 'Currency',
                      amountMicros: 300000,
                      currencyCode: 'USD',
                    },
                    createdBy: {
                      __typename: 'Actor',
                      source: 'MANUAL',
                      workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
                      name: 'Tim Cook',
                      context: {},
                    },
                  },
                },
                {
                  __typename: 'OpportunityEdge',
                  node: {
                    __typename: 'Opportunity',
                    closeDate: '2025-02-16T08:21:51.764Z',
                    companyId: '20202020-ed89-413a-b31a-962986e67bb4',
                    createdAt: '2025-02-16T08:21:51.715Z',
                    deletedAt: null,
                    id: '20202020-35b1-4045-9cde-42f715148954',
                    name: 'Opportunity 4',
                    pointOfContactId: '20202020-80f1-4dff-b570-a74942528de3',
                    position: 4,
                    stage: 'PROPOSAL',
                    updatedAt: '2025-02-16T08:21:51.715Z',
                    amount: {
                      __typename: 'Currency',
                      amountMicros: 4000000,
                      currencyCode: 'USD',
                    },
                    createdBy: {
                      __typename: 'Actor',
                      source: 'MANUAL',
                      workspaceMemberId: null,
                      name: '',
                      context: {},
                    },
                  },
                },
              ],
            },
            people: {
              __typename: 'PersonConnection',
              edges: [
                {
                  __typename: 'PersonEdge',
                  node: {
                    __typename: 'Person',
                    avatarUrl: '',
                    city: 'Seattle',
                    companyId: '20202020-ed89-413a-b31a-962986e67bb4',
                    createdAt: '2025-02-16T08:21:51.715Z',
                    deletedAt: null,
                    id: '20202020-6784-4449-afdf-dc62cb8702f2',
                    intro: '',
                    jobTitle: '',
                    performanceRating: null,
                    position: 5,
                    updatedAt: '2025-02-16T08:21:51.715Z',
                    workPreference: null,
                    createdBy: {
                      __typename: 'Actor',
                      source: 'MANUAL',
                      workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
                      name: 'Tim Apple',
                      context: {},
                    },
                    emails: {
                      __typename: 'Emails',
                      primaryEmail: 'nicholas.wright@microsoft.com',
                      additionalEmails: null,
                    },
                    linkedinLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                    name: {
                      __typename: 'FullName',
                      firstName: 'Nicholas',
                      lastName: 'Wright',
                    },
                    phones: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '781234567',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    whatsapp: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '781234567',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    xLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                  },
                },
                {
                  __typename: 'PersonEdge',
                  node: {
                    __typename: 'Person',
                    avatarUrl: '',
                    city: 'New York',
                    companyId: '20202020-ed89-413a-b31a-962986e67bb4',
                    createdAt: '2025-02-16T08:21:51.715Z',
                    deletedAt: null,
                    id: '20202020-490f-4466-8391-733cfd66a0c8',
                    intro: '',
                    jobTitle: '',
                    performanceRating: null,
                    position: 6,
                    updatedAt: '2025-02-16T08:21:51.715Z',
                    workPreference: null,
                    createdBy: {
                      __typename: 'Actor',
                      source: 'MANUAL',
                      workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
                      name: 'Tim Apple',
                      context: {},
                    },
                    emails: {
                      __typename: 'Emails',
                      primaryEmail: 'isabella.scott@microsoft.com',
                      additionalEmails: null,
                    },
                    linkedinLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                    name: {
                      __typename: 'FullName',
                      firstName: 'Isabella',
                      lastName: 'Scott',
                    },
                    phones: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '782345678',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    whatsapp: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '782345678',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    xLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                  },
                },
                {
                  __typename: 'PersonEdge',
                  node: {
                    __typename: 'Person',
                    avatarUrl: '',
                    city: 'Seattle',
                    companyId: '20202020-ed89-413a-b31a-962986e67bb4',
                    createdAt: '2025-02-16T08:21:51.715Z',
                    deletedAt: null,
                    id: '20202020-80f1-4dff-b570-a74942528de3',
                    intro: '',
                    jobTitle: '',
                    performanceRating: null,
                    position: 7,
                    updatedAt: '2025-02-16T08:21:51.715Z',
                    workPreference: null,
                    createdBy: {
                      __typename: 'Actor',
                      source: 'MANUAL',
                      workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
                      name: 'Tim Apple',
                      context: {},
                    },
                    emails: {
                      __typename: 'Emails',
                      primaryEmail: 'matthew.green@microsoft.com',
                      additionalEmails: null,
                    },
                    linkedinLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                    name: {
                      __typename: 'FullName',
                      firstName: 'Matthew',
                      lastName: 'Green',
                    },
                    phones: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '783456789',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    whatsapp: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '783456789',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    xLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                  },
                },
              ],
            },
          },
        },
        {
          __typename: 'CompanyEdge',
          cursor:
            'eyJwb3NpdGlvbiI6NSwiaWQiOiIyMDIwMjAyMC0xNzFlLTRiY2MtOWNmNy00MzQ0OGQ2ZmIyNzgifQ==',
          node: {
            __typename: 'Company',
            accountOwner: null,
            createdAt: '2025-02-16T08:21:51.715Z',
            deletedAt: null,
            employees: null,
            id: '20202020-171e-4bcc-9cf7-43448d6fb278',
            name: 'Airbnb',
            position: 5,
            opportunities: {
              __typename: 'OpportunityConnection',
              edges: [],
            },
            address: {
              __typename: 'Address',
              addressStreet1: '888 Brannan St',
              addressStreet2: null,
              addressCity: 'San Francisco',
              addressState: 'CA',
              addressCountry: 'United States',
              addressPostcode: '94103',
              addressLat: null,
              addressLng: null,
            },
            createdBy: {
              __typename: 'Actor',
              source: 'MANUAL',
              workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
              name: 'Tim Apple',
              context: {},
            },
            domainName: {
              __typename: 'Links',
              primaryLinkUrl: 'https://airbnb.com',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            linkedinLink: {
              __typename: 'Links',
              primaryLinkUrl: '',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            noteTargets: {
              __typename: 'NoteTargetConnection',
              edges: [],
            },
            taskTargets: {
              __typename: 'TaskTargetConnection',
              edges: [],
            },
            people: {
              __typename: 'PersonConnection',
              edges: [
                {
                  __typename: 'PersonEdge',
                  node: {
                    __typename: 'Person',
                    avatarUrl: '',
                    city: 'New York',
                    companyId: '20202020-171e-4bcc-9cf7-43448d6fb278',
                    createdAt: '2025-02-16T08:21:51.715Z',
                    deletedAt: null,
                    id: '20202020-338b-46df-8811-fa08c7d19d35',
                    intro: '',
                    jobTitle: '',
                    performanceRating: null,
                    position: 8,
                    updatedAt: '2025-02-16T08:21:51.715Z',
                    workPreference: null,
                    createdBy: {
                      __typename: 'Actor',
                      source: 'MANUAL',
                      workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
                      name: 'Tim Apple',
                      context: {},
                    },
                    emails: {
                      __typename: 'Emails',
                      primaryEmail: 'elizabeth.baker@airbnb.com',
                      additionalEmails: null,
                    },
                    linkedinLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                    name: {
                      __typename: 'FullName',
                      firstName: 'Elizabeth',
                      lastName: 'Baker',
                    },
                    phones: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '784567890',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    whatsapp: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '784567890',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    xLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                  },
                },
                {
                  __typename: 'PersonEdge',
                  node: {
                    __typename: 'Person',
                    avatarUrl: '',
                    city: 'San Francisco',
                    companyId: '20202020-171e-4bcc-9cf7-43448d6fb278',
                    createdAt: '2025-02-16T08:21:51.715Z',
                    deletedAt: null,
                    id: '20202020-64ad-4b0e-bbfd-e9fd795b7016',
                    intro: '',
                    jobTitle: '',
                    performanceRating: null,
                    position: 9,
                    updatedAt: '2025-02-16T08:21:51.715Z',
                    workPreference: null,
                    createdBy: {
                      __typename: 'Actor',
                      source: 'MANUAL',
                      workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
                      name: 'Tim Apple',
                      context: {},
                    },
                    emails: {
                      __typename: 'Emails',
                      primaryEmail: 'christopher.nelson@airbnb.com',
                      additionalEmails: null,
                    },
                    linkedinLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                    name: {
                      __typename: 'FullName',
                      firstName: 'Christopher',
                      lastName: 'Nelson',
                    },
                    phones: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '785678901',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    whatsapp: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '785678901',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    xLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                  },
                },
                {
                  __typename: 'PersonEdge',
                  node: {
                    __typename: 'Person',
                    avatarUrl: '',
                    city: 'New York',
                    companyId: '20202020-171e-4bcc-9cf7-43448d6fb278',
                    createdAt: '2025-02-16T08:21:51.715Z',
                    deletedAt: null,
                    id: '20202020-5d54-41b7-ba36-f0d20e1417ae',
                    intro: '',
                    jobTitle: '',
                    performanceRating: null,
                    position: 10,
                    updatedAt: '2025-02-16T08:21:51.715Z',
                    workPreference: null,
                    createdBy: {
                      __typename: 'Actor',
                      source: 'MANUAL',
                      workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
                      name: 'Tim Apple',
                      context: {},
                    },
                    emails: {
                      __typename: 'Emails',
                      primaryEmail: 'avery.carter@airbnb.com',
                      additionalEmails: null,
                    },
                    linkedinLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                    name: {
                      __typename: 'FullName',
                      firstName: 'Avery',
                      lastName: 'Carter',
                    },
                    phones: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '786789012',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    whatsapp: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '786789012',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    xLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                  },
                },
              ],
            },
          },
        },
        {
          __typename: 'CompanyEdge',
          cursor:
            'eyJwb3NpdGlvbiI6NiwiaWQiOiIyMDIwMjAyMC1jMjFlLTRlYzItODczYi1kZTQyNjRkODkwMjUifQ==',
          node: {
            __typename: 'Company',
            accountOwner: null,
            createdAt: '2025-02-16T08:21:51.715Z',
            deletedAt: null,
            employees: null,
            id: '20202020-c21e-4ec2-873b-de4264d89025',
            name: 'Google',
            position: 6,
            opportunities: {
              __typename: 'OpportunityConnection',
              edges: [],
            },
            address: {
              __typename: 'Address',
              addressStreet1: '760 Market St',
              addressStreet2: 'Floor 10',
              addressCity: 'San Francisco',
              addressState: null,
              addressCountry: 'United States',
              addressPostcode: '94102',
              addressLat: null,
              addressLng: null,
            },
            createdBy: {
              __typename: 'Actor',
              source: 'MANUAL',
              workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
              name: 'Tim Apple',
              context: {},
            },
            domainName: {
              __typename: 'Links',
              primaryLinkUrl: 'https://google.com',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            linkedinLink: {
              __typename: 'Links',
              primaryLinkUrl: '',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            noteTargets: {
              __typename: 'NoteTargetConnection',
              edges: [],
            },
            taskTargets: {
              __typename: 'TaskTargetConnection',
              edges: [],
            },
            people: {
              __typename: 'PersonConnection',
              edges: [
                {
                  __typename: 'PersonEdge',
                  node: {
                    __typename: 'Person',
                    avatarUrl: '',
                    city: 'Los Angeles',
                    companyId: '20202020-c21e-4ec2-873b-de4264d89025',
                    createdAt: '2025-02-16T08:21:51.715Z',
                    deletedAt: null,
                    id: '20202020-623d-41fe-92e7-dd45b7c568e1',
                    intro: '',
                    jobTitle: '',
                    performanceRating: null,
                    position: 11,
                    updatedAt: '2025-02-16T08:21:51.715Z',
                    workPreference: null,
                    createdBy: {
                      __typename: 'Actor',
                      source: 'MANUAL',
                      workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
                      name: 'Tim Apple',
                      context: {},
                    },
                    emails: {
                      __typename: 'Emails',
                      primaryEmail: 'ethan.mitchell@google.com',
                      additionalEmails: null,
                    },
                    linkedinLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                    name: {
                      __typename: 'FullName',
                      firstName: 'Ethan',
                      lastName: 'Mitchell',
                    },
                    phones: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '787890123',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    whatsapp: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '787890123',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    xLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                  },
                },
                {
                  __typename: 'PersonEdge',
                  node: {
                    __typename: 'Person',
                    avatarUrl: '',
                    city: 'Seattle',
                    companyId: '20202020-c21e-4ec2-873b-de4264d89025',
                    createdAt: '2025-02-16T08:21:51.715Z',
                    deletedAt: null,
                    id: '20202020-2d40-4e49-8df4-9c6a049190ef',
                    intro: '',
                    jobTitle: '',
                    performanceRating: null,
                    position: 12,
                    updatedAt: '2025-02-16T08:21:51.715Z',
                    workPreference: null,
                    createdBy: {
                      __typename: 'Actor',
                      source: 'MANUAL',
                      workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
                      name: 'Tim Apple',
                      context: {},
                    },
                    emails: {
                      __typename: 'Emails',
                      primaryEmail: 'madison.perez@google.com',
                      additionalEmails: null,
                    },
                    linkedinLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                    name: {
                      __typename: 'FullName',
                      firstName: 'Madison',
                      lastName: 'Perez',
                    },
                    phones: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '788901234',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    whatsapp: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '788901234',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    xLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                  },
                },
                {
                  __typename: 'PersonEdge',
                  node: {
                    __typename: 'Person',
                    avatarUrl: '',
                    city: 'Seattle',
                    companyId: '20202020-c21e-4ec2-873b-de4264d89025',
                    createdAt: '2025-02-16T08:21:51.715Z',
                    deletedAt: null,
                    id: '20202020-2d40-4e49-8df4-9c6a049190df',
                    intro: '',
                    jobTitle: '',
                    performanceRating: null,
                    position: 13,
                    updatedAt: '2025-02-16T08:21:51.715Z',
                    workPreference: null,
                    createdBy: {
                      __typename: 'Actor',
                      source: 'MANUAL',
                      workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
                      name: 'Tim Apple',
                      context: {},
                    },
                    emails: {
                      __typename: 'Emails',
                      primaryEmail: 'bertrand.voulzy@google.com',
                      additionalEmails: null,
                    },
                    linkedinLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                    name: {
                      __typename: 'FullName',
                      firstName: 'Bertrand',
                      lastName: 'Voulzy',
                    },
                    phones: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '788901234',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    whatsapp: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '788901234',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    xLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                  },
                },
                {
                  __typename: 'PersonEdge',
                  node: {
                    __typename: 'Person',
                    avatarUrl: '',
                    city: 'Seattle',
                    companyId: '20202020-c21e-4ec2-873b-de4264d89025',
                    createdAt: '2025-02-16T08:21:51.715Z',
                    deletedAt: null,
                    id: '20202020-2d40-4e49-8df4-9c6a049191de',
                    intro: '',
                    jobTitle: '',
                    performanceRating: null,
                    position: 14,
                    updatedAt: '2025-02-16T08:21:51.715Z',
                    workPreference: null,
                    createdBy: {
                      __typename: 'Actor',
                      source: 'MANUAL',
                      workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
                      name: 'Tim Apple',
                      context: {},
                    },
                    emails: {
                      __typename: 'Emails',
                      primaryEmail: 'louis.duss@google.com',
                      additionalEmails: null,
                    },
                    linkedinLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                    name: {
                      __typename: 'FullName',
                      firstName: 'Louis',
                      lastName: 'Duss',
                    },
                    phones: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '789012345',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    whatsapp: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '789012345',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    xLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                  },
                },
                {
                  __typename: 'PersonEdge',
                  node: {
                    __typename: 'Person',
                    avatarUrl: '',
                    city: 'Seattle',
                    companyId: '20202020-c21e-4ec2-873b-de4264d89025',
                    createdAt: '2025-02-16T08:21:51.715Z',
                    deletedAt: null,
                    id: '20202020-2d40-4e49-8df4-9c6a049191df',
                    intro: '',
                    jobTitle: '',
                    performanceRating: null,
                    position: 15,
                    updatedAt: '2025-02-16T08:21:51.715Z',
                    workPreference: null,
                    createdBy: {
                      __typename: 'Actor',
                      source: 'MANUAL',
                      workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
                      name: 'Tim Apple',
                      context: {},
                    },
                    emails: {
                      __typename: 'Emails',
                      primaryEmail: 'lorie.vladim@google.com',
                      additionalEmails: null,
                    },
                    linkedinLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                    name: {
                      __typename: 'FullName',
                      firstName: 'Lorie',
                      lastName: 'Vladim',
                    },
                    phones: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '788901235',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    whatsapp: {
                      __typename: 'Phones',
                      primaryPhoneNumber: '788901235',
                      primaryPhoneCountryCode: 'FR',
                      primaryPhoneCallingCode: '+33',
                      additionalPhones: null,
                    },
                    xLink: {
                      __typename: 'Links',
                      primaryLinkUrl: '',
                      primaryLinkLabel: '',
                      secondaryLinks: [],
                    },
                  },
                },
              ],
            },
          },
        },
        {
          __typename: 'CompanyEdge',
          cursor:
            'eyJwb3NpdGlvbiI6NywiaWQiOiIyMDIwMjAyMC03MDdlLTQ0ZGMtYTFkMi0zMDAzMGJmMWE5NDQifQ==',
          node: {
            __typename: 'Company',
            accountOwner: null,
            createdAt: '2025-02-16T08:21:51.715Z',
            deletedAt: null,
            employees: null,
            id: '20202020-707e-44dc-a1d2-30030bf1a944',
            name: 'Netflix',
            position: 7,
            opportunities: {
              __typename: 'OpportunityConnection',
              edges: [],
            },
            people: {
              __typename: 'PersonConnection',
              edges: [],
            },
            address: {
              __typename: 'Address',
              addressStreet1: '2300 Harrison St',
              addressStreet2: null,
              addressCity: 'San Francisco',
              addressState: 'CA',
              addressCountry: 'United States',
              addressPostcode: '94110',
              addressLat: null,
              addressLng: null,
            },
            createdBy: {
              __typename: 'Actor',
              source: 'MANUAL',
              workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
              name: 'Tim Apple',
              context: {},
            },
            domainName: {
              __typename: 'Links',
              primaryLinkUrl: 'https://netflix.com',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            linkedinLink: {
              __typename: 'Links',
              primaryLinkUrl: '',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            noteTargets: {
              __typename: 'NoteTargetConnection',
              edges: [],
            },
            taskTargets: {
              __typename: 'TaskTargetConnection',
              edges: [],
            },
          },
        },
        {
          __typename: 'CompanyEdge',
          cursor:
            'eyJwb3NpdGlvbiI6OCwiaWQiOiIyMDIwMjAyMC0zZjc0LTQ5MmQtYTEwMS0yYTcwZjUwYTE2NDUifQ==',
          node: {
            __typename: 'Company',
            accountOwner: null,
            createdAt: '2025-02-16T08:21:51.715Z',
            deletedAt: null,
            employees: null,
            id: '20202020-3f74-492d-a101-2a70f50a1645',
            name: 'Libeo',
            position: 8,
            opportunities: {
              __typename: 'OpportunityConnection',
              edges: [],
            },
            people: {
              __typename: 'PersonConnection',
              edges: [],
            },
            address: {
              __typename: 'Address',
              addressStreet1: null,
              addressStreet2: null,
              addressCity: null,
              addressState: null,
              addressCountry: null,
              addressPostcode: null,
              addressLat: null,
              addressLng: null,
            },
            createdBy: {
              __typename: 'Actor',
              source: 'MANUAL',
              workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
              name: 'Tim Apple',
              context: {},
            },
            domainName: {
              __typename: 'Links',
              primaryLinkUrl: 'https://libeo.io',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            linkedinLink: {
              __typename: 'Links',
              primaryLinkUrl: '',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            noteTargets: {
              __typename: 'NoteTargetConnection',
              edges: [],
            },
            taskTargets: {
              __typename: 'TaskTargetConnection',
              edges: [],
            },
          },
        },
        {
          __typename: 'CompanyEdge',
          cursor:
            'eyJwb3NpdGlvbiI6OSwiaWQiOiIyMDIwMjAyMC1jZmJmLTQxNTYtYTc5MC1lMzk4NTRkY2Q0ZWIifQ==',
          node: {
            __typename: 'Company',
            accountOwner: null,
            createdAt: '2025-02-16T08:21:51.715Z',
            deletedAt: null,
            employees: null,
            id: '20202020-cfbf-4156-a790-e39854dcd4eb',
            name: 'Claap',
            position: 9,
            opportunities: {
              __typename: 'OpportunityConnection',
              edges: [],
            },
            people: {
              __typename: 'PersonConnection',
              edges: [],
            },
            address: {
              __typename: 'Address',
              addressStreet1: null,
              addressStreet2: null,
              addressCity: null,
              addressState: null,
              addressCountry: null,
              addressPostcode: null,
              addressLat: null,
              addressLng: null,
            },
            createdBy: {
              __typename: 'Actor',
              source: 'MANUAL',
              workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
              name: 'Tim Apple',
              context: {},
            },
            domainName: {
              __typename: 'Links',
              primaryLinkUrl: 'https://claap.io',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            linkedinLink: {
              __typename: 'Links',
              primaryLinkUrl: '',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            noteTargets: {
              __typename: 'NoteTargetConnection',
              edges: [],
            },
            taskTargets: {
              __typename: 'TaskTargetConnection',
              edges: [],
            },
          },
        },
        {
          __typename: 'CompanyEdge',
          cursor:
            'eyJwb3NpdGlvbiI6MTAsImlkIjoiMjAyMDIwMjAtZjg2Yi00MTlmLWI3OTQtMDIzMTlhYmU4NjM3In0=',
          node: {
            __typename: 'Company',
            accountOwner: null,
            createdAt: '2025-02-16T08:21:51.715Z',
            deletedAt: null,
            employees: null,
            id: '20202020-f86b-419f-b794-02319abe8637',
            name: 'Hasura',
            position: 10,
            opportunities: {
              __typename: 'OpportunityConnection',
              edges: [],
            },
            people: {
              __typename: 'PersonConnection',
              edges: [],
            },
            address: {
              __typename: 'Address',
              addressStreet1: null,
              addressStreet2: null,
              addressCity: null,
              addressState: null,
              addressCountry: null,
              addressPostcode: null,
              addressLat: null,
              addressLng: null,
            },
            createdBy: {
              __typename: 'Actor',
              source: 'MANUAL',
              workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
              name: 'Tim Apple',
              context: {},
            },
            domainName: {
              __typename: 'Links',
              primaryLinkUrl: 'https://hasura.io',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            linkedinLink: {
              __typename: 'Links',
              primaryLinkUrl: '',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            noteTargets: {
              __typename: 'NoteTargetConnection',
              edges: [],
            },
            taskTargets: {
              __typename: 'TaskTargetConnection',
              edges: [],
            },
          },
        },
        {
          __typename: 'CompanyEdge',
          cursor:
            'eyJwb3NpdGlvbiI6MTEsImlkIjoiMjAyMDIwMjAtNTUxOC00NTUzLTk0MzMtNDJkOGViODI4MzRiIn0=',
          node: {
            __typename: 'Company',
            accountOwner: null,
            createdAt: '2025-02-16T08:21:51.715Z',
            deletedAt: null,
            employees: null,
            id: '20202020-5518-4553-9433-42d8eb82834b',
            name: 'Wework',
            position: 11,
            opportunities: {
              __typename: 'OpportunityConnection',
              edges: [],
            },
            people: {
              __typename: 'PersonConnection',
              edges: [],
            },
            address: {
              __typename: 'Address',
              addressStreet1: null,
              addressStreet2: null,
              addressCity: null,
              addressState: null,
              addressCountry: null,
              addressPostcode: null,
              addressLat: null,
              addressLng: null,
            },
            createdBy: {
              __typename: 'Actor',
              source: 'MANUAL',
              workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
              name: 'Tim Apple',
              context: {},
            },
            domainName: {
              __typename: 'Links',
              primaryLinkUrl: 'https://wework.com',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            linkedinLink: {
              __typename: 'Links',
              primaryLinkUrl: '',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            noteTargets: {
              __typename: 'NoteTargetConnection',
              edges: [],
            },
            taskTargets: {
              __typename: 'TaskTargetConnection',
              edges: [],
            },
          },
        },
        {
          __typename: 'CompanyEdge',
          cursor:
            'eyJwb3NpdGlvbiI6MTIsImlkIjoiMjAyMDIwMjAtZjc5ZS00MGRkLWJkMDYtYzM2ZTZhYmI0Njc4In0=',
          node: {
            __typename: 'Company',
            accountOwner: null,
            createdAt: '2025-02-16T08:21:51.715Z',
            deletedAt: null,
            employees: null,
            id: '20202020-f79e-40dd-bd06-c36e6abb4678',
            name: 'Samsung',
            position: 12,
            opportunities: {
              __typename: 'OpportunityConnection',
              edges: [],
            },
            people: {
              __typename: 'PersonConnection',
              edges: [],
            },
            address: {
              __typename: 'Address',
              addressStreet1: null,
              addressStreet2: null,
              addressCity: null,
              addressState: null,
              addressCountry: null,
              addressPostcode: null,
              addressLat: null,
              addressLng: null,
            },
            createdBy: {
              __typename: 'Actor',
              source: 'MANUAL',
              workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
              name: 'Tim Apple',
              context: {},
            },
            domainName: {
              __typename: 'Links',
              primaryLinkUrl: 'https://samsung.com',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            linkedinLink: {
              __typename: 'Links',
              primaryLinkUrl: '',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            noteTargets: {
              __typename: 'NoteTargetConnection',
              edges: [],
            },
            taskTargets: {
              __typename: 'TaskTargetConnection',
              edges: [],
            },
          },
        },
        {
          __typename: 'CompanyEdge',
          cursor:
            'eyJwb3NpdGlvbiI6MTMsImlkIjoiMjAyMDIwMjAtMTQ1NS00YzU3LWFmYWYtZGQ1ZGMwODYzNjFkIn0=',
          node: {
            __typename: 'Company',
            accountOwner: null,
            createdAt: '2025-02-16T08:21:51.715Z',
            deletedAt: null,
            employees: null,
            id: '20202020-1455-4c57-afaf-dd5dc086361d',
            name: 'Algolia',
            position: 13,
            opportunities: {
              __typename: 'OpportunityConnection',
              edges: [],
            },
            people: {
              __typename: 'PersonConnection',
              edges: [],
            },
            address: {
              __typename: 'Address',
              addressStreet1: null,
              addressStreet2: null,
              addressCity: null,
              addressState: null,
              addressCountry: null,
              addressPostcode: null,
              addressLat: null,
              addressLng: null,
            },
            createdBy: {
              __typename: 'Actor',
              source: 'MANUAL',
              workspaceMemberId: '20202020-0687-4c41-b707-ed1bfca972a7',
              name: 'Tim Apple',
              context: {},
            },
            domainName: {
              __typename: 'Links',
              primaryLinkUrl: 'https://algolia.com',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            linkedinLink: {
              __typename: 'Links',
              primaryLinkUrl: '',
              primaryLinkLabel: '',
              secondaryLinks: [],
            },
            noteTargets: {
              __typename: 'NoteTargetConnection',
              edges: [],
            },
            taskTargets: {
              __typename: 'TaskTargetConnection',
              edges: [],
            },
          },
        },
      ],
    },
  },
  loading: false,
  networkStatus: 7,
} as const;

export const allMockCompanyRecordsWithRelation =
  FIND_MANY_COMPANIES_WITH_RELATION_QUERY_RESULT.data.companies.edges.map(
    (edge) => getRecordFromRecordNode({ recordNode: edge.node }),
  );

export const getMockCompanyWithRelationRecord = (
  overrides?: Partial<ObjectRecord>,
  index = 0,
) => {
  return {
    ...allMockCompanyRecordsWithRelation[index],
    ...overrides,
  };
};

export const findMockCompanyWithRelationRecord = ({
  id: queriedCompanyId,
}: Pick<ObjectRecord, 'id'>) => {
  const company = allMockCompanyRecordsWithRelation.find(
    ({ id: currentCompanyId }) => currentCompanyId === queriedCompanyId,
  );

  if (!isDefined(company)) {
    throw new Error(`Could not find company with id, ${queriedCompanyId}`);
  }

  return company;
};
