export const getPeopleMock = () => {
  const peopleMock = peopleQueryResult.people.edges.map((edge) => edge.node);

  return peopleMock;
};

export const mockedEmptyPersonData = {
  id: 'ce7f0a37-88d7-4cd8-8b41-6721c57195b5',
  firstName: '',
  lastName: '',
  phone: null,
  email: null,
  city: null,
  displayName: null,
  avatarUrl: null,
  createdAt: null,
  jobTitle: null,
  linkedinUrl: null,
  xUrl: null,
  _activityCount: null,
  company: null,
  __typename: 'Person',
};

export const peopleQueryResult = {
  people: {
    __typename: 'PersonConnection',
    totalCount: 15,
    pageInfo: {
      __typename: 'PageInfo',
      hasNextPage: false,
      startCursor:
        'WzEsICIyMDIwMjAyMC0xYzBlLTQ5NGMtYTFiNi04NWIxYzZmZWZhYTUiXQ==',
      endCursor: 'WzE1LCAiMjAyMDIwMjAtMmQ0MC00ZTQ5LThkZjQtOWM2YTA0OTE5MWRmIl0=',
    },
    edges: [
      {
        __typename: 'PersonEdge',
        cursor: 'WzEsICIyMDIwMjAyMC0xYzBlLTQ5NGMtYTFiNi04NWIxYzZmZWZhYTUiXQ==',
        node: {
          __typename: 'Person',
          id: '20202020-1c0e-494c-a1b6-85b1c6fefaa5',
          email: 'christoph.calisto@linkedin.com',
          position: 1,
          testJson: {
            asd: 2,
            array: [1, 2, 3],
          },
          testRating: 'RATING_2',
          testMultiSelect: ['OPTION_5', 'OPTION_1', 'OPTION_2'],
          testBoolean: true,
          testSelect: 'OPTION_1',
          testDateOnly: '2024-06-04T00:00:00.000Z',
          phone: '+33789012345',
          createdAt: '2024-06-05T09:00:20.412Z',
          city: 'Seattle',
          testPhone: '+33143554657',
          jobTitle: 'CEO',
          testCurrency: {
            __typename: 'Currency',
            amountMicros: 100000000000,
            currencyCode: 'USD',
          },
          xLink: {
            __typename: 'Link',
            label: '',
            url: 'twitter.com',
          },
          testLinks: {
            __typename: 'Links',
            primaryLinkUrl: 'https://www.linkedin.com/in/charlesbochet/',
            primaryLinkLabel: '',
            secondaryLinks: [
              {
                url: 'https://msn.com',
                label: '',
              },
              {
                url: 'https://msn.com',
                label: '',
              },
              {
                url: 'https://msn.com',
                label: '',
              },
            ],
          },
          name: {
            __typename: 'FullName',
            firstName: 'Christoph',
            lastName: 'Callisto',
          },
          linkedinLink: {
            __typename: 'Link',
            label: '',
            url: 'linkedin.com',
          },
          testAddress: {
            __typename: 'Address',
            addressStreet1: '1 rue de la paix',
            addressStreet2: '',
            addressCity: 'Paris',
            addressState: 'Paris',
            addressCountry: 'France',
            addressPostcode: '75008',
            addressLat: null,
            addressLng: null,
          },
          testLink: {
            __typename: 'Link',
            label: '',
            url: 'singlelink.com',
          },
          bestCompany: {
            __typename: 'Company',
            id: '20202020-1455-4c57-afaf-dd5dc086361d',
            employees: null,
            previousEmployeesId: null,
            accountOwnerId: null,
            updatedAt: '2024-06-05T09:00:20.412Z',
            idealCustomerProfile: false,
            createdAt: '2024-06-05T09:00:20.412Z',
            name: 'Algolia',
            domainName: 'algolia.com',
            address: '',
            position: 13,
            linkedinLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
            annualRecurringRevenue: {
              __typename: 'Currency',
              amountMicros: null,
              currencyCode: '',
            },
            xLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
          },
          company: {
            __typename: 'Company',
            id: '20202020-3ec3-4fe3-8997-b76aa0bfa408',
            employees: null,
            previousEmployeesId: '20202020-2d40-4e49-8df4-9c6a049191de',
            accountOwnerId: null,
            updatedAt: '2024-06-05T09:39:33.886Z',
            idealCustomerProfile: false,
            createdAt: '2024-06-05T09:00:20.412Z',
            name: 'Linkedin',
            domainName: 'linkedin.com',
            address: '',
            position: 1,
            linkedinLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
            annualRecurringRevenue: {
              __typename: 'Currency',
              amountMicros: null,
              currencyCode: '',
            },
            xLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
          },
        },
      },
      {
        __typename: 'PersonEdge',
        cursor: 'WzIsICIyMDIwMjAyMC1hYzczLTQ3OTctODI0ZS04N2ExZjVhZWE5ZTAiXQ==',
        node: {
          __typename: 'Person',
          id: '20202020-ac73-4797-824e-87a1f5aea9e0',
          email: 'sylvie.palmer@linkedin.com',
          bestCompany: null,
          position: 2,
          testJson: null,
          testRating: 'RATING_5',
          testMultiSelect: ['OPTION_2', 'OPTION_3', 'OPTION_4'],
          testBoolean: false,
          testSelect: null,
          testDateOnly: '2024-06-06T00:00:00.000Z',
          phone: '+33780123456',
          createdAt: '2024-06-05T09:00:20.412Z',
          city: 'Los Angeles',
          testPhone: '',
          jobTitle: 'CEO',
          testCurrency: {
            __typename: 'Currency',
            amountMicros: 20323000000,
            currencyCode: 'USD',
          },
          xLink: {
            __typename: 'Link',
            label: '',
            url: 'twitter.com',
          },
          testLinks: {
            __typename: 'Links',
            primaryLinkUrl: 'https://algolia.com',
            primaryLinkLabel: '',
            secondaryLinks: [
              {
                url: 'https://paris.com',
                label: '',
              },
            ],
          },
          name: {
            __typename: 'FullName',
            firstName: 'Sylvie',
            lastName: 'Palmer',
          },
          linkedinLink: {
            __typename: 'Link',
            label: '',
            url: 'linkedin.com',
          },
          testAddress: {
            __typename: 'Address',
            addressStreet1: '',
            addressStreet2: '',
            addressCity: '',
            addressState: '',
            addressCountry: '',
            addressPostcode: '',
            addressLat: null,
            addressLng: null,
          },
          testLink: {
            __typename: 'Link',
            label: '',
            url: '',
          },
          company: {
            __typename: 'Company',
            id: '20202020-3ec3-4fe3-8997-b76aa0bfa408',
            employees: null,
            previousEmployeesId: '20202020-2d40-4e49-8df4-9c6a049191de',
            accountOwnerId: null,
            updatedAt: '2024-06-05T09:39:33.886Z',
            idealCustomerProfile: false,
            createdAt: '2024-06-05T09:00:20.412Z',
            name: 'Linkedin',
            domainName: 'linkedin.com',
            address: '',
            position: 1,
            linkedinLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
            annualRecurringRevenue: {
              __typename: 'Currency',
              amountMicros: null,
              currencyCode: '',
            },
            xLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
          },
        },
      },
      {
        __typename: 'PersonEdge',
        cursor: 'WzMsICIyMDIwMjAyMC1mNTE3LTQyZmQtODBhZS0xNDE3M2IzYjcwYWUiXQ==',
        node: {
          __typename: 'Person',
          id: '20202020-f517-42fd-80ae-14173b3b70ae',
          email: 'christopher.gonzalez@qonto.com',
          bestCompany: null,
          position: 3,
          testJson: null,
          testRating: 'RATING_3',
          testMultiSelect: ['OPTION_2', 'OPTION_4', 'OPTION_5'],
          testBoolean: true,
          testSelect: null,
          testDateOnly: '2024-06-04T00:00:00.000Z',
          phone: '+33789012345',
          createdAt: '2024-06-05T09:00:20.412Z',
          city: 'Seattle',
          testPhone: '',
          jobTitle: 'CTO',
          testCurrency: {
            __typename: 'Currency',
            amountMicros: 343434000000,
            currencyCode: 'USD',
          },
          xLink: {
            __typename: 'Link',
            label: '',
            url: 'twitter.com',
          },
          testLinks: {
            __typename: 'Links',
            primaryLinkUrl: '',
            primaryLinkLabel: '',
            secondaryLinks: null,
          },
          name: {
            __typename: 'FullName',
            firstName: 'Christopher',
            lastName: 'Gonzalez',
          },
          linkedinLink: {
            __typename: 'Link',
            label: '',
            url: 'linkedin.com',
          },
          testAddress: {
            __typename: 'Address',
            addressStreet1: '',
            addressStreet2: '',
            addressCity: '',
            addressState: '',
            addressCountry: '',
            addressPostcode: '',
            addressLat: null,
            addressLng: null,
          },
          testLink: {
            __typename: 'Link',
            label: '',
            url: '',
          },
          company: {
            __typename: 'Company',
            id: '20202020-0713-40a5-8216-82802401d33e',
            employees: null,
            previousEmployeesId: null,
            accountOwnerId: null,
            updatedAt: '2024-06-05T09:00:20.412Z',
            idealCustomerProfile: false,
            createdAt: '2024-06-05T09:00:20.412Z',
            name: 'Qonto',
            domainName: 'qonto.com',
            address: '',
            position: 3,
            linkedinLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
            annualRecurringRevenue: {
              __typename: 'Currency',
              amountMicros: null,
              currencyCode: '',
            },
            xLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
          },
        },
      },
      {
        __typename: 'PersonEdge',
        cursor: 'WzQsICIyMDIwMjAyMC1lZWUxLTQ2OTAtYWQyYy04NjE5ZTViNTZhMmUiXQ==',
        node: {
          __typename: 'Person',
          id: '20202020-eee1-4690-ad2c-8619e5b56a2e',
          email: 'ashley.parker@qonto.com',
          bestCompany: null,
          position: 4,
          testJson: null,
          testRating: 'RATING_4',
          testMultiSelect: ['OPTION_5', 'OPTION_2', 'OPTION_3'],
          testBoolean: true,
          testSelect: 'OPTION_4',
          testDateOnly: '2024-06-19T00:00:00.000Z',
          phone: '+33780123456',
          createdAt: '2024-06-05T09:00:20.412Z',
          city: 'Los Angeles',
          testPhone: '',
          jobTitle: 'CEO',
          testCurrency: {
            __typename: 'Currency',
            amountMicros: 219232302323000000,
            currencyCode: 'USD',
          },
          xLink: {
            __typename: 'Link',
            label: '',
            url: 'twitter.com',
          },
          testLinks: {
            __typename: 'Links',
            primaryLinkUrl: '',
            primaryLinkLabel: '',
            secondaryLinks: null,
          },
          name: {
            __typename: 'FullName',
            firstName: 'Ashley',
            lastName: 'Parker',
          },
          linkedinLink: {
            __typename: 'Link',
            label: '',
            url: 'linkedin.com',
          },
          testAddress: {
            __typename: 'Address',
            addressStreet1: '',
            addressStreet2: '',
            addressCity: '',
            addressState: '',
            addressCountry: '',
            addressPostcode: '',
            addressLat: null,
            addressLng: null,
          },
          testLink: {
            __typename: 'Link',
            label: '',
            url: '',
          },
          company: {
            __typename: 'Company',
            id: '20202020-0713-40a5-8216-82802401d33e',
            employees: null,
            previousEmployeesId: null,
            accountOwnerId: null,
            updatedAt: '2024-06-05T09:00:20.412Z',
            idealCustomerProfile: false,
            createdAt: '2024-06-05T09:00:20.412Z',
            name: 'Qonto',
            domainName: 'qonto.com',
            address: '',
            position: 3,
            linkedinLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
            annualRecurringRevenue: {
              __typename: 'Currency',
              amountMicros: null,
              currencyCode: '',
            },
            xLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
          },
        },
      },
      {
        __typename: 'PersonEdge',
        cursor: 'WzUsICIyMDIwMjAyMC02Nzg0LTQ0NDktYWZkZi1kYzYyY2I4NzAyZjIiXQ==',
        node: {
          __typename: 'Person',
          id: '20202020-6784-4449-afdf-dc62cb8702f2',
          email: 'nicholas.wright@microsoft.com',
          bestCompany: null,
          position: 5,
          testJson: null,
          testRating: null,
          testMultiSelect: null,
          testBoolean: false,
          testSelect: null,
          testDateOnly: null,
          phone: '+33781234567',
          createdAt: '2024-06-05T09:00:20.412Z',
          city: 'Seattle',
          testPhone: '',
          jobTitle: 'CTO',
          testCurrency: {
            __typename: 'Currency',
            amountMicros: null,
            currencyCode: 'USD',
          },
          xLink: {
            __typename: 'Link',
            label: '',
            url: 'twitter.com',
          },
          testLinks: {
            __typename: 'Links',
            primaryLinkUrl: '',
            primaryLinkLabel: '',
            secondaryLinks: null,
          },
          name: {
            __typename: 'FullName',
            firstName: 'Nicholas',
            lastName: 'Wright',
          },
          linkedinLink: {
            __typename: 'Link',
            label: '',
            url: 'linkedin.com',
          },
          testAddress: {
            __typename: 'Address',
            addressStreet1: '',
            addressStreet2: '',
            addressCity: '',
            addressState: '',
            addressCountry: '',
            addressPostcode: '',
            addressLat: null,
            addressLng: null,
          },
          testLink: {
            __typename: 'Link',
            label: '',
            url: '',
          },
          company: {
            __typename: 'Company',
            id: '20202020-ed89-413a-b31a-962986e67bb4',
            employees: null,
            previousEmployeesId: null,
            accountOwnerId: null,
            updatedAt: '2024-06-05T09:00:20.412Z',
            idealCustomerProfile: false,
            createdAt: '2024-06-05T09:00:20.412Z',
            name: 'Microsoft',
            domainName: 'microsoft.com',
            address: '',
            position: 4,
            linkedinLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
            annualRecurringRevenue: {
              __typename: 'Currency',
              amountMicros: null,
              currencyCode: '',
            },
            xLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
          },
        },
      },
      {
        __typename: 'PersonEdge',
        cursor: 'WzYsICIyMDIwMjAyMC00OTBmLTQ0NjYtODM5MS03MzNjZmQ2NmEwYzgiXQ==',
        node: {
          __typename: 'Person',
          id: '20202020-490f-4466-8391-733cfd66a0c8',
          email: 'isabella.scott@microsoft.com',
          bestCompany: null,
          position: 6,
          testJson: null,
          testRating: null,
          testMultiSelect: ['OPTION_1', 'OPTION_3', 'OPTION_5'],
          testBoolean: false,
          testSelect: 'OPTION_4',
          testDateOnly: null,
          phone: '+33782345678',
          createdAt: '2024-06-05T09:00:20.412Z',
          city: 'New York',
          testPhone: '',
          jobTitle: 'CFO',
          testCurrency: {
            __typename: 'Currency',
            amountMicros: null,
            currencyCode: 'USD',
          },
          xLink: {
            __typename: 'Link',
            label: '',
            url: 'twitter.com',
          },
          testLinks: {
            __typename: 'Links',
            primaryLinkUrl: '',
            primaryLinkLabel: '',
            secondaryLinks: null,
          },
          name: {
            __typename: 'FullName',
            firstName: 'Isabella',
            lastName: 'Scott',
          },
          linkedinLink: {
            __typename: 'Link',
            label: '',
            url: 'linkedin.com',
          },
          testAddress: {
            __typename: 'Address',
            addressStreet1: '',
            addressStreet2: '',
            addressCity: '',
            addressState: '',
            addressCountry: '',
            addressPostcode: '',
            addressLat: null,
            addressLng: null,
          },
          testLink: {
            __typename: 'Link',
            label: '',
            url: '',
          },
          company: {
            __typename: 'Company',
            id: '20202020-ed89-413a-b31a-962986e67bb4',
            employees: null,
            previousEmployeesId: null,
            accountOwnerId: null,
            updatedAt: '2024-06-05T09:00:20.412Z',
            idealCustomerProfile: false,
            createdAt: '2024-06-05T09:00:20.412Z',
            name: 'Microsoft',
            domainName: 'microsoft.com',
            address: '',
            position: 4,
            linkedinLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
            annualRecurringRevenue: {
              __typename: 'Currency',
              amountMicros: null,
              currencyCode: '',
            },
            xLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
          },
        },
      },
      {
        __typename: 'PersonEdge',
        cursor: 'WzcsICIyMDIwMjAyMC04MGYxLTRkZmYtYjU3MC1hNzQ5NDI1MjhkZTMiXQ==',
        node: {
          __typename: 'Person',
          id: '20202020-80f1-4dff-b570-a74942528de3',
          email: 'matthew.green@microsoft.com',
          bestCompany: null,
          position: 7,
          testJson: null,
          testRating: null,
          testMultiSelect: ['OPTION_6', 'OPTION_7'],
          testBoolean: false,
          testSelect: null,
          testDateOnly: null,
          phone: '+33783456789',
          createdAt: '2024-06-05T09:00:20.412Z',
          city: 'Seattle',
          testPhone: '',
          jobTitle: 'CEO',
          testCurrency: {
            __typename: 'Currency',
            amountMicros: null,
            currencyCode: 'USD',
          },
          xLink: {
            __typename: 'Link',
            label: '',
            url: 'twitter.com',
          },
          testLinks: {
            __typename: 'Links',
            primaryLinkUrl: '',
            primaryLinkLabel: '',
            secondaryLinks: null,
          },
          name: {
            __typename: 'FullName',
            firstName: 'Matthew',
            lastName: 'Green',
          },
          linkedinLink: {
            __typename: 'Link',
            label: '',
            url: 'linkedin.com',
          },
          testAddress: {
            __typename: 'Address',
            addressStreet1: '',
            addressStreet2: '',
            addressCity: '',
            addressState: '',
            addressCountry: '',
            addressPostcode: '',
            addressLat: null,
            addressLng: null,
          },
          testLink: {
            __typename: 'Link',
            label: '',
            url: '',
          },
          company: {
            __typename: 'Company',
            id: '20202020-ed89-413a-b31a-962986e67bb4',
            employees: null,
            previousEmployeesId: null,
            accountOwnerId: null,
            updatedAt: '2024-06-05T09:00:20.412Z',
            idealCustomerProfile: false,
            createdAt: '2024-06-05T09:00:20.412Z',
            name: 'Microsoft',
            domainName: 'microsoft.com',
            address: '',
            position: 4,
            linkedinLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
            annualRecurringRevenue: {
              __typename: 'Currency',
              amountMicros: null,
              currencyCode: '',
            },
            xLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
          },
        },
      },
      {
        __typename: 'PersonEdge',
        cursor: 'WzgsICIyMDIwMjAyMC0zMzhiLTQ2ZGYtODgxMS1mYTA4YzdkMTlkMzUiXQ==',
        node: {
          __typename: 'Person',
          id: '20202020-338b-46df-8811-fa08c7d19d35',
          email: 'elizabeth.baker@airbnb.com',
          bestCompany: null,
          position: 8,
          testJson: null,
          testRating: null,
          testMultiSelect: null,
          testBoolean: true,
          testSelect: 'OPTION_5',
          testDateOnly: '2024-06-11T00:00:00.000Z',
          phone: '+33784567890',
          createdAt: '2024-06-05T09:00:20.412Z',
          city: 'New York',
          testPhone: '',
          jobTitle: 'CTO',
          testCurrency: {
            __typename: 'Currency',
            amountMicros: null,
            currencyCode: 'USD',
          },
          xLink: {
            __typename: 'Link',
            label: '',
            url: 'twitter.com',
          },
          testLinks: {
            __typename: 'Links',
            primaryLinkUrl: '',
            primaryLinkLabel: '',
            secondaryLinks: null,
          },
          name: {
            __typename: 'FullName',
            firstName: 'Elizabeth',
            lastName: 'Baker',
          },
          linkedinLink: {
            __typename: 'Link',
            label: '',
            url: 'linkedin.com',
          },
          testAddress: {
            __typename: 'Address',
            addressStreet1: '',
            addressStreet2: '',
            addressCity: '',
            addressState: '',
            addressCountry: '',
            addressPostcode: '',
            addressLat: null,
            addressLng: null,
          },
          testLink: {
            __typename: 'Link',
            label: '',
            url: '',
          },
          company: {
            __typename: 'Company',
            id: '20202020-171e-4bcc-9cf7-43448d6fb278',
            employees: null,
            previousEmployeesId: null,
            accountOwnerId: null,
            updatedAt: '2024-06-05T09:00:20.412Z',
            idealCustomerProfile: false,
            createdAt: '2024-06-05T09:00:20.412Z',
            name: 'Airbnb',
            domainName: 'airbnb.com',
            address: '',
            position: 5,
            linkedinLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
            annualRecurringRevenue: {
              __typename: 'Currency',
              amountMicros: null,
              currencyCode: '',
            },
            xLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
          },
        },
      },
      {
        __typename: 'PersonEdge',
        cursor: 'WzksICIyMDIwMjAyMC02NGFkLTRiMGUtYmJmZC1lOWZkNzk1YjcwMTYiXQ==',
        node: {
          __typename: 'Person',
          id: '20202020-64ad-4b0e-bbfd-e9fd795b7016',
          email: 'christopher.nelson@airbnb.com',
          bestCompany: null,
          position: 9,
          testJson: null,
          testRating: null,
          testMultiSelect: null,
          testBoolean: true,
          testSelect: null,
          testDateOnly: null,
          phone: '+33785678901',
          createdAt: '2024-06-05T09:00:20.412Z',
          city: 'San Francisco',
          testPhone: '',
          jobTitle: 'CFO',
          testCurrency: {
            __typename: 'Currency',
            amountMicros: null,
            currencyCode: 'USD',
          },
          xLink: {
            __typename: 'Link',
            label: '',
            url: '',
          },
          testLinks: {
            __typename: 'Links',
            primaryLinkUrl: '',
            primaryLinkLabel: '',
            secondaryLinks: null,
          },
          name: {
            __typename: 'FullName',
            firstName: 'Christopher',
            lastName: 'Nelson',
          },
          linkedinLink: {
            __typename: 'Link',
            label: '',
            url: 'linkedin.com',
          },
          testAddress: {
            __typename: 'Address',
            addressStreet1: '',
            addressStreet2: '',
            addressCity: '',
            addressState: '',
            addressCountry: '',
            addressPostcode: '',
            addressLat: null,
            addressLng: null,
          },
          testLink: {
            __typename: 'Link',
            label: '',
            url: '',
          },
          company: {
            __typename: 'Company',
            id: '20202020-171e-4bcc-9cf7-43448d6fb278',
            employees: null,
            previousEmployeesId: null,
            accountOwnerId: null,
            updatedAt: '2024-06-05T09:00:20.412Z',
            idealCustomerProfile: false,
            createdAt: '2024-06-05T09:00:20.412Z',
            name: 'Airbnb',
            domainName: 'airbnb.com',
            address: '',
            position: 5,
            linkedinLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
            annualRecurringRevenue: {
              __typename: 'Currency',
              amountMicros: null,
              currencyCode: '',
            },
            xLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
          },
        },
      },
      {
        __typename: 'PersonEdge',
        cursor: 'WzEwLCAiMjAyMDIwMjAtNWQ1NC00MWI3LWJhMzYtZjBkMjBlMTQxN2FlIl0=',
        node: {
          __typename: 'Person',
          id: '20202020-5d54-41b7-ba36-f0d20e1417ae',
          email: 'avery.carter@airbnb.com',
          bestCompany: null,
          position: 10,
          testJson: null,
          testRating: null,
          testMultiSelect: null,
          testBoolean: false,
          testSelect: 'OPTION_2',
          testDateOnly: null,
          phone: '+33786789012',
          createdAt: '2024-06-05T09:00:20.412Z',
          city: 'New York',
          testPhone: '',
          jobTitle: 'CTO',
          testCurrency: {
            __typename: 'Currency',
            amountMicros: null,
            currencyCode: 'USD',
          },
          xLink: {
            __typename: 'Link',
            label: '',
            url: '',
          },
          testLinks: {
            __typename: 'Links',
            primaryLinkUrl: '',
            primaryLinkLabel: '',
            secondaryLinks: null,
          },
          name: {
            __typename: 'FullName',
            firstName: 'Avery',
            lastName: 'Carter',
          },
          linkedinLink: {
            __typename: 'Link',
            label: '',
            url: 'linkedin.com',
          },
          testAddress: {
            __typename: 'Address',
            addressStreet1: '',
            addressStreet2: '',
            addressCity: '',
            addressState: '',
            addressCountry: '',
            addressPostcode: '',
            addressLat: null,
            addressLng: null,
          },
          testLink: {
            __typename: 'Link',
            label: '',
            url: '',
          },
          company: {
            __typename: 'Company',
            id: '20202020-171e-4bcc-9cf7-43448d6fb278',
            employees: null,
            previousEmployeesId: null,
            accountOwnerId: null,
            updatedAt: '2024-06-05T09:00:20.412Z',
            idealCustomerProfile: false,
            createdAt: '2024-06-05T09:00:20.412Z',
            name: 'Airbnb',
            domainName: 'airbnb.com',
            address: '',
            position: 5,
            linkedinLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
            annualRecurringRevenue: {
              __typename: 'Currency',
              amountMicros: null,
              currencyCode: '',
            },
            xLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
          },
        },
      },
      {
        __typename: 'PersonEdge',
        cursor: 'WzExLCAiMjAyMDIwMjAtNjIzZC00MWZlLTkyZTctZGQ0NWI3YzU2OGUxIl0=',
        node: {
          __typename: 'Person',
          id: '20202020-623d-41fe-92e7-dd45b7c568e1',
          email: 'ethan.mitchell@google.com',
          bestCompany: null,
          position: 11,
          testJson: null,
          testRating: null,
          testMultiSelect: null,
          testBoolean: true,
          testSelect: null,
          testDateOnly: null,
          phone: '+33787890123',
          createdAt: '2024-06-05T09:00:20.412Z',
          city: 'Los Angeles',
          testPhone: '',
          jobTitle: 'CMO',
          testCurrency: {
            __typename: 'Currency',
            amountMicros: null,
            currencyCode: 'USD',
          },
          xLink: {
            __typename: 'Link',
            label: '',
            url: 'twitter.com',
          },
          testLinks: {
            __typename: 'Links',
            primaryLinkUrl: '',
            primaryLinkLabel: '',
            secondaryLinks: null,
          },
          name: {
            __typename: 'FullName',
            firstName: 'Ethan',
            lastName: 'Mitchell',
          },
          linkedinLink: {
            __typename: 'Link',
            label: '',
            url: 'linkedin.com',
          },
          testAddress: {
            __typename: 'Address',
            addressStreet1: '',
            addressStreet2: '',
            addressCity: '',
            addressState: '',
            addressCountry: '',
            addressPostcode: '',
            addressLat: null,
            addressLng: null,
          },
          testLink: {
            __typename: 'Link',
            label: '',
            url: '',
          },
          company: {
            __typename: 'Company',
            id: '20202020-c21e-4ec2-873b-de4264d89025',
            employees: null,
            previousEmployeesId: null,
            accountOwnerId: null,
            updatedAt: '2024-06-05T09:00:20.412Z',
            idealCustomerProfile: false,
            createdAt: '2024-06-05T09:00:20.412Z',
            name: 'Google',
            domainName: 'google.com',
            address: '',
            position: 6,
            linkedinLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
            annualRecurringRevenue: {
              __typename: 'Currency',
              amountMicros: null,
              currencyCode: '',
            },
            xLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
          },
        },
      },
      {
        __typename: 'PersonEdge',
        cursor: 'WzEyLCAiMjAyMDIwMjAtMmQ0MC00ZTQ5LThkZjQtOWM2YTA0OTE5MGVmIl0=',
        node: {
          __typename: 'Person',
          id: '20202020-2d40-4e49-8df4-9c6a049190ef',
          email: 'madison.perez@google.com',
          bestCompany: null,
          position: 12,
          testJson: null,
          testRating: null,
          testMultiSelect: null,
          testBoolean: true,
          testSelect: null,
          testDateOnly: null,
          phone: '+33788901234',
          createdAt: '2024-06-05T09:00:20.412Z',
          city: 'Seattle',
          testPhone: '',
          jobTitle: 'CHO',
          testCurrency: {
            __typename: 'Currency',
            amountMicros: null,
            currencyCode: 'USD',
          },
          xLink: {
            __typename: 'Link',
            label: '',
            url: '',
          },
          testLinks: {
            __typename: 'Links',
            primaryLinkUrl: '',
            primaryLinkLabel: '',
            secondaryLinks: null,
          },
          name: {
            __typename: 'FullName',
            firstName: 'Madison',
            lastName: 'Perez',
          },
          linkedinLink: {
            __typename: 'Link',
            label: '',
            url: 'linkedin.com',
          },
          testAddress: {
            __typename: 'Address',
            addressStreet1: '',
            addressStreet2: '',
            addressCity: '',
            addressState: '',
            addressCountry: '',
            addressPostcode: '',
            addressLat: null,
            addressLng: null,
          },
          testLink: {
            __typename: 'Link',
            label: '',
            url: '',
          },
          company: {
            __typename: 'Company',
            id: '20202020-c21e-4ec2-873b-de4264d89025',
            employees: null,
            previousEmployeesId: null,
            accountOwnerId: null,
            updatedAt: '2024-06-05T09:00:20.412Z',
            idealCustomerProfile: false,
            createdAt: '2024-06-05T09:00:20.412Z',
            name: 'Google',
            domainName: 'google.com',
            address: '',
            position: 6,
            linkedinLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
            annualRecurringRevenue: {
              __typename: 'Currency',
              amountMicros: null,
              currencyCode: '',
            },
            xLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
          },
        },
      },
      {
        __typename: 'PersonEdge',
        cursor: 'WzEzLCAiMjAyMDIwMjAtMmQ0MC00ZTQ5LThkZjQtOWM2YTA0OTE5MGRmIl0=',
        node: {
          __typename: 'Person',
          id: '20202020-2d40-4e49-8df4-9c6a049190df',
          email: 'bertrand.voulzy@google.com',
          bestCompany: null,
          position: 13,
          testJson: null,
          testRating: null,
          testMultiSelect: null,
          testBoolean: false,
          testSelect: null,
          testDateOnly: null,
          phone: '+33788901234',
          createdAt: '2024-06-05T09:00:20.412Z',
          city: 'Seattle',
          testPhone: '',
          jobTitle: 'CFO',
          testCurrency: {
            __typename: 'Currency',
            amountMicros: null,
            currencyCode: 'USD',
          },
          xLink: {
            __typename: 'Link',
            label: '',
            url: '',
          },
          testLinks: {
            __typename: 'Links',
            primaryLinkUrl: '',
            primaryLinkLabel: '',
            secondaryLinks: null,
          },
          name: {
            __typename: 'FullName',
            firstName: 'Bertrand',
            lastName: 'Voulzy',
          },
          linkedinLink: {
            __typename: 'Link',
            label: '',
            url: 'linkedin.com',
          },
          testAddress: {
            __typename: 'Address',
            addressStreet1: '',
            addressStreet2: '',
            addressCity: '',
            addressState: '',
            addressCountry: '',
            addressPostcode: '',
            addressLat: null,
            addressLng: null,
          },
          testLink: {
            __typename: 'Link',
            label: '',
            url: '',
          },
          company: {
            __typename: 'Company',
            id: '20202020-c21e-4ec2-873b-de4264d89025',
            employees: null,
            previousEmployeesId: null,
            accountOwnerId: null,
            updatedAt: '2024-06-05T09:00:20.412Z',
            idealCustomerProfile: false,
            createdAt: '2024-06-05T09:00:20.412Z',
            name: 'Google',
            domainName: 'google.com',
            address: '',
            position: 6,
            linkedinLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
            annualRecurringRevenue: {
              __typename: 'Currency',
              amountMicros: null,
              currencyCode: '',
            },
            xLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
          },
        },
      },
      {
        __typename: 'PersonEdge',
        cursor: 'WzE0LCAiMjAyMDIwMjAtMmQ0MC00ZTQ5LThkZjQtOWM2YTA0OTE5MWRlIl0=',
        node: {
          __typename: 'Person',
          id: '20202020-2d40-4e49-8df4-9c6a049191de',
          email: 'louis.duss@google.com',
          bestCompany: null,
          position: 14,
          testJson: null,
          testRating: null,
          testMultiSelect: null,
          testBoolean: true,
          testSelect: 'OPTION_1',
          testDateOnly: null,
          phone: '+33788901234',
          createdAt: '2024-06-05T09:00:20.412Z',
          city: 'Seattle',
          testPhone: '',
          jobTitle: 'CTO',
          testCurrency: {
            __typename: 'Currency',
            amountMicros: null,
            currencyCode: 'USD',
          },
          xLink: {
            __typename: 'Link',
            label: '',
            url: 'twitter.com',
          },
          testLinks: {
            __typename: 'Links',
            primaryLinkUrl: '',
            primaryLinkLabel: '',
            secondaryLinks: null,
          },
          name: {
            __typename: 'FullName',
            firstName: 'Louis',
            lastName: 'Duss',
          },
          linkedinLink: {
            __typename: 'Link',
            label: '',
            url: 'linkedin.com',
          },
          testAddress: {
            __typename: 'Address',
            addressStreet1: '',
            addressStreet2: '',
            addressCity: '',
            addressState: '',
            addressCountry: '',
            addressPostcode: '',
            addressLat: null,
            addressLng: null,
          },
          testLink: {
            __typename: 'Link',
            label: '',
            url: '',
          },
          company: {
            __typename: 'Company',
            id: '20202020-c21e-4ec2-873b-de4264d89025',
            employees: null,
            previousEmployeesId: null,
            accountOwnerId: null,
            updatedAt: '2024-06-05T09:00:20.412Z',
            idealCustomerProfile: false,
            createdAt: '2024-06-05T09:00:20.412Z',
            name: 'Google',
            domainName: 'google.com',
            address: '',
            position: 6,
            linkedinLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
            annualRecurringRevenue: {
              __typename: 'Currency',
              amountMicros: null,
              currencyCode: '',
            },
            xLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
          },
        },
      },
      {
        __typename: 'PersonEdge',
        cursor: 'WzE1LCAiMjAyMDIwMjAtMmQ0MC00ZTQ5LThkZjQtOWM2YTA0OTE5MWRmIl0=',
        node: {
          __typename: 'Person',
          id: '20202020-2d40-4e49-8df4-9c6a049191df',
          email: 'lorie.vladim@google.com',
          bestCompany: null,
          position: 15,
          testJson: null,
          testRating: null,
          testMultiSelect: null,
          testBoolean: false,
          testSelect: null,
          testDateOnly: null,
          phone: '+33788901235',
          createdAt: '2024-06-05T09:00:20.412Z',
          city: 'Seattle',
          testPhone: '',
          jobTitle: 'CEO',
          testCurrency: {
            __typename: 'Currency',
            amountMicros: null,
            currencyCode: 'USD',
          },
          xLink: {
            __typename: 'Link',
            label: '',
            url: '',
          },
          testLinks: {
            __typename: 'Links',
            primaryLinkUrl: '',
            primaryLinkLabel: '',
            secondaryLinks: null,
          },
          name: {
            __typename: 'FullName',
            firstName: 'Lorie',
            lastName: 'Vladim',
          },
          linkedinLink: {
            __typename: 'Link',
            label: '',
            url: 'linkedin.com',
          },
          testAddress: {
            __typename: 'Address',
            addressStreet1: '',
            addressStreet2: '',
            addressCity: '',
            addressState: '',
            addressCountry: '',
            addressPostcode: '',
            addressLat: null,
            addressLng: null,
          },
          testLink: {
            __typename: 'Link',
            label: '',
            url: '',
          },
          company: {
            __typename: 'Company',
            id: '20202020-c21e-4ec2-873b-de4264d89025',
            employees: null,
            previousEmployeesId: null,
            accountOwnerId: null,
            updatedAt: '2024-06-05T09:00:20.412Z',
            idealCustomerProfile: false,
            createdAt: '2024-06-05T09:00:20.412Z',
            name: 'Google',
            domainName: 'google.com',
            address: '',
            position: 6,
            linkedinLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
            annualRecurringRevenue: {
              __typename: 'Currency',
              amountMicros: null,
              currencyCode: '',
            },
            xLink: {
              __typename: 'Link',
              label: '',
              url: '',
            },
          },
        },
      },
    ],
  },
};
