import {
  defineField,
  FieldType,
  STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS,
} from 'twenty-sdk/define';

import {
  PDL_FIELD_UNIVERSAL_IDENTIFIERS,
  PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS,
} from 'src/constants/universal-identifiers';

export default defineField({
  universalIdentifier:
    PDL_FIELD_UNIVERSAL_IDENTIFIERS.person.pdlJobTitleSubRole,
  objectUniversalIdentifier:
    STANDARD_OBJECT_UNIVERSAL_IDENTIFIERS.person.universalIdentifier,
  type: FieldType.SELECT,
  name: 'pdlJobTitleSubRole',
  label: 'Job Sub-Role',
  description: 'People Data Labs canonical job sub-role.',
  isNullable: true,
  options: [
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.academic,
      value: 'ACADEMIC',
      label: 'Academic',
      color: 'blue',
      position: 0,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .accountExecutive,
      value: 'ACCOUNT_EXECUTIVE',
      label: 'Account Executive',
      color: 'red',
      position: 1,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .accountManagement,
      value: 'ACCOUNT_MANAGEMENT',
      label: 'Account Management',
      color: 'green',
      position: 2,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.accounting,
      value: 'ACCOUNTING',
      label: 'Accounting',
      color: 'orange',
      position: 3,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .accountingServices,
      value: 'ACCOUNTING_SERVICES',
      label: 'Accounting Services',
      color: 'purple',
      position: 4,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .administrative,
      value: 'ADMINISTRATIVE',
      label: 'Administrative',
      color: 'yellow',
      position: 5,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.advisor,
      value: 'ADVISOR',
      label: 'Advisor',
      color: 'pink',
      position: 6,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.agriculture,
      value: 'AGRICULTURE',
      label: 'Agriculture',
      color: 'cyan',
      position: 7,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.aides,
      value: 'AIDES',
      label: 'Aides',
      color: 'brown',
      position: 8,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.architecture,
      value: 'ARCHITECTURE',
      label: 'Architecture',
      color: 'lime',
      position: 9,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.artist,
      value: 'ARTIST',
      label: 'Artist',
      color: 'violet',
      position: 10,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.boardMember,
      value: 'BOARD_MEMBER',
      label: 'Board Member',
      color: 'gold',
      position: 11,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.bookkeeping,
      value: 'BOOKKEEPING',
      label: 'Bookkeeping',
      color: 'turquoise',
      position: 12,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.brand,
      value: 'BRAND',
      label: 'Brand',
      color: 'crimson',
      position: 13,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .buildingAndGrounds,
      value: 'BUILDING_AND_GROUNDS',
      label: 'Building and Grounds',
      color: 'sky',
      position: 14,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .businessAnalyst,
      value: 'BUSINESS_ANALYST',
      label: 'Business Analyst',
      color: 'amber',
      position: 15,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .businessDevelopment,
      value: 'BUSINESS_DEVELOPMENT',
      label: 'Business Development',
      color: 'plum',
      position: 16,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.chemical,
      value: 'CHEMICAL',
      label: 'Chemical',
      color: 'grass',
      position: 17,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.compliance,
      value: 'COMPLIANCE',
      label: 'Compliance',
      color: 'tomato',
      position: 18,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.construction,
      value: 'CONSTRUCTION',
      label: 'Construction',
      color: 'iris',
      position: 19,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.consulting,
      value: 'CONSULTING',
      label: 'Consulting',
      color: 'mint',
      position: 20,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.content,
      value: 'CONTENT',
      label: 'Content',
      color: 'ruby',
      position: 21,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .corporateDevelopment,
      value: 'CORPORATE_DEVELOPMENT',
      label: 'Corporate Development',
      color: 'bronze',
      position: 22,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.curation,
      value: 'CURATION',
      label: 'Curation',
      color: 'jade',
      position: 23,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .customerSuccess,
      value: 'CUSTOMER_SUCCESS',
      label: 'Customer Success',
      color: 'gray',
      position: 24,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .customerSupport,
      value: 'CUSTOMER_SUPPORT',
      label: 'Customer Support',
      color: 'blue',
      position: 25,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.dataAnalyst,
      value: 'DATA_ANALYST',
      label: 'Data Analyst',
      color: 'red',
      position: 26,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .dataEngineering,
      value: 'DATA_ENGINEERING',
      label: 'Data Engineering',
      color: 'green',
      position: 27,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.dataScience,
      value: 'DATA_SCIENCE',
      label: 'Data Science',
      color: 'orange',
      position: 28,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.dental,
      value: 'DENTAL',
      label: 'Dental',
      color: 'purple',
      position: 29,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.devops,
      value: 'DEVOPS',
      label: 'DevOps',
      color: 'yellow',
      position: 30,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.doctor,
      value: 'DOCTOR',
      label: 'Doctor',
      color: 'pink',
      position: 31,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.electric,
      value: 'ELECTRIC',
      label: 'Electric',
      color: 'cyan',
      position: 32,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.electrical,
      value: 'ELECTRICAL',
      label: 'Electrical',
      color: 'brown',
      position: 33,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .emergencyServices,
      value: 'EMERGENCY_SERVICES',
      label: 'Emergency Services',
      color: 'lime',
      position: 34,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .entertainment,
      value: 'ENTERTAINMENT',
      label: 'Entertainment',
      color: 'violet',
      position: 35,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.executive,
      value: 'EXECUTIVE',
      label: 'Executive',
      color: 'gold',
      position: 36,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.fashion,
      value: 'FASHION',
      label: 'Fashion',
      color: 'turquoise',
      position: 37,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.financial,
      value: 'FINANCIAL',
      label: 'Financial',
      color: 'crimson',
      position: 38,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.fitness,
      value: 'FITNESS',
      label: 'Fitness',
      color: 'sky',
      position: 39,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.fraud,
      value: 'FRAUD',
      label: 'Fraud',
      color: 'amber',
      position: 40,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .graphicDesign,
      value: 'GRAPHIC_DESIGN',
      label: 'Graphic Design',
      color: 'plum',
      position: 41,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.growth,
      value: 'GROWTH',
      label: 'Growth',
      color: 'grass',
      position: 42,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.hairStylist,
      value: 'HAIR_STYLIST',
      label: 'Hair Stylist',
      color: 'tomato',
      position: 43,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.hardware,
      value: 'HARDWARE',
      label: 'Hardware',
      color: 'iris',
      position: 44,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .healthAndSafety,
      value: 'HEALTH_AND_SAFETY',
      label: 'Health and Safety',
      color: 'mint',
      position: 45,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .humanResources,
      value: 'HUMAN_RESOURCES',
      label: 'Human Resources',
      color: 'ruby',
      position: 46,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .implementation,
      value: 'IMPLEMENTATION',
      label: 'Implementation',
      color: 'bronze',
      position: 47,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.industrial,
      value: 'INDUSTRIAL',
      label: 'Industrial',
      color: 'jade',
      position: 48,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .informationTechnology,
      value: 'INFORMATION_TECHNOLOGY',
      label: 'Information Technology',
      color: 'gray',
      position: 49,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.insurance,
      value: 'INSURANCE',
      label: 'Insurance',
      color: 'blue',
      position: 50,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .investmentBanking,
      value: 'INVESTMENT_BANKING',
      label: 'Investment Banking',
      color: 'red',
      position: 51,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.investor,
      value: 'INVESTOR',
      label: 'Investor',
      color: 'green',
      position: 52,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .investorRelations,
      value: 'INVESTOR_RELATIONS',
      label: 'Investor Relations',
      color: 'orange',
      position: 53,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.journalism,
      value: 'JOURNALISM',
      label: 'Journalism',
      color: 'purple',
      position: 54,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.judicial,
      value: 'JUDICIAL',
      label: 'Judicial',
      color: 'yellow',
      position: 55,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.legal,
      value: 'LEGAL',
      label: 'Legal',
      color: 'pink',
      position: 56,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .legalServices,
      value: 'LEGAL_SERVICES',
      label: 'Legal Services',
      color: 'cyan',
      position: 57,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.logistics,
      value: 'LOGISTICS',
      label: 'Logistics',
      color: 'brown',
      position: 58,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.machinist,
      value: 'MACHINIST',
      label: 'Machinist',
      color: 'lime',
      position: 59,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .marketingDesign,
      value: 'MARKETING_DESIGN',
      label: 'Marketing Design',
      color: 'violet',
      position: 60,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .marketingServices,
      value: 'MARKETING_SERVICES',
      label: 'Marketing Services',
      color: 'gold',
      position: 61,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.mechanic,
      value: 'MECHANIC',
      label: 'Mechanic',
      color: 'turquoise',
      position: 62,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.mechanical,
      value: 'MECHANICAL',
      label: 'Mechanical',
      color: 'crimson',
      position: 63,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.military,
      value: 'MILITARY',
      label: 'Military',
      color: 'sky',
      position: 64,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.network,
      value: 'NETWORK',
      label: 'Network',
      color: 'amber',
      position: 65,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.nursing,
      value: 'NURSING',
      label: 'Nursing',
      color: 'plum',
      position: 66,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.partnerships,
      value: 'PARTNERSHIPS',
      label: 'Partnerships',
      color: 'grass',
      position: 67,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.pharmacy,
      value: 'PHARMACY',
      label: 'Pharmacy',
      color: 'tomato',
      position: 68,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .planningAndAnalysis,
      value: 'PLANNING_AND_ANALYSIS',
      label: 'Planning and Analysis',
      color: 'iris',
      position: 69,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.plumbing,
      value: 'PLUMBING',
      label: 'Plumbing',
      color: 'mint',
      position: 70,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.political,
      value: 'POLITICAL',
      label: 'Political',
      color: 'ruby',
      position: 71,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .primaryAndSecondary,
      value: 'PRIMARY_AND_SECONDARY',
      label: 'Primary and Secondary',
      color: 'bronze',
      position: 72,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.procurement,
      value: 'PROCUREMENT',
      label: 'Procurement',
      color: 'jade',
      position: 73,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .productDesign,
      value: 'PRODUCT_DESIGN',
      label: 'Product Design',
      color: 'gray',
      position: 74,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .productManagement,
      value: 'PRODUCT_MANAGEMENT',
      label: 'Product Management',
      color: 'blue',
      position: 75,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.professor,
      value: 'PROFESSOR',
      label: 'Professor',
      color: 'red',
      position: 76,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .projectManagement,
      value: 'PROJECT_MANAGEMENT',
      label: 'Project Management',
      color: 'green',
      position: 77,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .protectiveService,
      value: 'PROTECTIVE_SERVICE',
      label: 'Protective Service',
      color: 'orange',
      position: 78,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .qaEngineering,
      value: 'QA_ENGINEERING',
      label: 'QA Engineering',
      color: 'purple',
      position: 79,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .qualityAssurance,
      value: 'QUALITY_ASSURANCE',
      label: 'Quality Assurance',
      color: 'yellow',
      position: 80,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.realtor,
      value: 'REALTOR',
      label: 'Realtor',
      color: 'pink',
      position: 81,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.recruiting,
      value: 'RECRUITING',
      label: 'Recruiting',
      color: 'cyan',
      position: 82,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.restaurants,
      value: 'RESTAURANTS',
      label: 'Restaurants',
      color: 'brown',
      position: 83,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.retail,
      value: 'RETAIL',
      label: 'Retail',
      color: 'lime',
      position: 84,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .revenueOperations,
      value: 'REVENUE_OPERATIONS',
      label: 'Revenue Operations',
      color: 'violet',
      position: 85,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.risk,
      value: 'RISK',
      label: 'Risk',
      color: 'gold',
      position: 86,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .salesDevelopment,
      value: 'SALES_DEVELOPMENT',
      label: 'Sales Development',
      color: 'turquoise',
      position: 87,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.scientific,
      value: 'SCIENTIFIC',
      label: 'Scientific',
      color: 'crimson',
      position: 88,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.security,
      value: 'SECURITY',
      label: 'Security',
      color: 'sky',
      position: 89,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .socialService,
      value: 'SOCIAL_SERVICE',
      label: 'Social Service',
      color: 'amber',
      position: 90,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.software,
      value: 'SOFTWARE',
      label: 'Software',
      color: 'plum',
      position: 91,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .solutionsEngineer,
      value: 'SOLUTIONS_ENGINEER',
      label: 'Solutions Engineer',
      color: 'grass',
      position: 92,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.strategy,
      value: 'STRATEGY',
      label: 'Strategy',
      color: 'tomato',
      position: 93,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.student,
      value: 'STUDENT',
      label: 'Student',
      color: 'iris',
      position: 94,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .talentAnalytics,
      value: 'TALENT_ANALYTICS',
      label: 'Talent Analytics',
      color: 'mint',
      position: 95,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.therapy,
      value: 'THERAPY',
      label: 'Therapy',
      color: 'ruby',
      position: 96,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole
        .tourAndTravel,
      value: 'TOUR_AND_TRAVEL',
      label: 'Tour and Travel',
      color: 'bronze',
      position: 97,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.training,
      value: 'TRAINING',
      label: 'Training',
      color: 'jade',
      position: 98,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.translation,
      value: 'TRANSLATION',
      label: 'Translation',
      color: 'gray',
      position: 99,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.transport,
      value: 'TRANSPORT',
      label: 'Transport',
      color: 'blue',
      position: 100,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.unemployed,
      value: 'UNEMPLOYED',
      label: 'Unemployed',
      color: 'red',
      position: 101,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.veterinarian,
      value: 'VETERINARIAN',
      label: 'Veterinarian',
      color: 'green',
      position: 102,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.warehouse,
      value: 'WAREHOUSE',
      label: 'Warehouse',
      color: 'orange',
      position: 103,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.web,
      value: 'WEB',
      label: 'Web',
      color: 'purple',
      position: 104,
    },
    {
      id: PDL_SELECT_OPTION_UNIVERSAL_IDENTIFIERS.personJobSubRole.wellness,
      value: 'WELLNESS',
      label: 'Wellness',
      color: 'yellow',
      position: 105,
    },
  ],
});
