export enum WidgetType {
  VIEW = 'VIEW',
  IFRAME = 'IFRAME',
  FIELDS = 'FIELDS',
  GRAPH = 'GRAPH',
  TIMELINE = 'TIMELINE',
  TASKS = 'TASKS',
  NOTES = 'NOTES',
  FILES = 'FILES',
  EMAILS = 'EMAILS',
  CALENDAR = 'CALENDAR',
  RICH_TEXT = 'RICH_TEXT',
}
