export enum WidgetConfigurationType {
  BAR_CHART_CONFIG = 'BAR_CHART_CONFIG',
  LINE_CHART_CONFIG = 'LINE_CHART_CONFIG',
  PIE_CHART_CONFIG = 'PIE_CHART_CONFIG',
  NUMBER_CHART_CONFIG = 'NUMBER_CHART_CONFIG',
  GAUGE_CHART_CONFIG = 'GAUGE_CHART_CONFIG',
  IFRAME_CONFIG = 'IFRAME_CONFIG',
}
