export const DIRECT_EXECUTION_ERROR_SUB_CODES = {
  WORKSPACE_QUERY_WITHOUT_WORKSPACE: 'WORKSPACE_QUERY_WITHOUT_WORKSPACE',
  WORKSPACE_SCHEMA_UNAVAILABLE: 'WORKSPACE_SCHEMA_UNAVAILABLE',
  UNKNOWN_ROOT_FIELD: 'UNKNOWN_ROOT_FIELD',
  MIXED_CORE_AND_WORKSPACE_FIELDS: 'MIXED_CORE_AND_WORKSPACE_FIELDS',
} as const;
