import {
  type FieldMetadataSettingsMapping,
  FieldMetadataType,
} from 'twenty-shared/types';
import { v4 } from 'uuid';

import { getTsVectorColumnExpressionFromFields } from 'src/engine/workspace-manager/utils/get-ts-vector-column-expression.util';
import { type UniversalFlatFieldMetadata } from 'src/engine/workspace-manager/workspace-migration/universal-flat-entity/types/universal-flat-field-metadata.type';
import { type UniversalFlatObjectMetadata } from 'src/engine/workspace-manager/workspace-migration/universal-flat-entity/types/universal-flat-object-metadata.type';

type BuildDefaultFlatFieldMetadataForCustomObjectArgs = {
  flatObjectMetadata: Pick<
    UniversalFlatObjectMetadata,
    'universalIdentifier' | 'applicationUniversalIdentifier'
  >;
  skipNameField?: boolean;
};

export type DefaultFlatFieldForCustomObjectMaps = ReturnType<
  typeof buildDefaultFlatFieldMetadatasForCustomObject
>;
// This could be replaced totally by an import schema + its transpilation when it's ready
export const buildDefaultFlatFieldMetadatasForCustomObject = ({
  flatObjectMetadata: {
    applicationUniversalIdentifier,
    universalIdentifier: objectMetadataUniversalIdentifier,
  },
  skipNameField = false,
}: BuildDefaultFlatFieldMetadataForCustomObjectArgs) => {
  const createdAt = new Date().toISOString();

  const idField: UniversalFlatFieldMetadata<FieldMetadataType.UUID> = {
    type: FieldMetadataType.UUID,
    isLabelSyncedWithName: false,
    isUnique: true,
    universalIdentifier: v4(),
    name: 'id',
    label: 'Id',
    icon: 'Icon123',
    description: 'Id',
    isNullable: false,
    isActive: true,
    isCustom: false,
    isSystem: true,
    isUIReadOnly: true,
    defaultValue: 'uuid',
    createdAt,
    updatedAt: createdAt,
    options: null,
    standardOverrides: null,
    morphId: null,
    applicationUniversalIdentifier,
    objectMetadataUniversalIdentifier,
    relationTargetObjectMetadataUniversalIdentifier: null,
    relationTargetFieldMetadataUniversalIdentifier: null,
    viewFilterUniversalIdentifiers: [],
    viewFieldUniversalIdentifiers: [],
    kanbanAggregateOperationViewUniversalIdentifiers: [],
    calendarViewUniversalIdentifiers: [],
    mainGroupByFieldMetadataViewUniversalIdentifiers: [],
    universalSettings: null,
  };

  const nameField: UniversalFlatFieldMetadata<FieldMetadataType.TEXT> | null =
    skipNameField
      ? null
      : {
          type: FieldMetadataType.TEXT,
          isLabelSyncedWithName: false,
          isUnique: false,
          universalIdentifier: v4(),
          name: 'name',
          label: 'Name',
          icon: 'IconAbc',
          description: 'Name',
          isNullable: true,
          isActive: true,
          isCustom: false,
          isSystem: false,
          isUIReadOnly: false,
          defaultValue: null,
          createdAt,
          updatedAt: createdAt,
          options: null,
          standardOverrides: null,
          morphId: null,
          applicationUniversalIdentifier,
          objectMetadataUniversalIdentifier,
          relationTargetObjectMetadataUniversalIdentifier: null,
          relationTargetFieldMetadataUniversalIdentifier: null,
          viewFilterUniversalIdentifiers: [],
          viewFieldUniversalIdentifiers: [],
          kanbanAggregateOperationViewUniversalIdentifiers: [],
          calendarViewUniversalIdentifiers: [],
          mainGroupByFieldMetadataViewUniversalIdentifiers: [],
          universalSettings: null,
        };

  const createdAtField: UniversalFlatFieldMetadata<FieldMetadataType.DATE_TIME> =
    {
      type: FieldMetadataType.DATE_TIME,
      isLabelSyncedWithName: false,
      isUnique: false,
      universalIdentifier: v4(),
      name: 'createdAt',
      label: 'Creation date',
      icon: 'IconCalendar',
      description: 'Creation date',
      isNullable: false,
      isActive: true,
      isCustom: false,
      isSystem: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      createdAt,
      updatedAt: createdAt,
      options: null,
      standardOverrides: null,
      morphId: null,
      applicationUniversalIdentifier,
      objectMetadataUniversalIdentifier,
      relationTargetObjectMetadataUniversalIdentifier: null,
      relationTargetFieldMetadataUniversalIdentifier: null,
      viewFilterUniversalIdentifiers: [],
      viewFieldUniversalIdentifiers: [],
      kanbanAggregateOperationViewUniversalIdentifiers: [],
      calendarViewUniversalIdentifiers: [],
      mainGroupByFieldMetadataViewUniversalIdentifiers: [],
      universalSettings: null,
    };

  const updatedAtField: UniversalFlatFieldMetadata<FieldMetadataType.DATE_TIME> =
    {
      type: FieldMetadataType.DATE_TIME,
      isLabelSyncedWithName: false,
      isUnique: false,
      universalIdentifier: v4(),
      name: 'updatedAt',
      label: 'Last update',
      icon: 'IconCalendarClock',
      description: 'Last time the record was changed',
      isNullable: false,
      isActive: true,
      isCustom: false,
      isSystem: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      createdAt,
      updatedAt: createdAt,
      options: null,
      standardOverrides: null,
      morphId: null,
      applicationUniversalIdentifier,
      objectMetadataUniversalIdentifier,
      relationTargetObjectMetadataUniversalIdentifier: null,
      relationTargetFieldMetadataUniversalIdentifier: null,
      viewFilterUniversalIdentifiers: [],
      viewFieldUniversalIdentifiers: [],
      kanbanAggregateOperationViewUniversalIdentifiers: [],
      calendarViewUniversalIdentifiers: [],
      mainGroupByFieldMetadataViewUniversalIdentifiers: [],
      universalSettings: null,
    };

  const deletedAtField: UniversalFlatFieldMetadata<FieldMetadataType.DATE_TIME> =
    {
      type: FieldMetadataType.DATE_TIME,
      isLabelSyncedWithName: false,
      isUnique: false,
      universalIdentifier: v4(),
      name: 'deletedAt',
      label: 'Deleted at',
      icon: 'IconCalendarClock',
      description: 'Deletion date',
      isNullable: true,
      isActive: true,
      isCustom: false,
      isSystem: false,
      isUIReadOnly: true,
      defaultValue: null,
      createdAt,
      updatedAt: createdAt,
      options: null,
      standardOverrides: null,
      morphId: null,
      applicationUniversalIdentifier,
      objectMetadataUniversalIdentifier,
      relationTargetObjectMetadataUniversalIdentifier: null,
      relationTargetFieldMetadataUniversalIdentifier: null,
      viewFilterUniversalIdentifiers: [],
      viewFieldUniversalIdentifiers: [],
      kanbanAggregateOperationViewUniversalIdentifiers: [],
      calendarViewUniversalIdentifiers: [],
      mainGroupByFieldMetadataViewUniversalIdentifiers: [],
      universalSettings: null,
    };

  const createdByField: UniversalFlatFieldMetadata<FieldMetadataType.ACTOR> = {
    type: FieldMetadataType.ACTOR,
    isLabelSyncedWithName: false,
    isUnique: false,
    universalIdentifier: v4(),
    name: 'createdBy',
    label: 'Created by',
    icon: 'IconCreativeCommonsSa',
    description: 'The creator of the record',
    isNullable: false,
    isActive: true,
    isCustom: false,
    isSystem: false,
    isUIReadOnly: true,
    defaultValue: { name: "''", source: "'MANUAL'" },
    createdAt,
    updatedAt: createdAt,
    options: null,
    standardOverrides: null,
    morphId: null,
    applicationUniversalIdentifier,
    objectMetadataUniversalIdentifier,
    relationTargetObjectMetadataUniversalIdentifier: null,
    relationTargetFieldMetadataUniversalIdentifier: null,
    viewFilterUniversalIdentifiers: [],
    viewFieldUniversalIdentifiers: [],
    kanbanAggregateOperationViewUniversalIdentifiers: [],
    calendarViewUniversalIdentifiers: [],
    mainGroupByFieldMetadataViewUniversalIdentifiers: [],
    universalSettings: null,
  };

  const updatedByField: UniversalFlatFieldMetadata<FieldMetadataType.ACTOR> = {
    type: FieldMetadataType.ACTOR,
    isLabelSyncedWithName: false,
    isUnique: false,
    universalIdentifier: v4(),
    name: 'updatedBy',
    label: 'Updated by',
    icon: 'IconUserCircle',
    description: 'The workspace member who last updated the record',
    isNullable: false,
    isActive: true,
    isCustom: false,
    isSystem: false,
    isUIReadOnly: true,
    defaultValue: { name: "''", source: "'MANUAL'" },
    createdAt,
    updatedAt: createdAt,
    options: null,
    standardOverrides: null,
    morphId: null,
    applicationUniversalIdentifier,
    objectMetadataUniversalIdentifier,
    relationTargetObjectMetadataUniversalIdentifier: null,
    relationTargetFieldMetadataUniversalIdentifier: null,
    viewFilterUniversalIdentifiers: [],
    viewFieldUniversalIdentifiers: [],
    kanbanAggregateOperationViewUniversalIdentifiers: [],
    calendarViewUniversalIdentifiers: [],
    mainGroupByFieldMetadataViewUniversalIdentifiers: [],
    universalSettings: null,
  };

  const positionField: UniversalFlatFieldMetadata<FieldMetadataType.POSITION> =
    {
      type: FieldMetadataType.POSITION,
      isLabelSyncedWithName: false,
      isUnique: false,
      universalIdentifier: v4(),
      name: 'position',
      label: 'Position',
      icon: 'IconHierarchy2',
      description: 'Position',
      isNullable: false,
      isActive: true,
      isCustom: false,
      isSystem: true,
      isUIReadOnly: true,
      defaultValue: 0,
      createdAt,
      updatedAt: createdAt,
      options: null,
      standardOverrides: null,
      morphId: null,
      applicationUniversalIdentifier,
      objectMetadataUniversalIdentifier,
      relationTargetObjectMetadataUniversalIdentifier: null,
      relationTargetFieldMetadataUniversalIdentifier: null,
      viewFilterUniversalIdentifiers: [],
      viewFieldUniversalIdentifiers: [],
      kanbanAggregateOperationViewUniversalIdentifiers: [],
      calendarViewUniversalIdentifiers: [],
      mainGroupByFieldMetadataViewUniversalIdentifiers: [],
      universalSettings: null,
    };

  const searchVectorSettings: FieldMetadataSettingsMapping['TS_VECTOR'] = {
    asExpression: getTsVectorColumnExpressionFromFields(
      nameField ? [nameField] : [],
    ),
    generatedType: 'STORED',
  };
  const searchVectorField: UniversalFlatFieldMetadata<FieldMetadataType.TS_VECTOR> =
    {
      type: FieldMetadataType.TS_VECTOR,
      isLabelSyncedWithName: false,
      isUnique: false,
      universalIdentifier: v4(),
      name: 'searchVector',
      label: 'Search vector',
      icon: 'IconSearch',
      description: 'Search vector',
      isNullable: true,
      isActive: true,
      isCustom: false,
      isSystem: true,
      isUIReadOnly: true,
      defaultValue: null,
      createdAt,
      updatedAt: createdAt,
      options: null,
      standardOverrides: null,
      morphId: null,
      applicationUniversalIdentifier,
      objectMetadataUniversalIdentifier,
      relationTargetObjectMetadataUniversalIdentifier: null,
      relationTargetFieldMetadataUniversalIdentifier: null,
      viewFilterUniversalIdentifiers: [],
      viewFieldUniversalIdentifiers: [],
      kanbanAggregateOperationViewUniversalIdentifiers: [],
      calendarViewUniversalIdentifiers: [],
      mainGroupByFieldMetadataViewUniversalIdentifiers: [],
      universalSettings: searchVectorSettings,
    };

  return {
    fields: {
      idField,
      ...(nameField && { nameField }),
      createdAtField,
      updatedAtField,
      updatedByField,
      deletedAtField,
      createdByField,
      positionField,
      searchVectorField,
    },
  } as const satisfies {
    fields: Record<string, UniversalFlatFieldMetadata>;
  };
};
