export enum CommandMenuPages {
  Root = 'root',
  ViewRecord = 'view-record',
  MergeRecords = 'merge-records',
  UpdateRecords = 'update-records',
  ViewEmailThread = 'view-email-thread',
  ViewCalendarEvent = 'view-calendar-event',
  EditRichText = 'edit-rich-text',
  Copilot = 'copilot',
  WorkflowTriggerSelectType = 'workflow-trigger-select-type',
  WorkflowStepCreate = 'workflow-step-create',
  WorkflowStepEditType = 'workflow-step-edit-type',
  WorkflowStepView = 'workflow-step-view',
  WorkflowStepEdit = 'workflow-step-edit',
  WorkflowRunStepView = 'workflow-run-step-view',
  SearchRecords = 'search-records',
  AskAI = 'ask-ai',
  ViewPreviousAIChats = 'view-previous-ai-chats',
  PageLayoutWidgetTypeSelect = 'page-layout-widget-type-select',
  PageLayoutGraphTypeSelect = 'page-layout-graph-type-select',
  PageLayoutGraphFilter = 'page-layout-graph-filter',
  PageLayoutIframeSettings = 'page-layout-iframe-settings',
  PageLayoutTabSettings = 'page-layout-tab-settings',
}
