export enum GmailDefaultMessageFolder {
  CATEGORY_PROMOTIONS = 'CATEGORY_PROMOTIONS',
  CATEGORY_SOCIAL = 'CATEGORY_SOCIAL',
  CATEGORY_FORUMS = 'CATEGORY_FORUMS',
  CATEGORY_UPDATES = 'CATEGORY_UPDATES',
}
