export enum CardType {
  FieldCard = 'FieldCard',
  TimelineCard = 'TimelineCard',
  TaskCard = 'TaskCard',
  NoteCard = 'NoteCard',
  CommentCard = 'CommentCard',
  FileCard = 'FileCard',
  EmailCard = 'EmailCard',
  CalendarCard = 'CalendarCard',
  WorkflowCard = 'WorkflowCard',
  WorkflowVersionCard = 'WorkflowVersionCard',
  WorkflowRunCard = 'WorkflowRunCard',
  FieldRichTextCard = 'FieldRichTextCard',
  DashboardCard = 'DashboardCard',
}
