import { type RecordGqlOperationGqlRecordFields } from 'twenty-shared/types';

export const COAT_DETAIL_GQL_FIELDS: RecordGqlOperationGqlRecordFields = {
  id: true,
  name: true,
  createdAt: true,
  contractId: true,
  contractName: true,
  contractType: true,
  program: true,
  programId: true,
  status: true,
  coatExportStatus: true,
  source: true,
  customerEmail: true,
  customerFirstName: true,
  customerLastName: true,
  customerPhone: true,
  customerGender: true,
  customerBirthday: true,
  customerStreet: true,
  customerCity: true,
  customerPostcode: true,
  customerCountry: true,
  valueGrossBase: true,
  currencyBase: true,
  durationMonths: true,
  startDate: true,
  endDate: true,
  completionDate: true,
  paymentTerms: true,
  specialAgreements: true,
  closerEmail: true,
  bexioId: true,
};
