export const APPLICATION_UNINSTALL_STEPS = [
  'UNINSTALL_HOOK',
  'COMPUTE_METADATA_TO_DELETE',
  'RUN_WORKSPACE_MIGRATION',
  'DELETE_APPLICATION',
  'CLEANUP_RUNTIME_RESOURCES',
] as const;

export type ApplicationUninstallStep =
  (typeof APPLICATION_UNINSTALL_STEPS)[number];
