export enum SubscriptionChannel {
  DATABASE_EVENT_CHANNEL = 'DATABASE_EVENT_CHANNEL',
  LOGIC_FUNCTION_LOGS_CHANNEL = 'LOGIC_FUNCTION_LOGS_CHANNEL',
  EVENT_STREAM_CHANNEL = 'EVENT_STREAM_CHANNEL',
}
