export enum SubscriptionChannel {
  DATABASE_EVENT_CHANNEL = 'DATABASE_EVENT_CHANNEL',
  DATABASE_BATCH_EVENTS_CHANNEL = 'DATABASE_BATCH_EVENTS_CHANNEL',
  SERVERLESS_FUNCTION_LOGS_CHANNEL = 'SERVERLESS_FUNCTION_LOGS_CHANNEL',
}
