export enum MessageImportManagerExceptionCode {
  HANDLE_REQUIRED = 'HANDLE_REQUIRED',
  SYNC_CURSOR_REQUIRED = 'SYNC_CURSOR_REQUIRED',
  IMAP_USERNAME_REQUIRED = 'IMAP_USERNAME_REQUIRED',
  ACCESS_TOKEN_REQUIRED = 'ACCESS_TOKEN_REQUIRED',
  SMTP_HOST_REQUIRED = 'SMTP_HOST_REQUIRED',
}
