export enum FeatureFlagKey {
  IsEventObjectEnabled = 'IS_EVENT_OBJECT_ENABLED',
  IsAirtableIntegrationEnabled = 'IS_AIRTABLE_INTEGRATION_ENABLED',
  IsPostgreSQLIntegrationEnabled = 'IS_POSTGRESQL_INTEGRATION_ENABLED',
  IsStripeIntegrationEnabled = 'IS_STRIPE_INTEGRATION_ENABLED',
  IsCopilotEnabled = 'IS_COPILOT_ENABLED',
  IsFreeAccessEnabled = 'IS_FREE_ACCESS_ENABLED',
  IsFunctionSettingsEnabled = 'IS_FUNCTION_SETTINGS_ENABLED',
  IsWorkflowEnabled = 'IS_WORKFLOW_ENABLED',
  IsMessageThreadSubscriberEnabled = 'IS_MESSAGE_THREAD_SUBSCRIBER_ENABLED',
  IsQueryRunnerTwentyORMEnabled = 'IS_QUERY_RUNNER_TWENTY_ORM_ENABLED',
  IsWorkspaceFavoriteEnabled = 'IS_WORKSPACE_FAVORITE_ENABLED',
  IsGmailSendEmailScopeEnabled = 'IS_GMAIL_SEND_EMAIL_SCOPE_ENABLED',
  IsAnalyticsV2Enabled = 'IS_ANALYTICS_V2_ENABLED',
  IsUniqueIndexesEnabled = 'IS_UNIQUE_INDEXES_ENABLED',
}
