export enum FeatureFlagKey {
  IsEventObjectEnabled = 'IS_EVENT_OBJECT_ENABLED',
  IsAirtableIntegrationEnabled = 'IS_AIRTABLE_INTEGRATION_ENABLED',
  IsPostgreSQLIntegrationEnabled = 'IS_POSTGRESQL_INTEGRATION_ENABLED',
  IsStripeIntegrationEnabled = 'IS_STRIPE_INTEGRATION_ENABLED',
  IsCopilotEnabled = 'IS_COPILOT_ENABLED',
  IsWorkflowEnabled = 'IS_WORKFLOW_ENABLED',
  IsAnalyticsV2Enabled = 'IS_ANALYTICS_V2_ENABLED',
  IsUniqueIndexesEnabled = 'IS_UNIQUE_INDEXES_ENABLED',
  IsJsonFilterEnabled = 'IS_JSON_FILTER_ENABLED',
  IsCustomDomainEnabled = 'IS_CUSTOM_DOMAIN_ENABLED',
  IsApprovedAccessDomainsEnabled = 'IS_APPROVED_ACCESS_DOMAINS_ENABLED',
  IsNewRelationEnabled = 'IS_NEW_RELATION_ENABLED',
  IsPermissionsV2Enabled = 'IS_PERMISSIONS_V2_ENABLED',
}
