import { defineObject, FieldType } from 'twenty-sdk/define';
import {
  TICKET_OBJECT_ID,
  TICKET_TITLE_FIELD_ID,
  TICKET_DESCRIPTION_FIELD_ID,
  TICKET_STATUS_FIELD_ID,
  TICKET_PRIORITY_FIELD_ID,
  TICKET_MULTICA_ISSUE_ID_FIELD_ID,
  TICKET_MULTICA_IDENTIFIER_FIELD_ID,
  TICKET_LAST_SYNCED_FROM_MULTICA_FIELD_ID,
  TICKET_ASSIGNEE_FIELD_ID,
  TICKET_DUE_DATE_FIELD_ID,
  TICKET_START_DATE_FIELD_ID,
  TICKET_LABELS_FIELD_ID,
  TICKET_METADATA_FIELD_ID,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: TICKET_OBJECT_ID,
  nameSingular: 'xopureTicket',
  namePlural: 'xopureTickets',
  labelSingular: 'Ticket',
  labelPlural: 'Tickets',
  description: 'Support tickets synced bidirectionally with Multica\'s Support project.',
  icon: 'IconTicket',
  labelIdentifierFieldMetadataUniversalIdentifier: TICKET_TITLE_FIELD_ID,
  fields: [
    {
      universalIdentifier: TICKET_TITLE_FIELD_ID,
      type: FieldType.TEXT,
      name: 'title',
      label: 'Title',
      icon: 'IconTypography',
    },
    {
      universalIdentifier: TICKET_DESCRIPTION_FIELD_ID,
      type: FieldType.TEXT,
      name: 'description',
      label: 'Description',
      icon: 'IconFileDescription',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: TICKET_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      icon: 'IconProgressCheck',
      defaultValue: "'OPEN'",
      options: [
        { id: 'e6b346b7-30e6-4302-9a15-8f02614df5d1', value: 'OPEN', label: 'Open', position: 0, color: 'blue' },
        { id: 'c4e65272-1f29-4584-8afe-d2aa6aa7ac1d', value: 'IN_PROGRESS', label: 'In Progress', position: 1, color: 'yellow' },
        { id: '75b27e5a-96a5-44c1-b5dd-f2a12d7ca6b2', value: 'WAITING', label: 'Waiting', position: 2, color: 'orange' },
        { id: '9b2867ca-e626-42da-b1c5-0a5df73843aa', value: 'RESOLVED', label: 'Resolved', position: 3, color: 'green' },
        { id: '3847489b-2a1e-46ba-80df-ff2ad75f74dc', value: 'CLOSED', label: 'Closed', position: 4, color: 'gray' },
      ],
    },
    {
      universalIdentifier: TICKET_PRIORITY_FIELD_ID,
      type: FieldType.SELECT,
      name: 'priority',
      label: 'Priority',
      icon: 'IconFlag',
      defaultValue: "'MEDIUM'",
      options: [
        { id: 'c7f69082-5bf6-4974-9b83-19a576c8837e', value: 'URGENT', label: 'Urgent', position: 0, color: 'red' },
        { id: '0a73c8fd-90af-4f33-bdda-685cdc4249cb', value: 'HIGH', label: 'High', position: 1, color: 'orange' },
        { id: '76b89608-36e6-45b4-bdf6-2e9ff5830996', value: 'MEDIUM', label: 'Medium', position: 2, color: 'yellow' },
        { id: 'b0569ded-7613-4468-b7c8-0a92b6cb148a', value: 'LOW', label: 'Low', position: 3, color: 'gray' },
      ],
    },
    {
      universalIdentifier: TICKET_MULTICA_ISSUE_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'multicaIssueId',
      label: 'Multica Issue ID',
      icon: 'IconDatabase',
      isUnique: true,
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: TICKET_MULTICA_IDENTIFIER_FIELD_ID,
      type: FieldType.TEXT,
      name: 'multicaIdentifier',
      label: 'Multica Identifier',
      icon: 'IconHash',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: TICKET_LAST_SYNCED_FROM_MULTICA_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'lastSyncedFromMulticaAt',
      label: 'Last synced from Multica at',
      icon: 'IconRefresh',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: TICKET_ASSIGNEE_FIELD_ID,
      type: FieldType.TEXT,
      name: 'assignee',
      label: 'Assignee',
      icon: 'IconUser',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: TICKET_DUE_DATE_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'dueDate',
      label: 'Due date',
      icon: 'IconCalendarDue',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: TICKET_START_DATE_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'startDate',
      label: 'Start date',
      icon: 'IconCalendarEvent',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: TICKET_LABELS_FIELD_ID,
      type: FieldType.TEXT,
      name: 'labels',
      label: 'Labels',
      icon: 'IconTag',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: TICKET_METADATA_FIELD_ID,
      type: FieldType.TEXT,
      name: 'metadata',
      label: 'Multica metadata',
      icon: 'IconJson',
      isNullable: true,
      defaultValue: null,
    },
  ],
});
