export const LICENSE_PRICE_ENTERPRISE_MONTH_ID =
  'LICENSE_PRICE_ENTERPRISE_MONTH_ID';
export const LICENSE_PRICE_PRO_MONTH_ID = 'LICENSE_PRICE_PRO_MONTH_ID';
export const LICENSE_PRICE_ENTERPRISE_YEAR_ID =
  'LICENSE_PRICE_ENTERPRISE_YEAR_ID';
export const LICENSE_PRICE_PRO_YEAR_ID = 'LICENSE_PRICE_PRO_YEAR_ID';

export const METER_PRICE_ENTERPRISE_MONTH_ID =
  'METER_PRICE_ENTERPRISE_MONTH_ID';
export const METER_PRICE_PRO_MONTH_ID = 'METER_PRICE_PRO_MONTH_ID';
export const METER_PRICE_ENTERPRISE_YEAR_ID = 'METER_PRICE_ENTERPRISE_YEAR_ID';
export const METER_PRICE_PRO_YEAR_ID = 'METER_PRICE_PRO_YEAR_ID';

export const METER_PRICE_ENTERPRISE_MONTH_TIER_LOW_ID =
  'METER_PRICE_ENTERPRISE_MONTH_TIER_LOW_ID';
export const METER_PRICE_ENTERPRISE_MONTH_TIER_HIGH_ID =
  'METER_PRICE_ENTERPRISE_MONTH_TIER_HIGH_ID';
export const METER_PRICE_PRO_MONTH_TIER_LOW_ID =
  'METER_PRICE_PRO_MONTH_TIER_LOW_ID';
export const METER_PRICE_PRO_MONTH_TIER_HIGH_ID =
  'METER_PRICE_PRO_MONTH_TIER_HIGH_ID';
