const PARTICIPANT_FIELD_NAMES = [
  'From',
  'Van',
  'De',
  'Von',
  'Fra',
  'Från',
  'Da',
  'Od',
  'Kimden',
  'Gönderen',
  'Lähettäjä',
  'Feladó',
  'Odesílatel',
  'Expeditor',
  'Nadawca',
  'Απ[όο]',
  'От',
  'Від',
  '差出人',
  '送信者',
  '发件人',
  '寄件者',
  '보낸\\s?사람',
  'To',
  'Cc',
  'Кому',
  '宛先',
  '收件人',
  '收件者',
  '받는\\s?사람',
];

const SUPPORTING_FIELD_NAMES = [
  'Subject',
  'Date',
  'Datum',
  'Sent',
  'Sendt',
  'Skickat',
  'Envoyé',
  'Gesendet',
  'Verzonden',
  'Enviado',
  'Enviada em',
  'Inviato',
  'Gönderilen',
  'Lähetetty',
  'Elküldve',
  'Тема',
  'Отправлено',
  'Дата',
  '送信日時',
  '件名',
  '主题',
  '日期',
  '主旨',
  '제목',
  '보낸\\s?날짜',
];

const HEADER_FIELD_NAMES = [
  ...PARTICIPANT_FIELD_NAMES,
  ...SUPPORTING_FIELD_NAMES,
].join('|');

const ORIGINAL_MESSAGE_TITLES = [
  'Original Message',
  'Reply Message',
  'Ursprüngliche Nachricht',
  'Antwort Nachricht',
  'Oprindelig meddelelse',
  'Oprindelig Besked',
  "Message d'origine",
  'Message original',
  'Mensaje original',
  'Messaggio originale',
  'Mensagem original',
  'Oorspronkelijk bericht',
  'Ursprungligt meddelande',
  'Opprinnelig melding',
  'Alkuperäinen viesti',
  'Wiadomość oryginalna',
  'Orijinal ileti',
  'Исходное сообщение',
  '原始邮件',
  '原始郵件',
  '元のメッセージ',
  '원본 메시지',
].join('|');

const WROTE_OPENERS = [
  'On',
  'Le',
  'El',
  'Il',
  'Em',
  'Am',
  'Op',
  'Den',
  'På',
  'Vào',
  'W dniu',
  'Dnia',
  'В',
  'Il giorno',
].join('|');

const WROTE_VERBS = [
  'wrote',
  'a écrit',
  'escribió',
  'scritto',
  'escreveu',
  'schrieb',
  'schreef',
  'geschreven',
  'verzond',
  'skrev',
  'napisał',
  'pisze',
  'kirjoitti',
  'đã viết',
  'yazdı',
  'έγραψε',
  'написал',
  'писал',
].join('|');

const LOCALIZED_ATTRIBUTION_LINES = [
  /^\s*在[\s\S]{0,200}?写道[:：]\s*(?:\n|$)/,
  /^\s*[^\n]{0,200}?於[\s\S]{0,80}?寫道[:：]\s*(?:\n|$)/,
  /^\s*20\d{2}[\s\S]{0,200}?のメッセージ[:：]\s*(?:\n|$)/,
  /^\s*[^\n]{0,200}?さん(?:は|が)[\s\S]{0,40}?書きました[:：]\s*(?:\n|$)/,
  /^\s*20\d{2}[\s\S]{0,200}?작성[:：]\s*(?:\n|$)/,
  /^\s*[^\n]{0,200}?님이\s[\s\S]{0,40}?작성했습니다[:：]\s*(?:\n|$)/,
  /^\s*\S{2,4},\s\d{1,2}\s\S{3,12}\s20\d{2}\s?(?:г\.)?[\s\S]{0,120}?(?:написал|писал)(?:\(а\))?[:：]\s*(?:\n|$)/,
  /^\s*\d{1,2}[./]\d{1,2}[./]\d{2,4}[\s\S]{0,120}?(?:пользователь|написал)[\s\S]{0,80}?[:：]\s*(?:\n|$)/,
];

export const QUOTE_HEADER_PATTERNS = {
  caretLine: /^\s*>/,
  headerField: new RegExp(
    `^\\s*[*]?(${HEADER_FIELD_NAMES})\\s?[:：][*]?(\\s|$)`,
    'i',
  ),
  participantField: new RegExp(
    `^\\s*[*]?(${PARTICIPANT_FIELD_NAMES.join('|')})\\s?[:：][*]?(\\s|$)`,
    'i',
  ),
  originalMessageBanner: new RegExp(
    `^\\s*-{2,}\\s*(${ORIGINAL_MESSAGE_TITLES})\\s*-{2,}`,
    'i',
  ),
  forwardedBanner:
    /^\s*-{2,}\s*(Forwarded message|Weitergeleitete Nachricht|Message transféré|Mensaje reenviado|Doorgestuurd bericht|Пересылаемое сообщение|転送されたメッセージ|已转发邮件)\s*-{2,}/i,
  wroteAttribution: new RegExp(
    `^\\s*-*\\s*(${WROTE_OPENERS})\\s[\\s\\S]{0,300}?(${WROTE_VERBS})[^\\n]{0,120}?(?:[:：]|-{2,})\\s*(?:\\n|$)`,
    'i',
  ),
  wroteAttributionEndingLine: new RegExp(
    `-*\\s*\\b(${WROTE_OPENERS})\\s[^\\n]{0,200}?(${WROTE_VERBS})\\s?[:：]\\s*-*$`,
    'i',
  ),
  localizedAttributionLines: LOCALIZED_ATTRIBUTION_LINES,
  datePersonAttribution:
    /^\s*(\d+\/\d+\/\d+|\d+\.\d+\.\d+)[^\n]*<[\w.+-]+@[\w-]+\.[\w.]{2,}>/,
  wrappedLink: /<(https?:\/\/[^>]*)>/,
  maskedLink: /@@(https?:\/\/[^>@]*)@@/,
} as const;
