import { QueryRunner } from 'typeorm';

import { RegisteredInstanceCommand } from 'src/engine/core-modules/upgrade/decorators/registered-instance-command.decorator';
import { FastInstanceCommand } from 'src/engine/core-modules/upgrade/interfaces/fast-instance-command.interface';

@RegisteredInstanceCommand('1.22.0', 1775749486425)
export class AutoGeneratedFastInstanceCommand implements FastInstanceCommand {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('CREATE TABLE "core"."upgradeMigration" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "status" character varying NOT NULL, "attempt" integer NOT NULL DEFAULT \'1\', "executedByVersion" character varying NOT NULL, "errorMessage" text, "workspaceId" uuid, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a43ea44de07f51fdc55b88af2ad" PRIMARY KEY ("id"))');
    await queryRunner.query('CREATE UNIQUE INDEX "UQ_upgrade_migration_workspace" ON "core"."upgradeMigration" ("name", "attempt", "workspaceId") WHERE "workspaceId" IS NOT NULL');
    await queryRunner.query('CREATE UNIQUE INDEX "UQ_upgrade_migration_instance" ON "core"."upgradeMigration" ("name", "attempt") WHERE "workspaceId" IS NULL');
    await queryRunner.query('ALTER TABLE "core"."commandMenuItem" ADD "payload" jsonb');
    await queryRunner.query('ALTER TYPE "core"."pageLayoutWidget_type_enum" RENAME TO "pageLayoutWidget_type_enum_old"');
    await queryRunner.query('CREATE TYPE "core"."pageLayoutWidget_type_enum" AS ENUM(\'VIEW\', \'IFRAME\', \'FIELD\', \'FIELDS\', \'GRAPH\', \'STANDALONE_RICH_TEXT\', \'TIMELINE\', \'TASKS\', \'NOTES\', \'FILES\', \'EMAILS\', \'CALENDAR\', \'FIELD_RICH_TEXT\', \'WORKFLOW\', \'WORKFLOW_VERSION\', \'WORKFLOW_RUN\', \'FRONT_COMPONENT\', \'RECORD_TABLE\', \'EMAIL_THREAD\')');
    await queryRunner.query('ALTER TABLE "core"."pageLayoutWidget" ALTER COLUMN "type" DROP DEFAULT');
    await queryRunner.query('ALTER TABLE "core"."pageLayoutWidget" ALTER COLUMN "type" TYPE "core"."pageLayoutWidget_type_enum" USING "type"::"text"::"core"."pageLayoutWidget_type_enum"');
    await queryRunner.query('ALTER TABLE "core"."pageLayoutWidget" ALTER COLUMN "type" SET DEFAULT \'VIEW\'');
    await queryRunner.query('DROP TYPE "core"."pageLayoutWidget_type_enum_old"');
    await queryRunner.query('CREATE INDEX "IDX_PERMISSION_FLAG_ROLE_ID" ON "core"."permissionFlag" ("roleId") ');
    await queryRunner.query('ALTER TABLE "core"."upgradeMigration" ADD CONSTRAINT "FK_77f64a697c55f8802592bd7eeba" FOREIGN KEY ("workspaceId") REFERENCES "core"."workspace"("id") ON DELETE CASCADE ON UPDATE NO ACTION');
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('ALTER TABLE "core"."upgradeMigration" DROP CONSTRAINT "FK_77f64a697c55f8802592bd7eeba"');
    await queryRunner.query('DROP INDEX "core"."IDX_PERMISSION_FLAG_ROLE_ID"');
    await queryRunner.query('CREATE TYPE "core"."pageLayoutWidget_type_enum_old" AS ENUM(\'CALENDAR\', \'EMAILS\', \'FIELD\', \'FIELDS\', \'FIELD_RICH_TEXT\', \'FILES\', \'FRONT_COMPONENT\', \'GRAPH\', \'IFRAME\', \'NOTES\', \'RECORD_TABLE\', \'STANDALONE_RICH_TEXT\', \'TASKS\', \'TIMELINE\', \'VIEW\', \'WORKFLOW\', \'WORKFLOW_RUN\', \'WORKFLOW_VERSION\')');
    await queryRunner.query('ALTER TABLE "core"."pageLayoutWidget" ALTER COLUMN "type" DROP DEFAULT');
    await queryRunner.query('ALTER TABLE "core"."pageLayoutWidget" ALTER COLUMN "type" TYPE "core"."pageLayoutWidget_type_enum_old" USING "type"::"text"::"core"."pageLayoutWidget_type_enum_old"');
    await queryRunner.query('ALTER TABLE "core"."pageLayoutWidget" ALTER COLUMN "type" SET DEFAULT \'VIEW\'');
    await queryRunner.query('DROP TYPE "core"."pageLayoutWidget_type_enum"');
    await queryRunner.query('ALTER TYPE "core"."pageLayoutWidget_type_enum_old" RENAME TO "pageLayoutWidget_type_enum"');
    await queryRunner.query('ALTER TABLE "core"."commandMenuItem" DROP COLUMN "payload"');
    await queryRunner.query('DROP INDEX "core"."UQ_upgrade_migration_instance"');
    await queryRunner.query('DROP INDEX "core"."UQ_upgrade_migration_workspace"');
    await queryRunner.query('DROP TABLE "core"."upgradeMigration"');
  }
}
