import { defineView, ViewKey } from 'twenty-sdk/define';

import {
  ASSIGNMENT_TEAM_MEMBER_IS_ACTIVE_FIELD_UNIVERSAL_IDENTIFIER,
  ASSIGNMENT_TEAM_MEMBER_OBJECT_UNIVERSAL_IDENTIFIER,
  ASSIGNMENT_TEAM_MEMBER_ROLE_FIELD_UNIVERSAL_IDENTIFIER,
  ASSIGNMENT_TEAM_MEMBER_SEARCH_ASSIGNMENT_FIELD_UNIVERSAL_IDENTIFIER,
  ASSIGNMENT_TEAM_MEMBER_WORKSPACE_MEMBER_FIELD_UNIVERSAL_IDENTIFIER,
  ASSIGNMENT_TEAM_MEMBERS_VIEW_IS_ACTIVE_FIELD_UNIVERSAL_IDENTIFIER,
  ASSIGNMENT_TEAM_MEMBERS_VIEW_ROLE_FIELD_UNIVERSAL_IDENTIFIER,
  ASSIGNMENT_TEAM_MEMBERS_VIEW_SEARCH_ASSIGNMENT_FIELD_UNIVERSAL_IDENTIFIER,
  ASSIGNMENT_TEAM_MEMBERS_VIEW_UNIVERSAL_IDENTIFIER,
  ASSIGNMENT_TEAM_MEMBERS_VIEW_WORKSPACE_MEMBER_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineView({
  universalIdentifier: ASSIGNMENT_TEAM_MEMBERS_VIEW_UNIVERSAL_IDENTIFIER,
  name: 'All Assignment Team Members',
  objectUniversalIdentifier: ASSIGNMENT_TEAM_MEMBER_OBJECT_UNIVERSAL_IDENTIFIER,
  icon: 'IconUsers',
  key: ViewKey.INDEX,
  position: 0,
  fields: [
    {
      universalIdentifier:
        ASSIGNMENT_TEAM_MEMBERS_VIEW_SEARCH_ASSIGNMENT_FIELD_UNIVERSAL_IDENTIFIER,
      fieldMetadataUniversalIdentifier:
        ASSIGNMENT_TEAM_MEMBER_SEARCH_ASSIGNMENT_FIELD_UNIVERSAL_IDENTIFIER,
      position: 0,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier:
        ASSIGNMENT_TEAM_MEMBERS_VIEW_WORKSPACE_MEMBER_FIELD_UNIVERSAL_IDENTIFIER,
      fieldMetadataUniversalIdentifier:
        ASSIGNMENT_TEAM_MEMBER_WORKSPACE_MEMBER_FIELD_UNIVERSAL_IDENTIFIER,
      position: 1,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier:
        ASSIGNMENT_TEAM_MEMBERS_VIEW_ROLE_FIELD_UNIVERSAL_IDENTIFIER,
      fieldMetadataUniversalIdentifier:
        ASSIGNMENT_TEAM_MEMBER_ROLE_FIELD_UNIVERSAL_IDENTIFIER,
      position: 2,
      isVisible: true,
      size: 160,
    },
    {
      universalIdentifier:
        ASSIGNMENT_TEAM_MEMBERS_VIEW_IS_ACTIVE_FIELD_UNIVERSAL_IDENTIFIER,
      fieldMetadataUniversalIdentifier:
        ASSIGNMENT_TEAM_MEMBER_IS_ACTIVE_FIELD_UNIVERSAL_IDENTIFIER,
      position: 3,
      isVisible: true,
    },
  ],
});
