// This query cannot be put in the graphQL folder because it cannot be generated by the graphQL codegen.
import { USER_QUERY_FRAGMENT } from '@/users/graphql/fragments/userQueryFragment';
import { gql } from '@apollo/client';

export const GET_CURRENT_USER = gql`
  ${USER_QUERY_FRAGMENT}
  query GetCurrentUser {
    currentUser {
      ...UserQueryFragment
    }
  }
`;
