const COLORS = {
  bg: '#ffffff',
  fg: '#1c1c1c',
  muted: '#1c1c1c99',
  subtle: '#1c1c1c66',
  border: '#1c1c1c1a',
  accent: '#4a38f5',
  accentSoft: 'rgba(74, 56, 245, 0.08)',
  mutedBg: '#f4f4f4',
} as const;

const FONT =
  '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif';
const MONO = '"Azeret Mono", ui-monospace, monospace';

export const PLAYBOOK_STYLES = {
  root: {
    display: 'flex',
    justifyContent: 'center',
    width: '100%',
    minHeight: 'calc(100dvh - 56px)',
    boxSizing: 'border-box' as const,
    padding: 32,
    fontFamily: FONT,
    color: COLORS.fg,
    background: COLORS.bg,
  },
  article: {
    width: '100%',
    maxWidth: 720,
  },
  kicker: {
    fontFamily: MONO,
    fontSize: 11,
    letterSpacing: 1.4,
    textTransform: 'uppercase' as const,
    color: COLORS.accent,
    margin: '0 0 8px',
  },
  title: {
    fontSize: 28,
    fontWeight: 500,
    letterSpacing: -0.4,
    margin: '0 0 8px',
  },
  lede: {
    color: COLORS.muted,
    fontSize: 15,
    lineHeight: '22px',
    margin: '0 0 28px',
  },
  step: {
    display: 'grid',
    gridTemplateColumns: '36px 1fr',
    gap: 16,
    padding: '20px 0',
    borderTop: `1px solid ${COLORS.border}`,
  },
  lastStep: {
    display: 'grid',
    gridTemplateColumns: '36px 1fr',
    gap: 16,
    padding: '20px 0',
    borderTop: `1px solid ${COLORS.border}`,
    borderBottom: `1px solid ${COLORS.border}`,
  },
  trust: {
    display: 'grid',
    gridTemplateColumns: '36px 1fr',
    gap: 16,
    padding: '20px 16px',
    margin: '0 -16px',
    borderTop: `1px solid ${COLORS.border}`,
    background: COLORS.accentSoft,
  },
  num: {
    fontFamily: MONO,
    fontSize: 13,
    color: COLORS.accent,
    paddingTop: 2,
  },
  heading: {
    fontSize: 16,
    fontWeight: 500,
    margin: '0 0 6px',
  },
  body: {
    margin: 0,
    color: COLORS.fg,
    fontSize: 14,
    lineHeight: '22px',
  },
  bodySpaced: {
    margin: '8px 0 0',
    color: COLORS.fg,
    fontSize: 14,
    lineHeight: '22px',
  },
  list: {
    margin: '8px 0 0',
    paddingLeft: 18,
    color: COLORS.fg,
    fontSize: 14,
    lineHeight: '22px',
  },
  note: {
    marginTop: 8,
    color: COLORS.subtle,
    fontSize: 13,
    lineHeight: '20px',
  },
  pillRow: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: 8,
    margin: '8px 0',
  },
  pill: {
    display: 'inline-flex',
    alignItems: 'center',
    fontFamily: MONO,
    fontSize: 11,
    letterSpacing: 0.4,
    textTransform: 'uppercase' as const,
    padding: '4px 8px',
    borderRadius: 2,
    background: COLORS.mutedBg,
    color: COLORS.muted,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    marginTop: 12,
    fontSize: 13,
  },
  th: {
    fontFamily: MONO,
    fontSize: 10,
    letterSpacing: 1.2,
    textTransform: 'uppercase' as const,
    textAlign: 'left' as const,
    color: COLORS.subtle,
    fontWeight: 500,
    padding: '6px 0',
    borderBottom: `1px solid ${COLORS.border}`,
  },
  thRight: {
    fontFamily: MONO,
    fontSize: 10,
    letterSpacing: 1.2,
    textTransform: 'uppercase' as const,
    textAlign: 'right' as const,
    color: COLORS.subtle,
    fontWeight: 500,
    padding: '6px 0',
    borderBottom: `1px solid ${COLORS.border}`,
  },
  td: {
    padding: '8px 0',
    borderBottom: `1px solid ${COLORS.border}`,
    verticalAlign: 'top' as const,
    lineHeight: '18px',
  },
  tdPoints: {
    padding: '8px 0 8px 16px',
    borderBottom: `1px solid ${COLORS.border}`,
    verticalAlign: 'top' as const,
    lineHeight: '18px',
    fontFamily: MONO,
    fontSize: 12,
    whiteSpace: 'nowrap' as const,
    textAlign: 'right' as const,
    color: COLORS.accent,
  },
  link: {
    color: COLORS.accent,
    textDecoration: 'underline' as const,
  },
} as const;
