import type { ExplorerNode } from '../types/editor-data.types';

export const EXPLORER_NODES: ExplorerNode[] = [
  {
    id: 'root',
    name: 'my-twenty-app',
    depth: 0,
    kind: 'folder',
    expanded: true,
  },
  { id: 'github', name: '.github', depth: 1, kind: 'folder', expanded: false },
  { id: 'src', name: 'src', depth: 1, kind: 'folder', expanded: true },
  { id: 'tests', name: '__tests__', depth: 2, kind: 'folder', expanded: false },
  { id: 'agents', name: 'agents', depth: 2, kind: 'folder', expanded: false },
  {
    id: 'command-menu-items',
    name: 'command-menu-items',
    depth: 2,
    kind: 'folder',
    expanded: true,
  },
  {
    id: 'file-cmd-add-payload',
    name: 'add-payload.command-menu-item.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'cmd-add-payload',
    generated: true,
  },
  {
    id: 'file-cmd-book-slot',
    name: 'book-slot.command-menu-item.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'cmd-book-slot',
    generated: true,
  },
  {
    id: 'file-cmd-book-window',
    name: 'book-window.command-menu-item.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'cmd-book-window',
    generated: true,
  },
  {
    id: 'file-cmd-fly-again',
    name: 'fly-again.command-menu-item.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'cmd-fly-again',
    generated: true,
  },
  {
    id: 'file-cmd-launches-from-site',
    name: 'launches-from-site.command-menu-item.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'cmd-launches-from-site',
    generated: true,
  },
  {
    id: 'file-cmd-reschedule-launch',
    name: 'reschedule-launch.command-menu-item.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'cmd-reschedule-launch',
    generated: true,
  },
  {
    id: 'file-cmd-retire-rocket',
    name: 'retire-rocket.command-menu-item.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'cmd-retire-rocket',
    generated: true,
  },
  {
    id: 'file-cmd-schedule-launch',
    name: 'schedule-launch.command-menu-item.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'cmd-schedule-launch',
    generated: true,
  },
  {
    id: 'file-cmd-set-customer-status',
    name: 'set-customer-status.command-menu-item.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'cmd-set-customer-status',
    generated: true,
  },
  {
    id: 'file-cmd-set-payload-status',
    name: 'set-payload-status.command-menu-item.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'cmd-set-payload-status',
    generated: true,
  },
  {
    id: 'file-cmd-set-site-status',
    name: 'set-site-status.command-menu-item.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'cmd-set-site-status',
    generated: true,
  },
  {
    id: 'file-cmd-upcoming-launches',
    name: 'upcoming-launches.command-menu-item.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'cmd-upcoming-launches',
    generated: true,
  },
  {
    id: 'constants',
    name: 'constants',
    depth: 2,
    kind: 'folder',
    expanded: true,
  },
  {
    id: 'file-schema-identifiers',
    name: 'schema-identifiers.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'schema-identifiers',
    generated: true,
  },
  { id: 'fields', name: 'fields', depth: 2, kind: 'folder', expanded: false },
  {
    id: 'front-components',
    name: 'front-components',
    depth: 2,
    kind: 'folder',
    expanded: false,
  },
  {
    id: 'logic-functions',
    name: 'logic-functions',
    depth: 2,
    kind: 'folder',
    expanded: false,
  },
  {
    id: 'navigation-menu-items',
    name: 'navigation-menu-items',
    depth: 2,
    kind: 'folder',
    expanded: true,
  },
  {
    id: 'file-nav-launch-sites',
    name: 'launch-sites.navigation-menu-item.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'nav-launch-sites',
    generated: true,
  },
  {
    id: 'file-nav-launches',
    name: 'launches.navigation-menu-item.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'nav-launches',
    generated: true,
  },
  {
    id: 'file-nav-past-launches',
    name: 'past-launches.navigation-menu-item.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'nav-past-launches',
    generated: true,
  },
  {
    id: 'file-nav-payloads',
    name: 'payloads.navigation-menu-item.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'nav-payloads',
    generated: true,
  },
  {
    id: 'file-nav-rockets',
    name: 'rockets.navigation-menu-item.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'nav-rockets',
    generated: true,
  },
  {
    id: 'file-nav-upcoming',
    name: 'upcoming-launches.navigation-menu-item.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'nav-upcoming',
    generated: true,
  },
  { id: 'objects', name: 'objects', depth: 2, kind: 'folder', expanded: true },
  {
    id: 'file-launch-site-object',
    name: 'launch-site.object.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'launch-site-object',
    generated: true,
  },
  {
    id: 'file-launch-object',
    name: 'launch.object.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'launch-object',
    generated: true,
  },
  {
    id: 'file-payload-object',
    name: 'payload.object.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'payload-object',
    generated: true,
  },
  {
    id: 'file-rocket-object',
    name: 'rocket.object.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'rocket-object',
    generated: true,
  },
  {
    id: 'page-layouts',
    name: 'page-layouts',
    depth: 2,
    kind: 'folder',
    expanded: false,
  },
  { id: 'roles', name: 'roles', depth: 2, kind: 'folder', expanded: false },
  { id: 'skills', name: 'skills', depth: 2, kind: 'folder', expanded: false },
  { id: 'views', name: 'views', depth: 2, kind: 'folder', expanded: true },
  {
    id: 'file-view-launch-sites',
    name: 'launch-sites.view.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'view-launch-sites',
    generated: true,
  },
  {
    id: 'file-view-launches',
    name: 'launches.view.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'view-launches',
    generated: true,
  },
  {
    id: 'file-view-past-launches',
    name: 'past-launches.view.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'view-past-launches',
    generated: true,
  },
  {
    id: 'file-view-payloads',
    name: 'payloads.view.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'view-payloads',
    generated: true,
  },
  {
    id: 'file-view-rockets',
    name: 'rockets.view.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'view-rockets',
    generated: true,
  },
  {
    id: 'file-view-upcoming',
    name: 'upcoming-launches.view.ts',
    depth: 3,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'view-upcoming',
    generated: true,
  },
  {
    id: 'application-config',
    name: 'application-config.ts',
    depth: 1,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
    fileId: 'application-config',
  },
  {
    id: 'gitignore',
    name: '.gitignore',
    depth: 1,
    kind: 'file',
    icon: 'git',
    iconLabel: 'GI',
  },
  {
    id: 'nvmrc',
    name: '.nvmrc',
    depth: 1,
    kind: 'file',
    icon: 'cf',
    iconLabel: 'CF',
  },
  {
    id: 'oxlintrc',
    name: '.oxlintrc.json',
    depth: 1,
    kind: 'file',
    icon: 'js',
    iconLabel: 'JS',
  },
  {
    id: 'yarnrc',
    name: '.yarnrc.yml',
    depth: 1,
    kind: 'file',
    icon: 'yaml',
    iconLabel: 'YM',
  },
  {
    id: 'llms',
    name: 'LLMS.md',
    depth: 1,
    kind: 'file',
    icon: 'md',
    iconLabel: 'MD',
  },
  {
    id: 'package',
    name: 'package.json',
    depth: 1,
    kind: 'file',
    icon: 'js',
    iconLabel: 'JS',
  },
  {
    id: 'readme',
    name: 'README.md',
    depth: 1,
    kind: 'file',
    icon: 'md',
    iconLabel: 'MD',
  },
  {
    id: 'tsconfig',
    name: 'tsconfig.json',
    depth: 1,
    kind: 'file',
    icon: 'js',
    iconLabel: 'JS',
  },
  {
    id: 'tsconfig-spec',
    name: 'tsconfig.spec.json',
    depth: 1,
    kind: 'file',
    icon: 'js',
    iconLabel: 'JS',
  },
  {
    id: 'vitest-config',
    name: 'vitest.config.ts',
    depth: 1,
    kind: 'file',
    icon: 'ts',
    iconLabel: 'TS',
  },
  {
    id: 'yarn-lock',
    name: 'yarn.lock',
    depth: 1,
    kind: 'file',
    icon: 'lock',
    iconLabel: 'LO',
  },
];
