export enum ActionViewType {
  GLOBAL = 'GLOBAL',
  INDEX_PAGE_BULK_SELECTION = 'INDEX_PAGE_BULK_SELECTION',
  INDEX_PAGE_SINGLE_RECORD_SELECTION = 'INDEX_PAGE_SINGLE_RECORD_SELECTION',
  INDEX_PAGE_NO_SELECTION = 'INDEX_PAGE_NO_SELECTION',
  SHOW_PAGE = 'SHOW_PAGE',
  FULL_TAB_WIDGET_EDIT_MODE = 'FULL_TAB_WIDGET_EDIT_MODE',
}
