import { constructIfAvailable } from './constructIfAvailable';

export const createInventoryFactories = ({
  renderedDiv,
  renderedSvg,
}: {
  renderedDiv: HTMLDivElement;
  renderedSvg: SVGSVGElement;
}): Record<string, () => unknown> => ({
  'rendered.div': () => renderedDiv,
  'rendered.svg': () => renderedSvg,
  document: () => globalThis.document,
  'window.document': () => window.document,
  'window.navigator': () => window.navigator,
  'window.location': () => window.location,
  'window.history': () => window.history,
  'window.localStorage': () => window.localStorage,
  'window.sessionStorage': () => window.sessionStorage,
  navigator: () => globalThis.navigator,
  location: () => globalThis.location,
  history: () => globalThis.history,
  screen: () => globalThis.screen,
  performance: () => globalThis.performance,
  crypto: () => globalThis.crypto,
  'navigator.clipboard': () => navigator.clipboard,
  'navigator.mediaDevices': () => navigator.mediaDevices,
  'navigator.permissions': () => navigator.permissions,
  localStorage: () => globalThis.localStorage,
  sessionStorage: () => globalThis.sessionStorage,
  'document.body': () => document.body,
  'document.head': () => document.head,
  'document.documentElement': () => document.documentElement,
  'div.style': () => document.createElement('div').style,
  'div.classList': () => document.createElement('div').classList,
  'div.dataset': () => document.createElement('div').dataset,
  'div.childNodes': () => document.createElement('div').childNodes,
  'div.attributes': () => document.createElement('div').attributes,
  text: () => document.createTextNode('audit'),
  comment: () => document.createComment('audit'),
  fragment: () => document.createDocumentFragment(),
  event: () => constructIfAvailable(globalThis.Event, 'audit'),
  customEvent: () => constructIfAvailable(globalThis.CustomEvent, 'audit'),
  mouseEvent: () => constructIfAvailable(globalThis.MouseEvent, 'audit'),
  keyboardEvent: () => constructIfAvailable(globalThis.KeyboardEvent, 'audit'),
  pointerEvent: () => constructIfAvailable(globalThis.PointerEvent, 'audit'),
  url: () => constructIfAvailable(globalThis.URL, 'https://example.test/audit'),
  urlSearchParams: () =>
    constructIfAvailable(globalThis.URLSearchParams, 'audit=1'),
  headers: () => constructIfAvailable(globalThis.Headers),
  request: () =>
    constructIfAvailable(globalThis.Request, 'https://example.test/audit'),
  response: () => constructIfAvailable(globalThis.Response),
  blob: () => constructIfAvailable(globalThis.Blob),
  file: () => constructIfAvailable(globalThis.File, [], 'audit'),
  formData: () => constructIfAvailable(globalThis.FormData),
  domParser: () => constructIfAvailable(globalThis.DOMParser),
  ...Object.fromEntries(
    [
      'a',
      'audio',
      'button',
      'canvas',
      'details',
      'dialog',
      'div',
      'form',
      'iframe',
      'img',
      'input',
      'label',
      'li',
      'ol',
      'option',
      'p',
      'select',
      'span',
      'style',
      'table',
      'tbody',
      'td',
      'template',
      'textarea',
      'tr',
      'ul',
      'video',
    ].map((tag) => [`html.${tag}`, () => document.createElement(tag)]),
  ),
  ...Object.fromEntries(
    ['svg', 'circle', 'g', 'path', 'rect', 'text', 'use'].map((tag) => [
      `svg.${tag}`,
      () => document.createElementNS('http://www.w3.org/2000/svg', tag),
    ]),
  ),
});
