"""
Migration 019 — Delete prod-only morph-relation fields targeting accounttag/persontag.

Per "resolve discrepancies once and for all" review (2026-05-09):
production has six fields that UAT lacks. The user has elected to remove them
from prod (deletion is the resolution direction):

  attachment.targetAccounttag        MORPH_RELATION   [0 prod rows]
  noteTarget.targetAccounttag        MORPH_RELATION   [0 prod rows]
  taskTarget.targetAccounttag        MORPH_RELATION   [0 prod rows]
  timelineActivity.targetAccounttag  MORPH_RELATION   [76 prod rows — audit data, intentionally lost]
  favorite.accounttag                RELATION         [0 prod rows]
  favorite.persontag                 RELATION         [0 prod rows]

The reverse-side fields (accounttag.attachments/favorites/noteTargets/taskTargets/
timelineActivities and persontag.favorites) are auto-generated by Twenty when
the primary side exists; they will disappear on their own once the primaries
are deleted.

WARNING — deleting timelineActivity.targetAccounttag drops the column on the
workspace schema, which orphans 76 rows of audit-trail data on prod. This is
intentional per user decision (2026-05-09).

Idempotent: skips fields that don't exist (UAT will be all-skips).
"""

MIGRATION_ID = '019-cleanup-prod-only-morph-fields'
DESCRIPTION = 'Delete prod-only morph/relation fields targeting accounttag/persontag (UAT no-op)'

DELETIONS = [
    ('attachment',       'targetAccounttag'),
    ('noteTarget',       'targetAccounttag'),
    ('taskTarget',       'targetAccounttag'),
    ('timelineActivity', 'targetAccounttag'),
    ('favorite',         'accounttag'),
    ('favorite',         'persontag'),
]


def run(client, dry_run: bool = False) -> None:
    objects = client.get_all_objects()

    for obj_name, fld_name in DELETIONS:
        obj = objects.get(obj_name)
        if not obj:
            print(f'  [skip] {obj_name} object not found')
            continue
        fields = client.get_object_fields(obj['id'])
        f = fields.get(fld_name)
        if not f:
            print(f'  [skip]   {obj_name}.{fld_name} already absent')
            continue
        ftype = f.get('type')
        print(f'  [delete] {obj_name}.{fld_name} ({ftype})')
        if not dry_run:
            try:
                deleted = client.delete_field(f['id'])
                if not deleted:
                    print(f'  [warn]   {obj_name}.{fld_name} delete returned not-found')
            except RuntimeError as e:
                print(f'  [warn]   {obj_name}.{fld_name} delete failed: {e}')
