import {
  RESEND_TEMPLATE_OBJECT_UNIVERSAL_IDENTIFIER,
  TEMPLATE_ALIAS_FIELD_UNIVERSAL_IDENTIFIER,
  TEMPLATE_CREATED_AT_FIELD_UNIVERSAL_IDENTIFIER,
  TEMPLATE_FROM_ADDRESS_FIELD_UNIVERSAL_IDENTIFIER,
  TEMPLATE_HTML_FIELD_UNIVERSAL_IDENTIFIER,
  TEMPLATE_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  TEMPLATE_PUBLISHED_AT_FIELD_UNIVERSAL_IDENTIFIER,
  TEMPLATE_REPLY_TO_FIELD_UNIVERSAL_IDENTIFIER,
  TEMPLATE_RESEND_ID_FIELD_UNIVERSAL_IDENTIFIER,
  TEMPLATE_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  TEMPLATE_SUBJECT_FIELD_UNIVERSAL_IDENTIFIER,
  TEMPLATE_TEXT_FIELD_UNIVERSAL_IDENTIFIER,
  TEMPLATE_UPDATED_AT_FIELD_UNIVERSAL_IDENTIFIER,
} from '@modules/resend/constants/universal-identifiers';
import { defineObject, FieldType } from 'twenty-sdk/define';

export default defineObject({
  universalIdentifier: RESEND_TEMPLATE_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'resendTemplate',
  namePlural: 'resendTemplates',
  labelSingular: 'Resend template',
  labelPlural: 'Resend templates',
  description: 'An email template from Resend',
  icon: 'IconTemplate',
  labelIdentifierFieldMetadataUniversalIdentifier:
    TEMPLATE_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: TEMPLATE_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Name of the template',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: TEMPLATE_ALIAS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'alias',
      label: 'Alias',
      description: 'Alternative identifier for the template',
      icon: 'IconTag',
    },
    {
      universalIdentifier: TEMPLATE_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      description: 'Publication status of the template',
      icon: 'IconStatusChange',
      options: [
        {
          id: '3047dfdd-5424-44bc-bead-f2e2a84f363f',
          value: 'DRAFT',
          label: 'Draft',
          position: 0,
          color: 'gray',
        },
        {
          id: '146cf14d-e276-4477-86f5-4114de97bccb',
          value: 'PUBLISHED',
          label: 'Published',
          position: 1,
          color: 'green',
        },
      ],
    },
    {
      universalIdentifier: TEMPLATE_FROM_ADDRESS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.EMAILS,
      name: 'fromAddress',
      label: 'From',
      description: 'Sender email address',
      icon: 'IconMailForward',
    },
    {
      universalIdentifier: TEMPLATE_SUBJECT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'subject',
      label: 'Subject',
      description: 'Email subject line',
      icon: 'IconMail',
    },
    {
      universalIdentifier: TEMPLATE_REPLY_TO_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.EMAILS,
      name: 'replyTo',
      label: 'Reply to',
      description: 'Reply-to email address',
      icon: 'IconMailReply',
    },
    {
      universalIdentifier: TEMPLATE_HTML_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'htmlBody',
      label: 'HTML body',
      description: 'HTML content of the template',
      icon: 'IconFileText',
    },
    {
      universalIdentifier: TEMPLATE_TEXT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'textBody',
      label: 'Text body',
      description: 'Plain text content of the template',
      icon: 'IconAlignLeft',
    },
    {
      universalIdentifier: TEMPLATE_RESEND_ID_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'resendId',
      label: 'Resend ID',
      description: 'Resend template identifier',
      icon: 'IconHash',
    },
    {
      universalIdentifier: TEMPLATE_CREATED_AT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'createdAt',
      label: 'Created at',
      description: 'When the template was created',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: TEMPLATE_UPDATED_AT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'resendUpdatedAt',
      label: 'Resend updated at',
      description: 'When the template was last updated in Resend',
      icon: 'IconCalendarClock',
    },
    {
      universalIdentifier: TEMPLATE_PUBLISHED_AT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'publishedAt',
      label: 'Published at',
      description: 'When the template was published',
      icon: 'IconCalendarEvent',
    },
  ],
});
