export enum IndexExceptionCode {
  INDEX_EMPTY_FIELDS = 'INDEX_EMPTY_FIELDS',
  INDEX_FIELD_NOT_FOUND = 'INDEX_FIELD_NOT_FOUND',
  INDEX_FIELD_WRONG_OBJECT = 'INDEX_FIELD_WRONG_OBJECT',
  INDEX_FIELD_INVALID_REFERENCE = 'INDEX_FIELD_INVALID_REFERENCE',
  INDEX_FIELD_ID_DUPLICATE = 'INDEX_FIELD_ID_DUPLICATE',
  INDEX_ALREADY_EXISTS = 'INDEX_ALREADY_EXISTS',
  INDEX_NOT_FOUND = 'INDEX_NOT_FOUND',
  INDEX_OBJECT_NOT_FOUND = 'INDEX_OBJECT_NOT_FOUND',
  INDEX_FIELD_INVALID_TYPE_FOR_UNIQUE = 'INDEX_FIELD_INVALID_TYPE_FOR_UNIQUE',
  INDEX_FIELD_INVALID_DEFAULT_VALUE = 'INDEX_FIELD_INVALID_DEFAULT_VALUE',
}
