export const SECRET_ENCRYPTION_ENVELOPE_PREFIX = 'enc:';
export const SECRET_ENCRYPTION_ENVELOPE_V2_PREFIX = 'enc:v2:';

export const SECRET_ENCRYPTION_KEY_ID_REGEX = /^[0-9a-f]{8}$/;

export const SECRET_ENCRYPTION_GCM_IV_LENGTH = 12;
export const SECRET_ENCRYPTION_GCM_TAG_LENGTH = 16;
export const SECRET_ENCRYPTION_DERIVED_KEY_LENGTH = 32;
export const SECRET_ENCRYPTION_HKDF_INFO_PREFIX = 'twenty:enc:v2:';
export const SECRET_ENCRYPTION_INSTANCE_CONTEXT = 'instance';

export const INSTANCE_HMAC_HKDF_INFO_PREFIX = 'twenty:hmac:v1:';
export const INSTANCE_HMAC_DERIVED_KEY_LENGTH = 32;
