import { FieldMetadataType } from 'twenty-shared/types';

import { getMockFieldMetadataEntity } from 'src/utils/__test__/get-field-metadata-entity.mock';
import { getMockObjectMetadataItemWithFieldsMaps } from 'src/utils/__test__/get-object-metadata-item-with-fields-maps.mock';

const workspaceId = '20202020-0000-0000-0000-000000000000';

export const mockObjectMetadataItemsWithFieldMaps = [
  getMockObjectMetadataItemWithFieldsMaps({
    id: '20202020-8dec-43d5-b2ff-6eef05095bec',
    standardId: '',
    nameSingular: 'person',
    namePlural: 'people',
    labelSingular: 'Person',
    labelPlural: 'People',
    description: 'A person',
    icon: 'test-person-icon',
    targetTableName: 'DEPRECATED',
    isCustom: false,
    isRemote: false,
    isActive: true,
    isSystem: false,
    isAuditLogged: true,
    isSearchable: true,
    labelIdentifierFieldMetadataId: 'nameFieldMetadataId',
    imageIdentifierFieldMetadataId: '',
    workspaceId,
    indexMetadatas: [],
    fieldsById: {
      nameFieldMetadataId: getMockFieldMetadataEntity({
        workspaceId,
        objectMetadataId: '20202020-8dec-43d5-b2ff-6eef05095bec',
        id: 'nameFieldMetadataId',
        type: FieldMetadataType.FULL_NAME,
        icon: 'test-field-icon',
        name: 'name',
        label: 'Name',
        defaultValue: {
          lastName: "''",
          firstName: "''",
        },
        description: "Contact's name",
        isCustom: false,
        isNullable: true,
        isUnique: false,
        isLabelSyncedWithName: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      }),
    },
    fieldIdByName: {
      name: 'nameFieldMetadataId',
    },
    fieldIdByJoinColumnName: {},
  }),
  getMockObjectMetadataItemWithFieldsMaps({
    id: '20202020-c03c-45d6-a4b0-04afe1357c5c',
    standardId: '',
    nameSingular: 'company',
    namePlural: 'companies',
    labelSingular: 'Company',
    labelPlural: 'Companies',
    description: 'A company',
    icon: 'test-company-icon',
    targetTableName: 'DEPRECATED',
    isCustom: false,
    isRemote: false,
    isActive: true,
    isSystem: false,
    isAuditLogged: true,
    isSearchable: true,
    labelIdentifierFieldMetadataId: 'nameFieldMetadataId',
    imageIdentifierFieldMetadataId: '',
    workspaceId,
    indexMetadatas: [],
    fieldsById: {
      nameFieldMetadataId: getMockFieldMetadataEntity({
        workspaceId,
        objectMetadataId: '20202020-c03c-45d6-a4b0-04afe1357c5c',
        id: 'nameFieldMetadataId',
        type: FieldMetadataType.TEXT,
        icon: 'test-field-icon',
        name: 'name',
        label: 'Name',
        defaultValue: '',
        isCustom: false,
        isNullable: true,
        isUnique: false,
        isLabelSyncedWithName: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      }),
      domainNameFieldMetadataId: getMockFieldMetadataEntity({
        workspaceId,
        objectMetadataId: '20202020-c03c-45d6-a4b0-04afe1357c5c',
        id: 'domainNameFieldMetadataId',
        type: FieldMetadataType.LINKS,
        icon: 'test-field-icon',
        name: 'domainName',
        label: 'Domain Name',
        defaultValue: {
          primaryLinkLabel: '',
          primaryLinkUrl: '',
          secondaryLinks: [],
        },
        isCustom: false,
        isNullable: true,
        isUnique: false,
        isLabelSyncedWithName: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      }),
    },
    fieldIdByName: {
      name: 'nameFieldMetadataId',
      domainName: 'domainNameFieldMetadataId',
    },
    fieldIdByJoinColumnName: {},
  }),
  getMockObjectMetadataItemWithFieldsMaps({
    id: '20202020-3d75-4aab-bacd-ee176c5f63ca',
    standardId: '',
    nameSingular: 'regular-custom-object',
    namePlural: 'regular-custom-objects',
    labelSingular: 'Regular Custom Object',
    labelPlural: 'Regular Custom Objects',
    description: 'A regular custom object',
    icon: 'test-regular-custom-object-icon',
    targetTableName: 'DEPRECATED',
    isCustom: true,
    isRemote: false,
    isActive: true,
    isSystem: false,
    isAuditLogged: true,
    isSearchable: true,
    labelIdentifierFieldMetadataId: 'nameFieldMetadataId',
    imageIdentifierFieldMetadataId: 'imageIdentifierFieldMetadataId',
    workspaceId,
    indexMetadatas: [],
    fieldsById: {
      nameFieldMetadataId: getMockFieldMetadataEntity({
        workspaceId,
        objectMetadataId: '20202020-3d75-4aab-bacd-ee176c5f63ca',
        id: 'nameFieldMetadataId',
        type: FieldMetadataType.TEXT,
        icon: 'test-field-icon',
        name: 'name',
        label: 'Name',
        defaultValue: '',
        isCustom: false,
        isNullable: true,
        isUnique: false,
        isLabelSyncedWithName: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      }),
      imageIdentifierFieldMetadataId: getMockFieldMetadataEntity({
        workspaceId,
        objectMetadataId: '20202020-3d75-4aab-bacd-ee176c5f63ca',
        id: 'imageIdentifierFieldMetadataId',
        type: FieldMetadataType.TEXT,
        icon: 'test-field-icon',
        name: 'imageIdentifierFieldName',
        label: 'Image Identifier Field Name',
        defaultValue: '',
        isCustom: false,
        isNullable: true,
        isUnique: false,
        isLabelSyncedWithName: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      }),
    },
    fieldIdByName: {
      name: 'nameFieldMetadataId',
      imageIdentifierFieldName: 'imageIdentifierFieldMetadataId',
    },
    fieldIdByJoinColumnName: {},
  }),
  getMockObjectMetadataItemWithFieldsMaps({
    id: '20202020-540c-4397-b872-2a90ea2fb809',
    standardId: '',
    nameSingular: 'non-searchable-object',
    namePlural: 'non-searchable-objects',
    labelSingular: '',
    labelPlural: '',
    description: '',
    icon: 'test-non-searchable-object-icon',
    targetTableName: 'DEPRECATED',
    isCustom: false,
    isRemote: false,
    isActive: true,
    isSystem: true,
    isAuditLogged: true,
    isSearchable: false,
    labelIdentifierFieldMetadataId: '',
    imageIdentifierFieldMetadataId: '',
    workspaceId,
    indexMetadatas: [],
    fieldsById: {},
    fieldIdByName: {},
    fieldIdByJoinColumnName: {},
  }),
];
