import {
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardFieldByObjectName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import { createStandardFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/create-standard-relation-field-flat-metadata.util';
import { type StandardFieldMetadataIdByObjectAndFieldName } from 'src/engine/workspace-manager/twenty-standard-application/utils/get-standard-field-metadata-id-by-object-and-field-name.util';

export const buildWorkflowRunStandardFlatFieldMetadatas = ({
  createdAt,
  workspaceId,
  standardFieldMetadataIdByObjectAndFieldName,
}: {
  createdAt: Date;
  workspaceId: string;
  standardFieldMetadataIdByObjectAndFieldName: StandardFieldMetadataIdByObjectAndFieldName;
}): Record<AllStandardFieldByObjectName<'workflowRun'>, FlatFieldMetadata> => ({
  id: createStandardFieldFlatMetadata({
    objectName: 'workflowRun',
    workspaceId,
    options: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: 'Id',
      description: 'Id',
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'uuid',
      createdAt,
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName: 'workflowRun',
    workspaceId,
    options: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Creation date',
      description: 'Creation date',
      icon: 'IconCalendar',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      settings: { displayFormat: 'RELATIVE' },
      createdAt,
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName: 'workflowRun',
    workspaceId,
    options: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Last update',
      description: 'Last time the record was changed',
      icon: 'IconCalendarClock',
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      settings: { displayFormat: 'RELATIVE' },
      createdAt,
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName: 'workflowRun',
    workspaceId,
    options: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Deleted at',
      description: 'Date when the record was deleted',
      icon: 'IconCalendarMinus',
      isNullable: true,
      isUIReadOnly: true,
      settings: { displayFormat: 'RELATIVE' },
      createdAt,
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  name: createStandardFieldFlatMetadata({
    objectName: 'workflowRun',
    workspaceId,
    options: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: 'Name',
      description: 'Name of the workflow run',
      icon: 'IconSettingsAutomation',
      isNullable: true,
      createdAt,
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  enqueuedAt: createStandardFieldFlatMetadata({
    objectName: 'workflowRun',
    workspaceId,
    options: {
      fieldName: 'enqueuedAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Workflow run enqueued at',
      description: 'Workflow run enqueued at',
      icon: 'IconHistory',
      isNullable: true,
      createdAt,
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  startedAt: createStandardFieldFlatMetadata({
    objectName: 'workflowRun',
    workspaceId,
    options: {
      fieldName: 'startedAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Workflow run started at',
      description: 'Workflow run started at',
      icon: 'IconHistory',
      isNullable: true,
      createdAt,
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  endedAt: createStandardFieldFlatMetadata({
    objectName: 'workflowRun',
    workspaceId,
    options: {
      fieldName: 'endedAt',
      type: FieldMetadataType.DATE_TIME,
      label: 'Workflow run ended at',
      description: 'Workflow run ended at',
      icon: 'IconHistory',
      isNullable: true,
      createdAt,
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  status: createStandardFieldFlatMetadata({
    objectName: 'workflowRun',
    workspaceId,
    options: {
      fieldName: 'status',
      type: FieldMetadataType.SELECT,
      label: 'Workflow run status',
      description: 'Workflow run status',
      icon: 'IconStatusChange',
      isNullable: false,
      defaultValue: "'NOT_STARTED'",
      options: [
        {
          value: 'NOT_STARTED',
          label: 'Not started',
          position: 0,
          color: 'gray',
        },
        { value: 'RUNNING', label: 'Running', position: 1, color: 'yellow' },
        { value: 'COMPLETED', label: 'Completed', position: 2, color: 'green' },
        { value: 'FAILED', label: 'Failed', position: 3, color: 'red' },
        { value: 'ENQUEUED', label: 'Enqueued', position: 4, color: 'blue' },
        { value: 'STOPPING', label: 'Stopping', position: 5, color: 'orange' },
        { value: 'STOPPED', label: 'Stopped', position: 6, color: 'gray' },
      ],
      createdAt,
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName: 'workflowRun',
    workspaceId,
    options: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: 'Executed by',
      description: 'The executor of the workflow',
      icon: 'IconCreativeCommonsSa',
      isNullable: false,
      createdAt,
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  state: createStandardFieldFlatMetadata({
    objectName: 'workflowRun',
    workspaceId,
    options: {
      fieldName: 'state',
      type: FieldMetadataType.RAW_JSON,
      label: 'State',
      description: 'State of the workflow run',
      icon: 'IconHierarchy2',
      isNullable: false,
      createdAt,
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  context: createStandardFieldFlatMetadata({
    objectName: 'workflowRun',
    workspaceId,
    options: {
      fieldName: 'context',
      type: FieldMetadataType.RAW_JSON,
      label: 'Context',
      description: 'Context of the workflow run',
      icon: 'IconHierarchy2',
      isNullable: true,
      createdAt,
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  output: createStandardFieldFlatMetadata({
    objectName: 'workflowRun',
    workspaceId,
    options: {
      fieldName: 'output',
      type: FieldMetadataType.RAW_JSON,
      label: 'Output',
      description: 'Output of the workflow run',
      icon: 'IconHierarchy2',
      isNullable: true,
      createdAt,
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  position: createStandardFieldFlatMetadata({
    objectName: 'workflowRun',
    workspaceId,
    options: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: 'Position',
      description: 'Workflow run position',
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
      createdAt,
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName: 'workflowRun',
    workspaceId,
    options: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: 'Search vector',
      description: 'Field used for full-text search',
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
      createdAt,
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  workflowVersion: createStandardRelationFieldFlatMetadata({
    objectName: 'workflowRun',
    workspaceId,
    options: {
      fieldName: 'workflowVersion',
      label: 'Workflow version',
      description: 'Workflow version linked to the run.',
      icon: 'IconVersions',
      isNullable: false,
      createdAt,
      targetObjectName: 'workflowVersion',
      targetFieldName: 'runs',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'workflowVersionId',
      },
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  workflow: createStandardRelationFieldFlatMetadata({
    objectName: 'workflowRun',
    workspaceId,
    options: {
      fieldName: 'workflow',
      label: 'Workflow',
      description: 'Workflow linked to the run.',
      icon: 'IconSettingsAutomation',
      isNullable: false,
      createdAt,
      targetObjectName: 'workflow',
      targetFieldName: 'runs',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.CASCADE,
        joinColumnName: 'workflowId',
      },
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  favorites: createStandardRelationFieldFlatMetadata({
    objectName: 'workflowRun',
    workspaceId,
    options: {
      fieldName: 'favorites',
      label: 'Favorites',
      description: 'Favorites linked to the workflow run',
      icon: 'IconHeart',
      isSystem: true,
      isNullable: false,
      createdAt,
      targetObjectName: 'favorite',
      targetFieldName: 'workflowRun',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
  timelineActivities: createStandardRelationFieldFlatMetadata({
    objectName: 'workflowRun',
    workspaceId,
    options: {
      fieldName: 'timelineActivities',
      label: 'Timeline Activities',
      description: 'Timeline activities linked to the run',
      icon: 'IconTimelineEvent',
      isSystem: true,
      isNullable: false,
      createdAt,
      targetObjectName: 'timelineActivity',
      targetFieldName: 'workflowRun',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardFieldMetadataIdByObjectAndFieldName,
  }),
});
