import { type MessageDescriptor } from '@lingui/core';
import { isNonEmptyString } from '@sniptt/guards';

// Translation catalogs are regenerated by the i18n pipeline after source
// changes land, so the catalog-pinning spec accepts an authored descriptor id
// in place of a catalog entry; every standard metadata label authoring site
// funnels through i18nLabel, which records the macro-computed ids here.
export const AUTHORED_STANDARD_METADATA_MESSAGE_IDS = new Set<string>();

export const i18nLabel = (descriptor: MessageDescriptor): string => {
  if (isNonEmptyString(descriptor.id)) {
    AUTHORED_STANDARD_METADATA_MESSAGE_IDS.add(descriptor.id);
  }

  return descriptor.message ?? '';
};
