import { msg } from '@lingui/core/macro';

import type { WebsiteRoute } from './types';

export const STATIC_WEBSITE_ROUTES = [
  {
    id: 'home',
    path: '/',
    title: msg`Twenty | #1 open source CRM`,
    description: msg`The #1 open source CRM for modern teams. Modular, scalable, and built to fit your business.`,
    changeFrequency: 'weekly',
    priority: 1,
    indexed: true,
  },
  {
    id: 'whyTwenty',
    path: '/why-twenty',
    title: msg`Why Twenty | Twenty`,
    description: msg`Most packaged software makes companies more similar. Learn why the future of CRM is built, not bought.`,
    changeFrequency: 'monthly',
    priority: 0.8,
    indexed: true,
  },
  {
    id: 'product',
    path: '/product',
    title: msg`Product | Twenty`,
    description: msg`Track relationships, manage pipelines, and take action quickly with a CRM that feels intuitive from day one.`,
    changeFrequency: 'monthly',
    priority: 0.8,
    indexed: true,
  },
  {
    id: 'pricing',
    path: '/pricing',
    title: msg`Pricing | Twenty`,
    description: msg`Plans that scale with your team. Compare tiers of the #1 open source CRM.`,
    changeFrequency: 'monthly',
    priority: 0.9,
    indexed: true,
  },
  {
    id: 'partners',
    path: '/partners',
    title: msg`Partners | Twenty`,
    description: msg`Join our partner ecosystem and grow with us as we build the #1 open source CRM.`,
    changeFrequency: 'monthly',
    priority: 0.7,
    indexed: true,
  },
  {
    id: 'releases',
    path: '/releases',
    title: msg`Releases | Twenty`,
    description: msg`Discover the newest features and improvements in Twenty, the #1 open source CRM.`,
    changeFrequency: 'weekly',
    priority: 0.7,
    indexed: true,
  },
  {
    id: 'customers',
    path: '/customers',
    title: msg`Customers | Twenty`,
    description: msg`Meet the teams running their business on Twenty. Real customer stories on how they shaped the CRM to fit their workflow.`,
    changeFrequency: 'monthly',
    priority: 0.7,
    indexed: true,
  },
  {
    id: 'privacyPolicy',
    path: '/privacy-policy',
    title: msg`Privacy Policy | Twenty`,
    description: msg`How Twenty collects, uses, safeguards, and discloses information when you use Twenty.com and related services.`,
    changeFrequency: 'yearly',
    priority: 0.3,
    indexed: true,
  },
  {
    id: 'terms',
    path: '/terms',
    title: msg`Terms of Service | Twenty`,
    description: msg`Terms of Service for Twenty.com PBC, including use of Twenty.com, sub-domains, and related services.`,
    changeFrequency: 'yearly',
    priority: 0.3,
    indexed: true,
  },
  {
    id: 'halftone',
    path: '/halftone',
    title: msg`Halftone Generator | Twenty`,
    description: msg`Interactive halftone generator exported from Twenty.`,
    changeFrequency: 'monthly',
    priority: 0,
    indexed: false,
    robotsDisallow: true,
  },
  {
    id: 'enterpriseActivate',
    path: '/enterprise/activate',
    title: msg`Enterprise activation | Twenty`,
    description: msg`Complete activation for your Twenty self-hosted enterprise license.`,
    changeFrequency: 'yearly',
    priority: 0,
    indexed: false,
    robotsDisallow: true,
  },
] as const satisfies readonly WebsiteRoute[];
