import { msg } from '@lingui/core/macro';

import type { WebsiteRoute } from './types';

export const STATIC_WEBSITE_ROUTES = [
  {
    id: 'home',
    path: '/',
    title: msg`Twenty | #1 Open Source CRM`,
    description: msg`The #1 Open Source CRM for modern teams. Modular, scalable, and built to fit your business.`,
    changeFrequency: 'weekly',
    priority: 1,
    indexed: true,
  },
  {
    id: 'whyTwenty',
    path: '/resources/why-twenty',
    title: msg`Why Twenty — The Open Source CRM Built to Be Customised`,
    description: msg`Packaged CRMs make every company look the same. Twenty is the open source CRM teams shape around their workflow, with a modern UI and a developer-first platform.`,
    changeFrequency: 'monthly',
    priority: 0.8,
    indexed: true,
  },
  {
    id: 'product',
    path: '/product',
    title: msg`Twenty CRM Features — Modern Open Source CRM Platform`,
    description: msg`Pipelines, custom objects, AI assistants, and a native API on top of Postgres. Twenty is the open source CRM with the modern UX teams actually want to use.`,
    changeFrequency: 'monthly',
    priority: 0.8,
    indexed: true,
  },
  {
    id: 'pricing',
    path: '/pricing',
    title: msg`Twenty CRM Pricing — Plans from $9 per User per Month`,
    description: msg`Cloud Pro starts at $9/user/month with unlimited custom objects. Self-host the open source core for free, or upgrade to Organization for SSO and row-level permissions.`,
    changeFrequency: 'monthly',
    priority: 0.9,
    indexed: true,
  },
  {
    id: 'partners',
    path: '/partners',
    title: msg`Twenty Partners — Certified Open Source CRM Implementers`,
    description: msg`Find a certified Twenty partner to migrate, customise, and operate your open source CRM, or join the ecosystem and grow your practice with us.`,
    changeFrequency: 'monthly',
    priority: 0.7,
    indexed: true,
  },
  {
    id: 'releases',
    path: '/releases',
    title: msg`Twenty Releases — What's New in the Open Source CRM`,
    description: msg`Every new release of Twenty, the #1 Open Source CRM, with changelogs, demos, and the highlights teams care about most.`,
    changeFrequency: 'weekly',
    priority: 0.7,
    indexed: true,
  },
  {
    id: 'customers',
    path: '/customers',
    title: msg`Twenty Customers — How Modern Teams Run Their CRM`,
    description: msg`Real customer stories from teams running their business on Twenty: how they migrated, what they customised, and what changed once their CRM finally fit.`,
    changeFrequency: 'monthly',
    priority: 0.7,
    indexed: true,
  },
  {
    id: 'articles',
    path: '/articles',
    title: msg`Twenty Articles — Open Source CRM Insights`,
    description: msg`Ideas from the team building Twenty on open source CRM, customer data, GTM systems, and building software that lasts.`,
    changeFrequency: 'daily',
    priority: 0.8,
    indexed: true,
    localeMode: 'source',
  },
  {
    id: 'privacyPolicy',
    path: '/privacy-policy',
    title: msg`Privacy Policy | Twenty`,
    description: msg`How Twenty collects, uses, safeguards, and discloses information when you use Twenty.com and related services.`,
    changeFrequency: 'yearly',
    priority: 0.3,
    indexed: true,
  },
  {
    id: 'terms',
    path: '/terms',
    title: msg`Terms of Service | Twenty`,
    description: msg`Terms of Service for Twenty.com PBC, including use of Twenty.com, sub-domains, and related services.`,
    changeFrequency: 'yearly',
    priority: 0.3,
    indexed: true,
  },
  {
    id: 'halftone',
    path: '/halftone',
    title: msg`Halftone Generator | Twenty`,
    description: msg`Interactive halftone generator exported from Twenty.`,
    changeFrequency: 'monthly',
    priority: 0,
    indexed: false,
    robotsDisallow: true,
  },
  {
    id: 'enterpriseActivate',
    path: '/enterprise/activate',
    title: msg`Enterprise Activation | Twenty`,
    description: msg`Complete activation for your Twenty self-hosted enterprise license.`,
    changeFrequency: 'yearly',
    priority: 0,
    indexed: false,
    robotsDisallow: true,
  },
] as const satisfies readonly WebsiteRoute[];
