export enum RelationMetadataExceptionCode {
  RELATION_METADATA_NOT_FOUND = 'RELATION_METADATA_NOT_FOUND',
  INVALID_RELATION_INPUT = 'INVALID_RELATION_INPUT',
  RELATION_ALREADY_EXISTS = 'RELATION_ALREADY_EXISTS',
  FOREIGN_KEY_NOT_FOUND = 'FOREIGN_KEY_NOT_FOUND',
}
