export enum FileFolder {
  ProfilePicture = 'profile-picture',
  WorkspaceLogo = 'workspace-logo',
  Attachment = 'attachment',
  PersonPicture = 'person-picture',
  ServerlessFunction = 'serverless-function',
  ServerlessFunctionToDelete = 'serverless-function-to-delete',
  File = 'file',
  AgentChat = 'agent-chat',
  BuiltFunction = 'built-function',
  BuiltFrontComponent = 'built-front-component',
  PublicAsset = 'public-asset',
  Source = 'source',
  TemporaryFilesField = 'temporary-files-field',
  FilesField = 'files-field',
}
