export enum FileFolder {
  ProfilePicture = 'profile-picture',
  WorkspaceLogo = 'workspace-logo',
  Attachment = 'attachment',
  PersonPicture = 'person-picture',
  CorePicture = 'core-picture',
  File = 'file',
  AgentChat = 'agent-chat',
  BuiltLogicFunction = 'built-logic-function',
  BuiltFrontComponent = 'built-front-component',
  PublicAsset = 'public-asset',
  Source = 'source',
  FilesField = 'files-field',
  Dependencies = 'dependencies',
}
