import type { DashboardBlueprint } from './dashboard-blueprint.type';

export const ambassadorCommandCenterBlueprint: DashboardBlueprint = {
  title: 'Ambassador Command Center',
  tabs: [
    {
      key: 'overview',
      title: 'Overview',
      position: 0,
      widgets: [
        {
          title: 'Total Ambassadors',
          type: 'GRAPH',
          objectNameSingular: 'xopureAmbassador',
          gridPosition: { row: 0, column: 0, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            label: 'Ambassadors',
            displayDataLabel: true,
          },
        },
        {
          title: 'Active Customer Count',
          type: 'GRAPH',
          objectNameSingular: 'xopureAmbassador',
          gridPosition: { row: 0, column: 3, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'activeCustomerCount',
            aggregateOperation: 'SUM',
            label: 'Active customers',
            displayDataLabel: true,
          },
        },
        {
          title: 'Team Volume',
          type: 'GRAPH',
          objectNameSingular: 'xopureAmbassador',
          gridPosition: { row: 0, column: 6, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'teamVolumeCents',
            aggregateOperation: 'SUM',
            label: 'Team volume cents',
            displayDataLabel: true,
          },
        },
        {
          title: 'Attributed Revenue',
          type: 'GRAPH',
          objectNameSingular: 'xopureAmbassador',
          gridPosition: { row: 0, column: 9, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'attributedRevenueCents',
            aggregateOperation: 'SUM',
            label: 'Attributed revenue cents',
            displayDataLabel: true,
          },
        },
        {
          title: 'Ambassador Status Mix',
          type: 'GRAPH',
          objectNameSingular: 'xopureAmbassador',
          gridPosition: { row: 2, column: 0, rowSpan: 4, columnSpan: 6 },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            groupByFieldName: 'status',
            orderBy: 'VALUE_DESC',
            displayDataLabel: true,
          },
        },
        {
          title: 'Paid-as Rank Mix',
          type: 'GRAPH',
          objectNameSingular: 'xopureAmbassador',
          gridPosition: { row: 2, column: 6, rowSpan: 4, columnSpan: 6 },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            groupByFieldName: 'paidAsRank',
            orderBy: 'VALUE_DESC',
            displayDataLabel: true,
          },
        },
      ],
    },
    {
      key: 'commissions',
      title: 'Commissions',
      position: 1,
      widgets: [
        {
          title: 'Total Commissions',
          type: 'GRAPH',
          objectNameSingular: 'xopureCommission',
          gridPosition: { row: 0, column: 0, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            label: 'Commissions',
            displayDataLabel: true,
          },
        },
        {
          title: 'Commission Amount',
          type: 'GRAPH',
          objectNameSingular: 'xopureCommission',
          gridPosition: { row: 0, column: 3, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'amountCents',
            aggregateOperation: 'SUM',
            label: 'Commission cents',
            displayDataLabel: true,
          },
        },
        {
          title: 'Held Balance',
          type: 'GRAPH',
          objectNameSingular: 'xopureAmbassador',
          gridPosition: { row: 0, column: 6, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'heldCommissionCents',
            aggregateOperation: 'SUM',
            label: 'Held cents',
            displayDataLabel: true,
          },
        },
        {
          title: 'Payable Balance',
          type: 'GRAPH',
          objectNameSingular: 'xopureAmbassador',
          gridPosition: { row: 0, column: 9, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'payableCommissionCents',
            aggregateOperation: 'SUM',
            label: 'Payable cents',
            displayDataLabel: true,
          },
        },
        {
          title: 'Commission Status Mix',
          type: 'GRAPH',
          objectNameSingular: 'xopureCommission',
          gridPosition: { row: 2, column: 0, rowSpan: 4, columnSpan: 6 },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            groupByFieldName: 'status',
            orderBy: 'VALUE_DESC',
            displayDataLabel: true,
          },
        },
        {
          title: 'Commission Ledger',
          type: 'RECORD_TABLE',
          objectNameSingular: 'xopureCommission',
          gridPosition: { row: 2, column: 6, rowSpan: 8, columnSpan: 6 },
          view: {
            name: 'Commission Dashboard Table',
            icon: 'IconReceiptDollar',
            position: 99,
            fields: [
              { fieldName: 'name', position: 0, size: 220 },
              { fieldName: 'status', position: 1, size: 140 },
              { fieldName: 'amountCents', position: 2, size: 140 },
              { fieldName: 'holdUntil', position: 3, size: 180 },
              { fieldName: 'payableAt', position: 4, size: 180 },
            ],
          },
        },
      ],
    },
    {
      key: 'network',
      title: 'Network',
      position: 2,
      widgets: [
        {
          title: 'Total Relationships',
          type: 'GRAPH',
          objectNameSingular: 'xopureReferralRelationship',
          gridPosition: { row: 0, column: 0, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            label: 'Relationships',
            displayDataLabel: true,
          },
        },
        {
          title: 'Active Relationships',
          type: 'GRAPH',
          objectNameSingular: 'xopureReferralRelationship',
          gridPosition: { row: 0, column: 3, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'isActive',
            aggregateOperation: 'COUNT_TRUE',
            label: 'Active links',
            displayDataLabel: true,
          },
        },
        {
          title: 'Max Downline Depth',
          type: 'GRAPH',
          objectNameSingular: 'xopureReferralRelationship',
          gridPosition: { row: 0, column: 6, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'depth',
            aggregateOperation: 'MAX',
            label: 'Depth',
            displayDataLabel: true,
          },
        },
        {
          title: 'Relationship Depth Mix',
          type: 'GRAPH',
          objectNameSingular: 'xopureReferralRelationship',
          gridPosition: { row: 2, column: 0, rowSpan: 4, columnSpan: 6 },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            groupByFieldName: 'depth',
            orderBy: 'VALUE_DESC',
            displayDataLabel: true,
          },
        },
        {
          title: 'Referral Network Ledger',
          type: 'RECORD_TABLE',
          objectNameSingular: 'xopureReferralRelationship',
          gridPosition: { row: 2, column: 6, rowSpan: 8, columnSpan: 6 },
          view: {
            name: 'Referral Network Dashboard Table',
            icon: 'IconTopologyStarRing3',
            position: 100,
            fields: [
              { fieldName: 'sponsorName', position: 0, size: 220 },
              { fieldName: 'sponsoredName', position: 1, size: 220 },
              { fieldName: 'depth', position: 2, size: 100 },
              { fieldName: 'isActive', position: 3, size: 120 },
              { fieldName: 'lastSyncedAt', position: 4, size: 180 },
            ],
          },
        },
      ],
    },
    {
      key: 'rank-elite-progress',
      title: 'Rank and Elite Progress',
      position: 3,
      widgets: [
        {
          title: 'Personal Volume',
          type: 'GRAPH',
          objectNameSingular: 'xopureAmbassador',
          gridPosition: { row: 0, column: 0, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'personalVolumeCents',
            aggregateOperation: 'SUM',
            label: 'Personal volume cents',
            displayDataLabel: true,
          },
        },
        {
          title: 'Team Volume Progress',
          type: 'GRAPH',
          objectNameSingular: 'xopureAmbassador',
          gridPosition: { row: 0, column: 3, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'teamVolumeCents',
            aggregateOperation: 'SUM',
            label: 'Team volume cents',
            displayDataLabel: true,
          },
        },
        {
          title: 'Active Customers Progress',
          type: 'GRAPH',
          objectNameSingular: 'xopureAmbassador',
          gridPosition: { row: 0, column: 6, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'activeCustomerCount',
            aggregateOperation: 'SUM',
            label: 'Active customers',
            displayDataLabel: true,
          },
        },
        {
          title: 'Career Rank Mix',
          type: 'GRAPH',
          objectNameSingular: 'xopureAmbassador',
          gridPosition: { row: 2, column: 0, rowSpan: 4, columnSpan: 6 },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            groupByFieldName: 'careerRank',
            orderBy: 'VALUE_DESC',
            displayDataLabel: true,
          },
        },
        {
          title: 'Rank Progress Ledger',
          type: 'RECORD_TABLE',
          objectNameSingular: 'xopureAmbassador',
          gridPosition: { row: 2, column: 6, rowSpan: 8, columnSpan: 6 },
          view: {
            name: 'Rank Progress Dashboard Table',
            icon: 'IconAward',
            position: 101,
            fields: [
              { fieldName: 'name', position: 0, size: 220 },
              { fieldName: 'paidAsRank', position: 1, size: 140 },
              { fieldName: 'careerRank', position: 2, size: 140 },
              { fieldName: 'activeCustomerCount', position: 3, size: 140 },
              { fieldName: 'personalVolumeCents', position: 4, size: 160 },
              { fieldName: 'teamVolumeCents', position: 5, size: 160 },
            ],
          },
        },
      ],
    },
    {
      key: 'ops-ftc-health',
      title: 'Ops and FTC Health',
      position: 4,
      widgets: [
        {
          title: 'Total Sync Records',
          type: 'GRAPH',
          objectNameSingular: 'xopureSyncMap',
          gridPosition: { row: 0, column: 0, rowSpan: 2, columnSpan: 4 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            label: 'Sync records',
            displayDataLabel: true,
          },
        },
        {
          title: 'Sync Status Mix',
          type: 'GRAPH',
          objectNameSingular: 'xopureSyncMap',
          gridPosition: { row: 0, column: 4, rowSpan: 4, columnSpan: 3 },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            groupByFieldName: 'lastStatus',
            orderBy: 'VALUE_DESC',
            displayDataLabel: true,
          },
        },
        {
          title: 'Cursor Runs Over Time',
          type: 'GRAPH',
          objectNameSingular: 'xopureSyncCursor',
          gridPosition: { row: 0, column: 7, rowSpan: 6, columnSpan: 5 },
          configuration: {
            configurationType: 'LINE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            primaryAxisGroupByFieldName: 'lastRunAt',
            primaryAxisOrderBy: 'FIELD_ASC',
            axisNameDisplay: 'NONE',
            displayDataLabel: false,
            timezone: 'UTC',
            firstDayOfTheWeek: 1,
          },
        },
      ],
    },
  ],
};
