import type { DashboardBlueprint } from './dashboard-blueprint.type';

export const leadsAndCustomersBlueprint: DashboardBlueprint = {
  title: 'Leads and Customers Dashboard',
  tabs: [
    {
      key: 'pipeline-and-customers',
      title: 'Pipeline and Customers',
      position: 0,
      widgets: [
        {
          title: 'Retail Prospects',
          type: 'GRAPH',
          objectNameSingular: 'retailProspect',
          gridPosition: { row: 0, column: 0, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            label: 'Retail prospects',
            displayDataLabel: true,
          },
        },
        {
          title: 'Influencer Prospects',
          type: 'GRAPH',
          objectNameSingular: 'influencerProspect',
          gridPosition: { row: 0, column: 3, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            label: 'Influencer prospects',
            displayDataLabel: true,
          },
        },
        {
          title: 'Customers',
          type: 'GRAPH',
          objectNameSingular: 'xopureCustomer',
          gridPosition: { row: 0, column: 6, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            label: 'Customers',
            displayDataLabel: true,
          },
        },
        {
          title: 'Customer Lifetime Value',
          type: 'GRAPH',
          objectNameSingular: 'xopureCustomer',
          gridPosition: { row: 0, column: 9, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'lifetimeValueCents',
            aggregateOperation: 'SUM',
            label: 'Lifetime value cents',
            displayDataLabel: true,
          },
        },
        {
          title: 'Retail Prospect Stage Mix',
          type: 'GRAPH',
          objectNameSingular: 'retailProspect',
          gridPosition: { row: 2, column: 0, rowSpan: 4, columnSpan: 4 },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            groupByFieldName: 'stage',
            orderBy: 'VALUE_DESC',
            displayDataLabel: true,
          },
        },
        {
          title: 'Influencer Prospect Stage Mix',
          type: 'GRAPH',
          objectNameSingular: 'influencerProspect',
          gridPosition: { row: 2, column: 4, rowSpan: 4, columnSpan: 4 },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            groupByFieldName: 'stage',
            orderBy: 'VALUE_DESC',
            displayDataLabel: true,
          },
        },
        {
          title: 'Customer Status Mix',
          type: 'GRAPH',
          objectNameSingular: 'xopureCustomer',
          gridPosition: { row: 2, column: 8, rowSpan: 4, columnSpan: 4 },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            groupByFieldName: 'status',
            orderBy: 'VALUE_DESC',
            displayDataLabel: true,
          },
        },
        {
          title: 'Retail Prospect Triage',
          type: 'RECORD_TABLE',
          objectNameSingular: 'retailProspect',
          gridPosition: { row: 6, column: 0, rowSpan: 8, columnSpan: 6 },
          view: {
            name: 'Retail Prospect Dashboard Table',
            icon: 'IconBuildingStore',
            position: 110,
            fields: [
              { fieldName: 'name', position: 0, size: 220 },
              { fieldName: 'companyName', position: 1, size: 220 },
              { fieldName: 'stage', position: 2, size: 140 },
              { fieldName: 'priorityScore', position: 3, size: 120 },
              { fieldName: 'nextFollowUpAt', position: 4, size: 180 },
            ],
          },
        },
        {
          title: 'Customer Snapshot',
          type: 'RECORD_TABLE',
          objectNameSingular: 'xopureCustomer',
          gridPosition: { row: 6, column: 6, rowSpan: 8, columnSpan: 6 },
          view: {
            name: 'Customer Dashboard Table',
            icon: 'IconUserHeart',
            position: 111,
            fields: [
              { fieldName: 'name', position: 0, size: 220 },
              { fieldName: 'status', position: 1, size: 140 },
              { fieldName: 'lifetimeValueCents', position: 2, size: 160 },
              { fieldName: 'orderCount', position: 3, size: 120 },
              { fieldName: 'lastOrderAt', position: 4, size: 180 },
            ],
          },
        },
      ],
    },
  ],
};
