import type { DashboardBlueprint } from './dashboard-blueprint.type';

export const opsCommandCenterBlueprint: DashboardBlueprint = {
  title: 'Ops Command Center',
  tabs: [
    {
      key: 'overview',
      title: 'Overview',
      position: 0,
      widgets: [
        {
          title: 'Total Orders',
          type: 'GRAPH',
          objectNameSingular: 'xopureOrder',
          gridPosition: { row: 0, column: 0, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            label: 'Orders',
            displayDataLabel: true,
          },
        },
        {
          title: 'Paid / Fulfilled Revenue',
          type: 'GRAPH',
          objectNameSingular: 'xopureOrder',
          gridPosition: { row: 0, column: 3, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'orderTotal',
            aggregateOperation: 'SUM',
            label: 'Paid / fulfilled revenue',
            filter: {
              status: { in: ['PAID', 'FULFILLED'] },
            },
            displayDataLabel: true,
          },
        },
        {
          title: 'Order Status Mix',
          type: 'GRAPH',
          objectNameSingular: 'xopureOrder',
          gridPosition: { row: 2, column: 0, rowSpan: 4, columnSpan: 6 },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            groupByFieldName: 'status',
            orderBy: 'VALUE_DESC',
            displayDataLabel: true,
          },
        },
        {
          title: 'Payment Status Mix',
          type: 'GRAPH',
          objectNameSingular: 'xopurePayment',
          gridPosition: { row: 2, column: 6, rowSpan: 4, columnSpan: 6 },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            groupByFieldName: 'status',
            orderBy: 'VALUE_DESC',
            displayDataLabel: true,
          },
        },
      ],
    },
    {
      key: 'fulfillment',
      title: 'Fulfillment',
      position: 1,
      widgets: [
        {
          title: 'Paid But Not Fulfilled',
          type: 'GRAPH',
          objectNameSingular: 'xopureOrder',
          gridPosition: { row: 0, column: 0, rowSpan: 4, columnSpan: 6 },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            groupByFieldName: 'fulfillmentStatus',
            orderBy: 'VALUE_DESC',
            displayDataLabel: true,
          },
        },
        {
          title: 'Fulfillment Status',
          type: 'GRAPH',
          objectNameSingular: 'xopureOrder',
          gridPosition: { row: 0, column: 6, rowSpan: 4, columnSpan: 6 },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            groupByFieldName: 'status',
            orderBy: 'VALUE_DESC',
            displayDataLabel: true,
          },
        },
        {
          title: 'Recent Orders',
          type: 'RECORD_TABLE',
          objectNameSingular: 'xopureOrder',
          gridPosition: { row: 4, column: 0, rowSpan: 6, columnSpan: 12 },
          view: {
            name: 'Ops Orders',
            icon: 'IconShoppingBag',
            fields: [
              { fieldName: 'orderNumber', position: 0, size: 150 },
              { fieldName: 'status', position: 1, size: 120 },
              { fieldName: 'paymentStatus', position: 2, size: 130 },
              { fieldName: 'fulfillmentStatus', position: 3, size: 140 },
              { fieldName: 'orderTotal', position: 4, size: 110 },
              { fieldName: 'orderedAt', position: 5, size: 160 },
            ],
          },
        },
      ],
    },
    {
      key: 'payments',
      title: 'Payments',
      position: 2,
      widgets: [
        {
          title: 'Successful Payment Volume',
          type: 'GRAPH',
          objectNameSingular: 'xopurePayment',
          gridPosition: { row: 0, column: 0, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'amount',
            aggregateOperation: 'SUM',
            label: 'Successful payment volume',
            filter: {
              status: { in: ['SUCCEEDED'] },
            },
            displayDataLabel: true,
          },
        },
        {
          title: 'Failed Payments (count)',
          type: 'GRAPH',
          objectNameSingular: 'xopurePayment',
          gridPosition: { row: 0, column: 3, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            label: 'Total payments',
            displayDataLabel: true,
          },
        },
        {
          title: 'Payment Status Mix',
          type: 'GRAPH',
          objectNameSingular: 'xopurePayment',
          gridPosition: { row: 2, column: 0, rowSpan: 4, columnSpan: 6 },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            groupByFieldName: 'status',
            orderBy: 'VALUE_DESC',
            displayDataLabel: true,
          },
        },
        {
          title: 'Payment Provider Mix',
          type: 'GRAPH',
          objectNameSingular: 'xopurePayment',
          gridPosition: { row: 2, column: 6, rowSpan: 4, columnSpan: 6 },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            groupByFieldName: 'provider',
            orderBy: 'VALUE_DESC',
            displayDataLabel: true,
          },
        },
      ],
    },
    {
      key: 'ambassadors',
      title: 'Ambassadors',
      position: 3,
      widgets: [
        {
          title: 'Total Ambassadors',
          type: 'GRAPH',
          objectNameSingular: 'xopureAmbassador',
          gridPosition: { row: 0, column: 0, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            label: 'Ambassadors',
            displayDataLabel: true,
          },
        },
        {
          title: 'Held Commissions',
          type: 'GRAPH',
          objectNameSingular: 'xopureAmbassador',
          gridPosition: { row: 0, column: 3, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'heldCommission',
            aggregateOperation: 'SUM',
            label: 'Held commission',
            displayDataLabel: true,
          },
        },
        {
          title: 'Ambassador Status Mix',
          type: 'GRAPH',
          objectNameSingular: 'xopureAmbassador',
          gridPosition: { row: 2, column: 0, rowSpan: 4, columnSpan: 6 },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            groupByFieldName: 'status',
            orderBy: 'VALUE_DESC',
            displayDataLabel: true,
          },
        },
        {
          title: 'Ambassador Level Mix',
          type: 'GRAPH',
          objectNameSingular: 'xopureAmbassador',
          gridPosition: { row: 2, column: 6, rowSpan: 4, columnSpan: 6 },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            groupByFieldName: 'level',
            orderBy: 'VALUE_DESC',
            displayDataLabel: true,
          },
        },
      ],
    },
    {
      key: 'commissions',
      title: 'Commissions',
      position: 4,
      widgets: [
        {
          title: 'Commission Amount',
          type: 'GRAPH',
          objectNameSingular: 'xopureCommission',
          gridPosition: { row: 0, column: 0, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'amount',
            aggregateOperation: 'SUM',
            label: 'Commission',
            displayDataLabel: true,
          },
        },
        {
          title: 'Commission Count',
          type: 'GRAPH',
          objectNameSingular: 'xopureCommission',
          gridPosition: { row: 0, column: 3, rowSpan: 2, columnSpan: 3 },
          configuration: {
            configurationType: 'AGGREGATE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            label: 'Commissions',
            displayDataLabel: true,
          },
        },
        {
          title: 'Commission Status Mix',
          type: 'GRAPH',
          objectNameSingular: 'xopureCommission',
          gridPosition: { row: 2, column: 0, rowSpan: 4, columnSpan: 6 },
          configuration: {
            configurationType: 'PIE_CHART',
            aggregateFieldName: 'id',
            aggregateOperation: 'COUNT',
            groupByFieldName: 'status',
            orderBy: 'VALUE_DESC',
            displayDataLabel: true,
          },
        },
        {
          title: 'Recent Commissions',
          type: 'RECORD_TABLE',
          objectNameSingular: 'xopureCommission',
          gridPosition: { row: 6, column: 0, rowSpan: 6, columnSpan: 12 },
          view: {
            name: 'Ops Commissions',
            icon: 'IconReceiptDollar',
            fields: [
              { fieldName: 'name', position: 0, size: 180 },
              { fieldName: 'status', position: 1, size: 120 },
              { fieldName: 'amount', position: 2, size: 120 },
              { fieldName: 'rate', position: 3, size: 80 },
              { fieldName: 'holdUntil', position: 4, size: 160 },
            ],
          },
        },
      ],
    },
    {
      key: 'exceptions',
      title: 'Exceptions',
      position: 5,
      widgets: [
        {
          title: 'Exception Commissions',
          type: 'RECORD_TABLE',
          objectNameSingular: 'xopureCommission',
          gridPosition: { row: 0, column: 0, rowSpan: 6, columnSpan: 12 },
          view: {
            name: 'Exception Commissions',
            icon: 'IconAlertTriangle',
            fields: [
              { fieldName: 'name', position: 0, size: 180 },
              { fieldName: 'status', position: 1, size: 120 },
              { fieldName: 'amount', position: 2, size: 120 },
              { fieldName: 'holdUntil', position: 3, size: 160 },
            ],
          },
        },
      ],
    },
  ],
};
