import { PageLayoutType } from '@/types/page-layout/PageLayoutType';
import { WidgetType } from '@/types/page-layout/WidgetType';

const PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM = [
  PageLayoutType.RECORD_PAGE,
  PageLayoutType.RECORD_INDEX,
  PageLayoutType.DASHBOARD,
  PageLayoutType.STANDALONE_PAGE,
] as const;

export const SUPPORTED_PAGE_LAYOUT_TYPES_BY_WIDGET_TYPE: Record<
  WidgetType,
  readonly PageLayoutType[]
> = {
  [WidgetType.VIEW]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.IFRAME]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.FIELD]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.FIELDS]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.GRAPH]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.STANDALONE_RICH_TEXT]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.TIMELINE]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.TASKS]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.NOTES]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.FILES]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.EMAILS]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.CALENDAR]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.FIELD_RICH_TEXT]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.WORKFLOW]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.WORKFLOW_VERSION]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.WORKFLOW_RUN]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.FRONT_COMPONENT]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.RECORD_TABLE]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.EMAIL_THREAD]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.CALL_RECORDING_SUMMARY]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.CALL_RECORDING_TRANSCRIPT]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.MESSAGE_CAMPAIGN_BODY]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.MESSAGE_CAMPAIGN_DETAILS]: PAGE_LAYOUT_TYPES_EXCEPT_RECORD_FORM,
  [WidgetType.FORM_FIELD]: [PageLayoutType.RECORD_FORM],
};

export const isWidgetTypeSupportedInPageLayoutType = ({
  widgetType,
  pageLayoutType,
}: {
  widgetType: WidgetType;
  pageLayoutType: PageLayoutType;
}): boolean =>
  SUPPORTED_PAGE_LAYOUT_TYPES_BY_WIDGET_TYPE[widgetType].includes(
    pageLayoutType,
  );
