import { FieldMetadataType } from 'twenty-shared/types';

import { WorkspaceEntityDuplicateCriteria } from 'src/engine/api/graphql/workspace-query-builder/types/workspace-entity-duplicate-criteria.type';
import { ObjectMetadataItemWithFieldMaps } from 'src/engine/metadata-modules/types/object-metadata-item-with-field-maps';

export const mockPersonObjectMetadata = (
  duplicateCriteria: WorkspaceEntityDuplicateCriteria[],
): ObjectMetadataItemWithFieldMaps => ({
  id: '',
  standardId: '',
  nameSingular: 'person',
  namePlural: 'people',
  labelSingular: 'Person',
  labelPlural: 'People',
  description: 'A person',
  targetTableName: 'DEPRECATED',
  isCustom: false,
  isRemote: false,
  isActive: true,
  isSystem: false,
  isAuditLogged: true,
  isSearchable: true,
  duplicateCriteria: duplicateCriteria,
  fromRelations: [],
  toRelations: [],
  labelIdentifierFieldMetadataId: '',
  imageIdentifierFieldMetadataId: '',
  workspaceId: '',
  fields: [],
  indexMetadatas: [],
  fieldsById: {},
  fieldsByJoinColumnName: {},
  fieldsByName: {
    name: {
      id: '',
      objectMetadataId: '',
      type: FieldMetadataType.FULL_NAME,
      name: 'name',
      label: 'Name',
      defaultValue: {
        lastName: "''",
        firstName: "''",
      },
      description: 'Contact’s name',
      isCustom: false,
      isNullable: true,
      isUnique: false,
      workspaceId: '',
    },
    emails: {
      id: '',
      objectMetadataId: '',
      type: FieldMetadataType.EMAILS,
      name: 'emails',
      label: 'Emails',
      defaultValue: {
        primaryEmail: "''",
        additionalEmails: null,
      },
      description: 'Contact’s Emails',
      isCustom: false,
      workspaceId: '',
    },
    linkedinLink: {
      id: '',
      objectMetadataId: '',
      type: FieldMetadataType.LINKS,
      name: 'linkedinLink',
      label: 'Linkedin',
      defaultValue: {
        primaryLinkUrl: "''",
        secondaryLinks: "'[]'",
        primaryLinkLabel: "''",
      },
      description: 'Contact’s Linkedin account',
      isCustom: false,
      isNullable: true,
      isUnique: false,
      workspaceId: '',
    },
    jobTitle: {
      id: '',
      objectMetadataId: '',
      type: FieldMetadataType.TEXT,
      name: 'jobTitle',
      label: 'Job Title',
      defaultValue: "''",
      description: 'Contact’s job title',
      isCustom: false,
      isNullable: false,
      isUnique: false,
      workspaceId: '20202020-1c25-4d02-bf25-6aeccf7ea419',
    },
  },
});
