import { COLOR_TOKENS } from './color';
import { GRAY_SCALE_TOKENS } from './grayScale';
export const TAG_TOKENS = {
  text: {
    gray: GRAY_SCALE_TOKENS.gray11,
    mauve: COLOR_TOKENS.mauve11,
    slate: COLOR_TOKENS.slate11,
    sage: COLOR_TOKENS.sage11,
    olive: COLOR_TOKENS.olive11,
    sand: COLOR_TOKENS.sand11,
    tomato: COLOR_TOKENS.tomato11,
    red: COLOR_TOKENS.red11,
    ruby: COLOR_TOKENS.ruby11,
    crimson: COLOR_TOKENS.crimson11,
    pink: COLOR_TOKENS.pink11,
    plum: COLOR_TOKENS.plum11,
    purple: COLOR_TOKENS.purple11,
    violet: COLOR_TOKENS.violet11,
    iris: COLOR_TOKENS.iris11,
    cyan: COLOR_TOKENS.cyan11,
    turquoise: COLOR_TOKENS.turquoise11,
    sky: COLOR_TOKENS.sky11,
    blue: COLOR_TOKENS.blue11,
    jade: COLOR_TOKENS.jade11,
    green: COLOR_TOKENS.green11,
    grass: COLOR_TOKENS.grass11,
    mint: COLOR_TOKENS.mint11,
    lime: COLOR_TOKENS.lime11,
    bronze: COLOR_TOKENS.bronze11,
    gold: COLOR_TOKENS.gold11,
    brown: COLOR_TOKENS.brown11,
    orange: COLOR_TOKENS.orange11,
    amber: COLOR_TOKENS.amber11,
    yellow: COLOR_TOKENS.yellow11,
  },
  background: {
    gray: GRAY_SCALE_TOKENS.gray3,
    mauve: COLOR_TOKENS.mauve3,
    slate: COLOR_TOKENS.slate3,
    sage: COLOR_TOKENS.sage3,
    olive: COLOR_TOKENS.olive3,
    sand: COLOR_TOKENS.sand3,
    tomato: COLOR_TOKENS.tomato3,
    red: COLOR_TOKENS.red3,
    ruby: COLOR_TOKENS.ruby3,
    crimson: COLOR_TOKENS.crimson3,
    pink: COLOR_TOKENS.pink3,
    plum: COLOR_TOKENS.plum3,
    purple: COLOR_TOKENS.purple3,
    violet: COLOR_TOKENS.violet3,
    iris: COLOR_TOKENS.iris3,
    cyan: COLOR_TOKENS.cyan3,
    turquoise: COLOR_TOKENS.turquoise3,
    sky: COLOR_TOKENS.sky3,
    blue: COLOR_TOKENS.blue3,
    jade: COLOR_TOKENS.jade3,
    green: COLOR_TOKENS.green3,
    grass: COLOR_TOKENS.grass3,
    mint: COLOR_TOKENS.mint3,
    lime: COLOR_TOKENS.lime3,
    bronze: COLOR_TOKENS.bronze3,
    gold: COLOR_TOKENS.gold3,
    brown: COLOR_TOKENS.brown3,
    orange: COLOR_TOKENS.orange3,
    amber: COLOR_TOKENS.amber3,
    yellow: COLOR_TOKENS.yellow3,
  },
};
