export const THEME_COMMON_ROOT_KEYS: readonly string[] = [
  'icon',
  'modal',
  'text',
  'tooltip',
  'animation',
  'spacingMultiplicator',
  'spacing',
  'betweenSiblingsGap',
  'table',
  'sidePanelWidth',
  'clickableElementBackgroundTransition',
  'lastLayerZIndex',
  'buttons',
];
