import { EmailDriver } from 'src/integrations/email/interfaces/email.interface';
import { SupportDriver } from 'src/integrations/environment/interfaces/support.interface';

import { EnvironmentType } from 'src/integrations/environment/envionment.type';
import { ExceptionHandlerDriver } from 'src/integrations/exception-handler/interfaces';
import { StorageDriverType } from 'src/integrations/file-storage/interfaces';
import { LoggerDriverType } from 'src/integrations/logger/interfaces';
import { MessageQueueDriverType } from 'src/integrations/message-queue/interfaces';

export const EnvironmentDefault: EnvironmentType = {
  DEBUG_MODE: false,
  SIGN_IN_PREFILLED: false,
  IS_BILLING_ENABLED: false,
  BILLING_PLAN_REQUIRED_LINK: '',
  BILLING_STRIPE_BASE_PLAN_PRODUCT_ID: '',
  BILLING_FREE_TRIAL_DURATION_IN_DAYS: 7,
  BILLING_STRIPE_API_KEY: '',
  BILLING_STRIPE_WEBHOOK_SECRET: '',
  TELEMETRY_ENABLED: true,
  TELEMETRY_ANONYMIZATION_ENABLED: true,
  PORT: 3000,
  REDIS_HOST: '127.0.0.1',
  REDIS_PORT: 6379,
  PG_DATABASE_URL: '',
  FRONT_BASE_URL: '',
  SERVER_URL: '',
  ACCESS_TOKEN_SECRET: 'random_string',
  ACCESS_TOKEN_EXPIRES_IN: '30m',
  REFRESH_TOKEN_SECRET: 'random_string',
  REFRESH_TOKEN_EXPIRES_IN: '30m',
  REFRESH_TOKEN_COOL_DOWN: '1m',
  LOGIN_TOKEN_SECRET: 'random_string',
  LOGIN_TOKEN_EXPIRES_IN: '30m',
  API_TOKEN_EXPIRES_IN: '100y',
  SHORT_TERM_TOKEN_EXPIRES_IN: '5m',
  FRONT_AUTH_CALLBACK_URL: '',
  MESSAGING_PROVIDER_GMAIL_ENABLED: false,
  MESSAGING_PROVIDER_GMAIL_CALLBACK_URL: '',
  AUTH_GOOGLE_ENABLED: false,
  AUTH_GOOGLE_CLIENT_ID: '',
  AUTH_GOOGLE_CLIENT_SECRET: '',
  AUTH_GOOGLE_CALLBACK_URL: '',
  STORAGE_TYPE: StorageDriverType.Local,
  STORAGE_S3_REGION: 'aws-east-1',
  STORAGE_S3_NAME: '',
  STORAGE_S3_ENDPOINT: '',
  STORAGE_LOCAL_PATH: '.local-storage',
  MESSAGE_QUEUE_TYPE: MessageQueueDriverType.Sync,
  EMAIL_FROM_ADDRESS: 'noreply@yourdomain.com',
  EMAIL_SYSTEM_ADDRESS: 'system@yourdomain.com',
  EMAIL_FROM_NAME: 'John from Twenty',
  EMAIL_DRIVER: EmailDriver.Logger,
  EMAIL_SMTP_HOST: '',
  EMAIL_SMTP_PORT: 587,
  EMAIL_SMTP_USER: '',
  EMAIL_SMTP_PASSWORD: '',
  SUPPORT_DRIVER: SupportDriver.None,
  SUPPORT_FRONT_CHAT_ID: '',
  SUPPORT_FRONT_HMAC_KEY: '',
  LOGGER_DRIVER: LoggerDriverType.Console,
  EXCEPTION_HANDLER_DRIVER: ExceptionHandlerDriver.Console,
  LOG_LEVELS: ['log', 'error', 'warn'],
  SENTRY_DSN: '',
  DEMO_WORKSPACE_IDS: [],
  OPENROUTER_API_KEY: '',
  PASSWORD_RESET_TOKEN_EXPIRES_IN: '5m',
  WORKSPACE_INACTIVE_DAYS_BEFORE_NOTIFICATION: 30,
  WORKSPACE_INACTIVE_DAYS_BEFORE_DELETION: 60,
  IS_SIGN_UP_DISABLED: false,
  API_RATE_LIMITING_TTL: 100,
  API_RATE_LIMITING_LIMIT: 500,
  MUTATION_MAXIMUM_RECORD_AFFECTED: 100,
  CACHE_STORAGE_TYPE: 'memory',
  CACHE_STORAGE_TTL: 3600 * 24 * 7,
};
