enableInlineHunks: true

enableScripts: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.2.cjs

supportedArchitectures:
  os:
    - current
    - linux
    - darwin
  cpu:
    - current
    - x64
    - arm64
