export const ALL_METADATA_NAME = {
  fieldMetadata: 'fieldMetadata',
  objectMetadata: 'objectMetadata',
  view: 'view',
  viewField: 'viewField',
  viewGroup: 'viewGroup',
  index: 'index',
  serverlessFunction: 'serverlessFunction',
  cronTrigger: 'cronTrigger',
  databaseEventTrigger: 'databaseEventTrigger',
  routeTrigger: 'routeTrigger',
  viewFilter: 'viewFilter',
  role: 'role',
  roleTarget: 'roleTarget',
} as const;
