import { type WorkflowValidationIssueCode } from '@/workflow/validation/types/workflow-validation.type';

export const INCOMPLETE_WORKFLOW_VALIDATION_ISSUE_CODES: ReadonlySet<WorkflowValidationIssueCode> =
  new Set([
    'MISSING_TRIGGER',
    'MISSING_TRIGGER_TYPE',
    'NO_STEPS',
    'TRIGGER_HAS_NO_NEXT_STEP',
    'UNREACHABLE_STEP',
    'INVALID_PICK_RECORD_CONFIG',
    'IF_ELSE_INSUFFICIENT_BRANCHES',
    'IF_ELSE_BRANCH_HAS_NO_NEXT_STEP',
    'ITERATOR_MISSING_LOOP_BODY',
    'VARIABLE_INVALID_PATH',
    'VARIABLE_UNKNOWN_STEP',
    'VARIABLE_NOT_UPSTREAM',
    'VARIABLE_MISSING_OUTPUT_SCHEMA',
    'VARIABLE_PATH_NOT_FOUND',
    'CODE_STEP_MISSING_OUTPUT_SCHEMA',
    'STEP_HAS_NO_VARIABLE_REFERENCE',
    'LOGIC_FUNCTION_OUTPUT_SCHEMA_MISMATCH',
    'AI_AGENT_MISSING_AGENT',
    'AI_AGENT_MISSING_OUTPUT_VARIABLE',
  ]);
