import {
  mkdir,
  mkdtemp,
  readdir,
  readFile,
  rm,
  writeFile,
} from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import {
  generateCoreClientFromSchema,
  generateCoreClientSource,
} from '../generate-core-client';

const SCHEMA = `
type Query {
  person(id: ID!): Person
}

type Person {
  id: ID!
  name: String
  status: PersonStatus
}

enum PersonStatus {
  ACTIVE
  INACTIVE
}

schema {
  query: Query
}
`;

const PROVENANCE_HEADER =
  '@generated by twenty dev:generate-client from http://localhost:3000';

describe('generateCoreClientSource', () => {
  let temporaryDir: string;

  beforeAll(async () => {
    temporaryDir = await mkdtemp(join(tmpdir(), 'twenty-genql-source-'));
  });

  afterAll(async () => {
    if (temporaryDir) {
      await rm(temporaryDir, { recursive: true, force: true });
    }
  });

  describe('full client source', () => {
    let outputPath: string;

    beforeAll(async () => {
      outputPath = join(temporaryDir, 'client');

      await generateCoreClientSource({
        schema: SCHEMA,
        outputPath,
        provenanceHeader: PROVENANCE_HEADER,
      });
    }, 60000);

    it('emits TypeScript source without compiled bundles', async () => {
      const entries = await readdir(outputPath);

      expect(entries).toEqual(
        expect.arrayContaining([
          'index.ts',
          'schema.ts',
          'types.ts',
          'runtime',
        ]),
      );
      expect(entries).not.toContain('index.mjs');
      expect(entries).not.toContain('index.cjs');
      expect(entries).not.toContain('package.json');
    });

    it('exports createClient without the in-app CoreApiClient wrapper', async () => {
      const indexContent = await readFile(
        join(outputPath, 'index.ts'),
        'utf-8',
      );

      expect(indexContent).toContain('createClient');
      expect(indexContent).not.toContain('CoreApiClient');
    });

    it('references no process.env at module scope (browser-safe)', async () => {
      const indexContent = await readFile(
        join(outputPath, 'index.ts'),
        'utf-8',
      );

      expect(indexContent).not.toContain('process.env');
    });

    it('prepends the provenance header to every TypeScript file', async () => {
      const indexContent = await readFile(
        join(outputPath, 'index.ts'),
        'utf-8',
      );
      const runtimeContent = await readFile(
        join(outputPath, 'runtime', 'createClient.ts'),
        'utf-8',
      );

      expect(indexContent.startsWith(`// ${PROVENANCE_HEADER}\n`)).toBe(true);
      expect(runtimeContent.startsWith(`// ${PROVENANCE_HEADER}\n`)).toBe(true);
    });
  });

  describe('types-only', () => {
    let outputPath: string;
    let schemaContent: string;

    beforeAll(async () => {
      outputPath = join(temporaryDir, 'types');

      await generateCoreClientSource({
        schema: SCHEMA,
        outputPath,
        typesOnly: true,
        provenanceHeader: PROVENANCE_HEADER,
      });

      schemaContent = await readFile(join(outputPath, 'schema.ts'), 'utf-8');
    }, 60000);

    it('emits only schema.ts', async () => {
      const entries = await readdir(outputPath);

      expect(entries).toEqual(['schema.ts']);
    });

    it('contains response types and enum constant maps', () => {
      expect(schemaContent).toContain('export interface Person');
      expect(schemaContent).toContain("'ACTIVE' | 'INACTIVE'");
      expect(schemaContent).toContain('export const enumPersonStatus');
    });

    it('contains no request/selection types or runtime client', () => {
      expect(schemaContent).not.toContain('PersonRequest');
      expect(schemaContent).not.toContain('createClient');
    });

    it('prepends the provenance header', () => {
      expect(schemaContent.startsWith(`// ${PROVENANCE_HEADER}\n`)).toBe(true);
    });
  });

  describe('in-app wrapper default url (generateCoreClientFromSchema)', () => {
    it('reads the default url through the safe process accessor', async () => {
      const outputPath = join(temporaryDir, 'wrapped');

      await generateCoreClientFromSchema({ schema: SCHEMA, outputPath });

      const indexContent = await readFile(
        join(outputPath, 'index.ts'),
        'utf-8',
      );

      expect(indexContent).toContain('getProcessEnvironment().TWENTY_API_URL');
      expect(indexContent).not.toContain('process.env.TWENTY_API_URL');
    }, 60000);
  });

  describe('output path overwrite guard', () => {
    it('refuses a non-empty directory that is not a previous generation', async () => {
      const outputPath = join(temporaryDir, 'occupied');
      await mkdir(outputPath, { recursive: true });
      await writeFile(join(outputPath, 'my-source-file.ts'), 'export {};\n');

      await expect(
        generateCoreClientSource({ schema: SCHEMA, outputPath }),
      ).rejects.toThrow('Refusing to overwrite');
    });

    it('refuses a directory mixing a schema.ts with unrelated files', async () => {
      const outputPath = join(temporaryDir, 'mixed');
      await mkdir(outputPath, { recursive: true });
      await writeFile(join(outputPath, 'schema.ts'), 'export {};\n');
      await writeFile(join(outputPath, 'my-source-file.ts'), 'export {};\n');

      await expect(
        generateCoreClientSource({ schema: SCHEMA, outputPath }),
      ).rejects.toThrow('Refusing to overwrite');
    });

    it('replaces a previous full generation, leaving no stale files', async () => {
      const outputPath = join(temporaryDir, 'regenerated');

      await generateCoreClientSource({ schema: SCHEMA, outputPath });
      await generateCoreClientSource({
        schema: SCHEMA,
        outputPath,
        typesOnly: true,
      });

      const entries = await readdir(outputPath);

      expect(entries).toEqual(['schema.ts']);
    }, 60000);

    it('does not touch an unrelated sibling <output>.tmp directory', async () => {
      const outputPath = join(temporaryDir, 'guarded');
      const siblingPath = `${outputPath}.tmp`;
      await mkdir(siblingPath, { recursive: true });
      await writeFile(join(siblingPath, 'keep-me.txt'), 'important\n');

      await generateCoreClientSource({
        schema: SCHEMA,
        outputPath,
        typesOnly: true,
      });

      await expect(
        readFile(join(siblingPath, 'keep-me.txt'), 'utf-8'),
      ).resolves.toBe('important\n');
    });
  });
});
