import { defineObject, FieldType } from 'twenty-sdk';

import {
  CLOUD_WORKSPACE_2_ACTIVATION_STATUS_FIELD_ID,
  CLOUD_WORKSPACE_2_ACTIVE_USERS_L24H_FIELD_ID,
  CLOUD_WORKSPACE_2_ACTIVE_USERS_L30D_FIELD_ID,
  CLOUD_WORKSPACE_2_ACTIVE_USERS_L7D_FIELD_ID,
  CLOUD_WORKSPACE_2_ALEXA_RANK_FIELD_ID,
  CLOUD_WORKSPACE_2_ANNUAL_REVENUE_FIELD_ID,
  CLOUD_WORKSPACE_2_ARR_FIELD_ID,
  CLOUD_WORKSPACE_2_COMPANY_FOUNDED_YEAR_FIELD_ID,
  CLOUD_WORKSPACE_2_COMPANY_LINKEDIN_FIELD_ID,
  CLOUD_WORKSPACE_2_COMPANY_NAME_FIELD_ID,
  CLOUD_WORKSPACE_2_CREATOR_EMAIL_FIELD_ID,
  CLOUD_WORKSPACE_2_CUSTOM_DOMAIN_FIELD_ID,
  CLOUD_WORKSPACE_2_DATA_LAST_UPDATED_AT_FIELD_ID,
  CLOUD_WORKSPACE_2_DESCRIPTION_FIELD_ID,
  CLOUD_WORKSPACE_2_EMPLOYEES_FIELD_ID,
  CLOUD_WORKSPACE_2_INDUSTRY_FIELD_ID,
  CLOUD_WORKSPACE_2_IS_ACTIVE_L24H_FIELD_ID,
  CLOUD_WORKSPACE_2_IS_ACTIVE_L30D_FIELD_ID,
  CLOUD_WORKSPACE_2_IS_ACTIVE_L7D_FIELD_ID,
  CLOUD_WORKSPACE_2_IS_ENRICHED_FIELD_ID,
  CLOUD_WORKSPACE_2_LAST_PAGE_VIEW_DATE_FIELD_ID,
  CLOUD_WORKSPACE_2_LATEST_FUNDING_STAGE_FIELD_ID,
  CLOUD_WORKSPACE_2_MRR_FIELD_ID,
  CLOUD_WORKSPACE_2_NEXT_RENEWAL_DATE_FIELD_ID,
  CLOUD_WORKSPACE_2_NUMBER_OF_EVENTS_L30D_FIELD_ID,
  CLOUD_WORKSPACE_2_NUMBER_OF_EVENTS_TOTAL_FIELD_ID,
  CLOUD_WORKSPACE_2_PAGE_VIEWS_L24H_FIELD_ID,
  CLOUD_WORKSPACE_2_PAGE_VIEWS_L30D_FIELD_ID,
  CLOUD_WORKSPACE_2_PAGE_VIEWS_L7D_FIELD_ID,
  CLOUD_WORKSPACE_2_PAYMENT_FREQUENCY_FIELD_ID,
  CLOUD_WORKSPACE_2_POTENTIAL_ARR_FIELD_ID,
  CLOUD_WORKSPACE_2_SUB_DOMAIN_FIELD_ID,
  CLOUD_WORKSPACE_2_SUBSCRIPTION_STATUS_FIELD_ID,
  CLOUD_WORKSPACE_2_TAGS_FIELD_ID,
  CLOUD_WORKSPACE_2_TOTAL_EVER_ACTIVE_WORKSPACE_USERS_FIELD_ID,
  CLOUD_WORKSPACE_2_TOTAL_FUNDING_FIELD_ID,
  CLOUD_WORKSPACE_2_TOTAL_WORKSPACE_USERS_FIELD_ID,
  CLOUD_WORKSPACE_2_UPDATED_BY_FIELD_ID,
  CLOUD_WORKSPACE_2_WORKSPACE_BUSINESS_DOMAIN_FIELD_ID,
  CLOUD_WORKSPACE_2_WORKSPACE_TENURE_FIELD_ID,
} from 'src/fields/cloud-workspace-2-field-ids';

export const CLOUD_WORKSPACE_2_UNIVERSAL_IDENTIFIER =
  '77376ed3-19c1-4859-bde5-90f19ad02113';

export default defineObject({
  universalIdentifier: CLOUD_WORKSPACE_2_UNIVERSAL_IDENTIFIER,
  nameSingular: 'cloudWorkspace2',
  namePlural: 'cloudWorkspaces2',
  labelSingular: 'Cloud workspace 2',
  labelPlural: 'Cloud workspaces 2',
  icon: 'IconBox',
  fields: [
    {
      universalIdentifier: CLOUD_WORKSPACE_2_CUSTOM_DOMAIN_FIELD_ID,
      type: FieldType.LINKS,
      name: 'customDomain',
      label: 'Custom domain',
      description: 'Custom domain set up by the customer to use their own.',
      icon: 'IconLink',
      isNullable: true,

    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_WORKSPACE_BUSINESS_DOMAIN_FIELD_ID,
      type: FieldType.LINKS,
      name: 'workspaceBusinessDomain',
      label: 'Workspace Business Domain',
      icon: 'IconLink',
      isNullable: true,

    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_COMPANY_LINKEDIN_FIELD_ID,
      type: FieldType.LINKS,
      name: 'companyLinkedin',
      label: 'Company LinkedIn',
      icon: 'IconBrandLinkedin',
      isNullable: true,

    },

    {
      universalIdentifier: CLOUD_WORKSPACE_2_DATA_LAST_UPDATED_AT_FIELD_ID,
      type: FieldType.DATE,
      name: 'dataLastUpdatedAt',
      label: 'Data last updated at',
      description: 'by workflow',
      icon: 'IconCalendarEvent',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_LAST_PAGE_VIEW_DATE_FIELD_ID,
      type: FieldType.DATE,
      name: 'lastPageViewDate',
      label: 'Last Page View Date',
      icon: 'IconCalendarEvent',
      isNullable: true,
      defaultValue: null,
    },

    {
      universalIdentifier: CLOUD_WORKSPACE_2_TOTAL_EVER_ACTIVE_WORKSPACE_USERS_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'totalEverActiveWorkspaceUsers',
      label: 'Total ever active workspace users',
      icon: 'IconUsers',
      isNullable: true,
      defaultValue: null,
      universalSettings: {
        type: 'number',
        decimals: 0,
      },
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_ACTIVE_USERS_L30D_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'activeUsersL30D',
      label: 'Active Users L30D',
      icon: 'IconUsersGroup',
      isNullable: true,
      defaultValue: null,
      universalSettings: {
        type: 'number',
        decimals: 0,
      },
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_ACTIVE_USERS_L7D_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'activeUsersL7D',
      label: 'Active Users L7D',
      icon: 'IconUsersGroup',
      isNullable: true,
      defaultValue: null,
      universalSettings: {
        type: 'number',
        decimals: 0,
      },
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_ACTIVE_USERS_L24H_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'activeUsersL24H',
      label: 'Active Users L24H',
      icon: 'IconUsersGroup',
      isNullable: true,
      defaultValue: null,
      universalSettings: {
        type: 'number',
        decimals: 0,
      },
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_WORKSPACE_TENURE_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'workspaceTenure',
      label: 'Workspace tenure',
      description: 'in days',
      icon: 'IconCalendarHeart',
      isNullable: true,
      defaultValue: null,
      universalSettings: {
        type: 'number',
        decimals: 0,
      },
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_PAGE_VIEWS_L30D_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'pageViewsL30D',
      label: 'Page Views L30D',
      icon: 'IconClick',
      isNullable: true,
      defaultValue: null,
      universalSettings: {
        type: 'number',
        decimals: 0,
      },
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_PAGE_VIEWS_L7D_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'pageViewsL7D',
      label: 'Page Views L7D',
      icon: 'IconClick',
      isNullable: true,
      defaultValue: null,
      universalSettings: {
        type: 'number',
        decimals: 0,
      },
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_PAGE_VIEWS_L24H_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'pageViewsL24H',
      label: 'Page Views L24H',
      icon: 'IconClick',
      isNullable: true,
      defaultValue: null,
      universalSettings: {
        type: 'number',
        decimals: 0,
      },
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_TOTAL_WORKSPACE_USERS_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'totalWorkspaceUsers',
      label: 'Total workspace users',
      icon: 'IconUsers',
      isNullable: true,
      defaultValue: null,
      universalSettings: {
        type: 'number',
        decimals: 0,
      },
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_NUMBER_OF_EVENTS_L30D_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'numberOfEventsL30D',
      label: 'Number of events L30D',
      icon: 'IconHandClick',
      isNullable: true,
      defaultValue: null,
      universalSettings: {
        type: 'number',
        decimals: 0,
      },
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_NUMBER_OF_EVENTS_TOTAL_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'numberOfEventsTotal',
      label: 'Number of events total',
      icon: 'IconHandClick',
      isNullable: true,
      defaultValue: null,
      universalSettings: {
        type: 'number',
        decimals: 0,
      },
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_ALEXA_RANK_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'alexaRank',
      label: 'Alexa Rank',
      icon: 'IconNumber9',
      isNullable: true,
      defaultValue: null,
      universalSettings: {
        type: 'number',
        decimals: 0,
      },
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_EMPLOYEES_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'employees',
      label: 'Employees',
      icon: 'IconUsers',
      isNullable: true,
      defaultValue: null,
      universalSettings: {
        type: 'number',
        decimals: 0,
      },
    },

    {
      universalIdentifier: CLOUD_WORKSPACE_2_IS_ACTIVE_L7D_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: 'isActiveL7D',
      label: 'Is Active L7D',
      icon: 'IconActivity',
      isNullable: true,
      defaultValue: false,
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_IS_ACTIVE_L24H_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: 'isActiveL24H',
      label: 'Is Active L24H',
      icon: 'IconActivity',
      isNullable: true,
      defaultValue: true,
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_IS_ACTIVE_L30D_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: 'isActiveL30D',
      label: 'Is Active L30D',
      icon: 'IconActivity',
      isNullable: true,
      defaultValue: false,
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_IS_ENRICHED_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: 'isEnriched',
      label: 'Is Enriched',
      icon: 'IconToggleLeft',
      isNullable: true,
      defaultValue: false,
    },

    {
      universalIdentifier: CLOUD_WORKSPACE_2_INDUSTRY_FIELD_ID,
      type: FieldType.TEXT,
      name: 'industry',
      label: 'Industry',
      icon: 'IconWorldLongitude',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_COMPANY_FOUNDED_YEAR_FIELD_ID,
      type: FieldType.TEXT,
      name: 'companyFoundedYear',
      label: 'Company Founded Year',
      icon: 'IconCalendarPlus',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_DESCRIPTION_FIELD_ID,
      type: FieldType.TEXT,
      name: 'description',
      label: 'Description',
      icon: 'IconBaselineDensitySmall',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_LATEST_FUNDING_STAGE_FIELD_ID,
      type: FieldType.TEXT,
      name: 'latestFundingStage',
      label: 'Latest Funding Stage',
      icon: 'IconBellDollar',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_COMPANY_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'companyName',
      label: 'Company Name',
      icon: 'IconTypography',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_SUB_DOMAIN_FIELD_ID,
      type: FieldType.TEXT,
      name: 'subDomain',
      label: 'Sub domain',
      description:
        'This is the subdomain chosen by customers to access their workspace',
      icon: 'IconLink',
      isNullable: true,
      defaultValue: null,
    },

    {
      universalIdentifier: CLOUD_WORKSPACE_2_ANNUAL_REVENUE_FIELD_ID,
      type: FieldType.CURRENCY,
      name: 'annualRevenue',
      label: 'Annual Revenue',
      icon: 'IconCurrencyDollar',
      isNullable: true,

    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_MRR_FIELD_ID,
      type: FieldType.CURRENCY,
      name: 'mrr',
      label: 'MRR',
      icon: 'IconMoneybag',
      isNullable: true,

    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_POTENTIAL_ARR_FIELD_ID,
      type: FieldType.CURRENCY,
      name: 'potentialArr',
      label: 'Potential ARR',
      icon: 'IconMoneybag',
      isNullable: true,

    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_ARR_FIELD_ID,
      type: FieldType.CURRENCY,
      name: 'arr',
      label: 'ARR',
      icon: 'IconMoneybag',
      isNullable: true,

    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_TOTAL_FUNDING_FIELD_ID,
      type: FieldType.CURRENCY,
      name: 'totalFunding',
      label: 'Total Funding',
      icon: 'IconMoneybag',
      isNullable: true,

    },

    {
      universalIdentifier: CLOUD_WORKSPACE_2_ACTIVATION_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: 'activationStatus',
      label: 'Activation Status',
      icon: 'IconTag',
      isNullable: true,
      defaultValue: null,
      options: [
        {
          id: 'c41ee49c-e629-431e-8601-183726f93315',
          color: 'yellow',
          label: 'Pending creation',
          value: 'PENDING_CREATION',
          position: 0,
        },
        {
          id: 'cb82ad14-5fcb-4ed0-af58-c92f84b45d2b',
          color: 'gray',
          label: 'Suspended',
          value: 'SUSPENDED',
          position: 1,
        },
        {
          id: 'b1084bc8-0efd-44ce-974c-7fb44c310be5',
          color: 'green',
          label: 'Active',
          value: 'ACTIVE',
          position: 2,
        },
        {
          id: 'b5b33c8e-eb3f-4758-99c9-d2f39c011b96',
          color: 'blue',
          label: 'Ongoing creation',
          value: 'ONGOING_CREATION',
          position: 3,
        },
        {
          id: '2ae41a69-c521-4545-9e0b-f1f941ceee83',
          color: 'purple',
          label: 'Empty',
          value: 'EMPTY',
          position: 4,
        },
      ],
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_SUBSCRIPTION_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: 'subscriptionStatus',
      label: 'Subscription Status',
      icon: 'IconTag',
      isNullable: true,
      defaultValue: null,
      options: [
        {
          id: 'b5ee9a91-0a15-4cbe-a36e-198f5bae431d',
          color: 'green',
          label: 'Active',
          value: 'ACTIVE',
          position: 0,
        },
        {
          id: '78837243-38d9-44d4-8b9c-a6c0ca082ba8',
          color: 'blue',
          label: 'Trialing',
          value: 'TRIALING',
          position: 1,
        },
        {
          id: '6b27ee33-3c30-4694-a607-19264765b11c',
          color: 'gray',
          label: 'Canceled',
          value: 'CANCELED',
          position: 2,
        },
        {
          id: '05118231-18b6-4589-be23-8f1368c0182f',
          color: 'yellow',
          label: 'Other',
          value: 'OTHER',
          position: 3,
        },
        {
          id: 'ea83a7ff-4fe0-4c56-88f8-cf0bdf76cb08',
          color: 'gray',
          label: 'Empty',
          value: 'EMPTY',
          position: 4,
        },
      ],
    },
    {
      universalIdentifier: CLOUD_WORKSPACE_2_PAYMENT_FREQUENCY_FIELD_ID,
      type: FieldType.SELECT,
      name: 'paymentFrequency',
      label: 'Payment Frequency',
      icon: 'IconCurrencyDollar',
      isNullable: true,
      defaultValue: null,
      options: [
        {
          id: 'fa97d4fb-12bf-4cf4-b252-14b1c657d3b6',
          color: 'sky',
          label: 'Month',
          value: 'MONTH',
          position: 0,
        },
        {
          id: 'c09c3f1d-31e7-4b29-969a-a4304f04abe0',
          color: 'purple',
          label: 'Year',
          value: 'YEAR',
          position: 1,
        },
        {
          id: 'a91d77ed-90ad-41fc-83ae-e688c981abb2',
          color: 'gray',
          label: 'Other',
          value: 'OTHER',
          position: 2,
        },
        {
          id: '5c595203-1b33-430b-abd8-8bc80aeedbd7',
          color: 'red',
          label: 'Empty',
          value: 'EMPTY',
          position: 3,
        },
      ],
    },

    {
      universalIdentifier: CLOUD_WORKSPACE_2_NEXT_RENEWAL_DATE_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'nextRenewalDate',
      label: 'Next Renewal Date',
      icon: 'IconCalendarClock',
      isNullable: true,
      defaultValue: null,
    },

    {
      universalIdentifier: CLOUD_WORKSPACE_2_CREATOR_EMAIL_FIELD_ID,
      type: FieldType.EMAILS,
      name: 'creatorEmail',
      label: 'Creator Email',
      icon: 'IconMail',
      isNullable: true,
      defaultValue: null,
    },

    {
      universalIdentifier: CLOUD_WORKSPACE_2_TAGS_FIELD_ID,
      type: FieldType.ARRAY,
      name: 'tags',
      label: 'Tags',
      icon: 'IconBracketsContain',
      isNullable: true,
      defaultValue: null,
    },

    {
      universalIdentifier: CLOUD_WORKSPACE_2_UPDATED_BY_FIELD_ID,
      type: FieldType.ACTOR,
      name: 'updatedBy',
      label: 'Updated by',
      description: 'The user who last updated the record',
      icon: 'IconUserCircle',
      isNullable: true,
    },
  ],
});
