export enum WorkflowStatusCombination {
  ACTIVE = 'ACTIVE',
  DRAFT = 'DRAFT',
  DEACTIVATED = 'DEACTIVATED',
  ACTIVE_AND_DRAFT = 'ACTIVE_AND_DRAFT',
  DEACTIVATED_AND_DRAFT = 'DEACTIVATED_AND_DRAFT',
  NO_STATUSES = 'NO_STATUSES',
}
