import { describe, expect, it } from 'vitest';

import { runAppFactoryPipeline } from './pipeline';

const validSpec = {
  app: {
    directory: 'generated-app',
    name: 'generated-app',
    displayName: 'Generated App',
    description: 'Generated by factory',
  },
  generation: {
    objects: [
      {
        universalIdentifier: '7e01862a-619e-4c6e-8ea9-8456b346f6a5',
        nameSingular: 'generatedContact',
        namePlural: 'generatedContacts',
        labelSingular: 'Generated Contact',
        labelPlural: 'Generated Contacts',
        icon: 'IconUser',
        fields: [
          {
            universalIdentifier: 'c9f936ff-3b90-4b6a-b727-b3459ccf0bbd',
            name: 'name',
            label: 'Name',
            type: 'TEXT',
            icon: 'IconAbc',
          },
        ],
      },
    ],
    logicFunctions: [
      {
        universalIdentifier: '85f8062a-9950-41c4-a2c4-17055126b9cd',
        name: 'factory-ingest-webhook',
        description: 'Receives payloads',
      },
    ],
  },
  pipeline: {
    dryRun: true,
  },
};

describe('runAppFactoryPipeline', () => {
  it('does not run install dependencies by default and emits stage statuses', () => {
    const result = runAppFactoryPipeline(validSpec);

    expect(result.success).toBe(true);

    const installCommand = result.commands.find(
      (command) => command.command.includes('yarn') && command.args[0] === 'install',
    );

    expect(installCommand).toBeUndefined();

    expect(result.stages).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          name: 'validateSpec',
          success: true,
          skipped: false,
        }),
        expect.objectContaining({
          name: 'installDependencies',
          success: true,
          skipped: true,
        }),
        expect.objectContaining({
          name: 'buildTarball',
          success: true,
          skipped: true,
        }),
      ]),
    );
  });
});
