import { describe, expect, it } from 'vitest';

import { validateAppFactorySpec } from './spec-validation';

const validSpec = {
  app: {
    directory: 'generated-app',
    name: 'generated-app',
    displayName: 'Generated App',
    description: 'Generated by factory',
  },
  generation: {
    objects: [
      {
        universalIdentifier: '7e01862a-619e-4c6e-8ea9-8456b346f6a5',
        nameSingular: 'generatedContact',
        namePlural: 'generatedContacts',
        labelSingular: 'Generated Contact',
        labelPlural: 'Generated Contacts',
        icon: 'IconUser',
        fields: [
          {
            universalIdentifier: 'c9f936ff-3b90-4b6a-b727-b3459ccf0bbd',
            name: 'name',
            label: 'Name',
            type: 'TEXT',
            icon: 'IconAbc',
          },
          {
            universalIdentifier: 'fbfa74f8-f775-4e16-a9b4-fa463bca0f78',
            name: 'stage',
            label: 'Stage',
            type: 'SELECT',
            icon: 'IconProgress',
            options: [
              {
                id: 'c53731a9-5891-4984-9960-c3ea3e140f24',
                value: 'NEW',
                label: 'New',
              },
            ],
          },
        ],
      },
    ],
    logicFunctions: [
      {
        universalIdentifier: '85f8062a-9950-41c4-a2c4-17055126b9cd',
        name: 'factory-ingest-webhook',
        description: 'Receives payloads',
        routeTrigger: {
          path: '/factory/ingest',
          httpMethod: 'POST',
          forwardedRequestHeaders: ['x-factory-signature'],
        },
      },
    ],
  },
};

describe('validateAppFactorySpec', () => {
  it('returns a normalized spec for valid input', () => {
    const result = validateAppFactorySpec(validSpec);

    expect(result.success).toBe(true);

    if (!result.success) {
      return;
    }

    expect(result.spec.app.skipLocalInstance).toBe(true);
    expect(result.spec.pipeline.installDependencies).toBe(true);
    expect(result.spec.pipeline.buildTarball).toBe(true);
    expect(result.spec.pipeline.deploy).toBe(false);
    expect(result.spec.pipeline.install).toBe(false);
    expect(result.spec.pipeline.dryRun).toBe(false);
  });

  it('normalizes pipeline and postInstall defaults when provided', () => {
    const result = validateAppFactorySpec({
      ...validSpec,
      pipeline: {
        installDependencies: false,
        buildTarball: false,
        deploy: true,
        install: true,
        remote: 'prod',
        dryRun: true,
        postInstall: {
          functionName: 'seed-data',
        },
      },
    });

    expect(result.success).toBe(true);

    if (!result.success) {
      return;
    }

    expect(result.spec.pipeline.installDependencies).toBe(false);
    expect(result.spec.pipeline.buildTarball).toBe(false);
    expect(result.spec.pipeline.deploy).toBe(true);
    expect(result.spec.pipeline.install).toBe(true);
    expect(result.spec.pipeline.remote).toBe('prod');
    expect(result.spec.pipeline.dryRun).toBe(true);
    expect(result.spec.pipeline.postInstall?.payload).toBe('{}');
    expect(result.spec.pipeline.postInstall?.preInstall).toBe(false);
    expect(result.spec.pipeline.postInstall?.functionName).toBe('seed-data');
  });

  it('returns descriptive errors for invalid input', () => {
    const result = validateAppFactorySpec({
      app: {
        directory: '',
        name: '',
        displayName: '',
        description: '',
        skipLocalInstance: 'yes',
      },
      generation: {
        objects: [
          {
            universalIdentifier: 'same-id',
            nameSingular: 'dup',
            namePlural: 'dups',
            labelSingular: 'Dup',
            labelPlural: 'Dups',
            icon: 'IconBox',
            fields: [
              {
                universalIdentifier: 'same-field',
                name: 'name',
                label: 'Name',
                type: 'INVALID',
                icon: 'IconAbc',
              },
              {
                universalIdentifier: 'same-field',
                name: 'name',
                label: 'Name 2',
                type: 'TEXT',
                icon: 'IconAbc',
              },
            ],
            labelIdentifierFieldMetadataUniversalIdentifier: 'unknown-field',
          },
          {
            universalIdentifier: 'same-id',
            nameSingular: 'dup',
            namePlural: 'dups2',
            labelSingular: 'Dup 2',
            labelPlural: 'Dups 2',
            icon: 'IconBox',
            fields: [],
          },
        ],
        logicFunctions: [
          {
            universalIdentifier: 'fn-id',
            name: 'dup-fn',
            description: 'First',
            routeTrigger: {
              path: 'invalid-path',
              httpMethod: 'TRACE',
              forwardedRequestHeaders: [''],
            },
          },
          {
            universalIdentifier: 'fn-id',
            name: 'dup-fn',
            description: '',
            timeoutSeconds: 0,
          },
        ],
      },
      pipeline: {
        installDependencies: 'true',
        postInstall: {
          payload: '',
        },
      },
    });

    expect(result.success).toBe(false);

    if (result.success !== false) {
      return;
    }

    expect(result.errors).toEqual(
      expect.arrayContaining([
        'app.directory must be a non-empty string',
        'app.name must be a non-empty string',
        'app.displayName must be a non-empty string',
        'app.description must be a non-empty string',
        'app.skipLocalInstance must be a boolean when provided',
        'generation.objects[0].fields[0].type must be one of TEXT, NUMBER, BOOLEAN, DATE_TIME, EMAILS, PHONES, LINKS, FULL_NAME, ADDRESS, SELECT, MULTI_SELECT, RATING, CURRENCY, UUID',
        'generation.objects[0].fields[1].name must be unique within an object',
        'generation.objects[0].fields[1].universalIdentifier must be unique within an object',
        'generation.objects[0].labelIdentifierFieldMetadataUniversalIdentifier must reference a field universalIdentifier from the same object',
        'generation.objects[1].nameSingular must be unique',
        'generation.objects[1].universalIdentifier must be unique',
        'generation.objects[1].fields must include at least one field',
        "generation.logicFunctions[0].routeTrigger.path must start with '/'",
        'generation.logicFunctions[0].routeTrigger.httpMethod must be GET|POST|PUT|PATCH|DELETE',
        'generation.logicFunctions[0].routeTrigger.forwardedRequestHeaders must contain only non-empty strings',
        'generation.logicFunctions[1].name must be unique',
        'generation.logicFunctions[1].universalIdentifier must be unique',
        'generation.logicFunctions[1].description must be a non-empty string',
        'generation.logicFunctions[1].timeoutSeconds must be a positive integer',
        'pipeline.installDependencies must be a boolean when provided',
        'pipeline.postInstall.payload must be a non-empty JSON string when provided',
        'pipeline.postInstall must provide functionName or functionUniversalIdentifier unless preInstall is true',
      ]),
    );
  });
});
