// Summaries are generated by default; an admin can disable them by setting the
// CALL_RECORDER_SUMMARY_ENABLED application variable to 'false'.
export const DEFAULT_CALL_RECORDER_SUMMARY_ENABLED = 'true';
