export type FrontComponentStorageErrorCode =
  | 'FRONT_COMPONENT_STORAGE_KEY_TOO_LONG'
  | 'FRONT_COMPONENT_STORAGE_VALUE_TOO_LARGE'
  | 'FRONT_COMPONENT_STORAGE_QUOTA_EXCEEDED'
  | 'FRONT_COMPONENT_STORAGE_UNAVAILABLE';
