import { type SelectOptionMeta } from 'src/types/select-option-meta.type';

export const INDUSTRY_OPTIONS: readonly SelectOptionMeta[] = [
  {
    key: 'accounting',
    value: 'ACCOUNTING',
    label: 'Accounting',
    color: 'blue',
    position: 0,
  },
  {
    key: 'airlinesAviation',
    value: 'AIRLINES_AVIATION',
    label: 'Airlines/Aviation',
    color: 'red',
    position: 1,
  },
  {
    key: 'alternativeDisputeResolution',
    value: 'ALTERNATIVE_DISPUTE_RESOLUTION',
    label: 'Alternative Dispute Resolution',
    color: 'green',
    position: 2,
  },
  {
    key: 'alternativeMedicine',
    value: 'ALTERNATIVE_MEDICINE',
    label: 'Alternative Medicine',
    color: 'orange',
    position: 3,
  },
  {
    key: 'animation',
    value: 'ANIMATION',
    label: 'Animation',
    color: 'purple',
    position: 4,
  },
  {
    key: 'apparelFashion',
    value: 'APPAREL_FASHION',
    label: 'Apparel & Fashion',
    color: 'yellow',
    position: 5,
  },
  {
    key: 'architecturePlanning',
    value: 'ARCHITECTURE_PLANNING',
    label: 'Architecture & Planning',
    color: 'pink',
    position: 6,
  },
  {
    key: 'artsAndCrafts',
    value: 'ARTS_AND_CRAFTS',
    label: 'Arts and Crafts',
    color: 'cyan',
    position: 7,
  },
  {
    key: 'automotive',
    value: 'AUTOMOTIVE',
    label: 'Automotive',
    color: 'brown',
    position: 8,
  },
  {
    key: 'aviationAerospace',
    value: 'AVIATION_AEROSPACE',
    label: 'Aviation & Aerospace',
    color: 'lime',
    position: 9,
  },
  {
    key: 'banking',
    value: 'BANKING',
    label: 'Banking',
    color: 'violet',
    position: 10,
  },
  {
    key: 'biotechnology',
    value: 'BIOTECHNOLOGY',
    label: 'Biotechnology',
    color: 'gold',
    position: 11,
  },
  {
    key: 'broadcastMedia',
    value: 'BROADCAST_MEDIA',
    label: 'Broadcast Media',
    color: 'turquoise',
    position: 12,
  },
  {
    key: 'buildingMaterials',
    value: 'BUILDING_MATERIALS',
    label: 'Building Materials',
    color: 'crimson',
    position: 13,
  },
  {
    key: 'businessSuppliesAndEquipment',
    value: 'BUSINESS_SUPPLIES_AND_EQUIPMENT',
    label: 'Business Supplies and Equipment',
    color: 'sky',
    position: 14,
  },
  {
    key: 'capitalMarkets',
    value: 'CAPITAL_MARKETS',
    label: 'Capital Markets',
    color: 'amber',
    position: 15,
  },
  {
    key: 'chemicals',
    value: 'CHEMICALS',
    label: 'Chemicals',
    color: 'plum',
    position: 16,
  },
  {
    key: 'civicSocialOrganization',
    value: 'CIVIC_SOCIAL_ORGANIZATION',
    label: 'Civic & Social Organization',
    color: 'grass',
    position: 17,
  },
  {
    key: 'civilEngineering',
    value: 'CIVIL_ENGINEERING',
    label: 'Civil Engineering',
    color: 'tomato',
    position: 18,
  },
  {
    key: 'commercialRealEstate',
    value: 'COMMERCIAL_REAL_ESTATE',
    label: 'Commercial Real Estate',
    color: 'iris',
    position: 19,
  },
  {
    key: 'computerNetworkSecurity',
    value: 'COMPUTER_NETWORK_SECURITY',
    label: 'Computer & Network Security',
    color: 'mint',
    position: 20,
  },
  {
    key: 'computerGames',
    value: 'COMPUTER_GAMES',
    label: 'Computer Games',
    color: 'ruby',
    position: 21,
  },
  {
    key: 'computerHardware',
    value: 'COMPUTER_HARDWARE',
    label: 'Computer Hardware',
    color: 'bronze',
    position: 22,
  },
  {
    key: 'computerNetworking',
    value: 'COMPUTER_NETWORKING',
    label: 'Computer Networking',
    color: 'jade',
    position: 23,
  },
  {
    key: 'computerSoftware',
    value: 'COMPUTER_SOFTWARE',
    label: 'Computer Software',
    color: 'gray',
    position: 24,
  },
  {
    key: 'construction',
    value: 'CONSTRUCTION',
    label: 'Construction',
    color: 'blue',
    position: 25,
  },
  {
    key: 'consumerElectronics',
    value: 'CONSUMER_ELECTRONICS',
    label: 'Consumer Electronics',
    color: 'red',
    position: 26,
  },
  {
    key: 'consumerGoods',
    value: 'CONSUMER_GOODS',
    label: 'Consumer Goods',
    color: 'green',
    position: 27,
  },
  {
    key: 'consumerServices',
    value: 'CONSUMER_SERVICES',
    label: 'Consumer Services',
    color: 'orange',
    position: 28,
  },
  {
    key: 'cosmetics',
    value: 'COSMETICS',
    label: 'Cosmetics',
    color: 'purple',
    position: 29,
  },
  {
    key: 'dairy',
    value: 'DAIRY',
    label: 'Dairy',
    color: 'yellow',
    position: 30,
  },
  {
    key: 'defenseSpace',
    value: 'DEFENSE_SPACE',
    label: 'Defense & Space',
    color: 'pink',
    position: 31,
  },
  {
    key: 'design',
    value: 'DESIGN',
    label: 'Design',
    color: 'cyan',
    position: 32,
  },
  {
    key: 'eLearning',
    value: 'E_LEARNING',
    label: 'E-Learning',
    color: 'brown',
    position: 33,
  },
  {
    key: 'educationManagement',
    value: 'EDUCATION_MANAGEMENT',
    label: 'Education Management',
    color: 'lime',
    position: 34,
  },
  {
    key: 'electricalElectronicManufacturing',
    value: 'ELECTRICAL_ELECTRONIC_MANUFACTURING',
    label: 'Electrical/Electronic Manufacturing',
    color: 'violet',
    position: 35,
  },
  {
    key: 'entertainment',
    value: 'ENTERTAINMENT',
    label: 'Entertainment',
    color: 'gold',
    position: 36,
  },
  {
    key: 'environmentalServices',
    value: 'ENVIRONMENTAL_SERVICES',
    label: 'Environmental Services',
    color: 'turquoise',
    position: 37,
  },
  {
    key: 'eventsServices',
    value: 'EVENTS_SERVICES',
    label: 'Events Services',
    color: 'crimson',
    position: 38,
  },
  {
    key: 'executiveOffice',
    value: 'EXECUTIVE_OFFICE',
    label: 'Executive Office',
    color: 'sky',
    position: 39,
  },
  {
    key: 'facilitiesServices',
    value: 'FACILITIES_SERVICES',
    label: 'Facilities Services',
    color: 'amber',
    position: 40,
  },
  {
    key: 'farming',
    value: 'FARMING',
    label: 'Farming',
    color: 'plum',
    position: 41,
  },
  {
    key: 'financialServices',
    value: 'FINANCIAL_SERVICES',
    label: 'Financial Services',
    color: 'grass',
    position: 42,
  },
  {
    key: 'fineArt',
    value: 'FINE_ART',
    label: 'Fine Art',
    color: 'tomato',
    position: 43,
  },
  {
    key: 'fishery',
    value: 'FISHERY',
    label: 'Fishery',
    color: 'iris',
    position: 44,
  },
  {
    key: 'foodBeverages',
    value: 'FOOD_BEVERAGES',
    label: 'Food & Beverages',
    color: 'mint',
    position: 45,
  },
  {
    key: 'foodProduction',
    value: 'FOOD_PRODUCTION',
    label: 'Food Production',
    color: 'ruby',
    position: 46,
  },
  {
    key: 'fundRaising',
    value: 'FUND_RAISING',
    label: 'Fund-Raising',
    color: 'bronze',
    position: 47,
  },
  {
    key: 'furniture',
    value: 'FURNITURE',
    label: 'Furniture',
    color: 'jade',
    position: 48,
  },
  {
    key: 'gamblingCasinos',
    value: 'GAMBLING_CASINOS',
    label: 'Gambling & Casinos',
    color: 'gray',
    position: 49,
  },
  {
    key: 'glassCeramicsConcrete',
    value: 'GLASS_CERAMICS_CONCRETE',
    label: 'Glass Ceramics & Concrete',
    color: 'blue',
    position: 50,
  },
  {
    key: 'governmentAdministration',
    value: 'GOVERNMENT_ADMINISTRATION',
    label: 'Government Administration',
    color: 'red',
    position: 51,
  },
  {
    key: 'governmentRelations',
    value: 'GOVERNMENT_RELATIONS',
    label: 'Government Relations',
    color: 'green',
    position: 52,
  },
  {
    key: 'graphicDesign',
    value: 'GRAPHIC_DESIGN',
    label: 'Graphic Design',
    color: 'orange',
    position: 53,
  },
  {
    key: 'healthWellnessAndFitness',
    value: 'HEALTH_WELLNESS_AND_FITNESS',
    label: 'Health Wellness and Fitness',
    color: 'purple',
    position: 54,
  },
  {
    key: 'higherEducation',
    value: 'HIGHER_EDUCATION',
    label: 'Higher Education',
    color: 'yellow',
    position: 55,
  },
  {
    key: 'hospitalHealthCare',
    value: 'HOSPITAL_HEALTH_CARE',
    label: 'Hospital & Health Care',
    color: 'pink',
    position: 56,
  },
  {
    key: 'hospitality',
    value: 'HOSPITALITY',
    label: 'Hospitality',
    color: 'cyan',
    position: 57,
  },
  {
    key: 'humanResources',
    value: 'HUMAN_RESOURCES',
    label: 'Human Resources',
    color: 'brown',
    position: 58,
  },
  {
    key: 'importAndExport',
    value: 'IMPORT_AND_EXPORT',
    label: 'Import and Export',
    color: 'lime',
    position: 59,
  },
  {
    key: 'individualFamilyServices',
    value: 'INDIVIDUAL_FAMILY_SERVICES',
    label: 'Individual & Family Services',
    color: 'violet',
    position: 60,
  },
  {
    key: 'industrialAutomation',
    value: 'INDUSTRIAL_AUTOMATION',
    label: 'Industrial Automation',
    color: 'gold',
    position: 61,
  },
  {
    key: 'informationServices',
    value: 'INFORMATION_SERVICES',
    label: 'Information Services',
    color: 'turquoise',
    position: 62,
  },
  {
    key: 'informationTechnologyAndServices',
    value: 'INFORMATION_TECHNOLOGY_AND_SERVICES',
    label: 'Information Technology and Services',
    color: 'crimson',
    position: 63,
  },
  {
    key: 'insurance',
    value: 'INSURANCE',
    label: 'Insurance',
    color: 'sky',
    position: 64,
  },
  {
    key: 'internationalAffairs',
    value: 'INTERNATIONAL_AFFAIRS',
    label: 'International Affairs',
    color: 'amber',
    position: 65,
  },
  {
    key: 'internationalTradeAndDevelopment',
    value: 'INTERNATIONAL_TRADE_AND_DEVELOPMENT',
    label: 'International Trade and Development',
    color: 'plum',
    position: 66,
  },
  {
    key: 'internet',
    value: 'INTERNET',
    label: 'Internet',
    color: 'grass',
    position: 67,
  },
  {
    key: 'investmentBanking',
    value: 'INVESTMENT_BANKING',
    label: 'Investment Banking',
    color: 'tomato',
    position: 68,
  },
  {
    key: 'investmentManagement',
    value: 'INVESTMENT_MANAGEMENT',
    label: 'Investment Management',
    color: 'iris',
    position: 69,
  },
  {
    key: 'judiciary',
    value: 'JUDICIARY',
    label: 'Judiciary',
    color: 'mint',
    position: 70,
  },
  {
    key: 'lawEnforcement',
    value: 'LAW_ENFORCEMENT',
    label: 'Law Enforcement',
    color: 'ruby',
    position: 71,
  },
  {
    key: 'lawPractice',
    value: 'LAW_PRACTICE',
    label: 'Law Practice',
    color: 'bronze',
    position: 72,
  },
  {
    key: 'legalServices',
    value: 'LEGAL_SERVICES',
    label: 'Legal Services',
    color: 'jade',
    position: 73,
  },
  {
    key: 'legislativeOffice',
    value: 'LEGISLATIVE_OFFICE',
    label: 'Legislative Office',
    color: 'gray',
    position: 74,
  },
  {
    key: 'leisureTravelTourism',
    value: 'LEISURE_TRAVEL_TOURISM',
    label: 'Leisure Travel & Tourism',
    color: 'blue',
    position: 75,
  },
  {
    key: 'libraries',
    value: 'LIBRARIES',
    label: 'Libraries',
    color: 'red',
    position: 76,
  },
  {
    key: 'logisticsAndSupplyChain',
    value: 'LOGISTICS_AND_SUPPLY_CHAIN',
    label: 'Logistics and Supply Chain',
    color: 'green',
    position: 77,
  },
  {
    key: 'luxuryGoodsJewelry',
    value: 'LUXURY_GOODS_JEWELRY',
    label: 'Luxury Goods & Jewelry',
    color: 'orange',
    position: 78,
  },
  {
    key: 'machinery',
    value: 'MACHINERY',
    label: 'Machinery',
    color: 'purple',
    position: 79,
  },
  {
    key: 'managementConsulting',
    value: 'MANAGEMENT_CONSULTING',
    label: 'Management Consulting',
    color: 'yellow',
    position: 80,
  },
  {
    key: 'maritime',
    value: 'MARITIME',
    label: 'Maritime',
    color: 'pink',
    position: 81,
  },
  {
    key: 'marketResearch',
    value: 'MARKET_RESEARCH',
    label: 'Market Research',
    color: 'cyan',
    position: 82,
  },
  {
    key: 'marketingAndAdvertising',
    value: 'MARKETING_AND_ADVERTISING',
    label: 'Marketing and Advertising',
    color: 'brown',
    position: 83,
  },
  {
    key: 'mechanicalOrIndustrialEngineering',
    value: 'MECHANICAL_OR_INDUSTRIAL_ENGINEERING',
    label: 'Mechanical or Industrial Engineering',
    color: 'lime',
    position: 84,
  },
  {
    key: 'mediaProduction',
    value: 'MEDIA_PRODUCTION',
    label: 'Media Production',
    color: 'violet',
    position: 85,
  },
  {
    key: 'medicalDevices',
    value: 'MEDICAL_DEVICES',
    label: 'Medical Devices',
    color: 'gold',
    position: 86,
  },
  {
    key: 'medicalPractice',
    value: 'MEDICAL_PRACTICE',
    label: 'Medical Practice',
    color: 'turquoise',
    position: 87,
  },
  {
    key: 'mentalHealthCare',
    value: 'MENTAL_HEALTH_CARE',
    label: 'Mental Health Care',
    color: 'crimson',
    position: 88,
  },
  {
    key: 'military',
    value: 'MILITARY',
    label: 'Military',
    color: 'sky',
    position: 89,
  },
  {
    key: 'miningMetals',
    value: 'MINING_METALS',
    label: 'Mining & Metals',
    color: 'amber',
    position: 90,
  },
  {
    key: 'motionPicturesAndFilm',
    value: 'MOTION_PICTURES_AND_FILM',
    label: 'Motion Pictures and Film',
    color: 'plum',
    position: 91,
  },
  {
    key: 'museumsAndInstitutions',
    value: 'MUSEUMS_AND_INSTITUTIONS',
    label: 'Museums and Institutions',
    color: 'grass',
    position: 92,
  },
  {
    key: 'music',
    value: 'MUSIC',
    label: 'Music',
    color: 'tomato',
    position: 93,
  },
  {
    key: 'nanotechnology',
    value: 'NANOTECHNOLOGY',
    label: 'Nanotechnology',
    color: 'iris',
    position: 94,
  },
  {
    key: 'newspapers',
    value: 'NEWSPAPERS',
    label: 'Newspapers',
    color: 'mint',
    position: 95,
  },
  {
    key: 'nonProfitOrganizationManagement',
    value: 'NON_PROFIT_ORGANIZATION_MANAGEMENT',
    label: 'Non-Profit Organization Management',
    color: 'ruby',
    position: 96,
  },
  {
    key: 'oilEnergy',
    value: 'OIL_ENERGY',
    label: 'Oil & Energy',
    color: 'bronze',
    position: 97,
  },
  {
    key: 'onlineMedia',
    value: 'ONLINE_MEDIA',
    label: 'Online Media',
    color: 'jade',
    position: 98,
  },
  {
    key: 'outsourcingOffshoring',
    value: 'OUTSOURCING_OFFSHORING',
    label: 'Outsourcing/Offshoring',
    color: 'gray',
    position: 99,
  },
  {
    key: 'packageFreightDelivery',
    value: 'PACKAGE_FREIGHT_DELIVERY',
    label: 'Package/Freight Delivery',
    color: 'blue',
    position: 100,
  },
  {
    key: 'packagingAndContainers',
    value: 'PACKAGING_AND_CONTAINERS',
    label: 'Packaging and Containers',
    color: 'red',
    position: 101,
  },
  {
    key: 'paperForestProducts',
    value: 'PAPER_FOREST_PRODUCTS',
    label: 'Paper & Forest Products',
    color: 'green',
    position: 102,
  },
  {
    key: 'performingArts',
    value: 'PERFORMING_ARTS',
    label: 'Performing Arts',
    color: 'orange',
    position: 103,
  },
  {
    key: 'pharmaceuticals',
    value: 'PHARMACEUTICALS',
    label: 'Pharmaceuticals',
    color: 'purple',
    position: 104,
  },
  {
    key: 'philanthropy',
    value: 'PHILANTHROPY',
    label: 'Philanthropy',
    color: 'yellow',
    position: 105,
  },
  {
    key: 'photography',
    value: 'PHOTOGRAPHY',
    label: 'Photography',
    color: 'pink',
    position: 106,
  },
  {
    key: 'plastics',
    value: 'PLASTICS',
    label: 'Plastics',
    color: 'cyan',
    position: 107,
  },
  {
    key: 'politicalOrganization',
    value: 'POLITICAL_ORGANIZATION',
    label: 'Political Organization',
    color: 'brown',
    position: 108,
  },
  {
    key: 'primarySecondaryEducation',
    value: 'PRIMARY_SECONDARY_EDUCATION',
    label: 'Primary/Secondary Education',
    color: 'lime',
    position: 109,
  },
  {
    key: 'printing',
    value: 'PRINTING',
    label: 'Printing',
    color: 'violet',
    position: 110,
  },
  {
    key: 'professionalTrainingCoaching',
    value: 'PROFESSIONAL_TRAINING_COACHING',
    label: 'Professional Training & Coaching',
    color: 'gold',
    position: 111,
  },
  {
    key: 'programDevelopment',
    value: 'PROGRAM_DEVELOPMENT',
    label: 'Program Development',
    color: 'turquoise',
    position: 112,
  },
  {
    key: 'publicPolicy',
    value: 'PUBLIC_POLICY',
    label: 'Public Policy',
    color: 'crimson',
    position: 113,
  },
  {
    key: 'publicRelationsAndCommunications',
    value: 'PUBLIC_RELATIONS_AND_COMMUNICATIONS',
    label: 'Public Relations and Communications',
    color: 'sky',
    position: 114,
  },
  {
    key: 'publicSafety',
    value: 'PUBLIC_SAFETY',
    label: 'Public Safety',
    color: 'amber',
    position: 115,
  },
  {
    key: 'publishing',
    value: 'PUBLISHING',
    label: 'Publishing',
    color: 'plum',
    position: 116,
  },
  {
    key: 'railroadManufacture',
    value: 'RAILROAD_MANUFACTURE',
    label: 'Railroad Manufacture',
    color: 'grass',
    position: 117,
  },
  {
    key: 'ranching',
    value: 'RANCHING',
    label: 'Ranching',
    color: 'tomato',
    position: 118,
  },
  {
    key: 'realEstate',
    value: 'REAL_ESTATE',
    label: 'Real Estate',
    color: 'iris',
    position: 119,
  },
  {
    key: 'recreationalFacilitiesAndServices',
    value: 'RECREATIONAL_FACILITIES_AND_SERVICES',
    label: 'Recreational Facilities and Services',
    color: 'mint',
    position: 120,
  },
  {
    key: 'religiousInstitutions',
    value: 'RELIGIOUS_INSTITUTIONS',
    label: 'Religious Institutions',
    color: 'ruby',
    position: 121,
  },
  {
    key: 'renewablesEnvironment',
    value: 'RENEWABLES_ENVIRONMENT',
    label: 'Renewables & Environment',
    color: 'bronze',
    position: 122,
  },
  {
    key: 'research',
    value: 'RESEARCH',
    label: 'Research',
    color: 'jade',
    position: 123,
  },
  {
    key: 'restaurants',
    value: 'RESTAURANTS',
    label: 'Restaurants',
    color: 'gray',
    position: 124,
  },
  {
    key: 'retail',
    value: 'RETAIL',
    label: 'Retail',
    color: 'blue',
    position: 125,
  },
  {
    key: 'securityAndInvestigations',
    value: 'SECURITY_AND_INVESTIGATIONS',
    label: 'Security and Investigations',
    color: 'red',
    position: 126,
  },
  {
    key: 'semiconductors',
    value: 'SEMICONDUCTORS',
    label: 'Semiconductors',
    color: 'green',
    position: 127,
  },
  {
    key: 'shipbuilding',
    value: 'SHIPBUILDING',
    label: 'Shipbuilding',
    color: 'orange',
    position: 128,
  },
  {
    key: 'sportingGoods',
    value: 'SPORTING_GOODS',
    label: 'Sporting Goods',
    color: 'purple',
    position: 129,
  },
  {
    key: 'sports',
    value: 'SPORTS',
    label: 'Sports',
    color: 'yellow',
    position: 130,
  },
  {
    key: 'staffingAndRecruiting',
    value: 'STAFFING_AND_RECRUITING',
    label: 'Staffing and Recruiting',
    color: 'pink',
    position: 131,
  },
  {
    key: 'supermarkets',
    value: 'SUPERMARKETS',
    label: 'Supermarkets',
    color: 'cyan',
    position: 132,
  },
  {
    key: 'telecommunications',
    value: 'TELECOMMUNICATIONS',
    label: 'Telecommunications',
    color: 'brown',
    position: 133,
  },
  {
    key: 'textiles',
    value: 'TEXTILES',
    label: 'Textiles',
    color: 'lime',
    position: 134,
  },
  {
    key: 'thinkTanks',
    value: 'THINK_TANKS',
    label: 'Think Tanks',
    color: 'violet',
    position: 135,
  },
  {
    key: 'tobacco',
    value: 'TOBACCO',
    label: 'Tobacco',
    color: 'gold',
    position: 136,
  },
  {
    key: 'translationAndLocalization',
    value: 'TRANSLATION_AND_LOCALIZATION',
    label: 'Translation and Localization',
    color: 'turquoise',
    position: 137,
  },
  {
    key: 'transportationTruckingRailroad',
    value: 'TRANSPORTATION_TRUCKING_RAILROAD',
    label: 'Transportation/Trucking/Railroad',
    color: 'crimson',
    position: 138,
  },
  {
    key: 'utilities',
    value: 'UTILITIES',
    label: 'Utilities',
    color: 'sky',
    position: 139,
  },
  {
    key: 'ventureCapitalPrivateEquity',
    value: 'VENTURE_CAPITAL_PRIVATE_EQUITY',
    label: 'Venture Capital & Private Equity',
    color: 'amber',
    position: 140,
  },
  {
    key: 'veterinary',
    value: 'VETERINARY',
    label: 'Veterinary',
    color: 'plum',
    position: 141,
  },
  {
    key: 'warehousing',
    value: 'WAREHOUSING',
    label: 'Warehousing',
    color: 'grass',
    position: 142,
  },
  {
    key: 'wholesale',
    value: 'WHOLESALE',
    label: 'Wholesale',
    color: 'tomato',
    position: 143,
  },
  {
    key: 'wineAndSpirits',
    value: 'WINE_AND_SPIRITS',
    label: 'Wine and Spirits',
    color: 'iris',
    position: 144,
  },
  {
    key: 'wireless',
    value: 'WIRELESS',
    label: 'Wireless',
    color: 'mint',
    position: 145,
  },
  {
    key: 'writingAndEditing',
    value: 'WRITING_AND_EDITING',
    label: 'Writing and Editing',
    color: 'ruby',
    position: 146,
  },
];
