import { type SelectOptionMeta } from 'src/types/select-option-meta';

export const JOB_ROLE_OPTIONS: readonly SelectOptionMeta[] = [
  {
    key: 'advisory',
    value: 'ADVISORY',
    label: 'Advisory',
    color: 'blue',
    position: 0,
  },
  {
    key: 'analyst',
    value: 'ANALYST',
    label: 'Analyst',
    color: 'red',
    position: 1,
  },
  {
    key: 'creative',
    value: 'CREATIVE',
    label: 'Creative',
    color: 'green',
    position: 2,
  },
  {
    key: 'education',
    value: 'EDUCATION',
    label: 'Education',
    color: 'orange',
    position: 3,
  },
  {
    key: 'engineering',
    value: 'ENGINEERING',
    label: 'Engineering',
    color: 'purple',
    position: 4,
  },
  {
    key: 'finance',
    value: 'FINANCE',
    label: 'Finance',
    color: 'yellow',
    position: 5,
  },
  {
    key: 'fulfillment',
    value: 'FULFILLMENT',
    label: 'Fulfillment',
    color: 'pink',
    position: 6,
  },
  {
    key: 'health',
    value: 'HEALTH',
    label: 'Health',
    color: 'cyan',
    position: 7,
  },
  {
    key: 'hospitality',
    value: 'HOSPITALITY',
    label: 'Hospitality',
    color: 'brown',
    position: 8,
  },
  {
    key: 'humanResources',
    value: 'HUMAN_RESOURCES',
    label: 'Human Resources',
    color: 'lime',
    position: 9,
  },
  {
    key: 'legal',
    value: 'LEGAL',
    label: 'Legal',
    color: 'violet',
    position: 10,
  },
  {
    key: 'manufacturing',
    value: 'MANUFACTURING',
    label: 'Manufacturing',
    color: 'gold',
    position: 11,
  },
  {
    key: 'marketing',
    value: 'MARKETING',
    label: 'Marketing',
    color: 'turquoise',
    position: 12,
  },
  {
    key: 'operations',
    value: 'OPERATIONS',
    label: 'Operations',
    color: 'crimson',
    position: 13,
  },
  {
    key: 'partnerships',
    value: 'PARTNERSHIPS',
    label: 'Partnerships',
    color: 'sky',
    position: 14,
  },
  {
    key: 'product',
    value: 'PRODUCT',
    label: 'Product',
    color: 'amber',
    position: 15,
  },
  {
    key: 'professionalService',
    value: 'PROFESSIONAL_SERVICE',
    label: 'Professional Service',
    color: 'plum',
    position: 16,
  },
  {
    key: 'publicService',
    value: 'PUBLIC_SERVICE',
    label: 'Public Service',
    color: 'grass',
    position: 17,
  },
  {
    key: 'research',
    value: 'RESEARCH',
    label: 'Research',
    color: 'tomato',
    position: 18,
  },
  {
    key: 'sales',
    value: 'SALES',
    label: 'Sales',
    color: 'iris',
    position: 19,
  },
  {
    key: 'salesEngineering',
    value: 'SALES_ENGINEERING',
    label: 'Sales Engineering',
    color: 'mint',
    position: 20,
  },
  {
    key: 'support',
    value: 'SUPPORT',
    label: 'Support',
    color: 'ruby',
    position: 21,
  },
  {
    key: 'trade',
    value: 'TRADE',
    label: 'Trade',
    color: 'bronze',
    position: 22,
  },
  {
    key: 'unemployed',
    value: 'UNEMPLOYED',
    label: 'Unemployed',
    color: 'jade',
    position: 23,
  },
];
