export enum CallRecordingStatus {
  SCHEDULED = 'SCHEDULED',
  JOINING = 'JOINING',
  RECORDING = 'RECORDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  NOT_ATTENDED = 'NOT_ATTENDED',
}
