export type CalendarEventRecordingDecisionReason =
  | 'WORKSPACE_RECORDING_DISABLED'
  | 'EVENT_CANCELED'
  | 'PREFERENCE_OFF'
  | 'PREFERENCE_ON'
  | 'AUTO_POLICY_MATCHED'
  | 'AUTO_MISSING_CONFERENCE_LINK'
  | 'AUTO_EVENT_NOT_UPCOMING'
  | 'AUTO_NO_EXTERNAL_PARTICIPANT';
