export enum ToolCategory {
  DATABASE_CRUD = 'DATABASE_CRUD',
  QUERY = 'QUERY',
  ACTION = 'ACTION',
  WORKFLOW = 'WORKFLOW',
  METADATA = 'METADATA',
  VIEW = 'VIEW',
  DASHBOARD = 'DASHBOARD',
  NAVIGATION_MENU_ITEM = 'NAVIGATION_MENU_ITEM',
  WEBHOOK = 'WEBHOOK',
  LOGIC_FUNCTION = 'LOGIC_FUNCTION',
}
