name: CD deploy tag

permissions:
  contents: read

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy-tag:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        env:
          GH_TOKEN: ${{ secrets.TWENTY_INFRA_TOKEN }}
        run: |
          gh api repos/twentyhq/twenty-infra/dispatches \
            --raw-field event_type=auto-deploy-tag \
            --raw-field 'client_payload={"github": {"sha": "${{ github.sha }}", "ref": "${{ github.ref }}", "ref_name": "${{ github.ref_name }}", "actor": "${{ github.actor }}", "run_id": "${{ github.run_id }}", "repository": "${{ github.repository }}"}}'
