name: CD deploy main

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  deploy-main:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        env:
          GH_TOKEN: ${{ secrets.TWENTY_INFRA_TOKEN }}
        run: |
          gh api repos/twentyhq/twenty-infra/dispatches \
            -f event_type=auto-deploy-main
