name: 'Push docs to Crowdin'

permissions:
  contents: write

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ['main']
    paths:
      - 'packages/twenty-docs/**/*.mdx'
      - '!packages/twenty-docs/l/**'
      - 'packages/twenty-docs/navigation/navigation.template.json'
      - '.github/crowdin-docs.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  push_docs:
    name: Push documentation to Crowdin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          token: ${{ github.token }}
          ref: ${{ github.ref }}

      - name: Install dependencies
        uses: ./.github/actions/yarn-install

      - name: Generate navigation template for Crowdin
        run: yarn docs:generate-navigation-template

      - name: Upload docs to Crowdin
        uses: crowdin/github-action@8868a33591d21088edfc398968173a3b98d51706 # v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          localization_branch_name: i18n-docs
          base_url: 'https://twenty.api.crowdin.com'
          config: '.github/crowdin-docs.yml'
        env:
          # Docs translations project
          CROWDIN_PROJECT_ID: '2'
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

