name: Semgrep

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Semgrep Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci
          generateSarif: "true"
        continue-on-error: true

      - name: Upload SARIF report
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
