export const companyObject = {
  singular: 'company',
  plural: 'companies',
  description: 'A company is an organization that you do business with.',
  icon: 'company',
  fields: [
    {
      displayName: 'name',
      description: 'The name of the company.',
      type: 'text',
      icon: null,
      isNullable: false,
    },
    {
      displayName: 'domainName',
      description: 'The domain name of the company.',
      type: 'text',
      icon: null,
      isNullable: false,
    },
    {
      displayName: 'linkedinUrl',
      description: 'The LinkedIn URL of the company.',
      type: 'text',
      icon: null,
      isNullable: true,
    },
    {
      displayName: 'annualRecurringRevenue',
      description: 'The annual recurring revenue of the company.',
      type: 'number',
      icon: null,
      isNullable: true,
    },
    {
      displayName: 'idealCustomerProfile',
      description: 'Whether the company is an ideal customer profile.',
      type: 'boolean',
      icon: null,
      isNullable: false,
    },
    {
      displayName: 'xUrl',
      description: 'The X URL of the company.',
      type: 'text',
      icon: null,
      isNullable: true,
    },
    {
      displayName: 'address',
      description: 'The address of the company.',
      type: 'text',
      icon: null,
      isNullable: false,
    },
    {
      displayName: 'employees',
      description: 'The number of employees at the company.',
      type: 'number',
      icon: null,
      isNullable: true,
    },
    {
      displayName: 'accountOwnerId',
      description: 'The account owner ID of the company.',
      type: 'text',
      icon: null,
      isNullable: true,
    },
    {
      displayName: 'workspaceMemberAccountOwnerId',
      description: 'The workspace member account owner ID of the company.',
      type: 'text',
      icon: null,
      isNullable: true,
    },
  ],
};
