import {
  normalizeHalftoneStudioSettings,
  type HalftoneExportPose,
  type HalftoneStudioSettings,
} from '@/lib/halftone';

export const PRODUCT_EFFECT_MODEL_URL = '/illustrations/product/hero/hero.glb';
export const PRODUCT_EFFECT_PREVIEW_DISTANCE = 2.5;
export const PRODUCT_EFFECT_VIRTUAL_RENDER_HEIGHT = 400;

export const PRODUCT_EFFECT_INITIAL_POSE: HalftoneExportPose = {
  autoElapsed: 0,
  rotateElapsed: 0,
  rotationX: 0.4,
  rotationY: 0,
  rotationZ: 0.6,
  targetRotationX: 0,
  targetRotationY: 0,
  timeElapsed: 0,
};

export const PRODUCT_EFFECT_SETTINGS: HalftoneStudioSettings =
  normalizeHalftoneStudioSettings({
    sourceMode: 'shape',
    shapeKey: 'userUpload_1776153228532',
    lighting: {
      intensity: 0.5,
      fillIntensity: 0,
      ambientIntensity: 0,
      angleDegrees: 80,
      height: -4,
    },
    material: {
      surface: 'solid',
      color: '#F5F5F5',
      roughness: 0.4,
      metalness: 0.1,
      thickness: 150,
      refraction: 2,
      environmentPower: 5,
    },
    halftone: {
      enabled: true,
      scale: 12,
      power: 0.1,
      toneTarget: 'light',
      width: 0.6,
      imageContrast: 1,
      dashColor: '#4A38F5',
      hoverDashColor: '#4A38F5',
    },
    background: {
      transparent: true,
      color: '#F4F4F4',
    },
    animation: {
      autoRotateEnabled: true,
      breatheEnabled: false,
      cameraParallaxEnabled: false,
      followHoverEnabled: false,
      followDragEnabled: true,
      floatEnabled: false,
      hoverHalftoneEnabled: false,
      hoverLightEnabled: false,
      dragFlowEnabled: false,
      lightSweepEnabled: false,
      rotateEnabled: false,
      autoSpeed: 0.01,
      autoWobble: 0.2,
      breatheAmount: 0.04,
      breatheSpeed: 0.8,
      cameraParallaxAmount: 0.3,
      cameraParallaxEase: 0.08,
      driftAmount: 8,
      hoverRange: 25,
      hoverEase: 0.08,
      hoverReturn: true,
      dragSens: 0.008,
      dragFriction: 0.08,
      dragMomentum: true,
      rotateAxis: 'y',
      rotatePreset: 'axis',
      rotateSpeed: 0.1,
      rotatePingPong: false,
      floatAmplitude: 0.16,
      floatSpeed: 0.8,
      lightSweepHeightRange: 0.5,
      lightSweepRange: 28,
      lightSweepSpeed: 0.7,
      springDamping: 0.52,
      springReturnEnabled: true,
      springStrength: 0.2,
      hoverHalftonePowerShift: 0.42,
      hoverHalftoneRadius: 0.2,
      hoverHalftoneWidthShift: -0.18,
      hoverLightIntensity: 0.8,
      hoverLightRadius: 0.2,
      dragFlowDecay: 0.08,
      dragFlowRadius: 0.24,
      dragFlowStrength: 1.8,
      hoverWarpStrength: 3,
      hoverWarpRadius: 0.15,
      dragWarpStrength: 5,
      waveEnabled: false,
      waveSpeed: 1,
      waveAmount: 2,
    },
  });
